### ISSUE TITLE
Butcher/disassemble more items at once

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#103]
# Is your feature request related to a problem? Please describe.

When disassembling more items from a big pile it would be nice to be able to specify how many items to butcher/disassemble.
I'm frustrated when doing this with 12 cellphones/smartphones and having to open the UI, find the item and then select it again and again. It's even more frustrating because the position of the item changes as the number of items to be disassembled goes lower so got to find it each time.

# Describe the solution you'd like

I would like to have a new feature added to the UI which after selecting the item and the pressing a key would ask how many items to do.
It could be done in similar fashion as move more items from a stack in 'Advanced Inventory UI'.

![image](https://user-images.githubusercontent.com/72284934/95720146-22d2a500-0c71-11eb-8ffc-50d902c7a2fe.png)

# Describe alternatives you've considered

Alternatively just add a keypres that would butcher/disassemble all items from the pile that is selected.
It would be also nice to be able to sort items by category/etc... just like in advanced inventory so the position of items would be more predictable and constant.
It would be likely even easier to add the option of disassembling to 'advanced inventory ui' while we're at it? I'm not sure how this works.

# Additional context

**Comment by Coolthulhu** [comment]
> Alternatively just add a keypres that would butcher/disassemble all items from the pile that is selected.

There is one, though. Stand over a pile, 'B'utcher it, then you can select butcher all or disassemble everything once or recursively.
I'm not sure how does your request differ from this implementation, other than that it uses the inventory.

**Comment by Krwak** [comment]
> 
> 
> > Alternatively just add a keypres that would butcher/disassemble all items from the pile that is selected.
> 
> There is one, though. Stand over a pile, 'B'utcher it, then you can select butcher all or disassemble everything once or recursively.
> I'm not sure how does your request differ from this implementation, other than that it uses the inventory.

This is a possible workaround but not very comfortable as rarely only items that one wants to butcher/disassemble are on spot so it requires previous preparation - moving those items to a different tile.
This isn't very practical in my opinion.

**Comment by Krwak** [comment]
stale for 3 years
