### ISSUE TITLE
Mutations can't be activated

### ISSUE THREAD

**Issue by 12347654** [cataclysmbnteam/Cataclysm-BN#1059]
# Describe the bug
You can't take a lot of mutations, because their activation requires buttons on the keyboard. When there are too many mutations, instead of binding to letters, there is a void. Mutations cannot be either unbind or rebind. Because of this, I can't use active mutations, because all the buttons have gone to passive ones.

# Steps To Reproduce
1. take 86+ mutations
2. try to activate them in the mutation menu
3. see the screenshot

# Expected behavior
I wanted to become a normal human, but I was only allowed to communicate with trees.

# Screenshots
![image](https://user-images.githubusercontent.com/55704998/137578490-b812353f-a635-4bf3-80f1-1012d80e8725.png)

# Versions and configuration
version: 2154 cda

# Additional context

**Comment by chaosvolt** [comment]
This could probably be fixed if the mutation menu allowed scrolling with standard keys like with the bionic menu.

**Comment by SaintCirno9** [comment]
@Coolthulhu I think this one has been fixed by #1484

**Comment by olanti-p** [comment]
Fixed by #1484
