### ISSUE TITLE
Switching fire mods impossible/buggy when bayonet is attached.

### ISSUE THREAD

**Issue by Lamandus** [cataclysmbnteam/Cataclysm-BN#1073]
# Describe the bug
When having a rifle with a sword bayonet, you can't change the fire mode correctly when in aim mode.

# Steps To Reproduce
1. Attach sword bayonet to multy fire mode rifle (for example the SIG 552
2. have the gun loaded and be either in AUTO, SINGLE or BURST mode
3. activate the [f]ire menu
4. press s to switch aim and fire mode
5. switch firemode to something else
6. see that the wrong fire mode is selected.

# Expected behavior
Select the correct fire mode

# Screenshots

![1](https://user-images.githubusercontent.com/33199510/138222317-774ad02d-0ecb-4e50-9882-7bee3134a795.gif)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: a48e632a78 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Faster Stamina Regen [stamina_regen_buff],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Prevent Zombie Revivication [no_reviving_zombies],
    SpeedyDex [speedydex],
    No Rail Stations [No_Rail_Stations],
    meins [meins],
    No Lifting Reqs [disable_lifting],
    Stackable Dried Items and Generic Fruits/Berries [drystack]
]

# Additional context
https://github.com/CleverRaven/Cataclysm-DDA/pull/47857

**Comment by Coolthulhu** [comment]
Confirming
Seems that it skips forward by one

**Comment by olanti-p** [comment]
Fixed by #1407
