### ISSUE TITLE
Map memory turn on/off don't work on curses x64

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#108]
# Describe the bug
Map memory turn on/off don't work on curses x64
**Needs confirmation.**

# Steps To Reproduce
1. Run lin x64 curses (non SDL version)
2. Try to sith map memory on/off "{"
3. Observe map memory behavior.

# Expected behavior
Map memory turning on/off working

# Actual behavior
Map memory turning on/off does not working.

# Screenshots

# Versions and configuration
Linux x64 curses

# Additional context
**Needs confirmation.**

**Comment by Coolthulhu** [comment]
Should be fixed in https://github.com/cataclysmbnteam/Cataclysm-BN/commit/712b9c72c1fbe9b52b4be3cad876f5da4671200c

**Comment by Firestorm01X2** [comment]
I didn't test it. I've got that report from anonymous.
But looks lite it is that.

**Comment by Firestorm01X2** [comment]
Yes, I think yit can be closed. It is it by description.
