### ISSUE TITLE
Some item sprites are missing or in wrong sizes

### ISSUE THREAD

**Issue by miu135** [cataclysmbnteam/Cataclysm-BN#1080]
Just downloaded the latest experimental and it seems like some item sprites are either missing or in the wrong size, this happens in some tilesets (RetroDays, Brownlikebears, Chesthole, Hoder)

![cddaspritebugs1](https://user-images.githubusercontent.com/54433550/138570130-4d1c769b-8a1b-4f6a-80f2-0bd22b42e3d6.PNG)

![cddaspritebugs2](https://user-images.githubusercontent.com/54433550/138570137-b9c79c01-0244-406d-963f-c3d49b220c36.PNG)

Here's my save:

[save.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/7403597/save.zip)

**Comment by miu135** [comment]
Seems like Undead_people's sprites are overwriting retrodays sprites

![cddaspritebugs3](https://user-images.githubusercontent.com/54433550/140242463-9121fb44-7762-4c88-a5ba-1fee179cff6b.PNG)

**Comment by olanti-p** [comment]
> Seems like Undead_people's sprites are overwriting retrodays sprites

Good catch! Turns out Aftershock's mod_tileset had misconfigured compatibility list, so the tiles that should've been loaded only for UDP and UltiCa were actually loaded for many other tilesets too, including RetroDays.
