### ISSUE TITLE
Baking Alive in Summer

### ISSUE THREAD

**Issue by Allmyusualnamesaretaken** [cataclysmbnteam/Cataclysm-BN#110]
# Describe the bug

I'm not sure what the exact cause is, but my character is reaching significant heat penalties in mid Summer even while completely naked and submerged in water.

# Steps To Reproduce

1. Load up a character in summer
2. Baked potato sim

# Expected behavior

Considering limited resources for reducing the effect of ambient temperatures on players and the generally mild nature of New England summers, low warmth scores should be more than sufficient to mitigate heat penalties from Summer weather.

# Screenshots

![ss1 heat bug](https://user-images.githubusercontent.com/49605446/96243101-45ff9c00-0f72-11eb-92db-1a005ac33e77.png)
![ss2 heat bug](https://user-images.githubusercontent.com/49605446/96243114-4ac45000-0f72-11eb-9b31-e2abf52d3066.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 1ab150f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Craftable Gun Pack [craftgp],
    Fuji's Military Profession Pack [fuji_mpp],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

[Blackrock.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5390682/Blackrock.zip)

**Comment by Kodiologist** [comment]
I've noticed this, too. Bright Nights was forked after my changes to CDDA to make temperature realistic, so the summer temperatures should be reasonable, but the game might be punishing the player too much given temperatures that aren't that bad in real life. Or, the new (actually throwback) default season length might be exposing a bug.

**Comment by MrOlaf** [comment]
Clothing with the model inherited from CDDA provides insulation. This is very buggy. The whole model for cold/heat insulation needs to be reworked. Just take off clothing and backpack :)

**Comment by Firestorm01X2** [comment]
Reference from DDA:
https://github.com/CleverRaven/Cataclysm-DDA/issues/43451

**Comment by Firestorm01X2** [comment]
@Allmyusualnamesaretaken Youcan try it after it builds. It should be more managable now. -5 degree colder. Downside is- winter nights also become colder, so wath out.
