### ISSUE TITLE
Packages of items can be cut up, destroying/transforming all contents in the process

### ISSUE THREAD

**Issue by ThinkInvis** [cataclysmbnteam/Cataclysm-BN#1104]
# Describe the bug

The "Cut up an item" action can be used on MREs, first aid kits, and radio car boxes (and likely other similar items). This will, without any warning, turn them into a few plastic chunks and nothing else.

# Steps To Reproduce

1. Obtain an MRE, a first aid kit, or a radio car box; and an item exposing the "Cut up an item" action (bug initially encountered with a scalpel).
2.
    a. Use the "Butcher" keybind while standing over the package item and select "Cut up everything" (more likely to come up in gameplay, e.g. dead soldier/medical zombies), or
    b. Use the "Cut up an item" action on the package item.
3. Observe that cutting up the package item resulted in ~1-5 plastic chunks, and that its valuable contents have been transmogrified into plastic or vanished.

# Expected behavior

As it stands, it's easy to accidentally miss and destroy a package item in a large stack while e.g. cutting up a zombie's clothing for salvage (especially MREs, which often drop alongside kevlar). It should instead be the case that:
- package items should not be compatible with the "Cut up an item" action,
- attempting to cut up a package item should result in a warning, or
- package items should drop their contents as part of the "Cut up an item" action.

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0.19042
- Game Version: dd8ef4b [64-bit], and also a custom build based on bee8a49 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]

**Comment by chaosvolt** [comment]
Adding the `NO_SALVAGE` flag to the affected items should fix them.
