### ISSUE TITLE
Crafting ANBC suit with plastic sheet

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#112]
# Describe the bug

Recipe for ANBC suit requires a plastic sheet. Plastic sheet can be crafted through crafting menu but the recipe for ANBC suit doesn't recognize it. Looking in debug menu i see there are two kinds of plastic sheets:
plastic_sheet - with which you can craft things
rigid_plastic_sheet - which doesn't show in any crafting recipes

# Steps To Reproduce

1. Make a character and give him all skills and recipes.
2. Spawn hazmat suit, arc welder, 800 duct tape, swat armor,  pair of metal tongs, crucible, sheet metal, electric forge, 200 plastic chunks
3. Craft plastic sheet
4. Try to craft ANBC suit

# Expected behavior

I would expect being able to craft ANBC suit with all items present but the item that i think i have is in fact a different item.
rigid_plastic_sheet and plastic_sheet shouldn't have the same name. Rename rigid_plastic_sheet to rigid plastic sheet in order to diferentiate these two items. Currently it is very confusing.

# Screenshots

![image](https://user-images.githubusercontent.com/72284934/96274532-e2588b80-0fd0-11eb-919a-071be461d0c7.png)
![image](https://user-images.githubusercontent.com/72284934/96276018-c1913580-0fd2-11eb-9662-36874e982e9c.png)
![image](https://user-images.githubusercontent.com/72284934/96274619-01efb400-0fd1-11eb-945d-594cd06317f4.png)
![image](https://user-images.githubusercontent.com/72284934/96274639-0ae08580-0fd1-11eb-9465-5f30311d1fe4.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: bee744c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by Coolthulhu** [comment]
Closed in https://github.com/cataclysmbnteam/Cataclysm-BN/commit/1f0b627535c01424965d4d4b70387e21de5ef809
(didn't make a PR because it's tiny)
