### ISSUE TITLE
after disassembling a straw hat or a straw basket made of birch bark, the character still receives straw

### ISSUE THREAD

**Issue by IvanGovnov** [cataclysmbnteam/Cataclysm-BN#1132]
# Describe the bug
After disassembling a straw hat or a straw basket made of birch bark, the character still receives straw
# Steps To Reproduce
1. take a sufficient amount of birch bark, you also need tailoring skill level 1
2. in the crafting menu, make a straw hat or straw basket using birch bark
3. disassemble the straw hat or straw basket
4.after disassembling, you will receive straw, although the items are made of birch bark
Expected behavior
after disassembling a straw hat or a straw basket, if they are made of birch bark, the player should receive birch bark, because this is logical
Screenshot
![Screenshot_20211113-173809_Cataclysm BN (experimental)](https://user-images.githubusercontent.com/58108687/141649361-ddf1f4ca-42c5-4418-9281-4a7a96fc80b3.jpg)
![Screenshot_20211113-173900_Cataclysm BN (experimental)](https://user-images.githubusercontent.com/58108687/141649370-d728a1c6-b224-4ccb-af3c-3b511f722424.jpg)
![Screenshot_20211113-173911_Cataclysm BN (experimental)](https://user-images.githubusercontent.com/58108687/141649393-18def495-3c08-4442-9ebe-88211376e319.jpg)
![Screenshot_20211113-174109_Cataclysm BN (experimental)](https://user-images.githubusercontent.com/58108687/141649401-db8670a7-2a98-4dee-8f29-f32e2255b87a.jpg)
![Screenshot_20211113-174114_Cataclysm BN (experimental)](https://user-images.githubusercontent.com/58108687/141649412-d7b7e4fc-1127-42ba-96fb-ec643d86c544.jpg)
![Screenshot_20211113-174152_Cataclysm BN (experimental)](https://user-images.githubusercontent.com/58108687/141649426-27a0a1f4-86f2-4a17-b3ec-84090e04fef0.jpg)
![Screenshot_20211113-174131_Cataclysm BN (experimental)](https://user-images.githubusercontent.com/58108687/141649435-c88f477a-4646-46c8-bf36-a5acfada2f29.jpg)

# Versions and configuration
 - OS: Android
 - Game Version: from the main menu, c02a963
 - Graphics version: Tiles Undead people 
 - Ingame language: English or Russian
 - Mods loaded: BN, Disassemble NPC needs,simplified nutrition

# Additional context
I propose to remove birch bark from possible materials for crafting a straw hat or birch bark and add a birch bark hat and a birch bark basket, which, when disassembled, would give birch bark

**Comment by chaosvolt** [comment]
The problem here looks like it's probably the item set to have an explicit uncraft recipe. So it would be perfectly reasonable to just remove that and designate the recipe itself as reversible, which would let it correctly return the right component and amount of it.
