### ISSUE TITLE
I just put a gun through locked gun safe

### ISSUE THREAD

**Issue by STAHP228** [cataclysmbnteam/Cataclysm-BN#1157]
It was like that: i thought what if my character will put gun in locked gun safe he will put on top of gun safe, but he actually put it through gun safe. And most interesting part, it that he can't take it back, like if gun was spawned inside safe.
![изображение_2021-12-02_005548](https://user-images.githubusercontent.com/95380386/144304470-25c29cb4-0487-44ca-af4f-91fd9ed3f7e1.png)
its how it looks when i try to pick up gun

**Comment by Coolthulhu** [comment]
I can't reproduce it. Any mods that could be redefining the safe?
Did you put it there with shift+D or some other method?

**Comment by Coolthulhu** [comment]
Couldn't reproduce
