### ISSUE TITLE
Autoclave tool sterilization require too much power.

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#1165]
Autoclave battery requirements should be double checked. Looks like sterilizing process require too much power.
![unknown2](https://user-images.githubusercontent.com/17512620/144757432-449a7ad5-b531-4262-ae0c-efcfd5daf5ed.png)

Translation:
What is wrong with the autoclave, it takes 8200 charge to start the working cycle
And a store for batteries, even a capacious heavy battery 2500
So what's this)
Am I doing something wrong? 
why, then, is it use batteries if it logically useless?

Autoclave tool used.

**Comment by Firestorm01X2** [comment]
Need double cheeking.

**Comment by Night-Pryanik** [comment]
Autoclave isn't designed to work through the batteries. It should be connected to some other, more powerful, power source, like a car.

If anything, it's the batteries-for-autoclave idea should be removed, it's power consumption looks like ok.

**Comment by chaosvolt** [comment]
Important side note: because the default storage battery used for grid batteries holds 7000 power, this value is going to need some sanity-checking even if we drop battery claves in favor of making the player plug it in.

**Comment by chaosvolt** [comment]
Additional side note: what the hell is going on with `power_draw`, codewise? It's supposed to be in milliwatts, but when I tinkered with fixing the broken bionic power cap via https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1071 none of the changes touched power_draw far as I can recall. Despite this, it appears to still be getting the right amount of battery charges, which is still 8200 kJ.

**Comment by chaosvolt** [comment]
Okay, so there is something weird going on with power_draw in the first place, in fact...
![image](https://user-images.githubusercontent.com/11582235/144773718-8c8b5fbc-d4d1-4bd4-b681-bdfd1c641491.png)

The amount of power consumed appears to be off by a factor of 100, not 1000 like you would expect.

**Comment by chaosvolt** [comment]
The weirdness observed above seems to no longer be present in current builds, so now I might eyeball the issue itself...
