### ISSUE TITLE
Pockets, hoods and wide collars do not warm unencumbered body parts.

### ISSUE THREAD

**Issue by stibbs109** [cataclysmbnteam/Cataclysm-BN#1167]
Game version: f54a109

Operating system: Windows 10

Tiles or curses: curses

Mods active: default mods only (Bright Nights, Disable NPC Needs, Simplified Nutrition).

### Expected behavior
Wearing clothing with pockets, hoods or wide collars will warm unencumbered body parts (hands, head, mouth respectively).

### Actual behavior
There is no change to the warmth value of these body parts when wearing clothing with pockets, hoods or wide collars.

### Steps to reproduce the behavior
I started a new game with the following setup:
Initial Day: 637 (Day 1, Winter)
Scenario: Wilderness
Profession: Landscaper

A landscaper profession character starts off wearing a windbreaker (has pockets, hood) and cargo pants (has pockets).
The character's head and hands were unencumbered (the work gloves were taken off and nothing was wielded).
When the character took off the windbreaker and cargo pants, there was no change in the warmth value of the head and hands.
Wearing just the windbreaker,  and then just the cargo pants did not change the warmth value of the hands.

I've also seen the same issue with the evac shelter's emergency jacket (has pockets, hood, wide collar). The wide collar of this jacket does not keep an unencumbered mouth warm.
As another example, the hood of a keffiyeh does not warm up an unencumbered head.

Many thanks to the Cataclysm BN team for this very enjoyable game! It's a real pleasure to play.

**Comment by Coolthulhu** [comment]
Confirmed, thanks for reporting.

Seems that `Character::bonus_item_warmth` is only checking items which actually cover the given body part. This means that hoodie would need to cover the head for this implementation to work and then it would make the hoodie warm the head twice as much as the rest...
Should be easily fixable.
