### ISSUE TITLE
Taste Modifier Bionic generates power instead of removing it.

### ISSUE THREAD

**Issue by Grave-Accent** [cataclysmbnteam/Cataclysm-BN#1168]
# Describe the bug

The Taste Modifier Bionic is a toggle-able Bionic that removes all negative joy modifiers from any food that has them, at the cost of a little bit of bionic power whenever you eat such a food while it is enabled, however it currently *restores* power for every piece of food eaten, which it shouldn't do.

# Steps To Reproduce

Create a character as the Bionic Monster, who starts with the Taste Modifier.

Do something that uses some of your Bionic Power.

Find a piece of food with a negative joy modifier, and activate your Taste Modifier.

Eat the food, and notice that you gain power instead of expending it.

# Expected behavior

Eating unenjoyable food with the Taste Modifier enabled should expend bionic power.

**Comment by Coolthulhu** [comment]
It sounds more interesting than its actual function, although still obviously a bug.
I'd probably just make the taste blocker cut the penalty by 75% at no energy cost.
