### ISSUE TITLE
Endgame lab not generating

### ISSUE THREAD

**Issue by Kodiologist** [cataclysmbnteam/Cataclysm-BN#117]
# Describe the bug

According to [the wiki](https://github.com/cataclysmbnteam/Cataclysm-BN/wiki/Changes-so-far), the endgame lab should generate around overmap (0, 0), but it doesn't.

# Steps To Reproduce

1. Create a new world with the default options and start a new character.
2. Long-range teleport to (0, 0).
3. Reveal the overmap, walking around a bit to generate more of it. Notice that in general, no lab is nearby on the surface level nor underground.

# Versions and configuration

I built the game from 04edad327c86bb7052f111a587cd85733d97efcb.

**Comment by Coolthulhu** [comment]
Check for access shaft on z=-1.

**Comment by Kodiologist** [comment]
It's all solid rock. The nearest lab square at z = -1 is far to the southwest.
![z-1](https://user-images.githubusercontent.com/322730/96451144-2623de80-11e5-11eb-813c-075de1370574.png)
There's a somewhat closer lab on z = -2. Is that it?
![z-2](https://user-images.githubusercontent.com/322730/96451167-2cb25600-11e5-11eb-9c13-f4b8db1a253c.png)

**Comment by Coolthulhu** [comment]
Try searching for access shaft on the whole `(0,0)` overmap.
That is, in the lower right, you have 3 coords: z-level, overmap (major), overmap tile (minor).
The finale is only supposed to be guaranteed on `(0,0)` overmap, but the tile coords themselves can be anything. For example, `0'0, 70'20` is a valid coord for it.

**Comment by Kodiologist** [comment]
Oh, I guess I was pretty confused. Are you sure the format isn't something like Level (z), (major x)'(minor x), (major y)'(minor y)? 0'0, #'# seems to be an infinite line of tiles on the north–south axis. By contast, 0'#, 0'# is finite and seems to have a few labs. What's a quick way to identify the endgame lab in debug mode?

**Comment by Coolthulhu** [comment]
> Are you sure the format isn't something like Level (z), (major x)'(minor x), (major y)'(minor y)?

You're probably right, I didn't check.
Either way, it's `(0,0)` on major that matters.

> What's a quick way to identify the endgame lab in debug mode?

* On overmap `(0,0)`
* Access shaft at z=-1 (AKA it's a central lab)
* No train connections
* Has a red-colored tile at the lowest z-level

**Comment by Kodiologist** [comment]
Thanks, got it. I added a few details to the description in the wiki.
