### ISSUE TITLE
Survivor packs have no warmth value

### ISSUE THREAD

**Issue by miu135** [cataclysmbnteam/Cataclysm-BN#1180]
Unless that's intentional

**Comment by Relgar** [comment]
This appears on purpose as the following survivor items do not have warmth values:

survivor duffel bag
survivor backpack
survivor rucksack
survivor runner pack

**Comment by Coolthulhu** [comment]
It makes them better in the summer and I don't think they need nerfs in the form of warmth.

I'll assume it is intended. Even if it wasn't, I think it's better this way.
