### ISSUE TITLE
Window with metal grate has infinite curtains

### ISSUE THREAD

**Issue by Soadreqm** [cataclysmbnteam/Cataclysm-BN#1181]
# Describe the bug

Windows with metal grates that generated at a mine entrance behave oddly in several ways. They are opaque and do not function as windows. They can be opened or closed with 'o' and 'c', but this does nothing. Most alarmingly, you can 'e'xamine the window to tear down the curtains over and over again, generating seemingly infinite amounts of sheets, strings, sticks and nails.

# Steps To Reproduce

1. Load attached save
2. Examine nearest window
3. Tear down curtains
4. Repeat

# Expected behavior

A window should only have a single set of curtains, and it should be possible to see through the window when the curtains are open.

# Versions and configuration

- OS: Windows 10 Pro N 2009
- Game Version: b153e66 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    No Rail Stations [No_Rail_Stations],
    Fuji's Military Profession Pack [fuji_mpp],
    Mythical Martial Arts [MMA]
]

# Additional context

[Faribault_curtains.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/7720371/Faribault_curtains.zip)

**Comment by Inglonias** [comment]
Similar bug was reported and fixed in DDA branch recently. https://github.com/CleverRaven/Cataclysm-DDA/issues/52782

**Comment by chaosvolt** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/53148 linked from that issue does not look like it actually fixes the root weirdness involving infinite curtains, because all it does is make mines not use the terrain that does that.

**Comment by olanti-p** [comment]
Fixed by #1409
