### ISSUE TITLE
Need to spawn protein drink-filled condoms in trash cans

### ISSUE THREAD

**Issue by EdgarMincuk** [cataclysmbnteam/Cataclysm-BN#1185]
I came up with a brilliant idea!  
A condom is a very useful container, it holds a lot, the volume and weight are negligible, but they come across extremely rarely (it would be very useful to make them spawn in trash bins, but fill them 1/15 with a protein drink) 
In my opinion it's just awesome! I represent the moral reflections of the gamer: "That is, we actually get 2 useful items: a container and a colorful drink, but it is psychologically difficult to take this thing out of the trash can, and even more difficult to drink the contents!"

**Comment by Coolthulhu** [comment]
lol wtf

**Comment by EdgarMincuk** [comment]
Hey, I am not kidding. This is part of the roleplay
