### ISSUE TITLE
Follower book reading activity interface is very disfunctional

### ISSUE THREAD

**Issue by RodriguesCIA** [cataclysmbnteam/Cataclysm-BN#1191]
Searching any term on the window will net 0 results, so you have to manually browse the books all the time. Furthermore, the color coding is based on your character's skills and attributes, rather than the target follower. This makes using this feature very awkward in comparison to the other fork.

**Comment by olanti-p** [comment]
> Searching any term on the window will net 0 results, so you have to manually browse the books all the time.

It's searching by localized skill name, not item name. Which is counter-intuitive and does not adhere to behavior of other similar UIs...

> Furthermore, the color coding is based on your character's skills and attributes, rather than the target follower.

Addressed by #1621
