### ISSUE TITLE
Create a Web Design For Main Website

### ISSUE THREAD

**Issue by rtizzy** [cataclysmbnteam/Cataclysm-BN#12]
See in title. 

We are requesting contributors with web design experience to help us create a proper website for Cataclysm: Bright Nights.

**Comment by mount2010** [comment]
Can manage basic Express + web stack. Probably won't be able to do this alone, and am completely able to help with PHP.

**Comment by elricsfate** [comment]
@mount2010 I think we've found a solution with a theme. Will likely use Hugo + After-Dark for now. Had an issue upstream that was just answered that should let me get most of it up :)

Do you know basic javascript and the like? It's mostly just javascript, css, html, and markdown.

**Comment by mount2010** [comment]
I can do all of that. Send me a DM on Discord - Mount2010#9649

**Comment by elricsfate** [comment]
@mount2010 Will contact you now

**Comment by elricsfate** [comment]
@mount2010 

Howdy I attempted reaching out via Discord but was unable to do so. 

Is there perhaps a better way to get ahold of you? If you'd like we can schedule a short meeting. I'm currently on Italian time and will be for the next 3 months. 

Let me know how I can help get you started. 

Thanks again for offering to help.

**Comment by mount2010** [comment]
@rtizzy Hey. Sorry for the late reply - are you sure you are unable to reach me via Discord? Please tell me your Discord username and discriminator.
