### ISSUE TITLE
.30-06 Springfield M2 AP, black powder problems

### ISSUE THREAD

**Issue by ProjectileWaterfowl** [cataclysmbnteam/Cataclysm-BN#1213]
There's a bunch of issues with _.30-06 Springfield M2 AP, black powder_. First, it should probably be named _.30-06 M2 AP, black powder_ because neither the reloaded nor the base ammunition add on the extra "Springfield." Second, it has only 2 armor penetration, which is worse than the 5 penetration that the regular _.30-06 Springfield, black powder_ has. For reference, the normal M2 AP has 18 armor penetration, and 5,56 black powder has 3. Lastly, it has the same description as all the _.30-06 Springfield_ ammo variants instead of the _.30-06 M2 AP_ like the reloaded version does.

**Comment by chaosvolt** [comment]
Rifle-caliber rounds in general have some weirdly low arpen values, and all blackpowder variants halve that already-low AP. The "blackpowder AP" issue sounds like either it's copying from the wrong item or whoever wrote the JSON for it set the value explicitly in an incorrect manner.

An overhaul of rifle-caliber arpen is part of what I want to tackle in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/359 but I keep putting it off because hashing out exactly how to handle things consistently is hard.

**Comment by Relgar** [comment]
.30-06 Springfield
.30-06 M14A1 tracer
.30-06 M2 AP
.30-06 Springfield, black powder
.30-06 Springfield tracer, black powder
.30-06 Springfield M2 AP, black powder
.30-06 Springfield, reloaded
.30-06 incendiary, reloaded
.30-06 M2 AP, reloaded

These are the strings that the ammo descriptions have - looks like there's a bit of a standardisation issue. Should it be ".30-06 Springfield" or just ".30-06"? If the latter, we can remove the word Springfield from all instances.

**Comment by ProjectileWaterfowl** [comment]
.30-06 Springfield
.30-06 Springfield, reloaded
.30-06 Springfield, black powder
.30-06 M2 AP
.30-06 M2 AP, reloaded
.30-06 Springfield M2 AP, black powder

The last one is the odd one out. Springfield is fine, like Winchester.

**Comment by ProjectileWaterfowl** [comment]
.30-06 Springfield
.30-06 Springfield, reloaded
.30-06 Springfield, black powder
.30-06 M2 AP
.30-06 M2 AP, reloaded
.30-06 Springfield M2 AP, black powder

The last one is the odd one out. Springfield is fine, like Winchester.

**Comment by Relgar** [comment]
I see the issue - the M2 AP BP ammo was derived from the normal .30-06 BP ammo, which means it's a worse version of an already worse ammo type. This bug would have persisted past the other changes. I'll make it derive from the normal M2 AP before applying all the BP modifiers (24% less dmg, 50% less AP, etc.). Does this sound like a suitable stopgap while we wait for the rebalance? New values should be 44 dmg, 9 AP. Worse than a normal .30-06 round, but better than the normal BP version.
