### ISSUE TITLE
NPCs are blind outside about 4 tiles

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#1219]
# Describe the bug

I noticed recently while cleaning out a next of bandits that they would wander in the direction of my gunfire but not actually charge me, and soon realized the ! indicator to show them as being able to see me wasn't popping up.

Later on I killed another hostile NPC via hit-and-run with a crossbow, and realized that the otherwise-unimpaired NPC was only able to see me if I got within 4 tiles or so, despite it being broad daylight.

# Steps To Reproduce

1. Find a bandit or other hostile NPC.
2. Check to see if it says they can see you.
3. Get about 10 tiles away, ideally in broad daylight.
4. Observe your lack of deadness.

# Expected behavior

For NPCs to be able to see however far out during daytime is considered normal range.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 60f5a6d [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Fewer Farms [Fewer_Farms],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Faster Stamina Regen [stamina_regen_buff],
    Manual Bionic Installation [manualbionicinstall],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Simplified Nutrition [novitamins]
]

# Additional context

**Comment by Coolthulhu** [comment]
Need re-test

**Comment by chaosvolt** [comment]
Retesting on:
```
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 25ad09d [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Elevated bridges [elevated_bridges],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall],
    Simplified Nutrition [novitamins]
]
```

I spawned in a bandit camp and walked around it until one of the bandits, roughly 30 tiles away, was in view. They pretty much immediately printed the "gets angry" message and started approaching me.

So I don't know what was going on in the previous version nor what could've changed to make them work just fine now.
