### ISSUE TITLE
Why do we have to compile this? isn't there a .exe or other way to install?

### ISSUE THREAD

**Issue by slingring** [cataclysmbnteam/Cataclysm-BN#1220]
# Is your feature request related to a problem? Please describe.
Im always frustrated that i have to compile programs (waste of time, and im no tech wizard) why cant we just install it like regular cdda?

# Describe the solution you'd like
No compiling crap or BS. I want to install the game like normal cdda.

# Describe alternatives you've considered
Not compiling it, Making this feature request

**Comment by Relgar** [comment]
I have never compiled this game, and as far as I know it's just either:

1. Unzip the ZIP file from the releases page (https://github.com/cataclysmbnteam/Cataclysm-BN/releases) and just run the exe, or 
2. Use a launcher like Catapault (https://github.com/qrrk/Catapult/releases) to install and handle your exe / mods for you.

**Comment by slingring** [comment]
Yeah.. nevermind, i had to find those links through some sneaky hidden area..
why isn't it just slapped in and compiling more hidden?
