### ISSUE TITLE
Trying to steal anything which has a 'charge' via the Advanced Inventory Management screen immediately empties the charge

### ISSUE THREAD

**Issue by Relgar** [cataclysmbnteam/Cataclysm-BN#1221]
# Describe the bug
Came across a Survivor's camp, tried to steal a 24/24 Oxygen tank via the AIM. Normally this simply results in the item not moving (you have to manually pick it up and go through the menu confirmations for stealing / speaking to the person who saw you stealing). Instead, this emptied the container to 0/24 (and also didn't move). Same thing occurred with an Oxygen Emergency Pack (12/12 to 0/12)

# Steps To Reproduce
1. Steal any owned item that has charges
2. Observe emptied cartridge

# Expected behavior
Item should not empty.

**Comment by olanti-p** [comment]
Fixed by #1582
