### ISSUE TITLE
Oddities when Building on open windows

### ISSUE THREAD

**Issue by Allmyusualnamesaretaken** [cataclysmbnteam/Cataclysm-BN#124]
# Describe the bug

Vehicle construction allows me to build a frame on top of an open window, and it functions as normal until I leave and reenter, causing the reality marble to reposition it so it's outside/clipping into solid objects and generally misbehaving when "g"rabbed and moved.

# Steps To Reproduce

1. Place a vehicle construction outside an open window
2. Add a frame that goes on top of the open window's tile, then more on the inside of the wall
3. Leave the area and go far enough that the construction is outside of the reality marble
4. Return, and reap your eldritch physics

# Expected behavior

I think it would be appropriate for constructions to not be moved supernaturally on area reload, or alternatively, that vehicle construction would disallow building on window tiles if that causes issues.

# Screenshots

Sorry, forgot to take one, here's a drawing

What I built: H is vehicle frames, - is the open window with a frame on it, + is the closed window south of it, | is a wall
H-H
H+H
H|H

# Versions and configuration

- OS: Windows 10 x64 Home
    - OS Version: 10.0 2004
- Game Version: bee744c [64-bit]
- Graphics Version: Tiles
- Game Language: System language [American English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Sorry this bug report is as janky as my vehicle wizardry, let me know if I can provide any more useful info.

**Comment by Coolthulhu** [comment]
The quickest fix may be to just forbid building vehicles on tiles not passable by vehicles.

**Comment by Allmyusualnamesaretaken** [comment]
I was honestly confused when it allowed it in the first place. You can't build vehicles onto counters or walls, it seems like an oversight that we can do it on window frames. Removing that ability would be no great loss.
