### ISSUE TITLE
Hyper Metabolism is non functional.

### ISSUE THREAD

**Issue by PsyXypher** [cataclysmbnteam/Cataclysm-BN#1255]
# Describe the bug
As the title says, Hyper Metabolism does not prevent you from vomiting, heal you or skip prompt for overeating.

# Steps To Reproduce

1. Get a character with Hyper Metabolism and some damage taken and eat until you are full. 

# Expected behavior

Expected Behavior is that the Chimera Mutant will not get a prompt for overeating and instead will turn excess nutrition into hit points, healing themselves. 

# Additional context

User Hardline Mike claimed that the Hyper Metabolism check is after the vomit/overeat check in consumption.ccp, which is probably a good place to check.

**Comment by chaosvolt** [comment]
https://github.com/cataclysmbnteam/Cataclysm-BN/issues/312 :V

**Comment by PsyXypher** [comment]
Whoops. 

> #312 :V

**Comment by olanti-p** [comment]
Should be fixed by #1292
