### ISSUE TITLE
Partial reloading does not work

### ISSUE THREAD

**Issue by Soadreqm** [cataclysmbnteam/Cataclysm-BN#126]
# Describe the bug

The "reload" and "part reload" actions for gun magazines do the exact same thing, i.e. fully load the magazine with all available ammunition. The only way to load a magazine partway is to drop some of your ammo or put it in a bandolier to break the stack. This is fairly inconvenient when reloading in the middle of a firefight.

Also, if the loading is interrupted at any point, nothing is loaded into the magazine. The action must be fully completed for any bullets to go in. This is a separate problem, but somewhat related.

# Steps To Reproduce

1. Obtain an empty gun magazine and some ammo
2. Attempt to partially reload the magazine
3. The magazine is fully loaded

# Expected behavior

The "part reload" option should either prompt for a number of rounds to load into the magazine, or only load a single round.

Alternatively, the "part reload" option could be removed, since it apparently does nothing.

# Versions and configuration

- OS: Windows 10 Pro N 2004
- Game Version: 6ff0a54 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Coolthulhu** [comment]
Can't reproduce.
Tried this:
* Spawn glock 17
* Unload glock
* Unload magazine
* Reload magazine, set ammo to 14, confirm
* Magazine has 14 ammo
* Reload glock with magazine
* Reload glock with 2 ammo
* Glock has 16 ammo (out of 17)

**Comment by olanti-p** [comment]
Looks like UI issue.

It was reproducing fine for me until I accidentally pressed left arrow and discovered that this menu allows changing amount to reload.
![image](https://user-images.githubusercontent.com/60584843/107888693-fed4e800-6f1e-11eb-9af6-ab7a4deb4cfe.png)
This is not stated anywhere, even in the `?` screen for this menu.

**Comment by Soadreqm** [comment]
Can confirm. Partial reloading does work, I just couldn't figure out how to do it.
