### ISSUE TITLE
Add a way to get rid of the red words on IOS

### ISSUE THREAD

**Issue by TheFIREgamer15** [cataclysmbnteam/Cataclysm-BN#1278]
So what ive seen so far is there is no way to get rid of the red letters, may you please add it in settings or notify me if there is a way to get rid of it. Thank you

**Comment by Coolthulhu** [comment]
Settings -> Colors, in main menu

**Comment by TheFIREgamer15** [comment]
Does it also get rid of the text whole to?

**Comment by olanti-p** [comment]
If you mean "Craft"/"Combat"/"Inventory/" entries on the right side of the screenshot you posted on discord 
![IMG_6213](https://user-images.githubusercontent.com/60584843/150215373-bbb4986f-3704-4e18-b37b-7fb09fd71944.png)
then you'll have to ask the author of the IOS app, as we have nothing to do with it.
