### ISSUE TITLE
Cataclysm BN does not start on mac m1

### ISSUE THREAD

**Issue by koltsovm** [cataclysmbnteam/Cataclysm-BN#1297]
I downloaded the version for mac os with tiles from the releases page. It does not start on my macbook with m1 . I moved the icon to the programs and launched it. The game icon appears in dock and immediately disappears. That's all.

At the same time, the version with curses started without problems.

**Comment by Coolthulhu** [comment]
A potential fix was merged recently. Does it happen with latest release as well?

**Comment by Coolthulhu** [comment]
Assuming it's fixed.
