### ISSUE TITLE
Infinite curtain bug

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#1308]
Found a weird one this time. In the living quarters of a mine I found at least one window that I can keep pulling the curtains down from. Each time I get all of the drops from pulling down a curtain (sheets, stick, long string) but the curtains are still there so I can do it again. Save game file is attached. My character is standing directly in front of the window this is happening with. I think it might have to do with it being a "window with metal grate".

I'm currently using the following mods:

"dda",
"no_npc_food",
"novitamins",
"elevated_bridges",
"a_mutated_arsenal",
"Tolerate_This__",
"bio_recipes",
"CBM_Arms",
"Uekibati_mod",
"growable-pots__",
"eps_cbm",
"makeshift_stuff",
"Survivors_Lost_item",
"food_irradiator",
"hydroponics__",
"mutant_npcs__",
"wandering_masters",
"WHALEYHAIR1",
"P_Caches",
"morlock_village",
"deoxymod__",
"shrub_mod",
"mxoudpcosmetics",
"zets_hair_extensions_undead",
"Mutation_Changes",
"stats_through_kills",
"StatsThroughSkills",
"ArmUpPAUtil",
"ArmUpSurvEx",
"makeshift_engine_hoist_mod",
"pressure_weapon",
"SM",
"more_survivor_stuff",
"recruitment_options",
"Dorf_Life",
"amplified_players_features",
"aftershock",
"Integrated_Fusion_Blaster"

[Taberville.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/7990897/Taberville.zip)

**Comment by dyxxzgc** [comment]
Same. Found this bug on 9941f2b.
Pretty sure it's not related to mods. Because I only enabled Bright Nights [dda]

**Comment by SaintCirno9** [comment]
Should be fixed by #1409.
