### ISSUE TITLE
Benches, flowers, small bushes, flowers, kitchen counters etc seem to be blocking light/sight completely

### ISSUE THREAD

**Issue by sappergr** [cataclysmbnteam/Cataclysm-BN#1336]
Game version:Latest experimental

Operating system: Ubuntu 21.10

Tiles or curses: tiles

Mods active: none

### Expected behavior
-
### Actual behavior
A kitchen counter, a bench or a flower should not block sight and light completely.
### Steps to reproduce the behavior
-

**Comment by chaosvolt** [comment]
Can now confirm this:
![image](https://user-images.githubusercontent.com/11582235/153799515-6a24acca-1b45-43fe-98eb-4233da504ef8.png)

**Comment by chaosvolt** [comment]
Most, if not all, furniture seems to be affected by this.

**Comment by chaosvolt** [comment]
Tested release https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2022-02-10-1039 and bug wasn't present, bug was introduced by the release right afterward, https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2022-02-10-1150

My tentative guess, not a well-informed one given my lack of C++ experience, is POSSIBLY from `transparent = false;` being moved into a different part of mapdata.cpp: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1307/files#diff-7abae324ade4ea2e8fcdcea7ba39c8f52c1df21ba2664abe503935ee4af9031aL1281

**Comment by Coolthulhu** [comment]
This is what happens when you don't playtest enough...
Will try to fix asap
