### ISSUE TITLE
Perpetuum mobile cows: the quest for infinite milkies

### ISSUE THREAD

**Issue by tyrael93** [cataclysmbnteam/Cataclysm-BN#134]
# Is your feature request related to a problem? Please describe.
Cows shit out milk on a timer, do not need any kind of maintenance, don't need to be fed and in return their milk is always fresh and stored in their quantum udders to be readily enjoyed at a moment's notice even if you haven't milked that cow in the last few months, essentially letting you live on a pure milk diet if you find a dairy farm or just find a couple wild cows if you so wish.

# Describe the solution you'd like
I understand that this is more of a personal gripe than anything, it would be tedious to add animal micromanagement to the game for the sake of realism: the only way I had any experience with balancing this was before animals could be milked and you had to custom craft NPC mutations, which would suck up the NPC's hunger and thirst every time you activated one of their mutations. Implementing this on every milkable animal would be a hell of a lot of work for very little gain. Maybe consider adding the "milkable" flag only after the animal has been bred? This would both fix the infinite food issue and at the same time incentivize farming, you'll get the nutrition from the slaughtered calf /or cow if you wish to wait for it to grow up) instead of the infinite supply of milk, which will run dry after several months. A cheap dirty way would most likely to make the animal "evolve" into a "pregnant" variant with a timer that would re-evolve it into a regular cow and adding the "milkable" flag to the "pregnant cow" instead of the regular cow, unlike now where you just turn them friendly and milkable by giving them cattle fodder.

# Describe alternatives you've considered
Just like don't milk cows naga haha like just don't craft the cattle fodder is that so hard

# Additional context
SAMPLE TEXT

**Comment by Coolthulhu** [comment]
> Maybe consider adding the "milkable" flag only after the animal has been bred?

This wouldn't solve the problem. You'd still have infinite food, just with more tedium. Unless cow impregnation required finding uncraftable items because all bulls in the world died or something.

My ideas:
* Have all living cows be considered mutants that produce milk with mutagenic toxins
* Get rid of milking mechanics
* Have cows turn grass tiles into dirt tiles every x turns or retroactively if loaded. If they can't turn enough nearby tiles from grass to dirt, they're considered starving and produce less milk, possibly making the milk counter negative.
* Cows become skittish and are only milkable after giving them cattle fodder. Every time you want to milk them.

**Comment by DrPariah** [comment]
It feels like a non-problem, really (and the OP said as much). Milk is perishable, needs pasteurized/cooked if you don't want to get sick, and takes a fair amount of time to dehydrate it which AFAIK can't be delegated to an NPC like you can with a faction base kitchen and pemmican. Basically, if you want the benefits of it you have to put in a fair amount of work. Stopping infinite milk is more the kind of thing that would go in the main fork of C:DDA and fits their simulation philosophy better than BN, though it'd be a fine mod. 
That being said, IMO, out of the proposed solutions above, the 'fairest' one would be Cattle Fodder to Milk. That's a resource conversion, and it's not impossible to get extra fodder suitable stuff for the dedicated dairy farmer.
--
Sent from myMail for Android Saturday, 24 October 2020, 04:49AM -05:00 from Coolthulhu  notifications@github.com :

**Comment by tyrael93** [comment]
I kinda like the toxic milk idea, pretty easy to implement as a .json edit.
Thanks.
