### ISSUE TITLE
Cutting logs into planks does not work with a wooden axe.

### ISSUE THREAD

**Issue by sappergr** [cataclysmbnteam/Cataclysm-BN#1346]
# Describe the bug

Cutting logs into planks does not work with a wooden axe.
# Steps To Reproduce

shown in screenshots

# Expected behavior

# Screenshots

https://imgur.com/a/77g4cvs
# Versions and configuration

 - OS:Ubuntu 21.10
 - Game Version: 4203108
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: default
# Additional context

**Comment by chaosvolt** [comment]
In the example video, you weren't standing on the same tile as the logs to be cut. It's a weird, janky limitation from the old days that survives to this day in both versions if I recall.

**Comment by sappergr** [comment]
> In the example video, you weren't standing on the same tile as the logs to be cut. It's a weird, janky limitation from the old days that survives to this day in both versions if I recall.

You are right, I guess I will close this one.
