### ISSUE TITLE
Huge characters with narcosis or have deadened mutation suffer pain in vehicle

### ISSUE THREAD

**Issue by Ruse-Stack** [cataclysmbnteam/Cataclysm-BN#136]
# Describe the bug

A medic post threshold character with freakishly huge and deadened mutation traits still experience pain and cramp messages while driving in a vehicle. Likewise, if I have the character use anesthetics and be under the narcosis effect, they would still accumulate pain while setting in a vehicle seat with controls.

# Steps To Reproduce

# Expected behavior

A character with the deadened mutation or is under the narcosis effect shouldn't accumulate any pain or proc the cramp messages while in a vehicle.

# Screenshots
I think I narrowed down the issue in character.ccp, BN code is on top while CDDA code is on the bottom, it seems like a simple fix.

![huge_pain_comparison](https://user-images.githubusercontent.com/73375696/97067939-e49e8500-1590-11eb-8ba9-4dc1d2bc711d.png)

# Versions and configuration

# Additional context

**Comment by olanti-p** [comment]
Pulling CleverRaven#41011 should fix this?
