### ISSUE TITLE
Odd basement generation

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#1365]
![Raymon 'Leodiensian' King __18-10-30_Eastern Standard Time](https://user-images.githubusercontent.com/24395352/155766321-a9e29da7-9c5c-498e-aa28-7b12461f31dd.png)

As seen in the screen shot this room in the basement generated with the door facing the wrong way blocking access to the room. I had to knock a hole in the wall with a homewrecker to get in. If it had hidden some secrets it might almost have made sense, but the contents of the room were normal basement stuff. Save included as well as the screenshot.

[Biggsville.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/8143338/Biggsville.zip)

The mods I'm using are:

[
  "dda",
  "no_npc_food",
  "novitamins",
  "elevated_bridges",
  "Arcana",
  "More_Bandits",
  "deoxymod__",
  "SzQmod",
  "Nonperishable_Overhaul",
  "drystack",
  "stats_through_kills",
  "StatsThroughSkills"
]

I don't _think_ anything but Arcana modifies basements or houses and this does not seem to be an Arcana related basement or house.

**Comment by Proxiehunter** [comment]
Well that was a terrible screenshot. How do I take a proper one in Bright Nights? I tried to hit print screen but for some reason only got the start screen, not the actual screen I was on.

**Comment by Coolthulhu** [comment]
On windows? Try print screen and pasting into paint. If it doesn't work, ctrl+print screen, alt+print screen, shift+print screen, with a paste to paint between each.

**Comment by Proxiehunter** [comment]
Windows yes, sorry. Print screen and pasting is what got me a shot of the start screen instead of my game in progress. Not sure how. Next time I'll try adding the other button presses. The attached save though should be right in the strange room.

**Comment by chaosvolt** [comment]
One thing that'd help here is if the debug map editing menu had some way to print the mapgen ID of the affected location, that'd make it easier to narrow down which place it is. I think DDA has SOME way to get the mapgen ID of a place but not sure what PR introduced it.
