### ISSUE TITLE
Temperature generation doesn't take eternal season into account

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#1373]
# Describe the bug

Temperature generation ignores seasons. It only cares about "percentage of year". Eternal summer will still be cold on "winter days".

# Steps To Reproduce

1. Create a world with season length 14, starting date 21, eternal season set
2. Start game in this world
3. Verify it is summer
4. Check temperature outside - should be sensible for summer
5. In debug menu, change current turn to 1, then change day to 49 (`14*3 + 7`)
6. Wait a few turns for temperature recalculation to happen
7. Check temperature again - it will be too cold for summer, more fitting for winter

# Expected behavior

Eternal season should disable seasonal temperature variation, setting temperature to mid-season one.
Alternatively, min and max temperature for a season should be calculated, then the seasonal temperature should follow a `sin/cos`-like curve, starting and ending the season at the same temperature.

# Screenshots

# Versions and configuration

# Additional context

Debug menu date change is bad when seasons are eternal. It pretends that `season` doesn't change, but you need to change day to `season_length + 1` 4 times for year to go up by 1.
Would be better to have it be enabled and show "underlying season", just with a note that eternal season is on and "effective season" is some number.

**Comment by Fruitybite** [comment]
In DDA, it seems this problem had already been solved (https://github.com/CleverRaven/Cataclysm-DDA/pull/54100)

I tried to port this to BN in past, but it was too hard for me :(
