### ISSUE TITLE
Permanently Chilly

### ISSUE THREAD

**Issue by RodriguesCIA** [cataclysmbnteam/Cataclysm-BN#1375]
At some point I got Chemical Inbalance and got Feeling Cold before I was able to purify it. However, now my character is stuck feeling Chilly. I assume it is because of the Eyes being at temp -30.

**Comment by Coolthulhu** [comment]
Yep, looks like Chemical Imbalance can cause it:
```C++
add_msg_if_player( m_bad, _( "You suddenly feel cold." ) );
temp_cur.fill( BODYTEMP_COLD );
```
No checks for eyes in there and temperature code skips eyes rather than resetting them.

For a quick fix, you can debug in the "HVAC" mutation, wait one turn, then un-debug it. This will reset all body temperature to comfortable.
