### ISSUE TITLE
Ammo conversion mods don't allow using new ammo, still allow using old ammo

### ISSUE THREAD

**Issue by RodriguesCIA** [cataclysmbnteam/Cataclysm-BN#1377]
What is said on the tin, the gun even show the stats but whenever it got Blackout ammo in it, it just refuses to fire, which is a shame as it could be a decent intermediate round between 223 and 308 (223 ammo capacity with a bit more of a punch).

**Comment by chaosvolt** [comment]
So I looked into this, and the issue seems to be that `ammo_modifier` doesn't seem to be working right, either that or it wasn't designed with magazine modifiers in mind and thus a system where a magazine can accept multiple ammo types just doesn't work right with it.

**Comment by Coolthulhu** [comment]
I'll change it to a broader problem, since it also happens with M27 IAR modified to use 300 blackout.
