### ISSUE TITLE
Prototype Cyborg can't walk through an open Secret Door tile

### ISSUE THREAD

**Issue by RodriguesCIA** [cataclysmbnteam/Cataclysm-BN#1390]
I checked for clothing, I checked if my implants had anything to do it, and I am not Large yet. I get no error message or anything, upon being ordered to walk through the door my character spends the time and creates noise but doesn't actually move.

**Comment by Coolthulhu** [comment]
Fix should be in the newest version, but Windows builds are broken at the moment.

**Comment by Coolthulhu** [comment]
I'm assuming it's fixed now.
