### ISSUE TITLE
Graphics bug with installed storage battery for electric grid

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#1393]
Installed a storage battery to expand the power available to my base in an evac shelter. It's to my characters left in this screenshot.

![Untitled](https://user-images.githubusercontent.com/24395352/157536594-81b64766-7e5a-42b4-8304-3dbbe39f9df5.png)

As you may be able to tell that is a _locker_. Now it's not a huge deal because it functions as a storage battery should be functioning; however this issue may startle and confuse new players who might think they've wasted the resources used so if the reason for the graphical glitch can be found and corrected it would be a good idea. I assume it should look like the one that comes with the evac shelter but for some reason it looks like _that_ instead.

**Comment by chaosvolt** [comment]
It's a looks_like issue, combined with Boophis and Firestorm still working on getting the revived UDP project ready for an update to BN's version. In the meantime, setting its looks like to use the smaller battery furniture should fix it.
