### ISSUE TITLE
Items can't used as tools and matterial in the same crafting/building recipe

### ISSUE THREAD

**Issue by Kuyumi0** [cataclysmbnteam/Cataclysm-BN#1408]
# Describe the bug

items can't used as tools and material in the same crafting/building recipe

# Steps To Reproduce

1. gather the items needed for a crafting recipe where one of their materials could be used as tool. Ex: Stone hammer made using two rocks. 
2. Rock is detected as a tool but excluded as material independent of amount 
3. Item cannot be crafted unless another item is used for the tool quality

# Expected behavior

Only the item being used as tool is excluded, any other extra copies are still valid for use

# Screenshots
![1](https://user-images.githubusercontent.com/102199822/159613990-248d3fd9-eaae-4605-9113-8502655c1414.png)
![2](https://user-images.githubusercontent.com/102199822/159614010-e802c8fe-5215-4dc4-be8c-fe1f8a878cea.png)

# Versions and configuration

 - OS: Windows 7
 - Game Version: cbn-windows-tiles-x64-msvc-untranslated-2022-03-22-0809
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Disable NPC needs, Simplified Nutrition, Elevated Bridges

**Comment by chaosvolt** [comment]
Some other things that were observed during testing of this:
1. Splitting a stack of rocks up, and spawning two separate stacks, did not fix it.
2. A similar issue was found with soldering irons, even when an unloaded one was available:
![image](https://user-images.githubusercontent.com/11582235/159618095-e9016957-b4fc-4634-9bca-6cac121b16d9.png)
![image](https://user-images.githubusercontent.com/11582235/159618102-5de9deda-f046-4882-a1af-d261d7080b6f.png)

Possible side effect of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1386 maybe?

**Comment by SaintCirno9** [comment]
The soldering irons problem existed  long before #1386, I used to edit the construction recipe to solve that.
Might be other part in the code, I'll try to solve that if I have time.
