### ISSUE TITLE
Multiple freezes since build 2022-03-23-0754

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#1412]
In general the build has greatly increased how fast the game is, but I've noticed that I tend to periodically freeze when reading books, dragging large amounts of items on the ground, and batch crafting. The game resumes after a few minutes (actual solid _minutes_ not an exaggeration).

This _could_ be due to large amounts of clutter near my base, however I've had freezes while dragging items in the near by town that should be distant enough that my base shouldn't be effecting it. Also I've only noticed this behavior since build 2022-03-23-0754 and the clutter should not have noticeably increased since then.

Mods in use currently are:

[
  "dda",
  "no_npc_food",
  "novitamins",
  "elevated_bridges",
  "Arcana",
  "mutant_insects",
  "mutant_npcs__",
  "deoxymod__",
  "SzQmod",
  "Tankmod_Revived",
  "StatsThroughSkills",
  "stats_through_kills",
  "Nonperishable_Overhaul"
]

If there's a good way to get rid of large amounts of unburnable clutter (like all this damn soil!) aside from running it over with a large vehicle that might help my issue if it's base clutter but I don't know what those ways are. I've been able to damage items to XX damage level through the debug menu but not past that to destroyed.

_Really_ don't want to abandon base and go full nomad to escape the freezes at the moment. In the near future I'm planning to do a "how to play Bright Nights" Youtube series and I wanted to do a deep dive into the faction camps system first so I can see what's actually good to do.

Definitely recommend starting a camp and at least getting a station set up for cooking. Once you do that you can send NPC's out to hunt instead of just hoping you run across a big animal.

Save file attached.
[Range.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/8353146/Range.zip)

**Comment by Proxiehunter** [comment]
We can add while sleeping to the times where the freeze can happen.

**Comment by SaintCirno9** [comment]
This is a problem of overmap pathfinding.
There is an "infinite" loop in `find_overmap_path`. Not actually infinite, but takes a long long time.
![image](https://user-images.githubusercontent.com/33447021/160226283-b78af4df-2c31-477f-bfbe-904c571b1f02.png)

So it is nearly half a minute for 10000 hits after 70000.
The time required increases linearly though.
![屏幕截图 2022-03-26 135344](https://user-images.githubusercontent.com/33447021/160226967-106d654a-0f4a-4a8a-a98f-88f3fb59e2bf.png)

More than 100000 times to return.
![屏幕截图 2022-03-26 135758](https://user-images.githubusercontent.com/33447021/160227005-fabd8faa-aecd-4bcf-8a22-60fce4c00880.png)

Maybe 4 minutes per npc?

Must be something wrong, but need some time to figure out what is going on.

**Comment by Zireael07** [comment]
Hm, I recall a PR in CDDA that fixed/ameliorated a similar issue.

**Comment by SaintCirno9** [comment]
I find an issue that may be same as this one  [CleverRaven/Cataclysm-DDA#54683](https://github.com/CleverRaven/Cataclysm-DDA/issues/54683#issue-1111745735)

**Comment by Coolthulhu** [comment]
> There is an "infinite" loop in find_overmap_path. Not actually infinite, but takes a long long time.

It's most likely to happen when an NPC tries to path to an unreachable location, like an island.

**Comment by SaintCirno9** [comment]
Not really. In fact this happens when npc tries to find an overmap location in different z-level.

**Comment by Proxiehunter** [comment]
> In fact this happens when npc tries to find an overmap location in different z-level. The algorithm here may need some optimization. I wonder if a bidirectional A* could help.

Presumably the attempt terminates at some point and they stay put otherwise the loop would be _actually_ infinite and I would have to reboot my computer (can't even alt tab out or open the task manager when this happens). Would a quick fix that causes the loop to terminate _sooner_ so that it turns into a minor hiccup of under a minute instead of multiple minutes be possible while a more thorough fix is underway?

**Comment by Trokinos** [comment]
Hello, i do not know if this is the exact same type of freeze, but in case i add it in this report.  
Playing "cbn-windows-tiles-x64-msvc-untranslated-2022-03-23-0754" on my window 10 , using these mods :  
  "dda",
  "no_npc_food",
  "novitamins",
  "elevated_bridges",
  "no_hope"

 i got 2 freezing with the log saying anything during that current run (world created in this version, it's not an older save)
1 during crafting some crude arrow : https://i.imgur.com/C4AVZBd.jpg
1 during sleeping in an abandonned shelter underground :  https://i.imgur.com/WMSsJId.jpg
  
I have crafted arrows and slept many time already in this version without problems, and reloading the last save and have not managed tor reproduce those freezes when trying to reproduce the actions in the same locations

**Comment by SaintCirno9** [comment]
> Would a quick fix that causes the loop to terminate sooner so that it turns into a minor hiccup of under a minute instead of multiple minutes be possible while a more thorough fix is underway?

Simply decrease the pathfinding radius may do that. Currently the radius is 720 overmap tiles.
But I don't think that is the best solution though.

**Comment by SaintCirno9** [comment]
This situation can be reproduced in a sense.
Just open the debug menu, go to "Map", then "Reveal map".
Make sure you are in floor 0. Open the world map, go up by press <, use "W" to set destination to any visible location. Then the freeze will happen, but not as bad as this one, since the revealed map is much smaller than a npc could use.

**Comment by Proxiehunter** [comment]
> > Would a quick fix that causes the loop to terminate sooner so that it turns into a minor hiccup of under a minute instead of multiple minutes be possible while a more thorough fix is underway?
> 
> Simply decrease the max search count may do that. Currently is 100000. But I don't think that is the best solution though.

I didn't think it was ideal, just a quick fix that could be reverted when a better solution was found. But it looks like a better solution was found quicker that I thought it would be. I know NPC behavior espesially pathing is complex and expected a full proper solution to take longer.
