### ISSUE TITLE
Clothes don't warm

### ISSUE THREAD

**Issue by seerdecker** [cataclysmbnteam/Cataclysm-BN#1417]
Game version: 
2022-03-23-0754

### Expected behavior

Wearing wool socks should increase feet temperature -- it doesn't. If I wear an helmet liner with an army helmet, the head temperature increases if I remove the helmet.

**Comment by SageB** [comment]
This is happening with me as well. 4 scarves and a balaclava, and my mouth is still getting frostbite.

**Comment by Proxiehunter** [comment]
On the other hand I'm on winter day four and comfortable outside while it's snowing. What _kind_ of scarves are they? There are multiple kinds and for some of them I don't think stacking four is as much warmth as the single fur scarf I'm wearing.

The wool sock thing though definitely sounds like an issue, as well as army helmets apparently making the head _colder_ in the OP's case if this can be duplicated.

**Comment by Coolthulhu** [comment]
The bug is that they don't stack well enough. I think only the best item on the body part works. I'm fixing it right now.

**Comment by seerdecker** [comment]
I reviewed the PR. I saw the change for max instead of sum. I'm still wondering why removing the army helmet increased the helmet temperature prior to this PR. Either way, both of _from_clothing()_ and _bonus_from_clothing()_ should be increasing (sum) or at worst staying the same (max) when more items are worn. I'll test it when the PR is merged. Apparently there are no build artifacts for unmerged PRs, and I'm too lazy to build it on Linux. Thanks for working on this!

**Comment by seerdecker** [comment]
Request to re-open this bug. This is not fixed as of 2022-04-03-1526. If I wear an helmet liner with an army helmet, the head temperature increases if I remove the helmet.

Head temperature with helmet: -11
Head temperature without helmet: 30

Day 3 of winter, normal season length.
Reproduction: I suggest debug-spawning army helmet & helmet liner and see what happens. If it doesn't reproduce, let me know.

**Comment by seerdecker** [comment]
*Update* On further testing, there's an interaction with the hood from a ski jacket. The helmet increases the head temperature but only if I remove the ski jacket first.

**Comment by seerdecker** [comment]
Another thing. Outdoor temperature is -9C, I'm wearing a wool scarf with warmth=50, and my mouth temperature is -17. The warmth scaling seems off.

**Comment by Coolthulhu** [comment]
> Update On further testing, there's an interaction with the hood from a ski jacket. The helmet increases the head temperature but only if I remove the ski jacket first.

Does the jacket say it has a hood? As in, not in description, but in the flag section where good parts are noted as green.
Hoods work like this: when your head encumbrance total is 9 or lower, the best hood warmth is added as "bonus warmth" to head. Bonus warmth only applies if your head is colder than midpoint of comfortable.

**Comment by seerdecker** [comment]
My bad. Wearing the helmet prevents the hood from the ski jacket from working, and thus it's normal that the head tempeature decreases then. Sorry for this. The tempeature scaling stills seems off though.

**Comment by Coolthulhu** [comment]
> Wearing the helmet prevents the hood from the ski jacket from working

I just realized hoods are a rather arcane mechanic. Might be better communicated.
> The temperature scaling stills seems off though.

I'll need some specific examples. It may be off, but I can't tell without anything to do math on.

**Comment by seerdecker** [comment]
> I'll need some specific examples. It may be off, but I can't tell without anything to do math on.

>> Outdoor temperature is -9C, I'm wearing a wool scarf with warmth=50, and my mouth temperature is -17.

Is this sufficiently specific, or do you need something else?

> I just realized hoods are a rather arcane mechanic. Might need to be better communicated.

To me it's clear enough, I just didn't realize that my ski jacket had a hood - my RL one doesn't - and I forgot to account for it. Oops! :-)

**Comment by seerdecker** [comment]
I have this theory that the reported temperature might be a little misleading in the UI.

This is my equipment list.
![image](https://user-images.githubusercontent.com/12588992/161437741-de35b23f-9adf-4c23-98a4-05267606e117.png)

This is the reported tempeature.
![image](https://user-images.githubusercontent.com/12588992/161437788-220b1b4c-7cd3-4ee7-bd0e-6aa45d31be32.png)

Hands warmth is glove liners (15) + white gloves (30) => total 45 (using baseball bat, so no pockets involved here).
Scarf warmth (50) => total 50.

Yet both body parts (hands, mouth) show up with -17 warmth in the UI. Perhaps the game is adjusting temperature under the hood to make the parts confortable. I'm unfamiliar with BN's new tempeature handling and the code is complex.

**Comment by Coolthulhu** [comment]
> Perhaps the game is adjusting temperature under the hood to make the parts confortable.

Some adjustments are there, but most try to round things toward 0 "character screen warmth". The warmth numbers are all over the place, which may be a big part of why it's hard to tell if things are going right. There are 3 "warmths": clothing, character screen, body part warmth (this one is also used by mutations and fields). Translations between them are non-linear.
Oh and not one of them translates neatly into real life temperature units.

I'm simplifying the temperature system and backing it with automated testing to make it less of a black box, but I haven't achieved not-black-box design yet.

**Comment by seerdecker** [comment]
Alright! Thanks for your work and good luck coming up with a new system. It's hard to balance simplicity with effectiveness.
