### ISSUE TITLE
Music pack volumes does not respects ingame music volume settings

### ISSUE THREAD

**Issue by Melodeiro** [cataclysmbnteam/Cataclysm-BN#1418]
# Describe the bug

When the next track is chosen - volume is used from soundpack json file. ingame settings is ignored

# Steps To Reproduce

1. Install music pack (Octopack for example)
2. Make sure that all tracks of the same volume. .ogg files are normalized, but you need the config file with the same levels as well: https://gist.github.com/Melodeiro/e2f177d9c241944c39f96e67f5849691
3. Start the game and set music volume to something like 20
4. When the next track starts playing, volume will be used from config (100 in my example above), music will be loud

# Expected behavior

Use game music volume as a ratio:

actual volume = ingame volume (%) * volume from soundpack json (%)

**Comment by Melodeiro** [comment]
I misunderstood that bug then, probably. Actually didn't tested on that exact file, but thought it will be simplier to find it out when all volumes are the same. For me it was also happening with different volumes setted in json. I was going to the settings and turning up the volume (or just re-saved the settings), and that always helped, thats why i came to this conclusion

So, i guess, we are talking about the same bug

**Comment by Coolthulhu** [comment]
Should be fixed by #1434. If not, I'll reopen.
