### ISSUE TITLE
Items are being added to type cache without building it first

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#1424]
# Describe the bug

Brosef on discord reported this:

```
DEBUG    : Tried to add item to inventory using cache without building the items_type_cache.

 FUNCTION : add_item_by_items_type_cache
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\inventory.cpp
 LINE     : 342
 VERSION  : BN 68b311f
```

He said it happened after dropping items into a vehicle.

# Steps To Reproduce

Didn't try reproducing yet... When I get to it, I'll edit it here.

# Expected behavior

# Screenshots

# Versions and configuration

# Additional context

**Comment by SaintCirno9** [comment]
I can reproduce it randomly when interacting with vehicle.
Don't exactly know what happened though, weird.
This might not cause any other problems, just a little annoying.

**Comment by SaintCirno9** [comment]
Oh, I see.
I forget this.
``` cpp
if( cargo ) {
     const auto items = veh->get_items( cargo->part_index() );
     *this += std::list<item>( items.begin(), items.end() );
}
```
It uses '+=' instead of add_item(), should be replaced by add_item_by_items_type_cache()
