### ISSUE TITLE
cataclysm-tiles.exe has stopped working

### ISSUE THREAD

**Issue by seerdecker** [cataclysmbnteam/Cataclysm-BN#1426]
Build cbn-windows-tiles-x64-msvc-untranslated-2022-04-03-1300.zip 
Commit 2bd4c03bd9fefbd5be5a13a10b16c81109dbe9fe
OS: Windows 8.1

Unhandled exception at 0x00007FF7EB474B4E in cataclysm-tiles.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

This occurs on program startup immediately, before the "main menu" window has shown up. It looks like something is dereferencing a NULL pointer. My VS debugger doesn't print more information before it exits complaining about an expired license. If you can't repro easily, let me know and I'll try to fix this license stuff and see if I can get a stack trace.

**Comment by Coolthulhu** [comment]
Yep, reproduces instantly. Really weird that it happens. Will be hard to debug, since it only happens on Windows builds.
Thanks for the report.

**Comment by seerdecker** [comment]
Confirmed fixed.
