### ISSUE TITLE
Failed to launch the latest build on Windows11 x64

### ISSUE THREAD

**Issue by SaintCirno9** [cataclysmbnteam/Cataclysm-BN#1427]
# Describe the bug

Failed to launch the latest build on Windows11 x64.

# Steps To Reproduce

1. Download the latest Windows build 2bd4c03 in https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2022-04-03-1300 and unzip.
2. Try launch the game by double-clicking cataclysm-tiles.exe.
3. Wait for a while, and finally no game launched and no log created.

# Expected behavior

The game should start normally.

# Screenshots

# Versions and configuration

# Additional context

VS2022 Debug displays this:
![image](https://user-images.githubusercontent.com/33447021/161433628-a595de2c-b2c4-4f31-9327-9f8f2adfd3e6.png)

After reverting #1423, the game complied and ran fine.

**Comment by SaintCirno9** [comment]
![image](https://user-images.githubusercontent.com/33447021/161434247-177dcdf8-9743-47d8-a098-4d55a1755410.png)
Might be something wrong here:
```cpp
time_point curmes = calendar::start_of_cataclysm;
```

`calendar::start_of_cataclysm` returns nullptr?

Not sure though.

**Comment by Coolthulhu** [comment]
Thanks for the stacktrace and exception location.
I think I know why it fails: I changed one of the variables `messages_impl` depends on to be a reference, but static initialization has undefined order (I think), so the reference is not initialized in time for the use.
