### ISSUE TITLE
Unclear if root cellars and grid refrigerators are actually working.

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#1443]
I harvested some vegetables from my farm and put them in the root cellar temporarily because I wanted to see how much of an improvement the refrigerator is over the root cellar. According to the (E)at menu the spoilage time was unchanged between putting them in the root cellar and just letting them sit on the ground. Putting them in the refrigerator (which I double checked was toggled to on and the electrical grid _DOES_ have power available) also showed no change in the (E)at menu's projected spoilage time.

Expected behavior is that the menu shows the change in spoilage time when perishable food or drink is placed into furniture that is supposed to slow spoilage. Either the menu is not showing this change in spoilage time or the change in spoilage time is not happening. Either one would seem to be a bug to me.

I observed this with zucchini and with broccoli, I have not tested other perishable items and it may be only these items or only vegetables are effected or something along those lines. 

I am also using the non-perishable overhaul mod which I suppose could be impacting this. I'm not sure if temporarily disabling that mod would just revert food back to normal spoilage times or if it would break my save in unpredictable ways so I have not attempted to disable it and check.

Mods in use:

[
  "dda",
  "no_npc_food",
  "novitamins",
  "elevated_bridges",
  "Arcana",
  "mutant_insects",
  "mutant_npcs__",
  "deoxymod__",
  "SzQmod",
  "Tankmod_Revived",
  "StatsThroughSkills",
  "stats_through_kills",
  "Nonperishable_Overhaul"
]

Save attached
[Range.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/8429858/Range.zip)
.

**Comment by Proxiehunter** [comment]
With my save backed up so I could attach it here I checked and it is not the non-perishable overhaul mod.

**Comment by Coolthulhu** [comment]
This may be somewhat hard because of how deeply nested the item display code often is, but from a quick skim, it looks doable.
