### ISSUE TITLE
Segfault when reloading UPS

### ISSUE THREAD

**Issue by SageB** [cataclysmbnteam/Cataclysm-BN#1448]
# Describe the bug
When I reload my UPS+1, the game segfaults.

# Steps To Reproduce
1. Load game
2. Press 'r'
3. Select UPS+1
4. Choose 'drop'
5. Game should immediately crash.

# Expected behavior
Game does not crash.

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20.2; Release: 20.2; Codename: uma; 
- Game Version: 92681fe [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Pneumatic fun [pneumo_fun],
    Tankmod: Revived [Tankmod_Revived],
    Roadheader and other mining vehicles* [Heavy miners__],
    No Hope [no_hope],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    <color_light_red>Lethal Zeds</color> [av_lethalzeds],
    Prevent Zombie Revivication [no_reviving_zombies],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Dorf Life [Dorf_Life],
    Mining Mod [Mining_Mod]
]

# Additional context
Save file is too big to include: https://ufile.io/hjz6t5hn
[crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/8459879/crash.log)
[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/8459880/debug.log)

**Comment by Coolthulhu** [comment]
Reproduces instantly, even without mods installed. Thanks for the report.

**Comment by Coolthulhu** [comment]
I tracked it down to the "favorite ammo" functionality.
Very fragile feature, uses what is essentially a pointer that gets all wrecked. I don't have a solution yet.
