### ISSUE TITLE
Obnoxious .22lr unspent casing behavior (Win)

### ISSUE THREAD

**Issue by RodriguesCIA** [cataclysmbnteam/Cataclysm-BN#1449]
Every time I am dealing with these, it takes several in-game minutes to pick them up or drop them. I think the game logic is not quite working out "it is a stack of 2000 casings, drop them all at once" and, instead, is taking a turn (one full second) to drop each casing. At first glance that wouldn't be a big issue as the 22 is an underused cartridge, but precisely because of this fact, it is prime disassembly fodder.

**Comment by Coolthulhu** [comment]
I tried to reproduce this on a default world, but casings were a single stack, dropped as one item.
Are you using any mods that could have changed it?
