### ISSUE TITLE
Ammo Disassembly Overflow (Win)

### ISSUE THREAD

**Issue by RodriguesCIA** [cataclysmbnteam/Cataclysm-BN#1450]
Last time I disassembled a big (around 20L) pile of various cartridges of various qualities, I ended up with such a gigantic pile of lead, gunpowder (of both types), casings and primers that it would take multiple trips to store it, rouhgly 100L, perhaps more.

My suspicion is that, when the game prompts you on how many cartridges to disassemble of a stack, regardless of how many there are, the number you input on the window is the number your will disassemble. Furthermore, I think I may have caused an overflow by forgetting to delete the default 0 before inputing the desired value (the max presented). For example, out of 17 9mm rounds to disassemble, I input 017 and hit enter.

**Comment by Coolthulhu** [comment]
I'm not sure if I understand. The way I read it, it looks like you have 2 situations:
1. Disassembled a big stack of ammo, which turned into an even bigger stack of materials
2. Disassembled a small stack of ammo with a "0" in front of the "disassemble how many" count

As for the case 2., I tried to reproduce it with a smaller stack, but it correctly read the number.
But the testing helped me uncover a different bug: you can input a number larger than the stack size, which will multiply time taken by that number, even if it's larger than stack size. Won't produce more output, at least.

As for 1., it seems that it must be dependent on type of ammo. I tested with 9x19mm and .50 BMG ball and both looked correct enough (material size sum was smaller than twice the ammo size).
It might be possible to write a script that would compare casing sizes to resulting ammo.
Do you use any mods that either add new ammo types or heavily alter existing ones?

**Comment by olanti-p** [comment]
May be a case of item duplication described in #621

**Comment by RodriguesCIA** [comment]
![image](https://user-images.githubusercontent.com/39223166/162852846-51f20b75-7e3e-4b96-80df-b79c57340bee.png)

So I had it again, once more, with an assortment of various ammo types. I should have written down the exact number of cartridges, but I forgot to. However, we can at least get a glimpse of what I had by the backlog

![image](https://user-images.githubusercontent.com/39223166/162852960-2a067776-d69a-4d31-967c-a7ed12a924f3.png)
![image](https://user-images.githubusercontent.com/39223166/162852991-2922dc7c-1f58-443f-a190-f0c9fc898c2a.png)
![image](https://user-images.githubusercontent.com/39223166/162853019-da652e28-8a53-4f4d-8f22-d5396ce2dc7a.png)

And one more interesting thing, though, is the casings I got.

![image](https://user-images.githubusercontent.com/39223166/162853055-465103a9-a0e4-4e30-9067-497cab86ea66.png)

I assure you, it didn't start with this neat, symmetrical number of casings all around. It was indeed a random assortment of ammo, as random as it could have been.
