### ISSUE TITLE
Mutagenic toxins seem to be non-functional

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#1466]
# Describe the bug

Mutagenic toxins no longer build up properly, with or without Simplified Nutrition.

# Steps To Reproduce

1. Create a world.
2. Eat several units of cooked mutant meat, lard, whatever you prefer.
3. Wait 24 hours at a time, checking after each wait and adjusting kcal/thirst/fatigue so you won't die.
4. Notice that mutagenic toxins never seems to go up.

# Expected behavior

Mutagenic toxins to build up as expected after binging on contaminated food.

# Screenshots

![image](https://user-images.githubusercontent.com/11582235/163743717-b3cd8b48-07b6-43dd-b5fe-1da4e48e483c.png)

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 92681fe [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Elevated bridges [elevated_bridges],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Manual Bionic Installation [manualbionicinstall]
]
```

Also tested in a compiled test build:
```
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 92681fe43f-dirty [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Elevated bridges [elevated_bridges]
]
```

# Additional context

**Comment by KheirFerrum** [comment]
Also, seems like this broke just after the last update on 6th April, since I had a working mutagenic system then when I updated from 1835 to 1910 via Catapult. I still have a working version of it on my computer right now, but if I have Catapult download an entirely new version Mutagenic Toxins don't work.

**Comment by chaosvolt** [comment]
So evidently, for some reason if you pick creating character via a template, even if it's just "last character used" it'll suddenly work, as does save and load, as found out in the BN discord:
![image](https://user-images.githubusercontent.com/11582235/164138412-0f2fa616-616d-4618-9317-9de4ad9a076c.png)

So evidently the root cause of this is that the vitamin array isn't being created right on a completely fresh character.
