### ISSUE TITLE
Crashing when reloading from/inside tiles

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#1472]
# Describe the bug

Whenever reloading something, while said something is on/inside a tile, the game crashes.

# Steps To Reproduce

1. ![image](https://user-images.githubusercontent.com/3938423/164405314-66207f70-c12c-4b62-a218-82a1616e3ab2.png)
That's me on a cargo space, in that cargo space are guns. I presss 'r', the reload screen comes up
2. Choose whatever to reload and press enter
3. Game crashes

# Expected behavior

To be able to reload without crashing.

# Versions and configuration
- OS: Windows 10
    - OS Version: 10.0 2009
- Game Version: f2f9fea [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Elevated bridges [elevated_bridges],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    PKs Rebalancing [PK_REBALANCE],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    <color_red>Sierra Madre</color> [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    Steampunk Mod [steampunk_arcanum],
    UnderrailMetro Mod [underrailmetro_mod],
    <color_light_green>Real Dark Skies</color> [realdarkskies],
]

# Additional context

Last working version is 1540:

![image](https://user-images.githubusercontent.com/3938423/164508445-df6909b8-679a-4ef1-8954-931318e3c062.png)

**Comment by Coolthulhu** [comment]
I managed to track it down to "favorite ammo" feature. It's caused by my fix to another crash.

**Comment by Unrepentant-Atheist** [comment]
Confirmed working now.
