### ISSUE TITLE
Not enough characters to represent all mutations

### ISSUE THREAD

**Issue by seerdecker** [cataclysmbnteam/Cataclysm-BN#1479]
Version cbn-windows-tiles-x64-msvc-untranslated-2022-04-03-1526

My character has 83 mutations. There aren't enough characters in a-z, A-Z, special chars (total 72) to uniquely represent all mutations, resulting in the broken menu shown in the screen shot. 

![image](https://user-images.githubusercontent.com/12588992/164912626-37029571-3369-4880-a1e3-fbceaf824cba.png)

**Comment by seerdecker** [comment]
The active mutations get characters last, so it's impossible to trigger them. I can't select them to assign them a character.

**Comment by SaintCirno9** [comment]
Maybe DDA has already fix this problem?

**Comment by Zireael07** [comment]
@SaintCirno9: Yep: https://github.com/CleverRaven/Cataclysm-DDA/pull/53764

**Comment by SaintCirno9** [comment]
Alright, I'll port it soon.

**Comment by SaintCirno9** [comment]
Appears there are more things need porting in mutations_ui.cpp.
A mess in deed._(:з)∠)_
