### ISSUE TITLE
A house's wall tile replaced by a sidewalk tile (Win)

### ISSUE THREAD

**Issue by RodriguesCIA** [cataclysmbnteam/Cataclysm-BN#1482]
I will upload the tile in question and a "zoomed out view" of the house for reference as I wouldn't be able to locate it myself to help you guys.

![image](https://user-images.githubusercontent.com/39223166/164946622-6b2cf5cb-efed-417b-92d9-4136351e9663.png)

![image](https://user-images.githubusercontent.com/39223166/164946628-ecd5df3a-07b8-4e4b-a14c-231fc7d3bf84.png)

**Comment by scarf005** [comment]
closing this, since i think `#1482` on the title of #1553 meant to close this issue.
please reopen if the bug persists.
