### ISSUE TITLE
Possible inspiration for a new anti-robot weapon

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#1489]
These [real life anti-drone weapons](https://www.militarytimes.com/off-duty/military-culture/2021/06/22/this-enormous-drone-gun-can-pluck-uavs-right-out-of-the-sky/) that are starting to be fielded look like they could be the inspiration for something that could be found in science labs and military bunkers. Powered by UPS with the same effect as an EMP grenade except targeted instead of an explosion. Possibly a monster power draw so it can't make areas with lots of turrets or bots (like say a lab finale) trivial. 

Probably not self craftable without a lab book on the level of the mutagen books and a super high electronics.

**Comment by Drugitechnik** [comment]
There is already EMP projector in game.
