### ISSUE TITLE
Wrong bridge's connection to a road

### ISSUE THREAD

**Issue by tyzegt** [cataclysmbnteam/Cataclysm-BN#1495]
Sometimes bridges does not connect to the roads

# Steps To Reproduce

1. Generate new map
2. Teleport around to the perpendicular road-bridge connections

# Expected behavior

roads must be connected to bridges correctly

# Screenshots
 
![image](https://user-images.githubusercontent.com/4536261/165745364-d12fead5-b05c-46bf-a27f-ff9dd3e9b452.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f2f9fea [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex]
]

**Comment by Coolthulhu** [comment]
Bridge gen got reworked since this bug was reported. It may have been fixed in meantime.

**Comment by olanti-p** [comment]
It's a different case, still relevant. Here, the bridge ends at overmap special's connection point and does not properly understand how it's supposed to connect only at specific angle. I have fixed it as part of connection gen rework for the railroads, but that's a rather big rework and not entirely finished...

**Comment by Vollch** [comment]
It's not actually. That PR only fixes connection points of specials. Lookin at screenshot this bridge is connected to overmap border, that's the different case.
