### ISSUE TITLE
NPCs Do Not Run To Catch Up

### ISSUE THREAD

**Issue by rtizzy** [cataclysmbnteam/Cataclysm-BN#15]
### Expected behavior
NPCs followers will run in an attempt to catch up with the player when they fall behind a certain distance

### Actual behavior
NPC followers do not change speed to match or catch up with player character. 

### Steps to reproduce the behavior
Attain an NPC follower, run faster than them. This is particularly apparent on characters with higher than default move speed.

**Comment by Coolthulhu** [comment]
They currently do not run ever. Running is hardcoded (badly) for player only.

**Comment by elricsfate** [comment]
@Coolthulhu Is there an upstream issue for that? Would we like to handle that first via upstream before moving to this?

**Comment by Coolthulhu** [comment]
I don't think there is one.
I'm pretty sure there is an upstream issue for NPCs not running away, but not one for them not running as in walking fast.

**Comment by elricsfate** [comment]
For anyone interested in taking a swing at this the majority of the code appears to be handled below 

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/master/src/player.cpp

@Coolthulhu 

I created an upstream ticket for the hard coding issue.
