### ISSUE TITLE
Allow "simple decontruction" option to Workbench

### ISSUE THREAD

**Issue by velddrinn** [cataclysmbnteam/Cataclysm-BN#1514]
# Is your feature request related to a problem? Please describe.
Right now a Workbench can`t be "simply deconstracted", but can be placed via Construction menu "Place workbench" using a single Workbench craftable furniture object.

# Describe the solution you'd like
Make it similar to Oven and other placeble furniture that doesn`t need to be scrapped to components to rebuild.

**Comment by RodriguesCIA** [comment]
Would be a good time saver for mobile bases, and very handy even for early game applications, as otherwise the character will have to drag the thing to their current base from the street which might be unpractical if you are playing a weak character.

**Comment by velddrinn** [comment]
> Would be a good time saver for mobile bases, and very handy even for early game applications, as otherwise the character will have to drag the thing to their current base from the street which might be unpractical if you are playing a weak character.

Yep, also you can`t drag it to another Z-level. And deconstructing something to "pipes and scraps" just to rebuild it in the same house, but downstairs is wierd (in early game you just lack skills and tools for that). We actually already have this mechanic for Jven implemented, so it just can be applied to other functional furniture that doesn`t exist just for scrapping.
