### ISSUE TITLE
Laser guns accept no magazines and cannot be fired

### ISSUE THREAD

**Issue by Zilenan** [cataclysmbnteam/Cataclysm-BN#1520]
# Describe the bug

They say they use UPS to fire but you can't actually load a UPS into it because it doesn't actually accept UPS as magazines. Weapon description included in the screenshot below.

# Steps To Reproduce

Get any laser weapon and try to reload it, I found a laser pistol and saw this issue, then checked if the Laser Rifle also had it and it does.

# Expected behavior

It turns out that not having a way to reload a weapon means you can't fire it. 

# Screenshots
 
![laser](https://user-images.githubusercontent.com/105184154/167330693-9320bc44-e287-4e6e-9e83-ace1db51e179.png)

 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]
 
![mods](https://user-images.githubusercontent.com/105184154/167330761-50a9d6b1-8b44-4bbb-9612-50599d9e5ded.PNG)

**Comment by Proxiehunter** [comment]
You don't load them. You should just be able to fire if you have a charged UPS on your person.

**Comment by Zilenan** [comment]
> You don't load them. You should just be able to fire if you have a charged UPS on your person.

Woops my bad, I thought they worked like every other gun in the game.
