### ISSUE TITLE
Bush and fungal elephants does not leave corpses

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#1522]
# Describe the bug

They does not leave any corpse behind.
Maybe elephants are from desert pack mod?

# Steps To Reproduce

1. spawn bush/fungal elephants.
2. kill them.

# Expected behavior

it leaves butcherable corpse behind.

# Screenshots and Videos
![2022-05-09_001](https://user-images.githubusercontent.com/54838975/167426105-f80a9a51-3bc4-4054-aa2b-f037ed16216b.png)

https://user-images.githubusercontent.com/54838975/167426342-fa13f5a6-154b-40bc-aa01-ebd3a7332d62.mp4

https://user-images.githubusercontent.com/54838975/167426315-80ff3a5f-45f7-4e19-872a-a0dcf5a571f0.mp4

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 21.10; Release: 21.10; Codename: impish; 
- Game Version: 41ae57c [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Magiclysm [magiclysm],
    Desert Region [desertpack],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Overhaul Tileset [Overhaul Tileset],
    No Lifting Reqs [disable_lifting],
    Plutonium instead of Beta Cells [Alt_Beta_Cells]
]

# Additional context
Currently only way to optain meat from elephants is by making them explode.
![image](https://user-images.githubusercontent.com/54838975/167426565-a1ba5a5f-9901-4055-9c66-81572282615d.png)

**Comment by DrPariah** [comment]
Check their weight. Desert Region is a ancient mod, hasn't really been touched in a long time, and therefore old enough that it probably still suffers from the corpses-over-a-certain-weight-disappear bug. Dinomod was fixed for that a while back, so compare the elephant weight to the four legged herbivore weight in Dinomod and if the elephants are heavier then adjust them to match.

**Comment by scarf005** [comment]
thank you for suggestion. i also wonder if the corpse disappearing bug could be solevd programmatically?
