### ISSUE TITLE
android versions crashes as soon as you open it.

### ISSUE THREAD

**Issue by SoggyLemon** [cataclysmbnteam/Cataclysm-BN#1535]
Game version: Latest experimental (at the time of this post)

Operating system: android

Tiles or curses: UDP

Mods active: None

### Expected behavior
Game runs
### Actual behavior
game crashes

### Steps to reproduce the behavior
Open up the android version

**Comment by Lamandus** [comment]
Can confirm. It also crashes for me

**Comment by olanti-p** [comment]
Can't reproduce.
Freshly installed version `2022-05-13-1804` works fine on Android 11.

**Comment by Lamandus** [comment]
cbn-android-x64-2022-05-13-1731.apk is what is not working for me

**Comment by Lamandus** [comment]
Maybe not anymore, since your version is newer than the day he posted

**Comment by olanti-p** [comment]
Can confirm for version [2022-05-03-0433](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2022-05-03-0433). Awfully similar to #1149: the only notable change I see is github updating its runner from [20220425.1](https://raw.githubusercontent.com/actions/virtual-environments/ubuntu20/20220425.1/images/linux/Ubuntu2004-Readme.md) to [20220508.1](https://raw.githubusercontent.com/actions/virtual-environments/ubuntu20/20220508.1/images/linux/Ubuntu2004-Readme.md).

**Comment by SoggyLemon** [comment]
the problem is fixed now after the update

**Comment by Coolthulhu** [comment]
I managed to get Android Studio emulator running and got to replicate the crash. The newest APK does run, but local builds do not. Stacktrace was useless, pointing to Android libs.
The problem may pop up again in the future.
