### ISSUE TITLE
fix russian translate

### ISSUE THREAD

**Issue by gogaster** [cataclysmbnteam/Cataclysm-BN#1541]
### Describe the bug

![photo_2022-05-15_07-11-45](https://user-images.githubusercontent.com/27226073/168456903-19c2f35d-8e84-46d8-bc61-2302a43baac0.jpg)

typo in Russian translation:

Мокровь = not true
Морковь = true

### Steps To Reproduce

typo in Russian translation:

Мокровь = not true
Морковь = true

### Expected behavior

typo in Russian translation:

Мокровь = not true
Морковь = true

### Screenshots

![photo_2022-05-15_07-11-45](https://user-images.githubusercontent.com/27226073/168456953-35483d1f-c0e5-4ca5-9b96-0064f754ad18.jpg)

### Versions and configuration

last version

**Comment by tyzegt** [comment]
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1549

**Comment by CV514** [comment]
Should be fixed by now.

![изображение](https://user-images.githubusercontent.com/60776130/170554552-ce190440-e9f8-4f5a-a84a-2c453d099a22.png)

**Comment by olanti-p** [comment]
Yep, merged in #1539
