### ISSUE TITLE
typo in Russian translation

### ISSUE THREAD

**Issue by gogaster** [cataclysmbnteam/Cataclysm-BN#1542]
### Describe the bug

Ошибка в этапе 2:

холодильник "выключен" = not true
холодильник "включен" = true

### Steps To Reproduce

Ошибка в этапе 2:

холодильник "выключен" = not true
холодильник "включен" = true

### Expected behavior

Ошибка в этапе 2:

холодильник "выключен" = not true
холодильник "включен" = true

### Screenshots

![photo_2022-05-15_07-11-44](https://user-images.githubusercontent.com/27226073/168457017-9ed02065-07e0-485b-a55d-4d2c0b9fb01b.jpg)

### Versions and configuration

last version

**Comment by tyzegt** [comment]
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1549

**Comment by olanti-p** [comment]
Looks like it was fixed on transifex, and merged in #1539
