### ISSUE TITLE
Bow reloading bug

### ISSUE THREAD

**Issue by Samarai** [cataclysmbnteam/Cataclysm-BN#1560]
### Describe the bug

After some time of using a self bow, shortbow, or longbow normally, eventually the bow will become unable to be fired due to not being loaded, with attempting to reload/part reload the bow resulting in nothing happening. After dropping both the arrows and bow, and trying to reload the bow from either arrows in your inventory or on the floor, attempting to reload will result in getting the error shown below. 

### Steps To Reproduce

1. Create a self bow, shortbow, or longbow. (presumably other bow types suffer the same problem)
2. Use and fire the bow as you normally would for some time. (I can't find a consistent cause of the bug, but all of the times it's happened to me thus far have been when using it against creatures and monsters)
3. Eventually, find yourself unable to reload and fire the bow despite having arrows in your inventory.

### Expected behavior

The bows should be able to be reloaded if you have arrows, and the name being green should mean the bow is actually loaded. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1180f84 [64-bit]
- Graphics Version: Tiles
- Game Language:  [] (it's english)
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Elevated bridges [elevated_bridges]

### Additional context

 DEBUG    : item_location lost its target item during a save/load cycle

 FUNCTION : ensure_unpacked
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\item_location.cpp
 LINE     : 106
 VERSION  : BN 1180f84

(note: sorry for how awfully this issue is formatted, I'm new to this but I couldn't find another report of what seems to be a pretty bad bug!)

**Comment by olanti-p** [comment]
It's hard to say for sure what happened in this case without debug log or save file, but I believe that was a combination of bugs that are getting fixed in the linked PR, so once it's merged this issue will most likely be resolved.
