### ISSUE TITLE
Can't use grid stove to heat up food

### ISSUE THREAD

**Issue by Zilenan** [cataclysmbnteam/Cataclysm-BN#1564]
### Describe the bug

Connected, working grid stoves and RV kitchen units are not used by your character to automatically heat your food.

### Steps To Reproduce

1. Get any eaten_hot food
2. get working grid stove or grid RV kitchen unit
3. he eats it raw like a caveman

### Expected behavior

Your character should automatically heat the food up with the grid stove or RV kitchen unit just like they do with nearby fires.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 41ae57c [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod* [makeshift__],
    MST Extra [MST_Extra],
    Survivor crowbar [surv_crowbar],
    Mining Mod [Mining_Mod],
    Mutant NPCs* [mutant_npcs__],
    Alternative Basement Layouts [basement_extension],
    Morlock Village [morlock_village],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Necropolis Actually Findable [necro_find],
    Nonperishable Overhaul [Nonperishable_Overhaul]
]

### Additional context

On another note with heating up food, the power/fuel use requirements for portable cooking equipment is probably a little excessive. It takes 25 units of battery to heat up 1 unit of food from a mess kit, and 25 units per unit from an oven would also probably be a little much as well.

**Comment by Proxiehunter** [comment]
Do you have something with the food cooking quality to actually heat the food in?

I forget if Bright Nights has eliminated the extra step DDA has of activating the cooking vessel to heat the food you want heated. I'm sure you still _need_ one though.

**Comment by Zilenan** [comment]
> Do you have something with the food cooking quality to actually heat the food in?
> 
> I forget if Bright Nights has eliminated the extra step DDA has of activating the cooking vessel to heat the food you want heated. I'm sure you still _need_ one though.

Yes. If I light a fire in the same room it heats it up, it just doesn't work off of grid appliances.
