### ISSUE TITLE
Soundpacks issue with smash_fail in game not emitting sound when smashing floors or walls 

### ISSUE THREAD

**Issue by Kenan2000** [cataclysmbnteam/Cataclysm-BN#1579]
### Describe the bug

When using a soundpack such as Otopack, for example, which has definitions for smash_fail when hitting floors or walls (thing to consider is: ids of these objects in core game have not been changed, neither have these files been changed in soundpacks), a smash_fail message can be seen but no sound is emitted even though in previous versions of game, (likely before JSONized ranged bash update that edited sound emission code for smash_fail if I understand it correctly), smash_fail sounds worked alright

### Steps To Reproduce

1. Download a soundpack such as Otopack, enable it in game
2. Spawn in vanilla locations such as evac shelters
3. Try to smash a floor or a wall
4. A thump message can be seen, yet no sound is emitted, however, all other sounds work alright 

### Expected behavior

Game emits smash_fail sounds defined in soundpacks when smashing floors or walls 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 41ae57c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Blazemod - Vehicle Additions Pack [blazemod]
]

**Comment by ccondry** [comment]
update: I think it is playing at least some of the "whump" sounds, but just very very quietly. I couldn't hear them until a bunch of them stacked up when a zombie right in front of me was breaking down a door and I was skipping turns very quickly. I still can't hear my own sounds of failing to smash a door, so I can't tell if it is also too quiet to hear
