### ISSUE TITLE
Grid welding rig doesn't work as soldering iron

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [cataclysmbnteam/Cataclysm-BN#1593]
### Describe the bug

It is constructed from same vehicle welding rig as in cars but doesn't act as soldering iron unlike vehicle part.

It uses same fake item so acts absolutely identically to grid arc welder but uses soldering iron as component.

### Steps To Reproduce

1. Acquire vehicle welding rig.
2. Place it in charged power grid.
3. Try to do something which require soldering iron (e.g. disassemble electronics).
4. Fail to do so because you lack soldering iron.

Also you can:
5. deconstruct grid welding rig.
6. put it in a vehicle.
7. Enjoy your soldering iron once again.

### Expected behavior

Either:
1. Since it uses vehicle part as component, it should act identically.
2. Or just remove this grid welding rig because there are already both grid arc welder and grid soldering iron.

### Versions and configuration

Game Version: `de64c76`

**Comment by olanti-p** [comment]
DDA issue for reference: https://github.com/CleverRaven/Cataclysm-DDA/issues/34851
PR that fixed this in DDA has a ton of conflicts with BN, so it might be easier to come up with some BN-specific solution instead of porting.

**Comment by KheirFerrum** [comment]
This should be fixed by #2172 which extends `crafting_pseudo_item` to allow the welding rig appliance to act as both a welding rig and soldering iron.
