### ISSUE TITLE
NPCs will not jump over wire fences or route to player

### ISSUE THREAD

**Issue by elricsfate** [cataclysmbnteam/Cataclysm-BN#16]
### Expected behavior

NPCs will climb over wire fences to follow player or attempt to route to player if they climb over a fence

### Actual behavior

NPCs will not climb over fences and will simply stand still if the player character climbs over a wire fence.

### Steps to reproduce the behavior

Climb over a fence

**Comment by elricsfate** [comment]
@Coolthulhu 

I'm sure we can agree this should likely be opened upstream as well?

**Comment by Coolthulhu** [comment]
My fix is compatible with upstream so it can be PR'd there afterwards.
