### ISSUE TITLE
Crafting categories not merging

### ISSUE THREAD

**Issue by TheThingG** [cataclysmbnteam/Cataclysm-BN#1607]
### Describe the bug

If a mod requires its own subcategories (e.g. Animals category in DinoMod), the categories will be duplicated in the crafting menu
It looks like the categories with the same id are not merged, when declared in the mod and in the base game .

### Steps To Reproduce

1. Create world with DinoMod enabled
2. Open crafting menu

### Expected behavior

Categories and their subcategories must be merged

### Screenshots

![image](https://user-images.githubusercontent.com/5640217/172693861-3750018d-12c4-47f2-b1b9-40703c77b0cd.png)

### Versions and configuration

Windows, build 2022-06-08-1648, default mod setup+DinoMod

**Comment by SaintCirno9** [comment]
That’s because DinoMod has defined a "CC_ANIMALS" recipe category, which is the same as the vanilla one.
If you want a quick fix, try edit pets_elephant.json in data\mods\DinoMod\recipes.
Remove this part:
```json
  {
    "type": "recipe_category",
    "id": "CC_ANIMALS",
    "recipe_subcategories": [
      "CSC_ALL",
      "CSC_ANIMALS_CANINE ARMOR",
      "CSC_ANIMALS_EQUINE ARMOR",
      "CSC_ANIMALS_ELEPHANT ARMOR",
      "CSC_ANIMALS_EQUINE STORAGE"
    ]
  },
```

**Comment by LyleSY** [comment]
How long are we talking? If this is a bug with BN I'm happy to make this fix for everyone

**Comment by SaintCirno9** [comment]
A quick fix is done. I just haven't played BN for a while so I'm lazy.
