### ISSUE TITLE
Mine Entrance location is broken

### ISSUE THREAD

**Issue by Bowie-the-Psycho** [cataclysmbnteam/Cataclysm-BN#1643]
### Describe the bug

The bug is how all mine entrances and their related underground level are equal, and, the elevator shaft down into the mine itself, alongside the available manhole entrance, allow no way back up to the previous Z level, or surface level. This makes them useless deathtraps.

### Steps To Reproduce

Activate elevator power
Take elevator down
OR
Enter manhole
Take ladder down

### Expected behavior

See, every tile in the game is uniquely generated. Mostly. But whats up with mines? I expected the mines to, well, not be locations that trap the player for exploring them. Obviously unintended, obviously broken.

### Versions and configuration

- OS: Windows 11
    - OS Version: 10.0.02204 2021
- Game Version: 8c816c9 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    anti-fungal gear [anti_fungal_gears],
    Armor Up! PA Utilities [ArmUpPAUtil],
    CIVILIAN POWER ARMOR [CIVILIANPOWAAA],
    Craftable Gun Pack [craftgp],
    Culinary Days Ahead [culinary_days_ahead],
    Dried Fruits [dried_fruits],
    Homemade Fungicide [homemade_fungicide],
    Kingsman Umbrella [kingsman],
    Make a Lot of Items [Make_a_Lot_of_Items_Mod],
    Metal materials [metal_elemental],
    MOD to grow tea leaves [More tea leaf],
    More Armors [More_Armors],
    Pipe Revolver Rifles [pipe_revolver_mod],
    Pixel's Various Fuckery [Pix's Shit],
    Power_Armor_Additions [Power_Armor_Additions],
    The Glory Of Cereal! [CerealMod],
    Whaleys Collectables [collectablemod],
    DinoMod [DinoMod],
    CDDA Variety Pack [ks_variety_pack],
    Crazy Pets! [crazypets],
    Merchant Mod [Merchant],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Trailer Parks [trailerpark],
    Water Towers [water_towers],
    Folding Parts pack [deoxymod],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Vanilla Additions [Graphical_Overmap_SDG],
    3x Healing [3x_healing],
    Fuji's Military Profession Pack [fuji_mpp],
    Gunslinger Mod [MkMaxxi's Gunslinger Mod],
    Remove Wet/Dry Morale Effects [wet_morale_removed],
    SpeedyDex [speedydex],
    Tame Bugs [tamebugs],
    Temperature Effects Reduced [temp_effects_reduced]
]

**Comment by olanti-p** [comment]
DDA ticket for reference https://github.com/CleverRaven/Cataclysm-DDA/issues/52517
