### ISSUE TITLE
Segfault on autodoc

### ISSUE THREAD

**Issue by DoctorGoat** [cataclysmbnteam/Cataclysm-BN#165]
When I attempted to use an autodoc last night in a prison, my game segfaulted immediately. Unfortunately, I have an unholy amount of mods installed. 

# Steps To Reproduce

https://mega.nz/file/EttlVKyD#pipkVWQkYnrDJSZrIstyU3R3-zj8J9zrUlccQ5QHSg8 Unholy modpack, BroadFlatNails has a copy. Mega was the only place I could find to upload the whole thing without revealing personal information. 
https://cdn.discordapp.com/attachments/733601534436180079/771506800108896266/save.zip Save. Examine the autodoc, choose install bionic, game crashes. I don't think any of my strange mods even touch bionics, making it extra strange.

# Expected behavior

I would expect the game to *not* crash at all.

# Screenshots

# Versions and configuration

Included is a test version with two of Aivean's PRs for CDDA manually merged and a normal release of release 760.

I'm on Windows 10, running SDL tiles. 

# Additional context

**Comment by Coolthulhu** [comment]
Found it: the code for anesthesia requirement assumes that anesthesia requirement:
* Is defined
* Contains at least one tool

**Comment by Firestorm01X2** [comment]
> Aftershock redefines anesthesia requirement to be empty.

I thought emtpy tools was ported. Looks like it it not.
It is this:
https://github.com/CleverRaven/Cataclysm-DDA/pull/42202

**Comment by Coolthulhu** [comment]
I pushed a fix. No PR because it's just a fix.

I bundled an undocumented tweak with it: anesthesia use no longer depends on body weight. But I don't see anesthesia bw dependency being documented anywhere, so it should be OK.
