### ISSUE TITLE
NPCs lose their inherent traits if they drink purifier

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [cataclysmbnteam/Cataclysm-BN#1670]
### Describe the bug

If you make NPC drink purifier, it loses traits (includes ones like Melee Weapon Training).

### Steps To Reproduce

1. Spawn an NPC.
2. Change their opinion to player character using debug menu to trust 20.
3. Ask it to be your follower (they would agree because p.2 ).
4. Spawn a purifier using debug menu.
5. Ask NPC to use purifier (they would agree because p.2 ).
6. It would lose their traits.

### Expected behavior

Inherent traits should not be affected by purifier like it happens with player character.

### Screenshots

![изображение](https://user-images.githubusercontent.com/13154246/176430804-ebd0b813-21ba-4037-a308-83b82423b270.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 81039bcb1e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Elevated bridges [elevated_bridges],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots]
]

**Comment by Coolthulhu** [comment]
Looks like they use `set_mutation` and not `toggle_trait` (should be `set`, having to `toggle` is bad design), so they don't have inherent traits.
Existing NPCs won't be fixable.

**Comment by AngelicosPhosphoros** [comment]
Workaround and fix for existing NPCs: open save in text editor (I use VS Code), find NPC by name (e.g. `"name": "Jessie Pinkman"`), find fields  `traits` and `mutations`.
Copy every key from `mutations` object to `traits` list.

**Comment by Coolthulhu** [comment]
It will make all mutations of a NPC innate, including all the ones gained during life.
