### ISSUE TITLE
Zombie not moving

### ISSUE THREAD

**Issue by Zorm** [cataclysmbnteam/Cataclysm-BN#1691]
### Describe the bug

There is a zombie soldier that can see me, and was moving towards me before. I broke line of sight (to deal with his friend), and now he isn't moving from the open canvas flap he is standing on. Game says he can see me, he's just not moving. I was standing on the other side of a fence, but crossing the fence does not make it start moving. Breaking line of sight does not fix. Waiting for hours does not fix (on either side of fence). Attacking it does not fix (and works like normal). Moving close enough does make it start moving again, but only from certain angles. Approaching from below alongside the wall does not let it move, but moving a single tile more to the right makes it move again. It is capable of attacking.

### Steps To Reproduce

I don't know.

### Expected behavior

The zombie would charge me like an angry boar, because that's what it always does.

### Screenshots

![bild](https://user-images.githubusercontent.com/946387/177008646-c19bec3c-5189-4a9e-9b50-1f66137ef527.png)

### Versions and configuration

- Windows 10
- 56fd4a3 / 2022-06-30-2022
- UNDEAD_PEOPLE (NEW VERSION)
- English
- Graphical Overmap, otherwise default

### Additional context

[Temperance (2022-06-30-2022) Zombie not moving.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/9033319/Temperance.2022-06-30-2022.Zombie.not.moving.zip)
[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/9033323/debug.log)

**Comment by Coolthulhu** [comment]
Thanks for the high quality report.

I suspect either the wall isn't properly bashable, the zombie fails to bash it properly, or it tries to treat it as passable.
Zombie soldiers don't stumble, so their movement is deterministic. Other zombies would hide this problem.
