### ISSUE TITLE
Choose vievable z-level while flying

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#1698]
### Is your feature request related to a problem? Please describe.

When flying and going to 3rd z-level and above, player sees mostly blue and occasionally some high building. This is a problem when trying to get to a specific point, one has to stop often to check the map and then going down to 2nd z level in order to see where they are. Normally when flying one would see the area under them very clearly.

### Describe the solution you'd like

If it was possible to set a z-level that a player would like to watch while flying, it would help a ton.
It could be accessible from driving menu when controlling a vehicle for example, a prompt to choose which z-level to watch.
Normally this kind of thing is only accessible when having 3-d vision enabled in the options. Unsure if this would be possible without it.

**Comment by thelonestander** [comment]
I would enjoy this for when im flying long distances. Also would just be nice to see the ground even when high up.

**Comment by Coolthulhu** [comment]
> Normally this kind of thing is only accessible when having 3-d vision enabled in the options. Unsure if this would be possible without it.

Not really. Not without making the bottom of the heli effectively transparent.

Overall it sounds like a good idea, but I can't think of a sane UI for it.
* "Lock view" in vehicle controls?
* Special case when in "look" action menu when driving?
* Per-player-character config somewhere?
* Require the player to re-set the offset every time?

Nothing unsolveable, just needs some thought.

The auto-resetting offset variant would be the easiest. The least useful, but the easiest. Might be doable in just a few lines.

**Comment by scarf005** [comment]
i belive the real solution to this is to render all layers simultaneosly, like this.
<a title="screenshot taken from youtube video" href="https://www.youtube.com/watch?v=rI4oXA1LVpc"><img width="1174" alt="image" src="https://user-images.githubusercontent.com/54838975/177662029-52447fc9-99b0-44a8-af0f-cc9bc7d321f0.png"></a>
in this screenshot, lower layer is hazy whereas upper layer is drawn normally.

**Comment by Krwak** [comment]
> Overall it sounds like a good idea, but I can't think of a sane UI for it.
> 
>     * "Lock view" in vehicle controls?
> 
>     * Special case when in "look" action menu when driving?
> 
>     * Per-player-character config somewhere?
> 
>     * Require the player to re-set the offset every time?
> 
> 
> Nothing unsolveable, just needs some thought.
> 
> The auto-resetting offset variant would be the easiest. The least useful, but the easiest. Might be doable in just a few lines.

It is useful sometimes to switch the z-level, when trying to see how high certain building is, so that you don't crash in it when flying over a town. Therefore something that would allow changing somewhat easy but it can be solved with just looking up/down - something like current situation but in reverse.
I wouldn't mind any of the options you offered but how about a dedicated keybind to change the viewable z-level so that it's easy to change it?

**Comment by olanti-p** [comment]
Does #1743 resolve this?

**Comment by Drugitechnik** [comment]
> Does #1743 resolve this?

It think this issue is resolved with that PR

**Comment by scarf005** [comment]
still you may want to view the game from different z-level, for example when throwing a grenade into high place, or flying through buildings.

also for kwybindings, maybe something like `alt`+`shift`+`<`/`>`?

**Comment by Krwak** [comment]
Apologies, didn't notice the comments above.
This #1743 resolves this issue. 
I'm closing it now.
