### ISSUE TITLE
statistics not working

### ISSUE THREAD

**Issue by Trokinos** [cataclysmbnteam/Cataclysm-BN#170]
using recent  cataclysmbn-821-win64-tiles  i noticed that for my character if i press ENTER -> "Info" -> "View Achievement, Scores and Kills" the game does not display any of them.
"this game has no valid achievement" for the achievement tab
"this game has no valid scores" for the score tab
"you haven't killed any monsters yet" for the kills tab.

I don't know if it ever worked or if BN has achievement or score alread implemented, but for the kills my character has many of them that should be listed.

As a test i copied my save and let my character gets killed to see if those informations are only displayed at death, but it's the same, it does not list any of my character kills., on the character tombstone there's even a Kills : 0 despite it has many of them (did with varied melee weapons and a few with a self bow)

**Comment by Coolthulhu** [comment]
Do you have event bus enabled or disabled?
Options->debug->event bus system - if this is set to disabled, the achievements, scores etc. can't be tracked.
It should default to enabled. Disabling it makes performance better.

**Comment by Trokinos** [comment]
Ah yes, that was it, because i prefer better performance i had disabled "event bus system" , i just had no idea it was also linked to the kill counts, too bad but better performance is always a better choice for me.

Thanks, i guess problem solved.
