### ISSUE TITLE
Recipe for Dried Beans not giving correct prediction of nutrition

### ISSUE THREAD

**Issue by Ker-Nes** [cataclysmbnteam/Cataclysm-BN#1701]
### Describe the bug

Drying raw beans predicts the result as having 42 calories. Actual resulting item seems to always have the usual 203 calories for one unit of dried beans.

I _think_ it may be inheriting the "nutrient_override" tag from raw beans, but only after it gets crafted, with the prediction just going from the raw beans calorie count. 

### Steps To Reproduce

Know the recipe for dried beans.
Have ingredients and tools.
See the predicted calorie count
Dry some beans.
See calorie count of resulting dried beans.

### Expected behavior

Predicted calorie count should match actual calorie count. 

Or actual calorie count should match calorie prediction, but this one would probably cause more than trouble than it helps with. 

### Screenshots

![image](https://user-images.githubusercontent.com/37450179/177430428-af615a80-3ee5-463c-8937-755ac7eff1ea.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 56fd4a3 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda]
]

**Comment by leoCottret** [comment]
Can confirm, same for dried lentils, calories 31 -> 230
