### ISSUE TITLE
Mining solid rock  leaves open air instead of rock floor

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [cataclysmbnteam/Cataclysm-BN#1711]
### Describe the bug

Mining (using pickaxe or any jackhammer) solid rock no more leaves rock floor but open air instead.

Probably something recent because I mined stone few weeks ago just fine.

Drilling regular walls (from brick or wood) above ground works as expected.

### Steps To Reproduce

1. Start a game as a evacuee.
2. Go to the basement of evac shelter.
3. Spawn any of pickaxe, jackhammer or electric jackhammer.
4. Drill a wall (would leave empty space).
5. Make a floor to be able to get to stone using debug menu.
6. Drill a solid rock (would leave empty space).
7. Teleport to nearest cathedral.
8. Drill a solid rock wall of cathedral (would leave empty space).

### Expected behavior

Mining solid rock should leave rock floor.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f15b4f8 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges]
]

### Additional context

Probably related to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1635

Other code in this actions haven't changed in years: https://github.com/cataclysmbnteam/Cataclysm-BN/blame/upload/src/map.cpp#L3631

**Comment by Secret-Cisco** [comment]
Can confirm that the bug is readily reproduced in any version of the game from [2022-06-30-1842](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2022-06-30-1842) onward, not present before.
