### ISSUE TITLE
.22 LRs spawn in 5.56 rifles

### ISSUE THREAD

**Issue by sanosit** [cataclysmbnteam/Cataclysm-BN#1768]
### Describe the bug

About all rifles, I found in lab/outpost/etc loaded with ruger mag with 25 .22 LR. 
Looks like mods conflict to me.

### Steps To Reproduce

1. Go to lab`s barracks armory.
2. Find any 5.56 rifle.
3. You are the greatest debugger this world seen.

### Expected behavior

Check spawn setups for guns, lock on stanags, like it was many many releases before.

### Screenshots

![image](https://user-images.githubusercontent.com/100729330/182003703-e4a40364-a5c8-4583-835c-aa98173567ee.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 5d36160 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Cataclysm++ [Cata++],
    Magiclysm [magiclysm],
    Advanced Technologies [advtech],
    BioCo Content [bioco],
    Bionic Space Expander [Bionic_Space_Expander],
    Bionics Systems Recipes [bio_recipes],
    CBM Equipment [CBM_Arms],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Large capacity storage CBMs [eps_cbm],
    Modern Weapon Pack Expanded [modern_weapon],
    Ricky's Future Armory [futurearmory],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Advanced Gear [adv_gear]
]

**Comment by Relgar** [comment]
This is because Modern Weapon Pack Expanded overrides the default weapons with it's own versions that take .22 and .308. This is an issue with the mod and not the base game.

`{
    "id": "sig552",
    "copy-from": "sig552",
    "type": "GUN",
    "name": { "str": "SIG 552" },
    "ammo": [ "308", "22", "223" ],
    "magazines": [
      [
        "223",
        [
          "stanag5",
          "stanag30",
          "transmag",
          "stanag10",
          "stanag20",
          "stanag40",
          "stanag50",
          "stanag60",
          "stanag60drum",
          "stanag90",
          "stanag100",
          "stanag100drum",
          "stanag150",
          "223betacmag",
          "survivor223mag"
        ]
      ],
      [ "22", [ "ruger1022bigmag", "ruger1022mag" ] ],
      [ "308", [ "g3mag", "g3bigmag", "308betacmag" ] ]
    ]
  }`

**Comment by chaosvolt** [comment]
I would suggest opening an issue for the repo the mod's from, either its source repo if it's still being maintained, or whichever compilation it's being maintained in if not.
