### ISSUE TITLE
Moving items from inventory in AIM bug

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#1773]
### Describe the bug

In the newest version of the game - release 567 (Cataclysm-BN experimental build 2022-07-30-2235) windows,
when moving items using AIM from inventory to a different tile, there is an error which says:
"You are not wearing that item."
The game also crashed on me on top of it, while trying to do that.

### Steps To Reproduce

1. Download new version of the game.
2. New world, new game
3. Open advanced inventory management and move items from Inventory to a tile nearby.
4. Observe that you can't do that.

### Expected behavior

Being able to move items from inventory using AIM, just like before.

### Screenshots

![image](https://user-images.githubusercontent.com/72284934/182755538-2d7a62b5-0814-4507-b24f-4716b54a79f5.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cb7204c [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges]
]

### Additional context

[crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/9256407/crash.log)
[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/9256408/debug.log)

**Comment by olanti-p** [comment]
Most likely caused by mine #1761

**Comment by Treah** [comment]
Sorry olanti-p I commented on your PR instead of this bug here which probably would have been the better place. I can confirm this happens on Linux as well but with no crash. At least in my case it does not crash just gives me the log message about not wearing the item. It however does let me put items into static containers like a cupboard but not the open floor.
