### ISSUE TITLE
Core dump crash.

### ISSUE THREAD

**Issue by JavelinHeadQueer** [cataclysmbnteam/Cataclysm-BN#179]
Game version:
826

Operating system:
Manjaro Linux, GNOME edition.

Tiles or curses:
Tiles.

Mods active:
Aftershock, speedydex, stats through kills and skills, no fungal monster, simplified nutrition, manual bionic installation, disable npc needs, no lifting requirements.

### Expected behavior
Not crashing randomly

### Actual behavior
Crashing randomly

### Steps to reproduce the behavior
No idea, crashes sometimes when reading maps in mega city world, sometimes when moving though that's only happened once. Affixing core dump to this post as reading I hardly qualify for reading through it myself.
https://gofile.io/d/llAMQL

Also previously to the core dump is this:
`The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 2bd90b4
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation faultError creating SDL message box: No message system available

STACK TRACE:

    ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x43) [0x55e556991cba]
    ./cataclysm-tiles(+0x63f6b2) [0x55e5569816b2]
    ./cataclysm-tiles(+0x63f825) [0x55e556981825]
    /usr/lib/libc.so.6(+0x3d6a0) [0x7f8e124ec6a0]
    ./cataclysm-tiles(_ZN6effect12set_durationERK13time_durationb+0x2b) [0x55e5569da0bd]
    ./cataclysm-tiles(_ZN6effect12mod_durationERK13time_durationb+0x2a) [0x55e5569da240]
    ./cataclysm-tiles(_ZN9Character5vomitEv+0x2a8) [0x55e5568f9dbe]
    ./cataclysm-tiles(_ZN6player18process_one_effectER6effectb+0xf02) [0x55e556ed658e]
    ./cataclysm-tiles(_ZN6player24process_effects_internalEv+0x410) [0x55e556ed4a96]
    ./cataclysm-tiles(_ZN8Creature15process_effectsEv+0x2a) [0x55e556984d3c]
    ./cataclysm-tiles(_ZN8Creature12process_turnEv+0x25) [0x55e556985011]
    ./cataclysm-tiles(_ZN9Character12process_turnEv+0x81) [0x55e5568eed8b]
    ./cataclysm-tiles(_ZN6player12process_turnEv+0x34) [0x55e556ee43a8]
    ./cataclysm-tiles(_ZN4game7do_turnEv+0x986) [0x55e556a6851e]
    ./cataclysm-tiles(main+0x12e0) [0x55e556740be3]
    /usr/lib/libc.so.6(__libc_start_main+0xf2) [0x7f8e124d7152]
    ./cataclysm-tiles(_start+0x2a) [0x55e5567c2e8a]`

**Comment by Coolthulhu** [comment]
Looks like it's the vomit crash, which should be fixed in 832.

**Comment by JavelinHeadQueer** [comment]
I will update the game then.
