### ISSUE TITLE
Stop NPC's from blocking damage using broken limbs

### ISSUE THREAD

**Issue by BoldTint** [cataclysmbnteam/Cataclysm-BN#1790]
### Is your feature request related to a problem? Please describe.

Problem: Human NPC's block your attacks with their hands, despite them being broken.
Because of that already long fights sometimes can take hours, while both you and the NPC can't do any meaningful damage to each other, despite the log stating that you actually do damage.

### Describe the solution you'd like

Make NPC's (maybe the player too?) unable to block incoming damage using a broken limb. Maybe add some sort of a check that stops the action, if the limb is broken. That's really it.

### Describe alternatives you've considered

Maybe add a feature that makes the limbs get damaged even after they've been broken, straight up destroying it if it receives too much total damage (double the normal amount, maybe?). But, even though this could potentially lead to some interesting ideas and force players to use mutations or bionics to heal lost limbs, and maybe could lead to some interesting enemies that specifically target limbs, it would probably take too much time and effort.

Also, maybe the damage dealt to the broken limb could instead be dealt to the torso or the other limb, that the attack was aimed at, but that would probably create even more bugs.

**Comment by Coolthulhu** [comment]
I don't think they explicitly block with limbs that are destroyed, it's just that the combat system doesn't avoid targeting those.

Some sort of "damage overflow" could be good, but it would need to be done carefully to avoid hurting player more than NPCs. Broken limbs on player are already unfun enough with the 2 week heal time.
It would be safer to make the attacks skip broken limbs where possible. Where not possible, they could cause bleed to the parent body part.

**Comment by BoldTint** [comment]
No, they actually do block attacks with their broken limbs, the game said so, almost every time I tried to attack a bandit that followed me to my home base. I wish I could attach a screenshot, but I didn't make any. If it'll be needed - I'll try to replicate that behaviour.

**Comment by leoCottret** [comment]
I can at least confirm this, spawned an NPC, broke his 2 arms, gave him an arm guard through the debug menu and he could still block my hits. I also broke my arms and could still block his hits.
