### ISSUE TITLE
Figure out a system for change log release

### ISSUE THREAD

**Issue by rtizzy** [cataclysmbnteam/Cataclysm-BN#18]
Discussing with @Coolthulhu possible methods of creating sane changelogs with a minimal amount of overhead. 

Possible solutions to help automate this process:

https://pypi.python.org/pypi/gitchangelog
https://github.com/skywinder/github-changelog-generator

Solutions that are largely manual but provide some automation help

https://github.com/mattbrictson/chandler

**Comment by elricsfate** [comment]
Worth reading

http://keepachangelog.com/en/1.0.0/
