### ISSUE TITLE
Helicopter won't lift off 

### ISSUE THREAD

**Issue by T-rexsuper1** [cataclysmbnteam/Cataclysm-BN#1810]
### Describe the bug

I am playing the game and my helicopter is stuck on Mi-Go tower because it can't lift off even though I removed the roof with map editor. The funny is that there was a roof in the first place (I don't think it should have been there) and that it landed there at all.

### Steps To Reproduce

It's hard to say but I guess land under a roof? 

### Expected behavior

I wanna take off! 

### Versions and configuration

[Earth.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/9424249/Earth.zip)

**Comment by Coolthulhu** [comment]
Dope of #1136
Related to #1197
