### ISSUE TITLE
drop tuxedo crash

### ISSUE THREAD

**Issue by Trokinos** [cataclysmbnteam/Cataclysm-BN#182]
was finishing a task in cataclysmbn-821-win64-tiles before updating to newer version and got a crash message .

my character was wearing a tuxedo, to check something i decided to drop it.
As soon as i pressed d then selected it and enter , crash message (interesting in the crash it mention "Tried to take off "tux" which isn't worn".

15:22:10.976 ERROR : (error message will follow backtrace)
  0
    (dbghelp: @0x6498d6[cataclysm-tiles.exe+0x2498d6]), 
    (libbacktrace: Z21debug_write_backtraceRSo+0x56@0x6498d6),
    (libbacktrace: 0x6498d6    [unknown src]:0    [unknown func]),
  1
    (dbghelp: @0x64a36a[cataclysm-tiles.exe+0x24a36a]), 
    (libbacktrace: Z8DebugLog10DebugLevel10DebugClass+0x34a@0x64a36a),
    (libbacktrace: 0x64a36a    [unknown src]:0    [unknown func]),
  2
    (dbghelp: @0x64d5d6[cataclysm-tiles.exe+0x24d5d6]), 
    (libbacktrace: Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x76@0x64d5d6),
    (libbacktrace: 0x64d5d6    [unknown src]:0    [unknown func]),
  3
    (dbghelp: @0xbac1fe[cataclysm-tiles.exe+0x7ac1fe]), 
    (libbacktrace: ZN13player_morale8set_wornERK4itemb+0xd4e@0xbac1fe),
    (libbacktrace: 0xbac1fe    [unknown src]:0    [unknown func]),
  4
    (dbghelp: @0x8402d3[cataclysm-tiles.exe+0x4402d3]), 
    (libbacktrace: ZN4item10on_takeoffER9Character+0x13@0x8402d3),
    (libbacktrace: 0x8402d3    [unknown src]:0    [unknown func]),
  5
    (dbghelp: @0xfd23f0[cataclysm-tiles.exe+0xbd23f0]), 
    (libbacktrace: ZN9visitableI9CharacterE17remove_items_withERKSt8functionIFbRK4itemEEi+0x100@0xfd23f0),
    (libbacktrace: 0xfd23f0    [unknown src]:0    [unknown func]),
  6
    (dbghelp: @0x57e4bc[cataclysm-tiles.exe+0x17e4bc]), 
    (libbacktrace: ZN9Character5i_remEPK4item+0x5c@0x57e4bc),
    (libbacktrace: 0x57e4bc    [unknown src]:0    [unknown func]),
  #7
    (dbghelp: @0x4c247d[cataclysm-tiles.exe+0xc247d]), 
    (libbacktrace: ZN6avatar5wieldER4item+0x1bd@0x4c247d),
    (libbacktrace: 0x4c247d    [unknown src]:0    [unknown func]),
  8
    (dbghelp: @0x4d32a0[cataclysm-tiles.exe+0xd32a0]), 
    (libbacktrace: ZN13avatar_action7plthrowER6avatar13item_locationRKN4cata8optionalI8tripointEE+0x350@0x4d32a0),
    (libbacktrace: 0x4d32a0    [unknown src]:0    [unknown func]),
  9
    (dbghelp: @0x7a19fa[cataclysm-tiles.exe+0x3a19fa]), 
    (libbacktrace: ZN4game13handle_actionEv+0x297a@0x7a19fa),
    (libbacktrace: 0x7a19fa    [unknown src]:0    [unknown func]),
  10
    (dbghelp: @0x76fc0f[cataclysm-tiles.exe+0x36fc0f]), 
    (libbacktrace: ZN4game7do_turnEv+0xc6f@0x76fc0f),
    (libbacktrace: 0x76fc0f    [unknown src]:0    [unknown func]),
  11
    (dbghelp: IMG_LoadWEBP_RW+0x77dbf8@0x1933778[cataclysm-tiles.exe+0x1533778]), 
    (libbacktrace: main+0x11a8@0x1933778),
    (libbacktrace: 0x1933778    [unknown src]:0    [unknown func]),
  12
    (dbghelp: @0x4013bd[cataclysm-tiles.exe+0x13bd]), 
    (libbacktrace: _tmainCRTStartup+0x23d@0x4013bd),
    (libbacktrace: 0x4013bd    ../gcc-5.5.0.build_/mingw-w64-v6.0.0/mingw-w64-crt/crt/crtexe.c:341    __tmainCRTStartup),
  13
    (dbghelp: @0x4014cb[cataclysm-tiles.exe+0x14cb]), 
    (libbacktrace: WinMainCRTStartup+0x1b@0x4014cb),
    (libbacktrace: 0x4014cb    ../gcc-5.5.0.build_/mingw-w64-v6.0.0/mingw-w64-crt/crt/crtexe.c:197    WinMainCRTStartup),
  14
    (dbghelp: BaseThreadInitThunk+0x14@0x7ff9923c7c24[KERNEL32.DLL+0x17c24]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  15
    (dbghelp: RtlUserThreadStart+0x21@0x7ff9938ecea1[ntdll.dll+0x6cea1]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 1 seconds.
src/morale.cpp:968 [void player_morale::set_worn(const item&, bool)] Tried to take off "tux" which isn't worn.
15:22:36.380 : Log shutdown.

**Comment by Coolthulhu** [comment]
It looks like a morale-related effect. Do you have the Stylish trait?

**Comment by olanti-p** [comment]
```
#8
(dbghelp: @0x4d32a0[cataclysm-tiles.exe+0xd32a0]),
(libbacktrace: ZN13avatar_action7plthrowER6avatar13item_locationRKN4cata8optionalI8tripointEE+0x350@0x4d32a0),
(libbacktrace: 0x4d32a0 [unknown src]:0 [unknown func]),
```
You probably meant when `t`hrowing worn tuxedo.
I tried reproducing - found no crash, but debugmsg pops up (regardless of `Stylish` trait), and otherwise throwing works fine.

**Comment by Trokinos** [comment]
I don't use the stylish trait on that character.
Trying to reproduce the problem, i managed to do it consistently.  Though i was sure i was simply dropping, but it's indeed t(hrowing)
Here is the save, Baldwinville :  
  
[Baldwinville.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5484038/Baldwinville.zip)

Load the save, press t then select the tuxedo and press enter, select "drop item" and the error message should appear (it does not crash though as you can press space to continue playing, but the message is the same as the one i reported )

**Comment by Coolthulhu** [comment]
I got it: `avatar::wield` has a redundant `on_takeoff`.
Regular wielding didn't trigger the bug because it does same things that `avatar::wield` does, then calls `avatar::wield` only when the item is un-worn and player's weapon is removed.

It's a very minor bug, so I'll bundle it with some minor throwing rebalancing.
