### ISSUE TITLE
Magiclysm ability to read spellbooks / scrolls

### ISSUE THREAD

**Issue by Robik81** [cataclysmbnteam/Cataclysm-BN#1827]
### Describe the bug

After activating book and choosing to learn spell, action is cancelled and there is 'It is too dark to read' in log. 

That is despite bright light. Reading normal books woks fine.

### Steps To Reproduce

1. make new game with character with spellbook
2. stand in the light
3. try to learn any spell

### Expected behavior

It should work...

### Versions and configuration

Irrelevant

### Additional context

It did work in build 2022-08-25-1937. (and does again after a revert)

It was broken in either 2022-09-28-1400 or 1433

**Comment by olanti-p** [comment]
Thanks for the report.
Fix is on the way, #1821

**Comment by Robik81** [comment]
Sorry, should have checked opened issues first! :)
