### ISSUE TITLE
"Clear forest" basecamp activity causes noise at wrong position

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#1829]
### Describe the bug

Basecamp activities work by loading a sector of map, operating on it, then saving it. In this case, they use the `map::destroy` function, but lack the `silent` parameter, so it defaults to noisy.
`map` class lacks "awareness" of whether it is the "real" map or a temporary one, so this causes noise on the "real" map (`g->m` or `get_map()`).

### Steps To Reproduce

1. Go to a field near a forest
2. Spawn NPC and tell them to start a basecamp
3. Debug NPC skills up to 10
4. Interact with spawned bulletin board and assign "clear forest" to the NPC, picking a forest tile that isn't to the northwest
5. Hear noise from northwest

### Expected behavior

No noise when just assigning the job, especially if the job is too far to be heard.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 2d4d88fc6e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Magiclysm [magiclysm]
]

**Comment by scarf005** [comment]
closing since basecamps were completely removed in #4369
