### ISSUE TITLE
Extinguish candle UI spam

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#1833]
### Is your feature request related to a problem? Please describe.

When using candle in order to extinguish it, a menu appears with options to light something on fire or extinguishing it.
This is completely redundant as PC uses candle automatically when lighting something on fire and the option in the menu serves no purpose other than spamming the player with the UI and requiring more key-presses to extinguish the candle.
![image](https://user-images.githubusercontent.com/72284934/188334246-f578841c-d3d5-4190-b5ba-d5bd49605cb9.png)

### Describe the solution you'd like

Remove the UI from candle and make it that using lit candle will extinguish it.

**Comment by Soadreqm** [comment]
Is there an alternative way to light a tile on fire, without applying a fire source?

**Comment by leoCottret** [comment]
Yes it would be nice to have a way to light something with one button (well 2 with the direction to choose, but still one button less), and except at the very beginning of the game you'll use better light sources for light anyway.

**Comment by Krwak** [comment]
Sorry for late reply but you can light something on fire from Item Action Menu, it will use any item that is available for this action.
You can find item action menu under keybindings menu, not sure what is the default binding key for it.

**Comment by leoCottret** [comment]
It's "%"

**Comment by Drugitechnik** [comment]
IMO this is working within expected behaviour from my perspective as player.
Item has 2 actions, after activating it needs clarification.

**Comment by chaosvolt** [comment]
To clarify, it seems that there's currently no way to remove the "want to maybe accidentally burn your house down?" action without it also breaking the ability to use it via `e`xamine, as lighting stuff via examining looks for the firestarter use_action in the item, to figure out stuff like how long it'll take.

Best solution is probably to make transform actions have priority on the list, but we'll need to figure out how the code orders them...

**Comment by Drugitechnik** [comment]
> To clarify, it seems that there's currently no way to remove the "want to maybe accidentally burn your house down?" action without it also breaking the ability to use it via `e`xamine, as lighting stuff via examining looks for the firestarter use_action in the item, to figure out stuff like how long it'll take.
> 
> Best solution is probably to make transform actions have priority on the list, but we'll need to figure out how the code orders them...

it requires more than single input to achive... it asks where you want to start fire...

**Comment by Coolthulhu** [comment]
I completely misread what's happening and treated it like a much more serious issue...

Having one item appear multiple times in use menu, with separate actions, could be nice, but it's not a serious problem to have to go through the nested menu.

**Comment by Krwak** [comment]
Ffs, this has been stale for a year, let it die.
