### ISSUE TITLE
Getting inside the large cardboard box grants clairvoyance for items and creatures to player.

### ISSUE THREAD

**Issue by NobleJake** [cataclysmbnteam/Cataclysm-BN#1858]
### Describe the bug

If you get inside the box, you can clearly see the surrounding creatures, items, bloodstains, etc. through the wall and appears on the memory map, though your vision impaired.

### Steps To Reproduce

1. Put a large cardboard box.
2. Get inside the box.
3. Now you can see the location of items and creatures through walls.

### Expected behavior

It's simply wall-hack with cardboard box.

### Screenshots

<img width="305" alt="jongeee" src="https://user-images.githubusercontent.com/108422062/190705353-d191bff8-d33e-487c-b72d-c9bb6e666a3d.png">

<img width="799" alt="jongee2" src="https://user-images.githubusercontent.com/108422062/190705486-c8100b7e-77f7-443b-abcf-fc3fd2ad22bc.png">

<img width="1280" alt="wallhack" src="https://user-images.githubusercontent.com/108422062/190706412-12c6490c-3e13-4ad1-996e-d06db03bf4fd.png">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f5cccb8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    PK's Rebalancing [PK_REBALANCE],
    Expanded Archery [ExArch],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Pneumatic fun [pneumo_fun],
    Craftable Gun Pack [craftgp],
    THRESHOLD [add_mutant],
    Mythical Martial Arts [MMA],
    Folding Parts pack* [deoxymod__],
    Alternate ear graphics [alt_ear_gfx],
    PK - No radioactive zombies [PK_zom_rads],
    No Fungal Monsters [No_Fungi],
    better cataclysm [better_cataclysm],
    Faster Stamina Regen [stamina_regen_buff],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Stronger archery [bow_opness],
    Targeted Mutations [TaMu],
    Stats Through Skills [StatsThroughSkills],
    No Lifting Reqs [disable_lifting],
    SpeedyDex [speedydex],
    Manual Bionic Installation [manualbionicinstall],
    Stats Through Kills [stats_through_kills],
    Prevent Zombie Revivication [no_reviving_zombies],
    3x Healing [3x_healing],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Blazemod - Vehicle Additions Pack* [blazemod__],
    Jury-Rigged Robots [jury_rigged_robots]
]

**Comment by chaosvolt** [comment]
Happens in general it seems, not just in boxes. Presumed side effect of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1743 most likely? @joveeater
