### ISSUE TITLE
Tile modding for RM216 SPIW not working

### ISSUE THREAD

**Issue by NobleJake** [cataclysmbnteam/Cataclysm-BN#1859]
### Describe the bug

I tried to make a new pixel art for RM216 SPIW by modifying the undead people tileset(normal_items.png) in aseprite, but it doesn't work at all, and the tiles before modding are reloaded.

### Steps To Reproduce

1. Modify the tile of RM216 SPIW with aseprite.
2. turn on the game and check.
3. not applied.

### Expected behavior

If it is the internal code error, it will block further tileset updates for the SPIW.

### Screenshots

<img width="447" alt="SPIWissue1" src="https://user-images.githubusercontent.com/108422062/190712073-3edc57b6-7bd9-4315-9656-1396cf3f11d6.png">
^modded tiles on aseprite

<img width="393" alt="SPIWissue2" src="https://user-images.githubusercontent.com/108422062/190712176-ac0bed24-0666-433d-b1ff-c985fe9917a9.png">
^not applied

### Versions and configuration

Game Version: https://github.com/cataclysmbnteam/Cataclysm-BN/commit/f5cccb87dfe69c436b5e5f82fc9efd4a91e1e33b [64-bit]

**Comment by olanti-p** [comment]
Looks like you've been modifying the wrong tile.
`RM216 SPIW` has an in-game id `needlegun`, on version https://github.com/cataclysmbnteam/Cataclysm-BN/commit/f5cccb87dfe69c436b5e5f82fc9efd4a91e1e33b stated in the report in UDP's `tile_config.json` that id corresponds to the following tiles:
```
    { "id": "needlegun", "fg": 4596, "bg": 9172, "rotates": false },
    { "id": "overlay_wielded_needlegun", "fg": 4597, "rotates": false },
```
Sprite with index `4596` is located at (128px, 9184px) in `normal_items.png`
![image](https://user-images.githubusercontent.com/60584843/210663826-b550dc9b-1f72-47f6-ba0c-9ccf85e2c1cd.png)
Modifying it and reloading the tileset makes the changes reflect in game.
![image](https://user-images.githubusercontent.com/60584843/210663875-af4cbbd1-6d8b-4d21-9d19-5c04c0d6136c.png)
