### ISSUE TITLE
Charcoal smokers cause lag

### ISSUE THREAD

**Issue by asterix-a** [cataclysmbnteam/Cataclysm-BN#189]
Describe the bug
Game lagging becose of charcoal smoker its no critical but annoying 

Steps To Reproduce
Just spawn charcoal smoker and tray to put some meat and start to smoke

I spawn some zombie-smokers and game work normal it just a charcoal smoker problem

**Comment by olanti-p** [comment]
Doesn't seem to be an issue in the current version, according to player feedback. At least no more lag than regular fields cause.
