### ISSUE TITLE
Extreme slowdown in the Prison Island (and literally only there)

### ISSUE THREAD

**Issue by tyrael93** [cataclysmbnteam/Cataclysm-BN#190]
# Describe the bug

Started a Prison Island character. Crafting and reading lags horribly (6 IRL seconds to read an 8 minute chapter of a book, several seconds to craft a 1 minute recipe etc). This happens even with Z-levels disabled (by default), all mobs killed with debug mode in the surrounding area.
Tried to reproduce the lag in a nearby island, lighthouse and other outcrops of land surrounded by huge swathes of water, but there the game runs fine. The lag is localized entirely withing the prison island.

# Steps To Reproduce

Read or craft anything in a prison island start, even after debug-killing all mobs.

# Expected behavior

/Not/ a fuckhuge slowdown localized entirely within the bermuda prison triangle.

# Versions and configuration

Just load anything. I've reproduced it with a heavily modded version of minecraft (and thought that was the issue) and a simple lightweight vanilla BN only world. Always lagged to hell and back.

**Comment by Coolthulhu** [comment]
Save?
I played a prison island start recently and it was fine.

**Comment by tyrael93** [comment]
'ere ya go
All mobs immediately killed, Z-levels disabled, Only DDA and disable NPC needs enabled, squarelos, reading a book takes ages compared to anywhere else.
https://files.catbox.moe/21l58n.zip

**Comment by Coolthulhu** [comment]
On my computer, it was ~2 minutes per IRL second.
The profiler doesn't say anything interesting.

**Comment by tyrael93** [comment]
Must be the ol' shitbox acting up then
me bad
