### ISSUE TITLE
Port request: progression diary

### ISSUE THREAD

**Issue by Wolf-93** [cataclysmbnteam/Cataclysm-BN#1917]
### Is your feature request related to a problem? Please describe.

If being a weirdo that likes to RP is a problem, then yes. Besides that, it's not a pressing matter. For non-weirdos, it's a good place to make to-do lists, raiding lists, etc.

### Describe the solution you'd like

I'm not very savvy on the topic, but it would involve forking the code from DDA. Here's the link to PR as Kheir suggested to me on Discord (also, thanks to Chaosvolt too!): [Feature progression diary - "Dark diary"](https://github.com/CleverRaven/Cataclysm-DDA/pull/52372)

### Describe alternatives you've considered

Learning C# and doing it myself. I predict very low probabilities of happening.

### Additional context

Here's a screenshot I shamelessly grabbed from the original PR for anyone that didn't know of the feature.

![138111899-82e10209-baa3-4547-8981-7c5b74be1321](https://user-images.githubusercontent.com/46269232/192335740-963caaea-ee28-4d32-b20f-405aa8cfe1a2.png)

**Comment by leoCottret** [comment]
@Wolf-93 Thanks for this port request, and if one day you want to participate the game is made with c++, not c#
