### ISSUE TITLE
Port request: shotshells fires a cloud of projectiles

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#1920]
### Is your feature request related to a problem? Please describe.

buckshot firing single projectile always felt weird

### Describe the solution you'd like

port over
- CleverRaven/Cataclysm-DDA#52583

**Comment by olanti-p** [comment]
IMO this would be a needless complication for little gain.

Reading that PR, this is just a physics-based simulation of shotgun damage decreasing with distance. It may work for DDA, but BN's focus is on depth, not complexity. A single ammo flag (with optional distance factor?) will work similarly enough:
```
if ( projectile.has_effect( DAMAGE_FALLS_WITH_DISTANCE ) {
    final_damage = projectile.damage / ( distance ^ projectile.distance_factor);
}
```

**Comment by scarf005** [comment]
but how about projectile counts?

**Comment by Coolthulhu** [comment]
We have cone AoE shots. They just need some balancing vs armor.

**Comment by scarf005** [comment]
iirc buckshot is single projectile. maybe it could also be changed into very narrow AoE, like 2 width max.
