### ISSUE TITLE
Examine auto-lockpick action asks for a direction

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#1923]
### Describe the bug

Examining a pickable object says "you attempt to pick lock", then asks for a direction instead of picking the examined object.

All iuse functions have a position argument and one is supplied to `pick_lock_actor::use`, but the function doesn't use it and unconditionally asks for direction instead.

### Steps To Reproduce

* Spawn a locked safe
* Spawn a lockpick
* Pick the lockpick up (wielding OK)
* Examine the safe
* Direction prompt appears

### Expected behavior

No direction prompt, examining the safe already required providing a direction.

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 68d3ee02ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Magiclysm [magiclysm],
    Manual Bionic Installation [manualbionicinstall]
]

**Comment by leoCottret** [comment]
Did this get fixed?
I couldn't reproduce.
- Spawn different kind of safe including lock safe
- Wield or not the lockpick
- Press "e" -> select safe direction
- It always lockpicking it after selection, without extra messages

**Comment by leoCottret** [comment]
Ah, I finally could reproduce on a door while fixing an other issue, I'll try to fix this one too
