### ISSUE TITLE
Text changelog in repo

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#1930]
### Is your feature request related to a problem? Please describe.

There's a text changelog in the repo. Should be updated before first stable.

### Describe the solution you'd like

Add https://github.com/cataclysmbnteam/Cataclysm-BN/wiki/Changes-so-far to changelog.txt.

### Describe alternatives you've considered

Remove the changelog from the repo and have it be somewhere else.

**Comment by olanti-p** [comment]
Closed by #1942
