### ISSUE TITLE
add JSON schema support

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#1948]
### Is your feature request related to a problem? Please describe.

Writing complex JSON only to find out it was invalid on loading can be quite frustrating.
Since we use JSON a lot, a schema would be useful.

### Describe the solution you'd like

1. create a vscode extension
2. add JSON schema to it

### Additional context

<https://json-schema.org/>
<https://code.visualstudio.com/docs/languages/json>
<https://pydantic-docs.helpmanual.io/>

**Comment by olanti-p** [comment]
Some types have extremely convoluted JSON layout, the potential extension would have to be able to handle them.

A quick rundown of needed functionality:
- Support for mandatory and optional fields
- Depending on the value of some field the game may attempt reading from additional mandatory/optional fields, so the extension would have to understand these values
- There's the whole copy-from thing to consider, some mandatory fields become optional if object is copy-from'ed

There's a lot of complex rules here, sometimes working differently depending on object type, so tracking down all of them and then maintaining them afterwards would be a pain.

A simpler error-checking extension, hovewer, should be doable. Say, like with json formatter, build a separate lightweight executable that quickly loads a single json file and reports the errors - a lot of them have context like field name or line and column, so a potential extension could parse the output and turn it into squiggly lines in the editor.

As a bonus, the extension could ask the executable to load a set of mods and report all errors from data checks and finalization - it'd take a couple dozen seconds, but would produce a list that's easy to browse in the editor - maybe also parse the name of erroneous objects from error log and highlight them.

As a second bonus, the extension could provide format-json-on-save functionality.

**Comment by scarf005** [comment]
alright, i'd start on ideal JSON schema without `copy-from` first.

**Comment by scarf005** [comment]
now it's a separate project: https://github.com/scarf005/Cataclysm-BN-tools
