### ISSUE TITLE
Can't drag or push vehicles over ramps

### ISSUE THREAD

**Issue by olanti-p** [cataclysmbnteam/Cataclysm-BN#1978]
### Describe the bug

It's impossible to drag or push vehicles over ramps.

### Steps To Reproduce

1. Enable "Elevated bridges" mod
2. Tp to a bridgehead
3. Debug spawn shopping cart
4. Try getting it up or down the ramp

### Expected behavior

The shopping cart does not mysteriously collide with the ramp, and the avatar does not let go of it when they ascend or descend.

### Versions and configuration

Game version 6b7f879b6e6247d628d4ba2ae4680d8d86d770d8

### Additional context

I may be mistaken, but pretty sure at some point it was possible to at least push it.

**Comment by RelMayers** [comment]
I was able to push/pull golf cart on not newest version, will do same test on newest.

**Comment by joveeater** [comment]
This is likely something I did when I changed how ramps work. I'll look into it.
