### ISSUE TITLE
QoL suggestion

### ISSUE THREAD

**Issue by JavelinHeadQueer** [cataclysmbnteam/Cataclysm-BN#198]
You ever struggle picking up books in a library, constantly having to look into your pack so you don't take multiples of one book?
Happens to me all the time too. It'd be neat if a number could be added to book titles that shows how many of that book is already in your inventory.

**Comment by Coolthulhu** [comment]
Nowadays you can insta-note that you have a book by skimming it in zero time.

**Comment by Coolthulhu** [comment]
Old feature request that would be hard to implement and is mostly resolved by filtering `(unread)`.
