### ISSUE TITLE
Make sawn-off shotguns holsterable and buffing the sawn-off mod in general

### ISSUE THREAD

**Issue by miu135** [cataclysmbnteam/Cataclysm-BN#199]
I just want my sawed-off shotguns back

**Comment by Coolthulhu** [comment]
What exactly do you want from them?
Volume, control, skill to use them, quick aim?

**Comment by miu135** [comment]
Volume so it could fit in a holster would be nice (an XL holster is fine too if you think it's more balanced)

**Comment by VuradoZ** [comment]
This can be done by changing the volume line in mod. I can do it, tests passed successfully

![image](https://user-images.githubusercontent.com/79693833/113640282-bbc40500-9683-11eb-8441-4767fed83cb4.png)

**Comment by Relgar** [comment]
Here are the ranges for our current shotgun-swingin' holsters:

Holster: 300-800 ml
XL Holster: 750-1250 ml
Survivor Harness: 1250-3750ml
Back Holster: 1500-9000ml

Shotguns range from 500ml to 4.7L so I think we're covered here. Should be good to close this.
