### ISSUE TITLE
tiles are not displayed at height

### ISSUE THREAD

**Issue by BROtania** [cataclysmbnteam/Cataclysm-BN#1995]
### Describe the bug

tiles are not displayed at height

### Steps To Reproduce

I can send a card and a character if necessary

### Expected behavior

displaying tiles

### Screenshots

![image](https://user-images.githubusercontent.com/73956193/194754563-a1275077-0ac8-4719-b56a-d306dec8cff7.png)

### Versions and configuration

[build 2022-10-05-1956](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2022-10-05-1956)

**Comment by BROtania** [comment]
![image](https://user-images.githubusercontent.com/73956193/195112883-62587acf-707e-416e-a6c5-2792776b9494.png)
one more bug

**Comment by olanti-p** [comment]
> tiles are not displayed at height

Не очень понятно из скриншота, что происходит. Тайлы справа от персонажа должны отрисовываться, но не отрисовываются?

Можете отправить файлы сохранения (папка `save/НазваниеМира/`) и настроек (`config/debug.log`)?

> one more bug

Это не баг, это особенность генерации локации. Дыра в полу вынуждает игрока искать обходные пути.
