### ISSUE TITLE
drawing lower z levels : zombies aren't appearing with default settings

### ISSUE THREAD

**Issue by Trokinos** [cataclysmbnteam/Cataclysm-BN#2032]
### Describe the bug

World is displayed on lower z level but zombies are invisible with CBN default settings

### Steps To Reproduce

Just started an evacuee scenario.
Zombies were around the starting shelter.
Ran back to the shelter and climbed on the roof to look at the surrounding.
Zombies following me aren't displayed , their sound still are.

### Screenshots

![8888](https://user-images.githubusercontent.com/14024168/196036392-8f36acc6-8d0c-4fad-a267-d47eed40cee7.jpg)

### Versions and configuration

Window 10
Experimental version of CBN  : cbn-windows-tiles-x64-msvc-2022-10-15-2049
windowed or borderless fullscreen makes no difference
render d3d11/d3d/opengl/software makes no difference

### Additional context

In CBN if you go to Options - > Debug , the "Experimental 3D View" is disabled by default

If i enable it , suddenly the zombies will be displayed on the lower z-level
If i disabled it again, they disappear from view again.

**Comment by joveeater** [comment]
This is working as intended. Without experimental 3d vision you can't see monsters or items above or below you and they can't see you.
