### ISSUE TITLE
Windows builds failing due to zlib version change

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#2082]
### Describe the bug

`vcpkg.exe` is trying to download https://www.zlib.net/zlib-1.2.12.tar.gz
The file has been removed, so the result is 404. This causes MSVC Windows builds to fail.

### Steps To Reproduce

Check any recent Windows build.
For example,
https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/3273584510/jobs/5385974426

### Versions and configuration

Github Actions

### Additional context

Would be great if we could figure out how to make it not require manual updates every time a library gets updated like this. It looks like dirty cache - maybe just clearing the cache would be enough.

**Comment by joveeater** [comment]
Sadly there doesn't seem to be a way to clear out the cache from the web ui. I'm gonna have a go at doing it with the REST api and if it works I'll document it here.

**Comment by joveeater** [comment]
It did not work. At the least the actions cache used by vcpkg wasn't the problem.

**Comment by olanti-p** [comment]
The cache shouldn't matter here, the build is using a "hardcoded" version of `vcpkg` that's been known to work (up until this point), and simply updating it to the latest should be enough
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/5bdea27530148fa2674c5fd04e61052fb6c93953/msvc-full-features/vcpkg.json#L13
(+3 instances in `.github/` folder, see https://github.com/cataclysmbnteam/Cataclysm-BN/search?q=9d9a6f486cc7da7664117a75d01440db0088634a )

Latest vcpkg right now is [f4b262b259145adb2ab0116a390b08642489d32b](https://github.com/microsoft/vcpkg/commit/f4b262b259145adb2ab0116a390b08642489d32b)
