### ISSUE TITLE
Night Vision is broken.

### ISSUE THREAD

**Issue by MisterWytt** [cataclysmbnteam/Cataclysm-BN#209]
# Describe the bug

It seems Night Vision does not work with the latest build. At first I thought it was one of my mods doing it, but after loading up a vanilla world with no mods whatsoever, toggling Night Vision on and off shows no difference in tile distance, whether it be in a dark building, or during the night. I can't see more than two tiles in front of me as a result.

# Steps To Reproduce

1. Make a new world with no mods loaded and set the world's starting time to late at night (10 PM or further, whichever).
2. Create a Character with the Night Vision Trait and enter the world.
3. Go into your toggleable abilities and try switching Night Vision on and off. There will be zero difference of seeing further, or reducing your vision, in the dark.

# Expected behavior

You should be able to see much further in the dark with the trait on, and see less in front of you when it's turned off.

# Versions and configuration

Version 881

  "dda",
  "no_npc_food"

**Comment by Coolthulhu** [comment]
I can't reproduce NV not working at all, but I can reproduce it not disabling itself.

What is your character's perception and eye encumbrance? What's your NV range underground? Does the NV range change if you debug-mutate NV up and down?

**Comment by olanti-p** [comment]
Can reproduce on version 39352544f4f5ada4a4a9388cbbf4ffd3f7047dfc
1. Make a new world, start with default character
2. Set time to 11 pm, set weather to clear
3. Teleport to a clear field
4. Note vision radius (10 tiles)
5. Through debug menu, add Night Vision mutation
6. Note that vision radius didn't change (expected an increase here)
7. Try toggling NV on and off, see no changes
8. Change weather to rain, note new vision radius (4 tiles)
9. Try toggling NV on and off, see no changes
10. Remove Night Vision through debug
11. Note that vision radius shrunk (to 2 tiles)

Conclusion:
1. Default (9 per, 0 enc) NV range without NV trait is surprisingly large 
2. NV trait works, but doesn't turn off
3. It works only when vision is partially obstructed by weather?

**Comment by Proxiehunter** [comment]
What the default night vision being so large and then night vision radius shrinking to 2 when the trait is removed by debug suggests to me is that for some reason night vision might be automatically on at all times _even for characters that aren't supposed to have it_ and then it goes away when removed by debug.
