### ISSUE TITLE
Crash when using a grenade launcher

### ISSUE THREAD

**Issue by leoCottret** [cataclysmbnteam/Cataclysm-BN#2093]
### Describe the bug

The game crash when using a grenade launcher in specific conditions

### Steps To Reproduce

1. Spawn a grenade launcher with multiple ammoes (eg the mark 19 one)
2. Shoot once
3. Press "a" (action menu)
4. The game crash

### Screenshots

![image](https://user-images.githubusercontent.com/71428793/196903402-33ed16e8-7dd7-479e-a1c6-13ed9a9c2de0.png)

### Versions and configuration

- Windows 10
- Branch: upload

**Comment by olanti-p** [comment]
> Branch: upload

is this from before or after be865de1cbb64f84c9b3d5395c31d2a638a7ccd4 ?

**Comment by leoCottret** [comment]
Not sure, but probably before.
For some reasons I couldn't trigger it anymore even on my bugged save, so I guess it is resolved by this change.
I'll just close it for now and reopen it the problem happens again.
