### ISSUE TITLE
Create a start where the player character starts with an NPC follower

### ISSUE THREAD

**Issue by rtizzy** [cataclysmbnteam/Cataclysm-BN#21]
Canonically it's been a few days since the cataclysm occurred

Humans are social creatures, it would make sense that the player character (PC) had formed an alliance with NPCs or even that the PC had arrived with existing friends or family members.

I would like to suggest a player start or perk where the player starts with one or more NPC followers.

**Comment by Coolthulhu** [comment]
The default start could be changed to make the NPC friendly, but at the cost of making that NPC always have the "no class" class.

**Comment by elricsfate** [comment]
@Coolthulhu I'm unfamiliar with this particular concept. Would you mind explaining or linking to some source?

**Comment by Coolthulhu** [comment]
`game::create_starting_npcs()` creates the first NPC. This NPC has 50% of being a doctor:
```
tmp->randomize( one_in(2) ? NC_DOCTOR : NC_NONE );
```

Doctors are really good as friendly NPCs because they can teach you ~5 in first aid.

**Comment by elricsfate** [comment]
@Coolthulhu For balance reasons it may make sense to what you mentioned previously (no class) but instead of doing that I think it would be prudent to implement SOME class. Everyone has a job of some sort or at least some skills. 

Even if you're a drifter or drug addict, there are things you learned in your life. 

50% for a doctor though seems way too high though, especially considering the circumstances. Doctors seem the most likely to die in such a circumstance considering their likely hood to provide aid to dangerous subjects (I.E People who are about to be zombies)

**Comment by Coolthulhu** [comment]
> Everyone has a job of some sort or at least some skills.

Class-less characters still get some skills. They aren't princesses in distress, just Joes Average whose skills aren't related to survival.

A more extensive option would be to reuse player generator for that one tailor-made NPC, though that would require stripping it off some options (scenario selection, location selection) for that one purpose.

**Comment by elricsfate** [comment]
@Coolthulhu 

I think if the easiest initial thing to do would be to just remove the class that's fine by me. We can always reevaluate later

**Comment by chaosvolt** [comment]
An alternative method would be implementing a new scenario flag that overrides normal starter NPC placement in whatever way is desired. This would be hardcoded and hacky fuckery, but simple enough if/else work I suspect.

More complex would be where full-on JSON properties are defined at the scenario level allowing to toggle whether any starter NPC spawns, what NC classes are considered for them (soldier would be expected for heli-crash, for example), and whether their attitude is set to stand around (default), wander as if dynamic, act as companion, attack the player, etc.

The latter would be annoying to implement but a lot more interesting and flexible, and useful for mods.
