### ISSUE TITLE
You should be able to craft a regular arc welder

### ISSUE THREAD

**Issue by yay855** [cataclysmbnteam/Cataclysm-BN#2101]
### Is your feature request related to a problem? Please describe.

The makeshift arc welder functions as a less-efficient normal arc welder, except that you can't hook it up to grid power. That's fine, it's a makeshift one, but the issue is that you can't make a regular one, you have to get lucky enough to find one. If my character has enough knowledge to build a shoddy arc welder, they should be able to make a regular one easily enough after a few more levels of Electrical skill.

### Describe the solution you'd like

Either remove the makeshift arc welder and have the recipe make a normal one instead, or add in a more difficult recipe for a normal arc welder.

**Comment by Zireael07** [comment]
My father is an electrician. I have seen him use an arc welder and I seriously doubt this is something a survivor can make without a factory.

**Comment by Krwak** [comment]
Whether they should or not is debatable.
For the purpose of making a grid welder, the option is already there. You can craft a welding component kit out of two makeshift arc welders. Then make a vehicle welding rig and you can place that one from construction menu to work as grid welder.

**Comment by yay855** [comment]
Alright, I wasn't aware you could place a vehicle welding rig onto a non-vehicle power grid. I'll close this thread, then.
