### ISSUE TITLE
Add option to not minimize game window on focus loss

### ISSUE THREAD

**Issue by yay855** [cataclysmbnteam/Cataclysm-BN#2102]
### Is your feature request related to a problem? Please describe.

The recent update changed how the game is displayed, and now even windowed fullscreen displays cause the entire game to minimize. This no doubt improves rendering speed, but it also means that I can't alt-tab during lengthy wait times and still see when it's finished.

### Describe the solution you'd like

Have the rendering method be something users can choose between, with a detailed description of the benfits of each method.

**Comment by olanti-p** [comment]
Is someone's willing to implement this, the relevant code change is here:
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2016/files#diff-2ae78b6561fcd4265438cd613a1ab5c42c494fb4e960daf2de3235f2817d99e4L251-R254

**Comment by chaosvolt** [comment]
Would the preferred answer be flipping the boolean again, or rigging it to be controlled by a new option separate from window setting?

**Comment by scarf005** [comment]
settings for separate window change changes seems nice.
