### ISSUE TITLE
Can't turn on electric chainsaw lajatang with ups

### ISSUE THREAD

**Issue by totoro0924** [cataclysmbnteam/Cataclysm-BN#2104]
### Describe the bug

when turn on electric chainsaw lajatang with ups
it didn't work and message pop up "You pull the trigger, but nothing happens."

### Steps To Reproduce

1. spawn electric chainsaw lajatang, ups conversion mod, any ups
2. install ups conversion mod in lajatang
3. activate lajatang and choose turn on

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: b197454 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda]
]

**Comment by Proxiehunter** [comment]
This is a stupid question but in the spirit of "Have you tried turning it off and on again" I feel like I should ask, do you have a _powered_ UPS for it to draw on? You mention duplicating the error by spawning in a UPS but you don't mention it being _charged_ and my recollection is that if you spawn in things that carry charges they spawn in with few or no charges. That sounds like the message you get for it not having enough charges available so you may be trying to turn it on without enough available charge.  

A second question, do you have _multiple_ UPS devices in range, one or more with available charge and one or more with _no_  or _insufficient_ charge? The game could be getting confused and trying to power it with a dead or low UPS even if you have a live one I've seen similar errors in the past. 

This may also be another situation like the last one I chimed in on and it's already a known error that neither of us recalls.

**Comment by totoro0924** [comment]
I created a new character and tested it by spawn fully charged ups, advanced ups and bionic ups with over 10000k bionic power in empty place but it didn't work too
and if power in ups didn't enough to turn on lajatang, message comes out different

**Comment by scarf005** [comment]
also another stupid question, how do you install ups conversion mod? I can't attach them to anything
![Cataclysm: Bright Nights - 0 E-4566-g0abf7d007f8-dirty_01](https://user-images.githubusercontent.com/54838975/197324413-8701a8e3-014c-469f-8553-966df4c1647d.png)
![Cataclysm: Bright Nights - 0 E-4566-g0abf7d007f8-dirty_02](https://user-images.githubusercontent.com/54838975/197324418-2ce0f532-569a-479c-8b4b-33b8a6eb9c65.png)

**Comment by scarf005** [comment]
> do you have a powered UPS for it to draw on?
you get something like `you need at least 375 charges to turn this on`.

**Comment by RelMayers** [comment]
I can confirm this bug.
