### ISSUE TITLE
When rotating the map during mapgen, vehicles keep original orientation

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#2107]
### Describe the bug

Vehicles do not get rotated with the rest of the mapgen.

### Steps To Reproduce

1. Debug-generate modern04_1_1_north, but don't apply yet
2. Note vehicle orientation
3. Press rotate
4. Repeat 2 and 3 twice
5. Notice that all of the vehicles spawn rotated towards the south

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0f564c94827 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Magiclysm [magiclysm],
    Manual Bionic Installation [manualbionicinstall]
]

### Additional context

First reported in #1981

**Comment by chaosvolt** [comment]
Seen this for a while, unsure of the cause but can happen with overmap specials as well as city buildings:
![image](https://user-images.githubusercontent.com/11582235/197353457-064db5d4-9058-472a-b909-3999fb26a5e0.png)

**Comment by RelMayers** [comment]
I can confirm that issue within surface lab appearing as well as houses...
