### ISSUE TITLE
Vegetable Pizza Only Accepts Dehydrated Tainted Meat and Mycus

### ISSUE THREAD

**Issue by yay855** [cataclysmbnteam/Cataclysm-BN#2127]
### Describe the bug

A vegetable pizza should, reasonably, accept any number of vegetables, given that the supreme pizza does. But it doesn't; instead, the only vegetables it accepts are dehydrated tainted veggies and mycus.

### Steps To Reproduce

1. Open crafting menu
2. Search "vegetable pizza"
3. Vegetable pizza can only be made with vegetables described.

### Screenshots

![image](https://user-images.githubusercontent.com/3629845/198179211-880a27cd-917c-4856-a3ca-290f19ae4262.png)

### Versions and configuration

- OS: Windows 10
    - OS Version: 21H2
- Game Version: 58aded6 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Craftable CBMs [Craft_CBMs],
    <color_cyan>Lones Translocator Gates</color> [translocator_gates],
    <color_cyan>Lones Tweaks</color> [lonestweaks],
    <color_cyan>Lones Wearable UPS</color> [lones_UPS],
    Bio-Synth Robot expansion [gekkobots],
    C.R.I.T Expansion Mod [crt_expansion],
    Camp Cost Reduced [CampCostReduced],
    Elevated bridges [elevated_bridges],
    PKs Rebalancing [PK_REBALANCE],
    UnderrailMetro Mod [underrailmetro_mod],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    Advanced Gear [adv_gear],
    Advanced Technologies [advtech],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    anti-fungal gear [anti_fungal_gears],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Arsenal Breach [arsenal_breach],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Bens GF recipes* [Tolerate_This__],
    BioCo Content [bioco],
    Bionics Systems Recipes [bio_recipes],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Bootleg Walkers [Bootleg_Walkers],
    Cataclysm: Second Chance [expansion_tefnut],
    CBM Equipment [CBM_Arms],
    CIVILIAN POWER ARMOR [CIVILIANPOWAAA],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Craftable Gun Pack [craftgp],
    Culinary Days Ahead [culinary_days_ahead],
    DeadLeaves' Fictional Guns* [FIC_Weapons__],
    Dried Fruits [dried_fruits],
    Expanded Archery [ExArch],
    Flowerpot (uekibati) mod [Uekibati_mod],
    Gourmand's Graces [Gourmand'sGraces],
    Homemade Fungicide [homemade_fungicide],
    Icecoon's Arsenal* [ew_pack__],
    Large capacity storage CBMs [eps_cbm],
    Makeshift Items Mod* [makeshift__],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Metal materials [metal_elemental],
    MOD to grow tea leaves [More tea leaf],
    More Armors [More_Armors],
    More Makeshift Stuff [makeshift_stuff],
    MST Extra [MST_Extra],
    Mythological Replicas* [nw_pack__],
    Nimian Manufacture Guns [NM_wpns],
    Pipe Revolver Rifles [pipe_revolver_mod],
    Pixel's Various Fuckery [Pix's Shit],
    Project APEX [apex],
    Ricky's Future Armory [futurearmory],
    Rivtech Beam Swords [beamswordmod],
    Soy mod [Soy mod],
    Survivor crowbar [surv_crowbar],
    The Glory Of Cereal! [CerealMod],
    The Vermilion Mod [VermilionMod],
    Thermal Electric UPS [thermal_ups],
    Wild Living [WildLiving],
    XEAS [XEAS],
    Bug's life [Bug's life],
    DinoMod [DinoMod],
    Draco's Dog Mod [DracoDogMod],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Salvaged Robots* [Salvaged_Robots__],
    Youkai Enemies [Youkai_Disco],
    Alternative Map Key [alt_map_key],
    CDDA Variety Pack [ks_variety_pack],
    Even More Mutations [even_more_mutations],
    Hydroponics* [hydroponics__],
    Jury-Rigged Robots [jury_rigged_robots],
    Merchant Mod [Merchant],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Mug NPCs [mug_NPCs],
    Mutant NPCs* [mutant_npcs__],
    Mycus mod [mycus_tomodati],
    NPC Recruitment Options [recruitment_options],
    Sarcophagi Access [sarcophagi_access],
    THRESHOLD [add_mutant],
    Wandering Masters [wandering_masters],
    Whaleys Hair Mod [WHALEYHAIR1],
    Alternative Basement Layouts [basement_extension],
    Caches [P_Caches],
    Dorf Life [Dorf_Life],
    More Locations* [more_locations__],
    Morlock Village [morlock_village],
    Ships From Oa Additional Buildings [Ships],
    Water Towers [water_towers],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Folding Parts pack* [deoxymod__],
    Tankmod: Revived [Tankmod_Revived],
    Roadheader and other mining vehicles* [Heavy miners__],
    SzQmod [SzQmod],
    Amplified @'s Features [amplified_players_features],
    Hair and Skin Color Cosmetics, UDP and MXotto+ version p10 [mxoudpcosmetics],
    sees-player icon, retrodays [sees_player_retro],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Zet's Hair - PKs Rebalancing [zets_hair_ext_pk_rebalance],
    No Fungal Monsters [No_Fungi],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Better Holsters [better_holsters],
    Disable NPC Needs [no_npc_food],
    Faster Stamina Regen [stamina_regen_buff],
    Fuji's Military Profession Pack [fuji_mpp],
    Gunslinger Mod [MkMaxxi's Gunslinger Mod],
    Manual Bionic Installation [manualbionicinstall],
    Necropolis Actually Findable [necro_find],
    No Lifting Reqs [disable_lifting],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Mutation Changes Snofielf [Mutation_Changes1],
    Prevent Zombie Revivication [no_reviving_zombies],
    Shinigami [shinigamimod],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stackable Dried Items and Generic Fruits/Berries [drystack],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Stronger archery [bow_opness],
    Tame Bugs [tamebugs],
    Targeted Mutations [TaMu],
    ZSFIXED_C:DDA Extra Professions & Gears [ZSFIXED_cddaxp],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch]
]

**Comment by chaosvolt** [comment]
Uh, retest without third-party mods too.

**Comment by chaosvolt** [comment]
Okay yeah, it's definitely one of those mods: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/json/recipes/food/veggi.json#L1041
