### ISSUE TITLE
Missing item definition for fema_data.

### ISSUE THREAD

**Issue by HollyOwly** [cataclysmbnteam/Cataclysm-BN#2147]
### Describe the bug

Asking the refugee center for the location of hub 01leads to accepting a quest to deliver an  item to hub 01. After accepting the quest, an item without definition spawns, triggering the bug notification.

### Steps To Reproduce

1. Start new world.
2. Locate refugee center.
3. Teleport there.
4. Ask for hub 01 location to the merchant with the option "Heard of any settlements nearby?"

### Screenshots

![Screenshot_20221031-113629](https://user-images.githubusercontent.com/117097732/199041657-b79eb8bc-d419-4f29-bae3-76ae153a923d.png)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: motorola; Model: moto g(9) play; Release: 11; Incremental: ad9c24; 
- Game Version: a6264ef [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Thog's Stuff [Thogs_Stuff],
    Cataclysm++ [Cata++]
]

**Comment by Krwak** [comment]
Kudos for reporting this but it's been already reported in #1452.

**Comment by HollyOwly** [comment]
Alright, closing it it then.
