### ISSUE TITLE
Baseball field is using road terrain for diamonds and has a roof. 

### ISSUE THREAD

**Issue by thelonestander** [cataclysmbnteam/Cataclysm-BN#2151]
### Describe the bug

Baseball field is using road terrain for diamonds and has a roof. 

It should be just a dirt path, and the diamonds having its own terrain. Also should not be roofed. See pics for details. 

### Steps To Reproduce

Spawn a baseball field

Notice it has a roof, and road tiles. 

### Screenshots

![Screenshot (1293)](https://user-images.githubusercontent.com/82045140/199251387-dfa06507-dd4d-4f2f-8c86-77693fb1031b.png)
![Screenshot (1294)](https://user-images.githubusercontent.com/82045140/199251399-10672e34-8a96-46c4-9eec-718f7c2da14c.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 17c7df7 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    <color_cyan>Lones CBM slot balance</color> [lones_CBM_slot balance],
    <color_cyan>Lones Flesh Raptor</color> [flesh raptors],
    <color_cyan>Lones Translocator Gates</color> [translocator_gates],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    <color_cyan>Lones Tweaks</color> [lonestweaks],
    <color_cyan>Lones Wearable UPS</color> [lones_UPS],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    PKs Rebalancing [PK_REBALANCE],
    <color_cyan>Lones Soda mod</color> [coke_flavors],
    Advanced Gear [adv_gear],
    Advanced Technologies [advtech],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Craftable Gun Pack [craftgp],
    Expanded Archery [ExArch],
    More Armors [More_Armors],
    Moutain dew [Mountain_Dew],
    MST Extra [MST_Extra],
    Pneumatic fun [pneumo_fun],
    Pressure Weapons [pressure_weapon],
    Ricky's Future Armory [futurearmory],
    Survivor's Lost item [Survivors_Lost_item],
    Survivor crowbar [surv_crowbar],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Thog's Stuff [Thogs_Stuff],
    Caches [P_Caches],
    Dorf Life [Dorf_Life],
    Fewer Farms [Fewer_Farms],
    Ships From Oa Additional Buildings [Ships],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived],
    MSX Fake Snow [UDP_BN_FAKE_SNOW],
    PK - No Doom Monsters [PK_No_Doom],
    No Fungal Monsters [No_Fungi],
    Bionic Slots [cbm_slots],
    Faster Stamina Regen [stamina_regen_buff],
    Fuji's Military Profession Pack [fuji_mpp],
    Manual Bionic Installation [manualbionicinstall],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Prevent Zombie Revivication [no_reviving_zombies],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by scarf005** [comment]
fixed by #2466, related: #2447
