### ISSUE TITLE
Fancy and super fancy items don't give the stylish bonus

### ISSUE THREAD

**Issue by leoCottret** [cataclysmbnteam/Cataclysm-BN#2159]
### Describe the bug

Fancy and super fancy items don't give the stylish bonus

### Steps To Reproduce

- Equip a super fancy armor
- Equip a ton of fancy jewelry
Where's the stylish bonus?

### Versions and configuration

Windows 10, BN upload branch

**Comment by olanti-p** [comment]
Can't reproduce.
Linux, game version 3d29308de6ae620806fd3b11e4146d89ba06a2aa
![image](https://user-images.githubusercontent.com/60584843/209476177-d9af407b-7652-4371-bdd5-60e8016a5b6b.png)
![image](https://user-images.githubusercontent.com/60584843/209476181-412fecd8-e0e0-441a-8db6-f48d93482d47.png)

**Comment by scarf005** [comment]
please reopen if the issue is still reproducible in experimental.
