### ISSUE TITLE
Inventory-management access violation error

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#218]
# Describe the bug

Hitting `/` to bring up AIM crashes the game.  Suspected to be related to this, debugging in an item too large for your inventory also crashes the game. Visual Studio reported it as an access violation, no crashlog file was produced and debug file does not seem to indicate any relevant error messages (unknown if possibly due to testing in version compiled from master instead of a recent build).

# Steps To Reproduce

1. Start a game.
2. Hit `/` or whatever one's AIM menu may be bound to.
3. Start a game again post-crash.
4. Debug in a steel frame or other item with more volume than you can hold.
5. Wait one turn.

# Expected behavior

Inventory management menu pops up as normal, overly-large items debugged into inventory fall to the floor one turn later.

# Screenshots

![image](https://user-images.githubusercontent.com/11582235/99127582-51280500-25ce-11eb-9444-fdd57bb7ea29.png)

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: dd73e8e5c4-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

# Additional context

[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5539591/debug.log)

Discovered during testing of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/217

**Comment by olanti-p** [comment]
Can't reproduce on build 891: I dropped all items, then debug-spawned pet carrier and opened AIM. Everything looks fine.
![Screenshot_20201114_112345](https://user-images.githubusercontent.com/60584843/99143079-e4634800-266b-11eb-8531-3f261a36e5f7.png)
Maybe I'm doing it wrong (e.g. trying it on linux, but that shouldn't matter). Could you upload the save / clarify the steps?

**Comment by Coolthulhu** [comment]
Never seen the bug happen.
Will need more data:
* Stacktrace if possible
* Z-levels on/off
* Info on local variables of the crashing function call. Ideally also a bunch of ones below, to see where does the "weirdness" start.

**Comment by chaosvolt** [comment]
That's odd. I'll grab the latest build and test it there too. Then I'll update my upload branch, compile it, and see if it still does it there. Having it highlight `optional_vpart_position_map::veh_at` is also unusual.

Z-levels are on as is default, not sure how to get more info on the fucntion that's causing the crash. Save is below, at least:
[save.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5541154/save.zip)

**Comment by chaosvolt** [comment]
Alright, tested 891 (Windows 64-bit version) and couldn't reproduce it, then dumped that save into it and still couldn't. Then I updated my upload branch, compiled it, and tested the save I still had in there. Immediate access violation.

```
Exception thrown at 0x00007FF7C05AE25C in Cataclysm-vcpkg-static-Release-x64.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```

Maybe it's something specific to Visual Studio? This time the function being reported was `advanced_inv_area::init` and this was testing trying to bring up AIM. So it seems it's `optional_vpart_position_map::veh_at` when handling debug-spawning excessively-large items in your inventory, `advanced_inv_area::init` when hitting `/`, possibly two separate bugs but not certain.

If it's not affecting actual builds then that's good at least.

**Comment by olanti-p** [comment]
I've compiled 891 with 112067e29ed81b5099b69962d92d7c8ee3eaed2f on top of it in Visual Studio 2019 (Release, x64), loaded that save and walked around in the world, pressing `/`. AIM works as expected.

Some time ago, I've encountered a problem with VS: after a checkout (or after editing one of the files in another editor) it wouldn't compile the project properly, and the game would crash out of the blue in seemingly random spots. But after running `Clean Solution` and compiling from scratch, the game works fine. Could it be the same problem?

**Comment by chaosvolt** [comment]
I'll give that a try in a bit, then. Could be the cause, as I've only recently learned the basics of compiling with VS.

**Comment by chaosvolt** [comment]
Alright, finally had the chance to give this a test. Updated the repo from upstream, cleaned solution, compiled, and tested both the actions that previously caused trouble. No crashing this time. Seems that was the cause, thank you for that.
