### ISSUE TITLE
Zooming in causes ugly lines and blurriness

### ISSUE THREAD

**Issue by BlueManedHawk** [cataclysmbnteam/Cataclysm-BN#2185]
### Describe the bug

Zooming in leads to ugly lines at tile borders and blurry pixelart.

### Steps To Reproduce

Zoom in with `[z]` during regular gameplay.

### Screenshots

![Blue-Maned_Hawk _2022-11-13_02-55-59_+0000](https://user-images.githubusercontent.com/50188776/201503532-3458e5ac-8b10-40b8-b223-44abd97ff317.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: GalliumOS 3.1; Release: 18.04; Codename: bionic; 
- Game Version: c2ebb51 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    Generic Guns [generic_guns],
    DinoMod [DinoMod],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Alternative Map Key [alt_map_key],
    Bright Nights (wrapper) [dda],
    Visible car roof [Visible_car_roof],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player icon, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by Krwak** [comment]
Isn't this caused by high DPI settings in your OS?

**Comment by Zireael07** [comment]
If not that, then it's likely what is known as tile bleeding issue. Over at DDA itself, some people found changing the renderer setting helps a bit.
