### ISSUE TITLE
Wrong body part names result in useless debugmsg

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#222]
If a modder supplies body part name using the DDA's format - ie. lowercase - the game will silently accept it and then later bug out like this:
```
DEBUG    : Error: bitset::set: __position (which is 12) >= _Nb (which is 12)

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 905
```

This is because one of the body part functions returns `NUM_BP`, which is `12`, when it can't find a body part of a given name.

**Comment by Fris0uman** [comment]
Bodyparts are hardcoded tough, so trying to mod a new one is pointless.

**Comment by Coolthulhu** [comment]
Doesn't seem to reproduce anymore. Nowadays it prints "invalid legacy body part id" before that useless message.
Changes to debugmsg during load?
