### ISSUE TITLE
Wielded firearm not automatically reloaded when pressing R

### ISSUE THREAD

**Issue by cuckmaster** [cataclysmbnteam/Cataclysm-BN#2226]
### Describe the bug

When wielding a firearm and pressing R to reload, you are presented with the "reload which item" menu instead of automatically reloading the currently wielded firearm.

### Steps To Reproduce

1. Have a character wielding a gun, with appropriate ammo/magazine in the inventory.
2. Press R to reload.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: ef5a513 [64-bit]
- Graphics Vers

**Comment by olanti-p** [comment]
That's intended behavior.

`r` (not `R` which is `Shift+r` which is Read) is generic reload, if you want it to automatically reload wielded item, you'll have to use the `Reload Wielded Item` hotkey (unbound by default, can be set through `?` menu). There's also `Reload Weapons` hotkey (also unbound by default) which reloads all weapons in inventory, and also attempts to load magazine with ammo _before_ loading it into the gun.
