### ISSUE TITLE
Put only official releases under the "releases" section on github

### ISSUE THREAD

**Issue by wiki-me** [cataclysmbnteam/Cataclysm-BN#2231]
### Is your feature request related to a problem? Please describe.

It's hard to find the official releases, due to the many "experimental build" releases.

Some people (like myself) have a pretty low frustration tolerance for games, and would like to use something stable.

### Describe the solution you'd like

Put the experimental builds under only the "tags" section.

Or maybe in a different repository?

**Comment by Zireael07** [comment]
I believe releases is automated and everything that's tagged goes into it?

**Comment by wiki-me** [comment]
Another option is it seems DDA marks experimental builds as "Pre-release", so on the [github page](https://github.com/CleverRaven/Cataclysm-DDA) under releases it shows the official release.
