### ISSUE TITLE
Can't load mods/get to the character creation screen

### ISSUE THREAD

**Issue by Saloth** [cataclysmbnteam/Cataclysm-BN#2259]
### Describe the bug

 DEBUG    : Error: Json error: C:/Users/Jack Bauer/Desktop/bn/userdata/mods/nocts_cata_mod_BN/Surv_help/c_materials.json:13:23: missing mandatory member "bullet_resist"

    "cut_resist": 38,
    "acid_resist": 5,
    "fire_resist": 10,
                      ^
    "elec_resist": 5,
    "chip_resist": 20,
    "repaired_with": "alloy_sheet",

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\main_menu.cpp
 LINE     : 871
 VERSION  : BN 3d29308

### Steps To Reproduce

It happens when I create the world, add a few mods (now most of them don't work) and then go to character creation. I use the latest experimental version from the Catapult launcher.

### Versions and configuration

Win7 x64
3d29308
Mods loaded:
Bright Nights
Disable npc  needs
Simplified nutrition
Bright Nights wrapper
Elevated bridges
Cataclysm ++

**Comment by chaosvolt** [comment]
You're using an outdated version of Cataclysm++ mod, make sure you're grabbing the proper master version of it, NOT any of the releases. When in doubt, update it manually instead of using a launcher: https://github.com/Noctifer-de-Mortem/nocts_cata_mod

**Comment by Saloth** [comment]
Thx for reaching out. But here's another thing. I just added Arcana And
Magic Items mod and here's how it looks like now. So that'd mean most mods
from the Catapult repository are outdated?

 DEBUG    : Error: Json error: C:/Users/Jack
Bauer/Desktop/bn/userdata/mods/Arcana_BN/materials.json:10:23: missing
mandatory member "bullet_resist"

    "cut_resist": 20,
    "acid_resist": 99,
    "fire_resist": 99,
                      ^
    "elec_resist": 99,
    "chip_resist": 99,
    "dmg_adj": [ "lightly damaged", "damaged", "very damaged", "thoroughly
damaged" ],


 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\main_menu.cpp
 LINE     : 871
 VERSION  : BN 3d29308

But I just noticed, the file path doesn't exist anymore and i have both BN
and Catapult on C drive and even though I used a new launcher and installed
a clean game it still for some reason looks for files in the old location.
How can I change that and point the right directory to the mod repository
and the game itself?

**Comment by olanti-p** [comment]
We're not developers of Catapult, questions regarding the launcher should be addressed to the developer of the launcher over at https://github.com/qrrk/Catapult

That said, from what I remember the launcher does not automatically update mods, you have to open the mods tab, deleted them all, then redownload and reinstall. For instance, Arcana mentioned in the error has been removed from Kenan's compilation https://github.com/Kenan2000/BrightNights-Structured-Kenan-Modpack (that's where launcher downloads from) and now lives only in CV's repo https://github.com/chaosvolt/cdda-arcana-mod , so has to be installed manually.

> But I just noticed, the file path doesn't exist anymore and i have both BN
and Catapult on C drive and even though I used a new launcher and installed
a clean game it still for some reason looks for files in the old location.

If you mean `D:\a\Cataclysm-BN\Cataclysm-BN\src\main_menu.cpp` mentioned in the error, that path shows where in the source code the error comes from, it exists on developers' machines only.

The contents of the error refer to `C:/Users/Jack
Bauer/Desktop/bn/userdata/mods/Arcana_BN/materials.json`, that's the file it trips over when it tries to load the mods.

**Comment by Saloth** [comment]
Ok thx much for the reply.
