### ISSUE TITLE
Can't start world with mods on Android

### ISSUE THREAD

**Issue by Yrrag** [cataclysmbnteam/Cataclysm-BN#2260]
### Describe the bug

I have a problem, I play on android and worlds with mods that I create do not start and I don’t use third-party mods, I use only those that are directly built into the game and only worlds with completely missing mods like aftershok or K.R.I.T and so on and if this will help you, I copied the configs (I don’t speak English, so I write through a translator, because of which the text may seem broken)

### Steps To Reproduce

1create a world with mods 2run it 

### Versions and configuration

-----------------------------------------
21:29:32.495 : Starting log.
21:29:32.495 INFO : Cataclysm BN version 3d29308
21:29:32.500 INFO : C locale on startup: 'C.UTF-8'
21:29:32.500 INFO : C++ locale on startup: ''
21:29:32.512 WARNING : Failed to detect system UI language.
21:29:32.512 INFO : SDL version used during compile is 2.0.12
21:29:32.512 INFO : SDL version used during linking and in runtime is 2.0.12
21:29:32.547 WARNING : opendir [/storage/emulated/0/Android/data/com.cataclysmbnteam.cataclysmbn.experimental/files/sound/] failed with "No such file or directory".
21:29:32.592 INFO : Active audio driver: openslES
21:29:32.669 INFO : Opened mixer with specs: 44100 Hz, 2 channel(s), format 0x8010
21:29:33.552 INFO : Language set to 'en'
21:29:33.553 INFO : C locale set to 'C.UTF-8'
21:29:33.553 INFO : C++ locale set to ''
21:29:36.712 WARNING : opendir [/storage/emulated/0/Android/data/com.cataclysmbnteam.cataclysmbn.experimental/files/mods/] failed with "No such file or directory".
21:29:39.954 INFO : Language set to 'ru_RU'
21:29:39.958 INFO : C locale set to 'C.UTF-8'
21:29:39.958 INFO : C++ locale set to 'en_US.UTF-8'
21:31:33.730 INFO : Loaded tileset: UNDEAD_PEOPLE_BASE

android version 11

**Comment by Yrrag** [comment]
I forgot to tell the model of my smartphone galaxy A10

**Comment by olanti-p** [comment]
Можете уточнить, что происходит?
Вы пытаетесь начать игру в новом мире с модами - и игра закрывается? Или выдаёт ошибку и возвращает в главное меню? Работает ли, если начинать игру без модов?
В логе, к сожалению, подробностей нет, а на моём Андроиде 11 с кастомной прошивкой на той же версии игры всё работает (получается создать мод в Афтершоком и КРИТ и погулять в нём).

**Comment by Yrrag** [comment]
нет я создавал новый мир с модами и когда я пытался создать персонажа тот просто вылетал без меню ошибки not on the main menu of the game, but on the phone screen, that is, completely

**Comment by Yrrag** [comment]
> 

1no, I am creating a world with mods and trying to create a new character in it, but the game just crashes at the moment of checking without an error menu on the smartphone screen, that is, completely 2Yes, it works3 in the log there is a message that the file or directory was not found, which is why the game ends most likely the problem is this

**Comment by olanti-p** [comment]
> in the log there is a message that the file or directory was not found

It's not an error, it's a warning, and it's about a folder for third-party mods, which you don't have installed anyway (hence the lack of folder). 

> the game just crashes at the moment of checking without an error menu on the smartphone screen

Is there a `crash.log` in same folder as `debug.log` you've attached? If so, could you post it here?

If there's no crash log, it might be some tricky crash (e.g. system ran out of memory). Disabling tileset in options (or switching to some lightweight one like RetroDays) may help in that case, or reinstalling the game with software rendering disabled.

Since creating world without mods works fine, disabling mods one-by-one should narrow down which one causes the issue.

**Comment by Yrrag** [comment]
> > in the log there is a message that the file or directory was not found
> 
> It's not an error, it's a warning, and it's about a folder for third-party mods, which you don't have installed anyway (hence the lack of folder).
> 
> > the game just crashes at the moment of checking without an error menu on the smartphone screen
> 
> Is there a `crash.log` in same folder as `debug.log` you've attached? If so, could you post it here?
> 
> If there's no crash log, it might be some tricky crash (e.g. system ran out of memory). Disabling tileset in options (or switching to some lightweight one like RetroDays) may help in that case, or reinstalling the game with software rendering disabled.
> 
> Since creating world without mods works fine, disabling mods one-by-one should narrow down which one causes the issue.


I'll try to do this, if it helps I'll write
