### ISSUE TITLE
Elevator shaft erases items after use

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#2269]
### Describe the bug

After using elevator in the elevator shaft at the small lab, all items located in the area disappear.
IIRC this is fairly new behavior.

### Steps To Reproduce

1. Go to a small lab.
2. Put some items in the shaft.
3. Use elevator controls
4. Use them again to return to lab
5. Observe

### Screenshots

![image](https://user-images.githubusercontent.com/72284934/210196552-6ec2ba54-bebc-4917-a4fb-e59d2464ec7d.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3d29308 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Bright Nights (wrapper) [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Lighter vehicle parts [lighter_vehicle_parts],
    no ups mp3 [no_UPS_mp3],
    Prevent Zombie Revivication [no_reviving_zombies]
]

### Additional context

[Steubenville.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/10330083/Steubenville.zip)

**Comment by scarf005** [comment]
shouyld be fixed by #3151 and #3181
