### ISSUE TITLE
Can't retaliate turret fire in helicopter without 3d vision ON

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#2275]
### Describe the bug

Turrets can shoot on helicopters that are above them even with 3d vision off but player can't retaliate back. 
Even tried using auto targeting turret but no dice, simple can't shoot on enemies on different z-level.
I believe that turrets shouldn't be able to do that unless you really want to create a no-fly zone above military installations and similar.

### Steps To Reproduce

1. Have 3D vision OFF
2.  Spawn heli
3. Spawn turret
4. Fly with heli above the turret
5. Install a mounted .50 and turret control unit for good measure.

### Screenshots

https://discord.com/channels/830879262763909202/830916329053487124/1059959245241581638
![image](https://user-images.githubusercontent.com/72284934/210452395-beefc160-a648-4b80-9c25-3d25726cd91b.png)
![image](https://user-images.githubusercontent.com/72284934/210452435-22bc03c1-7e9e-4abc-a0f7-0b71cf72c6ef.png)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3d29308 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Bright Nights (wrapper) [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Lighter vehicle parts [lighter_vehicle_parts],
    no ups mp3 [no_UPS_mp3],
    Prevent Zombie Revivication [no_reviving_zombies]
]

**Comment by olanti-p** [comment]
Should be fixed by #2285
