### ISSUE TITLE
Add maximum float weight on vehicle information panel when boat hulls are connected

### ISSUE THREAD

**Issue by Kaylakaze** [cataclysmbnteam/Cataclysm-BN#2276]
### Is your feature request related to a problem? Please describe.

It's almost impossible to tell how much cargo a boat can carry. It's super annoying to climb on your boat to drive it only for it to sink out from under you.

### Describe the solution you'd like

Among the other vehicle information listed like Draft and Clearance, add a maximum float weight value. A "remaining floatable weight" would also be nice, but some people may consider that too much hand-holding.

**Comment by Kaylakaze** [comment]
After making this issue/request, I made my first helicopter and noticed it has a "Maximum Lift" value. This is an example of the exact sort of thing I'd like to see for floatation.

**Comment by scarf005** [comment]
hello @Kaylakaze , you may be interested in #1631 adds display support for vehicle maximum lift. same could be done for maximum float weight.
