### ISSUE TITLE
Blank screen (but map fills in etc) on reaching -10 in a central lab

### ISSUE THREAD

**Issue by AdamTheLang** [cataclysmbnteam/Cataclysm-BN#2301]
### Describe the bug

I have a game where I started in a lab with a subway connection to a huge sprawling central lab. (Maybe something special from BN? Dunno. But damn is it big.) A large part of the central lab is only three levels deep, but there's a small subsection that is very deep.

I just advanced for the first time to -10, and ... I can't see. The screen is simply black. If I hit 'x' it highlights a black square, and if I hit 'e' then, I can examine myself. If I hit 'x' and then hit a directional arrow I can examine another square, and it shows me the terrain etc. The minimap (lower right hand corner) populates, as does the 'local area' map (to the right of 'date', 'time', 'light', etc, although all it shows is a single 'L' since I can't see beyond the walls of the current area.

This isn't like it's dark, as I have the night vision mutation. This isn't even like I have my optical dampers turned on, because that at least populates a single square, the one the player is in, when you move into an area you haven't seen. It's more like the visible area is simply offscreen, but it isn't, since if I hit 'x' it locates me right in the middle of the screen.

Since nobody else has noticed this by now, I'm guessing that it's not 100% repeatable. I'll bundle up my safe file for you folks.

I have made a couple of minor changes to the json: making the 'ji' a valid silaat weapon, and making it fit in a damn spear strap. I am pretty sure neither of those things would have any significant effect, let alone this one.

### Steps To Reproduce

I don't think it's really reproducible. But for the record, all I did was:

1) Go down a flight of stairs from -9 to -10 in a central lab.

That's not a whole of steps, I realize.

### Screenshots

Character on -9 stairs down:
<img width="2053" alt="image" src="https://user-images.githubusercontent.com/29169689/213884550-8f6edffd-ec05-4af0-91c7-79128b7ae8b3.png">
Screen once I went down to -10:
<img width="2052" alt="image" src="https://user-images.githubusercontent.com/29169689/213884554-ec7d3b61-b580-464f-87ad-9f4cb344330d.png">
After I hit 'x' (shows my character in the right hand pane, and light 'bright'):
<img width="2049" alt="image" src="https://user-images.githubusercontent.com/29169689/213884575-8cbc268f-d7a3-4baf-9104-4e82c2ecd88f.png">
After I then hit the up arrow, moving the 'examine' square one north:
<img width="2050" alt="image" src="https://user-images.githubusercontent.com/29169689/213884602-074998c5-1956-46d5-9acb-d152aa320bc5.png">

### Versions and configuration

- OS: macOS 13.1 (22C65)
- Game version: Cataclysm BN 4f6e937
- Graphics version: Tiles
- Game language: English
- Mods loaded:
- - Bright Nights
- - Disable NPC Needs
- - Simplified Nutrition
- - Elevated Bridges
- - Aftershock
- - C.R.I.T.
- - Alternative Map Key
- - Sees player icon retrodays
- - No Fungal Monsters
- - Fuji's Military Profession Pack
- - SpeedyDex
- - Stats Through Kills

### Additional context

[Anaheim.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/10472913/Anaheim.zip)

**Comment by olanti-p** [comment]
Thanks for the report!
This has been fixed for stable 0.2 available at
https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-0.2
