### ISSUE TITLE
NPCs cannot be damaged on any location other than arms when using a melee weapons ranged attack

### ISSUE THREAD

**Issue by AshleyKendris** [cataclysmbnteam/Cataclysm-BN#2328]
### Describe the bug

When attacking an NPC with a melee weapon that can be used at range, ie. spear, an NPC will eventually die.

But,

NPC only takes damage on arms until the heat death of the universe.

### Steps To Reproduce

Equip melee weapon with a ranged attack (spear, whip...)
Find an NPC
Use `f` to use melee weapon at range

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 04775f5 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    No name () [],
    Arcana and Magic Items [Arcana],
    No name () [],
    Cataclysm++ [Cata++],
    Magiclysm [magiclysm],
    Mutant NPCs [mutant_npcs],
    Psychiclysm [psychiclysm],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Bens GF recipes [Tolerate_This],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Craftable Gun Pack [craftgp],
    Culinary Days Ahead [culinary_days_ahead],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Dried Fruits [dried_fruits],
    Expanded Archery [ExArch],
    Gourmand's Graces [Gourmand'sGraces],
    Make a Lot of Items [Make_a_Lot_of_Items_Mod],
    Makeshift Items Mod [makeshift],
    Modern Weapon Pack Expanded [modern_weapon],
    More Makeshift Stuff [makeshift_stuff],
    More Survivor Notes [more_survive_notes],
    Pixel's Various Fuckery [Pix's Shit],
    Survivor crowbar [surv_crowbar],
    The Vermilion Mod [VermilionMod],
    Wild Living [WildLiving],
    Bug's life [Bug's life],
    Crazy Labs [crazy_labs],
    DinoMod [DinoMod],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Mythical Martial Arts [MMA],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Alternative Map Key [alt_map_key],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    CDDA Variety Pack [ks_variety_pack],
    Even More Mutations [even_more_mutations],
    Hydroponics [hydroponics],
    More Survivor Stuff [more_survivor_stuff],
    Wandering Masters [wandering_masters],
    Alternative Basement Layouts [basement_extension],
    Beta National Guard Camp [national_guard_camp],
    Caches [P_Caches],
    More Locations [more_locations],
    Morlock Village [morlock_village],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Ships From Oa Additional Buildings [Ships],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Shrub it off [shrub_mod],
    Magiclysm Revamp and Additions [magicrevamp],
    Necromancy [necromancy],
    Amplified @'s Features [amplified_players_features],
    MSX Fake Snow [UDP_BN_FAKE_SNOW],
    Fuji's Military Profession Pack [fuji_mpp],
    Mutation Changes Snofielf [Mutation_Changes1],
    No Lifting Reqs [disable_lifting],
    Shinigami [shinigamimod],
    Stats Through Kills [stats_through_kills],
    Tame Bugs [tamebugs],
    Targeted Mutations [TaMu]
]

### Additional context

Additionally, using the autoattack feature will not damage NPCs on any location other than arms. Default key `tab`.

**Comment by KheirFerrum** [comment]
Should be fixed by #2535

**Comment by scarf005** [comment]
closing as completed, please reopen the issue if #2535 does not fix it.
