### ISSUE TITLE
[m]ap invisible in fresh curses build

### ISSUE THREAD

**Issue by OrenAudeles** [cataclysmbnteam/Cataclysm-BN#2333]
### Describe the bug

In a fresh download, as of the [latest experimental release](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2023-02-06-2215), on entering a new game opening the map does not show the expected immediate area. Instead it shows the sidebar only. Does not show the cursor or any of the overmap characters.

### Steps To Reproduce

1. Download experimental release. Known to occur on [this experimental release](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2023-02-06-2215)
2. Start new game
3. Open [m]ap
4. ???
5. Despair!

### Screenshots

![image_problem](https://user-images.githubusercontent.com/8597997/217718934-182834af-8b4f-4fd8-b34e-e16a3a4bb2ce.png)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.5 LTS; Release: 20.04; Codename: focal; 
- Game Version: cda4bc7 [64-bit]
- Graphics Version: Curses
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges]
]

**Comment by OrenAudeles** [comment]
The cause of this issue is a dependency on a TILES build only option `USE_TILES_OVERMAP` which defaults to `"True"` as of #2256 
If the option is not present it defaults to True and does not care that we can't draw tiles in a Curses build.

Simple manual fix is to add this line as the last option in `./config/options.json`
`{ "info": "If true, replaces some TTF-rendered text with tiles for overmap display.", "default": "Default: True", "name": "USE_TILES_OVERMAP", "value": "false" }`
if `"USE_TILES_OVERMAP"` option is not present. And if it is we can manually change that value from `"true"` to `"false"`

Once this is done it works as expected:
![image_solution](https://user-images.githubusercontent.com/8597997/217720524-09e2034d-4257-486a-89a7-616f45e7c292.png)

**Comment by Wad67** [comment]
Here is the game report as requested 

`- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.1 LTS; Release: 22.04; Codename: jammy; 
- Game Version: cda4bc75df6 [64-bit]
- Graphics Version: Curses
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    No Lifting Reqs [disable_lifting],
    No Filthy Clothing [no_filthy_clothing],
    Prevent Zombie Revivication [no_reviving_zombies]
]`
