### ISSUE TITLE
Kilns cannot be lit with "Finger Lighter" CBM

### ISSUE THREAD

**Issue by Goredell** [cataclysmbnteam/Cataclysm-BN#2340]
### Describe the bug

As the title suggests, kilns cannot be lit with "lighter" CBM, even if u have enough bionic power.

### Steps To Reproduce

1. Create and fill any kiln
2. Install "Finger Lighter" CBM to ur character
3. Try litting the kiln  - You cannot
4. Take lighter/matches - you can

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: cda4bc7 [64-bit]
- Graphics Vers

**Comment by weakman54** [comment]
Can confirm this on my setup, Windows 10, Stable 0.2

Same bug also exists for Constructed Charcoal smoker

**Comment by chaosvolt** [comment]
My guess is the code for the charcoal kiln, smoker, etc examine actions aren't taking `fake_item` entries from CBMs into account.

**Comment by yay855** [comment]
Can confirm this also applies to the smoker.
