### ISSUE TITLE
zombie_gasbag continue spawning with mod "no explosive zombies"

### ISSUE THREAD

**Issue by BROtania** [cataclysmbnteam/Cataclysm-BN#2391]
### Describe the bug

In mod "no explosive zombies" missing "  "mon_zombie_gasbag", "mon_zombie_gasbag_fungus",  " lines, causing zombies to keep spawning. This is a very old problem. especially annoying because they are the most imbalanced zombies in the game

### Steps To Reproduce

This zombie continue spawning with mod "no explosive zombies"
Eazy fixing, adding  "mon_zombie_gasbag", "mon_zombie_gasbag_fungus",  lines in mod

### Versions and configuration

Any version

**Comment by Coolthulhu** [comment]
I think the intent of no-explosive mod was removal of zombies capable of doing "damage explosions", not "bursting zombies" in general.

**Comment by scarf005** [comment]
i kinda understand why brotania thought this mod removed self-exploding zombies, it's matter of throwing explody thing vs. itself being explody. @Coolthulhu, if you won't mind i think it'd be better to add them to blacklist.

**Comment by chaosvolt** [comment]
I could've sworn zombie grenadiers were already dummied out in favor of dispatch robots, a change BN inherited from DDA. If so, then no exploding zombies presumably should be either obsoleted (if not already) or reworked to serve the purpose expected by players. In which case bloated zombies probably would be valid to blacklist in it since they can inflict poison damage.

**Comment by scarf005** [comment]
i think a decision needs to be made. it's either

## 1. remove only bloated zombies

```json
  {
    "type": "MONSTER_BLACKLIST",
    "monsters": [
      "mon_zombie_grenadier",
      "mon_zombie_grenadier_elite",
      "mon_zombie_flamer",
      "mon_gas_zombie",
      "mon_zombie_gasbag",
      "mon_zombie_gasbag_fungus"
    ]
  }
```

## 2. remove all zeds with `"emit_fields"`
![image](https://user-images.githubusercontent.com/54838975/227078983-7e960049-1271-44fb-b850-9745703cd613.png)
