### ISSUE TITLE
All weapons dropped by zombie cops have damage regardless of corresponding monsterdrops JSON

### ISSUE THREAD

**Issue by metalheimer** [cataclysmbnteam/Cataclysm-BN#2400]
### Describe the bug

When a zombie cop drops a weapon such as the PR-24 baton, it will ALWAYS have one degree of damage. If I'm reading the corresponding monster drop JSON right...

      { "group": "cop_weapons", "prob": 50, "damage": [ 0, 1 ], "dirt": [ 1500, 7050 ] },

\data\json\monsterdrops\zombie_cop.json

...There should be 50% chance of damage, and if damage, it should be one degree. It's just that the game doesn't seem to be OK with the zero there, so it applies the damage every time.

This of course has the wider implication that the zero in monsterdrops isn't respected at all, at least not for damage, which probably means many items drop in more damaged condition than intended.

### Steps To Reproduce

1. Use debug to spawn a large group (100 minimum) of zombie cops. (zombie_cop)
2. Use debug to immediately kill the said group with the "Kill All" or "Kill In Area" command.
3. Observe the dropped items with the view command.
4. You should see all the weapons have sustained one damage degree, and not one weapon in undamaged condition.

### Versions and configuration

0.2 stable, x64, Win, tiles

**Comment by olanti-p** [comment]
Okay, I did some code digging and this seems to be a legacy thing.

Long time ago, internally damage was measured as a floating-point value. The item could have values like `2.3` or `0.35`, even if in JSON you could only define integer values like 0, 1, 2, 3 or 4, and in UI it would be rounded to integer when showing the item's hp bars.

It caused some issues, with saving and loading so in https://github.com/CleverRaven/Cataclysm-DDA/pull/25004 the underlying code was reworked to have damage as integers, but multiplied by 1000, so these `2.3` and `0.3` turned to `2300` and `350`, and each hp bar represents 1000.

The damage defined in itemgroup JSONs was made to scale as well, so this `[ 0, 1 ]` we see here turns into `[ 0, 1000 ]` under the hood, so there is only a 0.1% chance to spawn a pristine item, not 50% as may be expected. On the flip side, the chance to spawn an item with "1" damage is also 0.1%, the rest 99.8% fall between 0 and 1.

If we were to change the code to first roll the given damage value, _then_ scale it by 1000, it would work as the issue expects. So, `[ 0, 1 ]` would result in either `0` damage or `1000` damage, and not something in between.
