### ISSUE TITLE
Unpacking multiple bundles of rags in one go causes a crash.

### ISSUE THREAD

**Issue by metalheimer** [cataclysmbnteam/Cataclysm-BN#2401]
### Describe the bug

(should be self-explanatory)

### Steps To Reproduce

1. Craft or spawn 2 or more items called "bundle of rags".
2. Drop them all on the ground.
3. Issue the uncraft command via the butcher command ["B"] and choose "uncraft all"
4. The game freezes and crashes.

### Versions and configuration

0.2 stable, x64, Win, tiles

**Comment by chaosvolt** [comment]
This will be fixed by: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2344

**Comment by chaosvolt** [comment]
Eh, not completed yet since that hasn't been merged, though. ^^"
