### ISSUE TITLE
Crafting menu full text search (the d: switch) is broken

### ISSUE THREAD

**Issue by metalheimer** [cataclysmbnteam/Cataclysm-BN#2455]
### Describe the bug

It produces highly inconsistent results. Unable to distinguish any kind of pattern in it. It can find SOME of the items, but not all, not even close. For example, you used to be able to find all spears capable of reach attacks by entering "d: reach attack" but not anymore. I noticed this already back in 0.2 stable but who knows how old this bug is. You could even try just "d: reach", and it'll find results, but again not all.

### Steps To Reproduce

1. Pick a random recipe in the crafting menu. Pick a semi-rare word that appears in it.
2. Use the d: search in the crafting menu for that word.
3. Repeat a few times with other words from other recipes. You should see the erratic behavior, the absence of the recipes you chose.

### Versions and configuration

win 64-bit, tiles, since 0.2 stable or earlier

**Comment by scarf005** [comment]
Let's continue the discussion in #2903 as it's about same issue and provides some screenshots.
