### ISSUE TITLE
Inventory alphabetical order anarchy

### ISSUE THREAD

**Issue by metalheimer** [cataclysmbnteam/Cataclysm-BN#2477]
### Describe the bug

Item names that start with capital letters are placed strangely and out of alphabetical order. It appears they will always be the 2nd from the top in their category. See screenshot, particularly Swiss army knife and Prussian blue. Also the placement of steel spear there is weird, probably because of its ++ reinforcement symbols. Capital letters are not a problem in adv. inventory, and appears to follow alphabetical rules. I forgot to check how the ++ items behave in AI...

### Steps To Reproduce

1. Obtain several items (10+) to establish a proper list.
2. Obtain items that start with capital letter, such as Swiss army knife and Prussian blue.
3. View inventory, witness anarchy and hear the lamentation of librarians.

### Screenshots

![alph2](https://user-images.githubusercontent.com/127426533/227716352-4fbf75d1-910b-46c8-8da5-2e330dd68854.png)

### Versions and configuration

win64bit, tiles, game version 6f61158

**Comment by olanti-p** [comment]
May be related to #903

**Comment by scarf005** [comment]
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/7758e1ca-0929-47cf-a712-afce49147747)

couldn't reproduce on linux. could you confirm which version of windows BN you're using? (MSVC/MSYS2)
if it's latter, please follow the issue on #903.

closing as stale for now. please let us know if anything isn't right.
