### ISSUE TITLE
Weird charge display when crafting

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#249]
* Spawn hotplate, 100 meat, 100 charcoal. Place a smoking rack with map editor.
* Reload rack with charcoal.
* Try to craft 3 cooked meat.

Expected:
* Menu opens, has "21/500 hotplate" and "21/100 charcoal cooker". Order not relevant, but that 21 is important.

Got:
* Menu has "9/100 charcoal cooker" and just "hotplate".

I tracked it down to tool selection, where we have this weird:
```
            comp_selection<tool_comp> ts = crafter->select_tool_component(
            it, batch_size, map_inv, DEFAULT_HOTKEYS, true, true, []( int charges ) {
                return charges / 20 + charges % 20;
            } );
```
Apparently, that `/20 + %20` is supposed to account for finishing incomplete crafts, but it's displayed even when starting new ones.

Fixing it may be as simple as not displaying that weird charge, but still using it to filter tools without enough charges.

**Comment by olanti-p** [comment]
Seems to be fixed as of 39352544f4f5ada4a4a9388cbbf4ffd3f7047dfc.
Tried repeating the steps, got expected result.
