### ISSUE TITLE
Drawing time related performance regression

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#251]
Somewhere during the `ui_adaptor` migration, overdraw must have been introduced.
Drawing got noticeably slower, which can be seen by comparing execution time of redraw-heavy actions like walking vs waiting, which skips redraws.

The debug benchmark (debug menu->enter->b->enter) seems to redraw everything the same way as the game does normally, so it should be good enough.
In my test, the FPS dropped from 77 in 906-Linux-64-Tiles, to 59 in 1028-Linux-64-Tiles.

**Comment by olanti-p** [comment]
Apparently, ui migration also changed how debug benchmark works.

I've compiled builds 906 and 1009 on Windows 10 x64, selected `opengl` renderer, maximized game window and did the benchmark under profiler.
FPS, indeed, dropped from 25.230 to 19.593.

On the other hand, when running benchmark on build 906 the display stays at "Enter benchmark duration" popup, while on build 1009 it switches to show the terrain view with "Benchmark in progress" at the top of the screen.
This led me to believe that benchmark actually started refreshing the game window.

Here's the graph of CPU usage on build 906:
![image](https://user-images.githubusercontent.com/60584843/101485143-cab3d880-396b-11eb-9e08-f4e3be002182.png)
The game fully uses a single virtual core.

And on build 1009:
![image](https://user-images.githubusercontent.com/60584843/101485192-dc957b80-396b-11eb-9273-bcd37d4f9c59.png)
CPU usage has dropped, which indicates a blocking operation, and waiting for the OS to refresh the window is a likely candidate.

Going through the benchmark code indicates that, indeed, it now calls `refresh_display()`. Removing that call raises CPU usage back, and testing (in a different spot on the map) showed that FPS drops from 27.014 to 26.784. Still a drop, but a tiny one. Switching to `direct3d11` completely eliminates the difference.

Not sure how to measure redrawing while walking though.

Btw, 59 looks suspiciously like common vsync limit of 60.

**Comment by Coolthulhu** [comment]
> CPU usage has dropped, which indicates a blocking operation, and waiting for the OS to refresh the window is a likely candidate.

Could be it. Before, it was possible for some frames to be skipped. Now it looks like every frame is forced onto the screen.
This would explain why things feel so slow, even if the numbers only show a modest drop in framerate.

**Comment by Coolthulhu** [comment]
Oh right, there's a "force redraw".
Now it actually works and works too well.

Well, I guess we need some sort of frame skip, but for now the issue is not easily solvable and not exactly a performance thing.
