### ISSUE TITLE
Game keeps crashing when trying to fire a turret from vehicle

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#2512]
### Describe the bug

Latest working build for me is [build 2023-03-30-2208](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2023-03-30-2208) . Since build 2023-03-30-2256 the game keeps crashing with nothing in the logs whenever I try to fire a turret in the vehicle. My guess is: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2468 .

### Steps To Reproduce

1. Enter vehicle
2. Fire turret
3. Game goes kaput

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 42cb8b6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    <color_light_green>Cataclysm++</color> [Cata++],
    Aftershock [aftershock],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    PKs Rebalancing [PK_REBALANCE],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    <color_red>Sierra Madre</color> [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    Steampunk Mod [steampunk_arcanum],
    UnderrailMetro Mod [underrailmetro_mod],
    <color_light_blue>Really Dark Skies</color> [realdarkskies],
    <color_red>C.R.I.T. Expansion</color> [crt_expansion],
    Nechronica Redux [Nechronica_Redux],
    Magiclysm [magiclysm]
]

**Comment by Unrepentant-Atheist** [comment]
Doesn't really fix ;). Now I get to see the segfault actually! 

![image](https://user-images.githubusercontent.com/3938423/229268696-2e2bd043-7235-46fa-9f24-752f8a269d43.png)

https://pastebin.com/jsZATmyS

**Comment by KheirFerrum** [comment]
#2533 should have fixed this.
