### ISSUE TITLE
Magiclysm mod magic light error popup.

### ISSUE THREAD

**Issue by Pleinmitz** [cataclysmbnteam/Cataclysm-BN#2518]
### Describe the bug
```
 DEBUG    : Called item::wind_resist on an item (<color_c_light_green>|| </color>magic light (997 turns) [magic_light]) made of nothing!

 FUNCTION : wind_resist
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\item.cpp
 LINE     : 6774
 VERSION  : BN 0.2
```

### Steps To Reproduce

Cast magic light with the magiclysm mod
error pops up

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 0.2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    No Fungal Monsters [No_Fungi],
    Craftable Gun Pack [craftgp],
    Magiclysm [magiclysm]
]

**Comment by Ishindri** [comment]
Can confirm, this is still occurring on 0.4 stable. Additionally, it causes significant performance issues - not so much during normal gameplay, but I was trying to read while wearing the magic light item, and it caused the game to slow to a crawl.

**Comment by chrsrns** [comment]
This is still happening on Experimental 2024-05-18.
