### ISSUE TITLE
Extreme slowdown for initial bullet hit

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#2523]
### Describe the bug

Upon loading the game, a lag of approximately 4 seconds occurs when the first bullet hits the target. This issue seems to happen once per submap

### Steps To Reproduce

1. Spawn a gun.
2. Fire it.
3. When the first bullet hits the target. there's an extreme slowdown for around 4 seconds.

### Video

https://user-images.githubusercontent.com/54838975/229287206-0270a464-65b8-4cb4-a240-33bc17acf2b0.mp4

### Flamegraph

![flamegraph](https://user-images.githubusercontent.com/54838975/229287408-8a60445b-6eed-493b-ae38-4c0f4069d5bb.svg)
[flamegraph](https://github.com/flamegraph-rs/flamegraph) from the moment before firing the bullet until the freeze ended. download and open in browser for interactive zoom.

![Mozilla Firefox_01](https://user-images.githubusercontent.com/54838975/229288166-f3570fd7-57b5-473f-bebb-a331eac1d0a4.png)

as suspected, firing gun invalidates the map cache, which causes the extreme lag once.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-11.2ubuntu1-noarch:security-11.2ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 22.10; Release: 22.10; Codename: kinetic; 
- Game Version: cbn-experimental-2023-03-31-2027 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges]
]

### Additional context

[test.tar.gz](https://github.com/cataclysmbnteam/Cataclysm-BN/files/11129361/test.tar.gz)

**Comment by scarf005** [comment]
![do-turn](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/6fa0cd44-5f24-4d10-9814-1c6ee5bb1dd2)

kcachegrind report (lost the actual log file)

**Comment by olanti-p** [comment]
Do you play with sound enabled?

**Comment by scarf005** [comment]
yes, i do.

**Comment by olanti-p** [comment]
Does the issue persist if you run the game with sound off?

**Comment by scarf005** [comment]
i'll rebuild without sounds and try again.

**Comment by scarf005** [comment]
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/1923569e-1441-4c2a-b059-144e993f84b1)

yes, i do not get any lags with sounds disabled. maybe the sound was blocking and i haven't noticed it since i always muted the game.

**Comment by olanti-p** [comment]
Then there's most likely same root cause as #114

**Comment by scarf005** [comment]
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/5a4dfcf3-b1e6-40be-9e5a-0aa930794766)

yeah, i've been using `otopack` soundpack, and the root cause seems to be identical. closing in favor of #114.

**Comment by scarf005** [comment]
...wait, added these to preload.json yet they doesn't seem to work
```json
[
  {
    "type": "sound_effect_preload",
    "preload": [
      { "id": "environment" },
      { "id": "fire_gun" },
      { "id": "reload" },
      { "id": "bullet_hit" },
      { "id": "plmove" },
      { "id": "danger_low" },
      { "id": "danger_medium" },
      { "id": "danger_high" },
      { "id": "danger_extreme" },
      { "id": "radio", "variant": "inaudible_chatter" }
    ]
  }
]
```

**Comment by scarf005** [comment]
```
10:38:34.263 ERROR SDL : /home/scarf/repo/cata/Cataclysm/src/sdlsound.cpp:585: (error message will follow backtrace)
    ./cataclysm-tiles(+0x8e0b5a) [0x555b64153b5a]
    ./cataclysm-tiles(+0x8dee2c) [0x555b64151e2c]
    ./cataclysm-tiles(+0x15ea118) [0x555b64e5d118]
    ./cataclysm-tiles(+0x161c21f) [0x555b64e8f21f]
    ./cataclysm-tiles(+0x61a520) [0x555b63e8d520]
    ./cataclysm-tiles(+0x14bb819) [0x555b64d2e819]
    ./cataclysm-tiles(+0x4b2d38) [0x555b63d25d38]
    ./cataclysm-tiles(+0x148e562) [0x555b64d01562]
    ./cataclysm-tiles(+0xabec1f) [0x555b64331c1f]
    ./cataclysm-tiles(+0x180b17c) [0x555b6507e17c]
    /lib/x86_64-linux-gnu/libc.so.6(+0x23a90) [0x7f0f1fe23a90]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x89) [0x7f0f1fe23b49]
    ./cataclysm-tiles(+0x471355) [0x555b63ce4355]

    Attempting to repeat stack trace using debug symbols…
    ??
    ??:0
    ??
    ??:0
    ??
    ??:0
    ??
    ??:0
    ??
    ??:0
    ??
    ??:0
    ??
    ??:0
    ??
    ??:0
    ??
    ??:0
    ??
    ??:0
    ??
    ??:0
    ??
    ??:0
    ??
    ??:0
Backtrace emission took 5 seconds.
(continued from above) ERROR: Failed to play sound effect: Tried to play a chunk with a bad frame
10:38:39.777 ERROR SDL : /home/scarf/repo/cata/Cataclysm/src/sdlsound.cpp:585: Failed to play sound effect: Tried to play a chunk with a bad frame
10:38:40.074 ERROR SDL : /home/scarf/repo/cata/Cataclysm/src/sdlsound.cpp:585: Failed to play sound effect: Tried to play a chunk with a bad frame
10:38:40.351 ERROR SDL : /home/scarf/repo/cata/Cataclysm/src/sdlsound.cpp:585: Failed to play sound effect: Tried to play a chunk with a bad frame
```
wait, maybe the issue was entirely unrelated to preloading?

**Comment by scarf005** [comment]
indeed it was that i was using soundpack from half a year ago: https://github.com/Kenan2000/Otopack-Mods-Updates/pull/51
