### ISSUE TITLE
Experimental release tarball contains broken symlinks

### ISSUE THREAD

**Issue by jmzumg** [cataclysmbnteam/Cataclysm-BN#2526]
### Describe the bug

`cataclysmbn-unstable/doc/CONTRIBUTING.md` and `cataclysmbn-unstable/doc//CONTRIBUTING.ko.md` in the experimental release tarball are symlinks to files that do not exist

I discovered this because it appears it might be the cause of a bug in [Catpult launcher](https://github.com/qrrk/Catapult/issues/106) 

### Steps To Reproduce

* These two files are symlinks to files in the `.github` directory:

```
$ tar -tvzf cbn-linux-tiles-x64-2023-03-31-2027.tar.gz | grep 'CONTRIBUTING.*\.md'
lrwxrwxrwx runner/docker     0 2023-03-31 22:44 cataclysmbn-unstable/doc/CONTRIBUTING.md -> ../.github/CONTRIBUTING.md
lrwxrwxrwx runner/docker       0 2023-03-31 22:44 cataclysmbn-unstable/doc/CONTRIBUTING.ko.md -> ../.github/CONTRIBUTING.ko.md
```

* But the `.github` directory is not included in the tarball:

```
$ tar -tzf cbn-linux-tiles-x64-2023-03-31-2027.tar.gz | grep .github | wc -l
0
```

### Versions and configuration

- Gameversion: cbn-linux-tiles-x64-2023-03-31-2027

**Comment by scarf005** [comment]
hello, thank you for the bug report. i'll make hotfix that will move CONTRIBUTING.md to project root, which would remove dependency from .github directory.
