### ISSUE TITLE
Performance issues after build 2023-03-31-1439

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#2537]
### Describe the bug

Somthing in the build 2023-03-31-1439 , slowed the game a lot. I'm in the middle of nowhere, reading a book. Any build prior to this, time flies. 2023-03-31-1439, the game's slow. Playable but the slowdown's noticeable. 

### Steps To Reproduce

1. Teleport / Go to the middle of nowhere
2. Read a book
3. See how time moves...

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 42cb8b6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    <color_light_green>Cataclysm++</color> [Cata++],
    Aftershock [aftershock],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    PKs Rebalancing [PK_REBALANCE],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    <color_red>Sierra Madre</color> [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    UnderrailMetro Mod [underrailmetro_mod],
    <color_light_blue>Really Dark Skies</color> [realdarkskies],
    <color_red>C.R.I.T. Expansion</color> [crt_expansion],
    Nechronica Redux [Nechronica_Redux],
    Magiclysm [magiclysm]
]

### Additional context

Save: https://nowtransfer.de/3662ee5e7b7d

**Comment by olanti-p** [comment]
Has this resolved itself in the latest releases, after msvc builds has been fixed? For example, in release 2023-04-05-1022.

**Comment by olanti-p** [comment]
Assuming this way some difference between mxe and msvc builds.
