### ISSUE TITLE
remove `EDIBLE_FROZEN` flag

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#2555]
### Is your feature request related to a problem? Please describe.

since we don't have item temperatures. less flag = faster to load

### Describe the solution you'd like

remove `EDIBLE_FROZEN` from flags. it cannot be used like `EATEN_COLD` flag because it mostly worked out like 'you can eat even when its frozen, but you won't like it'

**Comment by olanti-p** [comment]
Implemented in #2607
