### ISSUE TITLE
Hordes and how to improve them, a very short essay

### ISSUE THREAD

**Issue by tyrael93** [cataclysmbnteam/Cataclysm-BN#256]
Yo coolguy, how fucked is the horde code?

Is there a way to add some settings to hordes so that they can toggled to start only after a certain time or add a .json blacklist/whitelist only spawn certain types of enemy groups? I wanted to have a more invasion-y feely to my games but it seems like the entire setting is legacy whalescode that never really gets used.

thanks

**Comment by Coolthulhu** [comment]
Currently hordes have to be generated at overmap gen. They don't generate afterwards, except on new overmaps.

**Comment by tyrael93** [comment]
So basically that's a "no and rewriting that would be way too much work for something so simple" a'ght that's understandable
