### ISSUE TITLE
SCAR-L becomes oddly slow to aim when a mag is inserted

### ISSUE THREAD

**Issue by metalheimer** [cataclysmbnteam/Cataclysm-BN#2561]
### Describe the bug

SCAR-L's aim speed drops from 91 to 52 when a mag is inserted, and I have no idea why. The SIG 552, M4A1, M16A1 or HK416 do not present similar behavior, aim speeds dropping slightly. Obv no other attachments involved. Char's mship and rifles skills at 3.

### Steps To Reproduce

1. spawn in SCAR-L
2. check its stats (it should spawn with a full mag)
3. remove mag, check stats again, insert mag, check stats once more...
5. do same with other ARs

### Screenshots

![slowscarl](https://user-images.githubusercontent.com/127426533/229915293-0fcbe5cc-c5e7-408f-8403-73de7c24ed6f.png)

### Versions and configuration

cbn-windows-tiles-x64-msvc-2023-03-31-0134

**Comment by kebkebongit** [comment]
I think this has to do with gun volume penalizing aim speed up to a point. If you attach a grip or a suppressor to a SCAR-L it will increase the volume and decrease the aim speed as well. Magazines add their volume directly to the gun when loaded, so a SCAR-L loaded with a 30 round magazine is .5L bigger than unloaded, and the aim speed probably goes down to reflect this.

**Comment by scarf005** [comment]
| without mag | with mag |
| :-: | :-: |
| ![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/48fb3488-40f5-4263-85b5-b1b3eef03ee4) | ![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/ebf4d3ac-5beb-4847-9142-2d74f466122d) |

hi, this issue would now be fixed by #3820.
