### ISSUE TITLE
Auto aim occasionally re-aims dead enemy

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#2567]
### Describe the bug

When there's multiple enemies, sometimes killing last enemy will not switch re-aiming to new enemy but at the last enemy, which is dead.

### Steps To Reproduce

1. give player a gun. it does not matter if it's auto or not.
2. place yourself around lots of enemies.
3. fire the gun repeatedly.
4. sometimes, even when the enemy is killed, re-aim will still point at the (now corpse) previous enemy.

### Screenshots

https://user-images.githubusercontent.com/54838975/229955111-7d2ecdca-df52-43d5-bc5a-b213a0d97ef6.mp4

around 00:03, even when the bee is dead from bullet, new re-aims still targets the (now dead) bee.

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: core-11.2ubuntu1-noarch:security-11.2ubuntu1-noarch; Distributor ID: Ubuntu; Description: Ubuntu 22.10; Release: 22.10; Codename: kinetic; 
- Game Version: a6d29fdef56 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges]
]

### Additional context

save file: [test.tar.gz](https://github.com/cataclysmbnteam/Cataclysm-BN/files/11154248/test.tar.gz)
may be related to #2468.

**Comment by Ignaramico** [comment]
i havent checked, but that happens with spells too iirc

**Comment by chaosvolt** [comment]
> i havent checked, but that happens with spells too iirc

Sometimes happens, another more common annoyance is that spells with self/ally as their targets will still default to aiming at a hostile if one's in range. Easy to accidentally buff your enemies when you meant to use it on yourself.

**Comment by Ignaramico** [comment]
wait, how can the spell buff an hostile by accident?, i mean the spell shouldnt be cast cast since it isnt a valid target (unless you used an AOE with ground target stuff) that seems like a whole new bug

**Comment by chaosvolt** [comment]
Went ahead and tested this just to see.
![image](https://user-images.githubusercontent.com/11582235/230668964-dc92b948-6b4d-4868-9dbc-577997eaeb5a.png)
![image](https://user-images.githubusercontent.com/11582235/230668994-2486db9b-a5be-45f2-92f2-e5ac2f797785.png)
![image](https://user-images.githubusercontent.com/11582235/230669024-01c4a645-9d39-4d03-a4e1-6a38ce498bf8.png)

I was partially correct. It still defaults to targeting a hostile monster if doing so is an option, but it doesn't let you follow through with it unless the spell allows targeting hostile or ground with it, it seems.

Still an annoyance but at least muscle memory can't cause you to waste a buff on hostile monsters. It is definitely a completely different buff however, this has been around for much longer (more spellcasting code weirdness). Should I open an issue for it?

**Comment by Ignaramico** [comment]
> Should I open an issue for it?

if you would be kind enough. glad to see it didnt cast the spell.
