### ISSUE TITLE
 change temperature in codebase from fahrenheit to celcius

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#2569]
### Is your feature request related to a problem? Please describe.

see #1678

### Describe the solution you'd like

use `units::temperature` and celcius literal (`_c`) to wipe the word 'fahrenheit' in codebase (except when displaying to users)

**Comment by Unrepentant-Atheist** [comment]
Use kelvin instead...

**Comment by scarf005** [comment]
wish we could, but we're stuck with weird mix of celsius and fahrenheit, so kelvin would wait until we resolve that
