### ISSUE TITLE
Turrets began to see through walls.

### ISSUE THREAD

**Issue by KoverUnderCover** [cataclysmbnteam/Cataclysm-BN#2578]
### Describe the bug

Turrets began to see through bunker walls. If you turn 3D on, they begin to see through the lower floors of the bunkers.

### Steps To Reproduce

1. Approach the military bunker, which has turrets inside. 
2. Hear the firing.
 3. There is no one inside except the turrets.

### Versions and configuration

- OS: Windows
- OS Version: 10.0 2009
- Game Version: 45939d4 [64-bit]
- Graphics Version: Tiles
- Game Language: [russian]

**Comment by olanti-p** [comment]
Were you approaching in a vehicle? I think I saw someone complaining turrets ignore line of sight to vehicle when they fire at it, but I didn't check.

**Comment by KoverUnderCover** [comment]
I can confirm that if you duck in transport, the turrets still shoot. But I thought it was a peculiarity of vision turrets, as with the mutation "cold blooded" turrets do not shoot at you.

And as for my bug - turrets shot at me as a car and without, when he was on the floor above.

**Comment by olanti-p** [comment]
> if you duck in transport, the turrets still shoot

Turrets shoot at the cabin of a moving vehicle regardless of whether they see you, or whether there is anyone inside.

> turrets shot at me as a car and without, when he was on the floor above

Yeah, _that_ shouldn't happen.

**Comment by metalheimer** [comment]
> I think I saw someone complaining turrets ignore line of sight to vehicle when they fire at it, but I didn't check.

Yeah, that was me.

https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2431
