### ISSUE TITLE
Missing "character" tab in autopickup manager

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#2585]
### Describe the bug

Compare build Cataclysm-BN experimental build 2023-04-07-0224

![image](https://user-images.githubusercontent.com/3938423/230602649-f8fd12cd-dc0a-420a-bef0-f8ba6cba94ee.png)

with build Cataclysm-BN experimental build 2023-04-07-0301

![image](https://user-images.githubusercontent.com/3938423/230602752-768e902a-3fb5-47ad-99d7-f8c1cd2c05d5.png)

The character tab is missing.

### Steps To Reproduce

1. Try different builds
2. go to autopickup manager

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 333f1ac [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    <color_light_green>Cataclysm++</color> [Cata++],
    Aftershock [aftershock],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    PKs Rebalancing [PK_REBALANCE],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    <color_red>C.R.I.T. Expansion</color> [crt_expansion],
    <color_red>Sierra Madre</color> [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    UnderrailMetro Mod [underrailmetro_mod],
    Nechronica Redux [Nechronica_Redux],
    Magiclysm [magiclysm],
    <color_light_blue>Really Dark Skies</color> [realdarkskies],
    <color_light_blue>Really Dark Skies</color> plus <color_light_green>Cataclysm++</color> [realdarkskies_CATA_patchmod],
    <color_light_blue>Really Dark Skies</color> plus <color_pink>Aftershock</color> [realdarkskies_aftershock_patchmod],
    <color_light_blue>Really Dark Skies</color> plus <color_cyan>Arcana</color> [realdarkskies_Arcana_patchmod],
    <color_light_blue>Really Dark Skies</color> plus <color_red>C.R.I.T.</color> [realdarkskies_CRIT_patchmod],
    <color_light_blue>Really Dark Skies</color> plus <color_yellow>Bio-Synth Robot Expansion</color> [realdarkskies_gekkobots_patchmod],
]

**Comment by olanti-p** [comment]
Should be fixed by #2586
