### ISSUE TITLE
Excessive duplicate books and magazines in Apartment Tower

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#2626]
### Describe the bug

When looting an Apartment Tower on normal world settings, the bookshelves have an absurd number of books and magazines, up to 10 of the same one. Combined with there being a bookshelf or several in each apartment, and 8 apartments per level, this creates an absurd amount of the same magazines. The bookshelf distribution uses the itemgroups SUS_tailoring_bookcase SUS_crafts_bookcase and SUS_cooking_bookcase with a chance of 75.

The itemgroup SUS_tailoring_bookcase is set to spawn from 1 to 10 mag_tailor with a probability of 80, in addition to 1-4 tailor manuals and 1-4 tailor textbooks both of which at same probability.

The itemgroup SUS_crafts_bookcase is very similar, at 1-10 mag_fabrication at 80 in addition to an array of other fabrication books at 1-4, 1-4, etc.

The itemgroup SUS_cooking_bookcase again has a 1-10 for mag_cooking at 80 probability, and many other cookbooks, including 4 separate entries with 1-2.

I believe these itemgroups allowing between 1 and 10 was an oversight, possibly even being used straight from the library.

### Steps To Reproduce

1. Create a new world with default settings.
2. Go to the Apartment tower.
3. Loot the place.
4. Scream "Unlimited Power"

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    FoxMod for Bright Nights [FoxMod],
    Fuji's Military Profession Pack [fuji_mpp],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Bright Nights (wrapper) [dda],
    Cataclysm++ [Cata++],
    <color_cyan>Lones Soda mod</color> [coke_flavors],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Dorf Life [Dorf_Life],
    Fewer Farms [Fewer_Farms],
    SzQmod [SzQmod],
    Tankmod: Revived [Tankmod_Revived],
    No Addictions [No_Addictions],
    Nonperishable Overhaul [Nonperishable_Overhaul]
]

### Additional context

Forgive me if it's not really considered a bug, I figured 30 Bon Appetit magazines per floor was unintended behavior.

**Comment by chaosvolt** [comment]
Will take a crack at this while I've got wifi.
