### ISSUE TITLE
Antibiotics to have too low change to cure infection

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#263]
# Describe the bug
Antibiotics to have too low change to cure infection

# Steps To Reproduce
1. Start infected scenario
2. Spawn ton of antibiotics (normal antibiotics, not weak or strong one)
3. Try to recover from infection.

# Expected behavior
You are recovered from infection eventially.

# Actual behavior
You are going to die.

# Screenshots

# Versions and configuration
Build 1044

# Additional context

**Comment by Firestorm01X2** [comment]
Looks a the code:
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/093b950329cec5560c47825f6e0c60232c08daf2/src/player_hardcoded_effects.cpp#L895

```
else if( id == effect_bite ) {
        bool recovered = false;
        /* Recovery chances, use binomial distributions if balancing here. Healing in the bite
         * stage provides additional benefits, so both the bite stage chance of healing and
         * the cumulative chances for spontaneous healing are both given.
         * Cumulative heal chances for the bite + infection stages:
         * -200 health - 38.6%
         *    0 health - 46.8%
         *  200 health - 53.7%
         *
         * Heal chances in the bite stage:
         * -200 health - 23.4%
         *    0 health - 28.3%
         *  200 health - 32.9%
         *
         * Cumulative heal chances the bite + infection stages with the resistant mutation:
         * -200 health - 82.6%
         *    0 health - 84.5%
         *  200 health - 86.1%
         *
         * Heal chances in the bite stage with the resistant mutation:
         * -200 health - 60.7%
         *    0 health - 63.2%
         *  200 health - 65.6%
         */
        if( dur % 10_turns == 0_turns )  {
            int recover_factor = 100;
            if( has_effect( effect_recover ) ) {
                recover_factor -= get_effect_dur( effect_recover ) / 1_hours;
            }
            if( has_trait( trait_INFRESIST ) ) {
                recover_factor += 200;
            }
            if( has_effect( effect_panacea ) ) {
                recover_factor = 648000; //panacea is a guaranteed cure
            } else if( has_effect( effect_strong_antibiotic ) ) {
                recover_factor += 400;
            } else if( has_effect( effect_antibiotic ) ) {
                recover_factor += 200;
            } else if( has_effect( effect_weak_antibiotic ) ) {
                recover_factor += 100;
            }
            recover_factor += get_healthy() / 10;

            if( x_in_y( recover_factor, 648000 ) ) {
                //~ %s is bodypart name.
                add_msg_if_player( m_good, _( "Your %s wound begins to feel better!" ),
                                   body_part_name( bp ) );
                // Set ourselves up for removal
                it.set_duration( 0_turns );
                recovered = true;
            }
        }
```

Looks like recovery factor insanely low. So chance to recovery insanely low.

**Comment by JHQWER** [comment]
It seems to have couple of excess zeroes not to mention how crude and simplistic the whole formula is. No cumulative effect of devouring antibiotics for weeks huh just pure chance?

**Comment by Coolthulhu** [comment]
Infection kills you in 24 hours.
The math is as follows:
* One antibiotic lasts 12 hours and stops all progression
* This 12 hours on antibiotic gives you an 22% chance of healing the infection
* One whole stack of antibiotic is 15, giving you a final chance of 97% and over a week of time to find a next stack
* Recovering from an infection is unlikely to be a strong factor, as recovery at near-death is just 4 days averaging -1/6 chance of recovery

It's not an urgent risk of death by any means.
It looks fine for "infected" start, though infections after 2-3 days become a non-issue, as bite wound are incredibly easy to heal. Except for some challenge starts, I guess.

**Comment by Firestorm01X2** [comment]
Updated test case. I've tested Infected scenario with normal antibiotics specifically and star using antibiotics almost instantly. Something is definitely wrong here.

**Comment by TrainTurningPoint** [comment]
I don't see the precise cause of the issue, but some things to consider (checked on DDA code so might be different):
1. There are two separate status effects: "antibiotic_visible" and "antibiotic". The first one is visible in the status screen, the latter one actually does things; they have different duration. The game is misleading by design here, telling player to take the next dose too soon or too late.
2. Taking the next dose too late causes you to irrevocably lose some of your remaining time to live, unless you have strong antibiotics.
3. Getting bitten while already infected instantly progresses your infection by 25 minutes, no counter. Which is a lot, so actively scavenging for antibiotics while already infected is incredibly dangerous.

**Comment by Coolthulhu** [comment]
BN doesn't have `*_visible` effects - they were utterly broken, with actual antibiotic duration being constant, but the "visible" effect having random duration. Assuming the author was sane, the original intent must have been to do it the other way around.

Here's a test I did:
* Create world with no zombie rez
* Start a character with infected start
* Debug-kill everything in bubble
* Apply debug life support
* Spawn and consume 15 units (default charge count of a fresh spawn) of antibiotic at once
* Wait for a week

Result:
The character survived and got "recovering from infection".

**Comment by Firestorm01X2** [comment]
Hm. Then I've somehow got in 4% chance of not surviving? Or something happened during my test? Still it is possible. Need more testing.

**Comment by Coolthulhu** [comment]
> Then I've somehow got in 4% chance of not surviving?

How many antibiotics did you take?

**Comment by Firestorm01X2** [comment]
> How many antibiotics did you take?

Defintely more than 20. I've did testing without dedub life support, through. So getting hungty, thirsty happened.
I've periodically edited my stats directy.

**Comment by Firestorm01X2** [comment]
Overall chance of my survaval was:
1- (1-0.22)^20= 0.92
So dying was tehcnically possible.

**Comment by TrainTurningPoint** [comment]
Don't really understand the point in trying to trigger recovery every 10 turns with minuscule chance.
It just makes it harder to guesstimate the real combined probability. 

In my opinion, it would be better to try once per hour or so, with appropriately raised chances (and probably an additional last ditch attempt right before player dies).
Make it so active 12h antibiotic effect is renewed and increased in intensity if the next dose is taken while the effect of a previous one is still active, with appropriate penalties to discourage player from just consuming multiple at once.
Then apply a stacking bonus to recovery chance for each level of intensity, going up to 100% by the end of a full course.

That would guarantee that player can always get rid of infection in a predictable time interval if he has the antibiotic supply, or can still try his luck if there are only a few tablets left.

**Comment by Firestorm01X2** [comment]
It may be implemented with additional effect that could count time of total antibiotics consumption. 
If player consumed antibiotics over 5 days- automatically "cure" infection and trigger recovery.
Chance based recovery still may stay.

**Comment by Coolthulhu** [comment]
@TrainTurningPoint 
> Don't really understand the point in trying to trigger recovery every 10 turns with minuscule chance.
> It just makes it harder to guesstimate the real combined probability.

I thought about a more explicit way of solving it - an explicit function like this:
```
/**
 * Given an expected chance of success (>0, <1) over time, returns the probability p, such that x_in_y( p, duration ) repeated duration / tick_size times has @param chance probability of being true at least once.
 **/
float geometric_distribution::probability_for_expected( time_duration chance, time_duration duration, time_duration tick_size = 1_turns );
```
It would only need a good name and description.

Once it's obvious that it's a geometric distribution, anyone with basic knowledge in probability (or google) could quickly extrapolate from it with simple tools, just knowing that it's supposed to be 20% per day or something like this.

> Make it so active 12h antibiotic effect is renewed and increased in intensity if the next dose is taken while the previous one is still active, with harsh OD penalties to discourage player from just consuming multiple at once.

Why the penalty?
The cost of spending extra antibiotics should be enough.

@Firestorm01X2 
> If player consume antibiotics over 5 days (for example) continuously- automatically "cure" infection and trigger recovery.

We don't have an "automatically consume x if needed" system, so this could get tedious.
If most infections are supposed to go away through this guaranteed way, it would be better to cure it immediately and just apply penalties for a random time depending on health and antibiotic strength. Though health is currently broken.

**Comment by TrainTurningPoint** [comment]
> I thought about a more explicit way of solving it - an explicit function like this:

Not sure if it helps much if we leave the current system in place, as recovery chance and duration change over time are affected by other factors.

> Why the penalty?

It's what player would expect of antibiotics. Strong ones IRL are usually pretty taxing for the body itself, there's a reason recommended dosage exists.
While realism is not the focus, I don't think we should stretch the suspension of disbelief for no clear reason.

> We don't have an "automatically consume x if needed" system, so this could get tedious.
It's not that tedious though.
Infection is a rather rare thing to have, usually you can clean the wound long before if goes bad. So it won't become a routine thing.
Forcing player to run around for some time with a green wound and a ticking timer, keeping track of an additional objective, is fine for a change.

**Comment by Firestorm01X2** [comment]
> We don't have an "automatically consume x if needed" system, so this could get tedious.

No I mean **cumulative** effect. If plyer manage to be on antibiotics for certain amount of time- just cure infection. Probably dependent on infection time. 

>We don't have an "automatically consume x if needed" system, so this could get tedious.

But currently it works exactly like that. But recovering even is not even guaranteed.

**Comment by Coolthulhu** [comment]
> Not sure if it helps much if we leave the current system in place, as recovery chance and duration change over time are affected by other factors.

It would still give a ton of info: "You have x% chance to recover per day. For regular antibiotics, x = 22." would be clearly visible in the code.

> While realism is not the focus, I don't think we should stretch the suspension of disbelief for no clear reason.

I'm inherently opposed to any sort of realism that is implemented entirely through tedium. Antibiotics don't rot and have tiny volume, so there is no excuse not to allow stacking them.

> Infection is a rather rare thing to have

Basically, we have three "types" of infection:
* Infection start - this one matters
* Getting infected on day 1-3 - this one matters a bit less, but makes early game kite-heavy
* Getting infected after that - this one doesn't work and should be removed, as it adds less than nothing to the game

**Comment by Coolthulhu** [comment]
> But currently it works exactly like that.

No, you can consume in advance, not necessarily continuously.

**Comment by Firestorm01X2** [comment]
> No, you can consume in advance, not necessarily continuously.

Oh. Yes, Effect just stacks.

**Comment by Firestorm01X2** [comment]
So.. apparently you can just eat all antibiotics without that "one in 12 hours"

**Comment by Firestorm01X2** [comment]
@Coolthulhu 
Then what about guaranteed recovery after certain tiime on antibiotics, but without word "continuously"? Just "in total".

**Comment by TrainTurningPoint** [comment]
@Coolthulhu 
> It would still give a ton of info:

Fair enough. Still think that making the check every 10 seconds is excessive. Both of these could be made at once.
> I'm inherently opposed to any sort of realism that is implemented entirely through tedium. 

I think you are being overzealous in this case.
It's literally four keypresses per an ingame day to satisfy your infection clock. Only two, if antibiotics are changed to a tablet per day dosage. Ten, maybe twenty keypresses total to heal the infection completely.
Player spends much, much more on hunger and thirst ones.
> Getting infected after that - this one doesn't work and should be removed, as it adds less than nothing to the game

I'd rather we make it matter instead.
A panicking survivor searching everywhere for an antibiotic to treat his growing infection is a classic scenario for post-apocalyptic media.

@Firestorm01X2 
> So.. apparently you can just eat all antibiotics without that "one in 12 hours"

Yes. Description implies that it's a bad idea, but they apparently didn't actually implement anything to this effect, just hoped player would be discouraged from trying.

**Comment by Coolthulhu** [comment]
@Firestorm01X2 
OK. Depending on how you want it, it could be very easy to implement.
I see the following variants:
* Add a new effect, something like "antibiotic accumulation". Generated by the 3 existing antibiotic effects. Once it hits a threshold, it cures any infection and bite the player may have. Might be weird, because it would grant immunity to infections, as long as you keep popping pills.
* Change infection to start from where bite left off (ie. have it start at intensity 4). Then have antibiotics reverse it, with stronger ones doing it faster. Also make it not permanent, so that if it reaches 0, it clears itself. Make sure to update infected start. This would have the advantage of not having a threshold.
* Have infections that last for x days automatically go into recovery. Since the only way to slow down an infection is antibiotics, this would do what you want in an indirect way.

**Comment by Coolthulhu** [comment]
> I'd rather we make it matter instead.

I'd rather not try without an idea that obviously works. The cost of doing it wrong is pushing combat in the direction of complete damage avoidance, which is already a giant problem.
There is currently no mechanism that forces the player to take risks after first few days. Working infections would heavily punish those who get into melee and encourage even more kiting.

**Comment by Coolthulhu** [comment]
At the moment, antibiotics prevent infection death.
Infection could use some reworking, but too low chance is no longer a big problem.
