### ISSUE TITLE
Controlled Monster AI tag in player status window

### ISSUE THREAD

**Issue by Phenomphear** [cataclysmbnteam/Cataclysm-BN#2637]
### Describe the bug

Found nano-mutagenic serum, injected it and received 2 mutations and Controlled Monster (tors...) under Effects

The serum is from Cata++.

### Steps To Reproduce

Take nano-mutagenic serum, receive 2 mutations, and Controlled Monster under effects

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.2 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    PKs Rebalancing [PK_REBALANCE],
    Elevated bridges [elevated_bridges],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    Tankmod: Revived [Tankmod_Revived],
    Roadheader and other mining vehicles [Heavy miners],
    Pneumatic fun [pneumo_fun],
    Blazemod - Vehicle Additions Pack [blazemod],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    C.R.I.T Expansion Mod [crt_expansion],
    Nechronica Redux [Nechronica_Redux],
    Aftershock [aftershock],
    Bug's life [Bug's life],
    DinoMod [DinoMod],
    Draco's Dog Mod [DracoDogMod],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Mining Mod [Mining_Mod],
    Wild Living [WildLiving],
    Survivor's Lost item [Survivors_Lost_item],
    Rivtech Beam Swords [beamswordmod],
    Ricky's Future Armory [futurearmory],
    More Survivor Notes [more_survive_notes],
    Modern Weapon Pack Expanded [modern_weapon],
    Metal materials [metal_elemental],
    Large capacity storage CBMs [eps_cbm],
    Icecoon's Arsenal [ew_pack],
    Gourmand's Graces [Gourmand'sGraces],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    CBM Equipment [CBM_Arms],
    Bionic Space Expander [Bionic_Space_Expander],
    Arsenal Breach [arsenal_breach],
    Advanced Technologies [advtech],
    Adurnsyl's Assorted Arms and Armour [AAA],
    Bionic Slots [cbm_slots],
    Tame Bugs [tamebugs],
    <color_light_green>Cataclysm++</color> [Cata++],
    Stats Through Skills [StatsThroughSkills],
    BioCo Content [bioco],
    Even More Mutations [even_more_mutations],
    Caches [P_Caches],
    Water Towers [water_towers],
    Folding Parts pack [deoxymod],
    Shrub it off [shrub_mod],
    Advanced Gear [adv_gear],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Expanded Archery [ExArch],
    More Armors [More_Armors],
    Thermal Electric UPS [thermal_ups],
    XEAS [XEAS],
    Alternative Basement Layouts [basement_extension],
    Beta National Guard Camp [national_guard_camp],
    sees-player icon, retrodays [sees_player_retro],
    Mutation Changes Snofielf [Mutation_Changes1],
    Stats Through Kills [stats_through_kills]
]

**Comment by chaosvolt** [comment]
So I'm looking at what actually applies this in the code. Were you near the thriller (unlikely since Crazy Cataclysm not on the modlist) or a brain blob? Those are the only things that can apply that effect in vanilla, not sure if it can bug out and apply it to players but who knows.

Otherwise, possibly one of the misc mods in there has a spell or monster attack effect that can, for whatever insane reason, slap the effect `ai_controlled` on the player (likely expecting to be used on monsters but target fields might not have properly avoided anything the player might count as).

**Comment by Phenomphear** [comment]
I was in a dino-bio lab. I don't think there were any blobs around? I have a backup of the save, I could try and inject it somewhere else, and or slowly remove mods and inject it each time.

**Comment by chaosvolt** [comment]
The somewhat slow but through way, if you have notepad++ or the like, would be to do a search-in-folder of your data/mods folder, in this case searching for `ai_controlled`. That would spot if any mods actually call for the effect in their JSON.

**Comment by Phenomphear** [comment]
I did that quickly with grepWin. 
![image](https://user-images.githubusercontent.com/28910998/231882638-554aea42-c491-4fbc-a7c2-3614ff52a50f.png)

Secronom has some. I'll make a backup, remove the mod and then try injecting

**Comment by Phenomphear** [comment]
Removed it and injected, still got the Controlled Monster effect. Its definitely a mod issue, I made a new world with base mods and then the cata++ and spawned it in and injected, everything went fine, no Controlled Monster effect. Gonna play around some more to try and find which one.

**Comment by chaosvolt** [comment]
Huh, weird.

**Comment by chaosvolt** [comment]
Additional complication: that effect is a permanent one, so testing it with that character is likely not going to go well since the instant it's applied to the player by whatever that field is, it's not going away (if it's caused by the enchantment then no longer piloting whatever mech the filename implies it's tied to should remove it).

You sure testing Cata++ with other mods but not Secronom still suffers this?

**Comment by Phenomphear** [comment]
I'm not sure what causes it anymore. I made a new world, with all the same mods as the one that had the issue, made a new character, and spawned that in and injected, and did NOT receive the effect. So something with that other character is causing it, so I don't know.

**Comment by olanti-p** [comment]
Ruling this out as a mod issue.
In game, `ai_controlled` is used only by Jackson zombie and blob brain, and both apply them only to monsters.
