### ISSUE TITLE
Suggestion: Label Weapon Categories in Item Description

### ISSUE THREAD

**Issue by yay855** [cataclysmbnteam/Cataclysm-BN#2641]
### Is your feature request related to a problem? Please describe.

Simply put, the weapon categories an item may fall into can be somewhat obscure, though not necessarily always. Having a method to easily ascertain what weapon categories a weapon falls under simply makes sense.

### Describe the solution you'd like

Have the item description for weapons describe what weapon categories they fall under.

**Comment by olanti-p** [comment]
Implemented in #1709
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/60584843/f102805c-ddd5-4559-91bc-ef3f7bdac1a2)
