### ISSUE TITLE
Cracklins byproducts from human lard is not flagged as human flesh

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#2646]
### Describe the bug

When creating human lard, the cracklins byproduct isn't flagged as human flesh. When making cracklins directly from human fat, it is properly flagged as such.

The discord mentions this also happens with tainted lard giving cracklins but I've yet to verify that.

### Steps To Reproduce

1. Find chunks of human fat.
2. Try to cook human lard.
3. Notice that cracklins doesn't have the flag.

### Screenshots

Here is the screenshot of cracklins from human lard.
![image](https://user-images.githubusercontent.com/112293514/232246563-1823e491-d069-4542-8ce0-9552eee0d32a.png)
Here is the screenshot of cracklins made directly.
![image](https://user-images.githubusercontent.com/112293514/232246578-66dc0773-b6b1-4140-980d-3961e26ab5b3.png)
Here is a bonus screenshot of cracklins made from normal chunks of fat.
![image](https://user-images.githubusercontent.com/112293514/232246590-c867bc38-c906-41b9-adbb-27c8bcf7f50b.png)

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Pro for workstations Build 19045
- Game Version: 0.2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    FoxMod for Bright Nights [FoxMod],
    Fuji's Military Profession Pack [fuji_mpp],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Bright Nights (wrapper) [dda],
    Cataclysm++ [Cata++],
    <color_cyan>Lones Soda mod</color> [coke_flavors],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Dorf Life [Dorf_Life],
    Fewer Farms [Fewer_Farms],
    SzQmod [SzQmod],
    Tankmod: Revived [Tankmod_Revived],
    No Addictions [No_Addictions],
    Nonperishable Overhaul [Nonperishable_Overhaul]
]

**Comment by RoyalFox2140** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/45812 This pull may fix the issue.

**Comment by Agoelia** [comment]
I suspect the issue is not solved. Crafting mutant lard from mutant fat also produces cracklins with no toxins or mutagens in latest stable (0.10.0)
