### ISSUE TITLE
Food in vehicle freezers/fridge not showing in description if they are preserved or not

### ISSUE THREAD

**Issue by Phenomphear** [cataclysmbnteam/Cataclysm-BN#2647]
### Describe the bug

![image](https://user-images.githubusercontent.com/28910998/232261184-8b1ac789-c392-412b-95f7-8373946b7320.png)

### Steps To Reproduce

Place items in vehicle freezer or fridge, description does not change

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.2 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    PKs Rebalancing [PK_REBALANCE],
    Elevated bridges [elevated_bridges],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    Tankmod: Revived [Tankmod_Revived],
    Roadheader and other mining vehicles [Heavy miners],
    Pneumatic fun [pneumo_fun],
    Blazemod - Vehicle Additions Pack [blazemod],
    <color_light_red>Secronom</color> [secronom],
    <color_light_red>Secronom+ Lore Expansion</color> [secronom_lore_expansion],
    C.R.I.T Expansion Mod [crt_expansion],
    Nechronica Redux [Nechronica_Redux],
    Aftershock [aftershock],
    Bug's life [Bug's life],
    DinoMod [DinoMod],
    Draco's Dog Mod [DracoDogMod],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Mining Mod [Mining_Mod],
    Wild Living [WildLiving],
    Survivor's Lost item [Survivors_Lost_item],
    Rivtech Beam Swords [beamswordmod],
    Ricky's Future Armory [futurearmory],
    More Survivor Notes [more_survive_notes],
    Modern Weapon Pack Expanded [modern_weapon],
    Metal materials [metal_elemental],
    Large capacity storage CBMs [eps_cbm],
    Icecoon's Arsenal [ew_pack],
    Gourmand's Graces [Gourmand'sGraces],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    CBM Equipment [CBM_Arms],
    Bionic Space Expander [Bionic_Space_Expander],
    Arsenal Breach [arsenal_breach],
    Advanced Technologies [advtech],
    Adurnsyl's Assorted Arms and Armour [AAA],
    Bionic Slots [cbm_slots],
    Tame Bugs [tamebugs],
    <color_light_green>Cataclysm++</color> [Cata++],
    Stats Through Skills [StatsThroughSkills],
    BioCo Content [bioco],
    Even More Mutations [even_more_mutations],
    Caches [P_Caches],
    Water Towers [water_towers],
    Folding Parts pack [deoxymod],
    Shrub it off [shrub_mod],
    Advanced Gear [adv_gear],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Expanded Archery [ExArch],
    More Armors [More_Armors],
    Thermal Electric UPS [thermal_ups],
    XEAS [XEAS],
    Alternative Basement Layouts [basement_extension],
    Beta National Guard Camp [national_guard_camp],
    sees-player icon, retrodays [sees_player_retro],
    Mutation Changes Snofielf [Mutation_Changes1],
    Stats Through Kills [stats_through_kills]
]

### Additional context

I am on stable 0.2

**Comment by scarf005** [comment]
![image](https://user-images.githubusercontent.com/54838975/232264369-ce28fe64-b717-46bf-97a1-2056e8484ef5.png)

when minifridge vehiclepart is loaded, looks like `FRIDGE` vehicle part flag is not being set.

@Coolthulhu @joveeater

**Comment by Coolthulhu** [comment]
Possible causes:
* The flag is not being set on the vehicle part
* The flag is not being translated from string flag to bitset flag
* The bitset flag is not being applied to rot calculations
* The bitset flag is not being applied to UI check

**Comment by scarf005** [comment]
`vpart_info::finalize` isn't the curprit as
<details><summary>this worked</summary>


```c++
void vpart_info::finalize()
{
    DynamicDataLoader::get_instance().load_deferred( deferred );

    for( auto &e : vpart_info_all ) {
        if( e.second.folded_volume > 0_ml ) {
            e.second.set_flag( "FOLDABLE" );
        }

        for( const auto &f : e.second.flags ) {
            if( e.first->name() == "minifridge" ) {
                debugmsg( "minifridge flag: %s", f.c_str() );
            }
            auto b = vpart_bitflag_map.find( f );
            if( b != vpart_bitflag_map.end() ) {
                e.second.bitflags.set( b->second );
                if ( f == "FRIDGE" ) {
                    if ( e.second.has_flag( "FRIDGE" ) ) {
                        debugmsg( "minifridge flag: %s is found", f.c_str() );
                    } else {
                        debugmsg( "minifridge flag: %s is not found???", f.c_str() );
                    }
                }
            } else {
                if ( f == "FRIDGE" ) {
                    debugmsg( "minifridge flag: %s is not found???", f.c_str() );
                }
            }
        }
```

</details> 


![image](https://user-images.githubusercontent.com/54838975/232314142-087fc9cf-3c11-4e13-b56d-c2a3ce9767c0.png)
what's weird is that part retrieved via `const vehicle_part &part = veh.cpart( part_index );` seems to reset its flag to 0.
