### ISSUE TITLE
flags all 0 with `vehicle::cpart` or `vehicle::get_all_parts`

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#2651]
### Describe the bug

see https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2647#issuecomment-1510379989 for details.

looks like it's supposed to use `vpart_info` to use lookup (which caches lookups), rather than using `vehicle_part.flags` directly. I guess it should be noted in docstring?

**Comment by olanti-p** [comment]
Possibly related: #331
