### ISSUE TITLE
metric bullets

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#2690]
### Is your feature request related to a problem? Please describe.

bullets with well known metric names should be displayed in metric, as it improves consistency and helps non-US players to understand better.

(copied from #2691)
inconsistency in naming bullets with same calibre causes issues.
  - some bullets use `5.56 NATO`, wheras others use `.223` for names and description, confusing.
  - you need to search twice, once for `.223` and once again for `5.56`.
  - `5.56x45mm ammo belt` is crafted from `.223 ammo belt linkage`, unintuitive.

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/54838975/234036295-bcc65c79-121c-4979-aa9d-b9d93b3c0d4d.png)
use metric names like 7.62mm rounds. this is to make searching bullet consistent. after the changes, finding bullet would always adhere to `<bullet dimension> <bullet name>` which would make finding and sorting compatible bullets easier.

e.g
| name                         | dimension(compatible gun) | name(identifier) |
| ---------------------------- | ------------------------- | ---------------- |
| `5.56x45mm (.223 Remington)` | 5.56x45mm                 | .223 Remington   |
| `5.56x45mm NATO M855A1`      | 5.56x45mm                 | NATO M855A1      |

- #2691
- #2724
- [x] migrate bullet ids to `{calibre}x{length}mm_{name}`
~~- [ ] `.30-06` -> `7.62x63mm`~~
~~- [ ] `.50 BMG` -> `12.7×99mm`~~
- [ ] [standardise RPG-7 ammo names](https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2690#issuecomment-1520935326)

**Comment by chaosvolt** [comment]
That definitely indicates that .50 is much more well-known as a name than 12.7mm I'd say, to be honest. So long as the name it's known as in the country that developed it is still present it's probably fine, displaying both works if needed. I'd mainly just say don't axe one name in favor of the other, otherwise it just trades confusing one part of the playerbase for another.

**Comment by chaosvolt** [comment]
So after more discussion, I think I'm okay with current proposal for how to name .223 and .308, so long as .30-06 and .50 stay with their more common, country-of-origin measurements first, i.e. use `.50 BMG "12.7×99mm"` if we include the metric designation.

However, this has reminded me of a more muddled ammo type:
`"name": "PG-7VL 93mm rocket",`
`"name": "PG-7VR 64mm/105mm rocket",`
`"name": "TBG-7V 105mm rocket"`,
`"name": "OG-7V 40mm rocket",`

**Comment by scarf005** [comment]
RPG-7 names are to be tracked in #2843
i guess others are done and id migration wouldn't worth the hassle
