### ISSUE TITLE
Recipes locked only behind skill level should be visible

### ISSUE THREAD

**Issue by Wreckstation** [cataclysmbnteam/Cataclysm-BN#272]
# Is your feature request related to a problem? Please describe.
Early game, I often get confused when people tell me to make recipes but they didn't show up when I searched them. Ex, ammo pouches, braziers. It turns out that they're only visible in my crafting menu when I hit the specific skill threshold. This was doubly confusing to me as in the corner it states "No hidden recipes". There is no way to learn what things you can craft unless you googled it on the cdda trunk or someone told you.

# Describe the solution you'd like
I would like them to show up in the crafting list, but all information can be hidden, just the information that you will learn it is sufficient and good motivation for new players to level up that particular skill.

# Describe alternatives you've considered
* Not changing anything,
* Still hide certain recipes, but only because they are too high level compared to the player's current skill. (ex. hiding a level 5 fabrication recipe when the player is still fabrication level 1, but show a preview of a level 3 recipe)

# Additional context
I created a mock up of a possible way for an unlearned recipe to appear. Sorry for wrong terminus font lol
![image](https://user-images.githubusercontent.com/53310247/102570180-da8e9380-40b4-11eb-9cdc-f9a1f9e8e241.png)

**Comment by Coolthulhu** [comment]
I like the idea. It might be easy to implement too.

I wouldn't really hide the details, though. It's "meta knowledge" that the player (not the character) retains between games and can look up, so hiding it doesn't look right.

My implementation would look like this:
* New keybind: `[u]nknown` - if enabled, all recipes are shown
* Unmemorized recipes show which books that the character has read have this recipe
* Autolearn requirements are shown, if higher than skills

**Comment by Wreckstation** [comment]
My justification for hiding the info is that it feels a little silly for the character to be like "Hmm, I know that you can make nitric acid by combining hydrochloric acid and saltpeter, if only I was a little bit better at boiling". When they're at the sufficient skill level it would dawn on them what ingredients and tools are required.

But also, this is the branch that's supposed to be more fun than real so your implementation is also fine.
