### ISSUE TITLE
You can sleep thought smoke whitout issues.

### ISSUE THREAD

**Issue by Xindage** [cataclysmbnteam/Cataclysm-BN#2734]
### Describe the bug

Seems like if smoke manages to reach you while you're sleeping, it'll not affect you at all, you should be able to sleep thought it as if nothing is happening.

### Steps To Reproduce

1. Get a mask activated.
2. Sleep in a place where smoker zombie cannot reach you but the smoke can.
3. Notice that your mask will lose all the charges but you'll keep sleeping without inhaling smoke.

### Screenshots

![image](https://user-images.githubusercontent.com/6380147/235349682-7fddd18c-a70d-4f39-bba5-2e388a0d43f8.png)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 638c4d1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Aftershock [aftershock],
    Chorus's Gear [Chorus_Weapons]
]

**Comment by gridbugsmasher42** [comment]
I ran a test that involved being in the interior of a vehicle, spawning hundreds of smoker zombies, allowing them to smoke up the place. Even without a filter and there being thick smoke on the same tile as the player, nothing happened while I was standing still in the interior, moving would cause the player to start coughing.

Setting fd_smoke's immune_in_vehicle value to false (in data/json/field_type.json) seems to fix this problem for me. I'm too tired right now to look further into this.

**Comment by chaosvolt** [comment]
A vehicle keeping minor levels of smoke out is probably okay, but I'm not sure if it can check for properly enclosed vehicles. If it can't check for whether you actually count as indoors in that vehicle it probably would be better to just axe it yeah. Most other gases like toxic gas seem to apply through vehicles too.
