### ISSUE TITLE
Equipping items onto an NPC from the armor sort menu segfaults if item is on floor on same tile as player.

### ISSUE THREAD

**Issue by KheirFerrum** [cataclysmbnteam/Cataclysm-BN#2743]
### Describe the bug

When equipping items onto a naked and inventory empty NPC from armor sort menu, if the item is on the floor on the same tile as you, the game crashes.

### Steps To Reproduce

1. Spawn into game and recruit an NPC. Delete all items from them.
2. Spawn a backpack, drop it directly under you.
3. Examine an NPC and select sort armor. Then (E)quip from nearby.
4. Select the backpack and confirm, game crashes.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 9c7997b [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges]
]

### Additional context

Attaching a debugger to the process confirms it's an issue [here](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/2886e11055038346388f4e59a5032ed9591d1af0/src/armor_layers.cpp#L874). However, I cannot discern the exact issue, hence the making of this one.

**Comment by SaintCirno9** [comment]
I'm unable to reproduce the crash, maybe it's OK now?🤔🤔🤔

**Comment by KheirFerrum** [comment]
> I'm unable to reproduce the crash, maybe it's OK now?🤔🤔🤔

Nope. But double checking has revealed that it's specific to if the NPC has nothing in their inventory. So I guess it's not a particularly critical bug.
