### ISSUE TITLE
obsolete `RECOVER_[N]` flag in favor of `dont_recover_one_in` field

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#2769]
### Is your feature request related to a problem? Please describe.

there's two way to decribe chance of recovering projectiles: `RECOVER_[N]`, which is a flag, and `dont_recover_one_in`, which is a field.
using flag with a suffix felt very hacky, and there's no way to validate non-number values like `RECOVER_asdf`.
also it's not obvious what does `RECOVER_[N]` do.

### Describe the solution you'd like

these flags could be obsoleted in favor of more descriptive `dont_recover_one_in` field.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/5343c2833edaab210d7cf5987678402a9b84621a/src/item_factory.cpp#L1686

![Cataclysm: Bright Nights - cbn-experimental-2023-05-05-0302-1-g297ff0128ce_01](https://user-images.githubusercontent.com/54838975/236630608-05cd6d8c-da6e-4955-9fad-558f06d9ae48.png)
(set `dont_recover_one_in` to 2 then tested)
relevent code and manual testing shows that the field actually works but was forgotten until now.

### Additional context

this can be automated using TS.

**Comment by chaosvolt** [comment]
Is `dont_recover_one_in` actually functional, or is it dead spaghetti code? I don't recall ever seeing it used by an item before.

**Comment by scarf005** [comment]
oh yeah, forgot to provide screenshots. it works as expected, but you also could test it yourself by replacing
```json
{
  // ...
  "flags": [ "RECOVER_4" ]
} 
```
with
```json
{
  // ...
  "dont_recover_one_in": 4
}
```
best way is to edit pebble ammo then use fire pneumatic rifle on auto (total 20 rounds) at debug monster. in this example there would be around 16 pebbles recovered on ground.

**Comment by chaosvolt** [comment]
Interesting, seems like it should be easy enough to do then.

**Comment by chaosvolt** [comment]
Interestingly, discovered this seems to only work in BN, I figured I'd try converting ammo in my mods to use this and found that DDA reports it as an invalid/misplaced field. Seems to work fine in BN in testing though:
![image](https://user-images.githubusercontent.com/11582235/236633837-38a6ba4c-451f-404c-b7f5-b318969df423.png)

**Comment by AniDemi** [comment]
Is there a possibility to replace `dont_recover_one_in` with `recover_chance` or something similar? I feel like the latter name is more intuitive than what we have now.

**Comment by olanti-p** [comment]
> Is dont_recover_one_in actually functional, or is it dead spaghetti code? I don't recall ever seeing it used by an item before.
> this seems to only work in BN

You could've checked with git blame, Github has great interface for that.

Support for RECOVER_x has been left in so the external mods wouldn't break after https://github.com/cataclysmbnteam/Cataclysm-BN/pull/1345 , it should have been long enough for this not to be a concern anymore. `dont_recover_one_in` is the new and proper way, RECOVER_ should be removed.

> Is there a possibility to replace dont_recover_one_in with recover_chance or something similar? I feel like the latter name is more intuitive than what we have now.

I disagree, this is the most concise and clear name. `"recover_chance": X` implies it's `1 in X` chance to recover or maybe `X%` chance to recover (note how `chance` is ambiguous, ergo it shouldn't be used in name), but the actual formula is `(X-1) in X`, which is way off.

**Comment by chaosvolt** [comment]
> dont_recover_one_in is the new and proper way, RECOVER_ should be removed.

That would explain it, it's a BN-specific code it seems. I'd assumed it was something old and not something new because BN has zero in-repo usage of it to my knowledge.
