### ISSUE TITLE
(Debian) Experimental builds fail to run due to missing libraries

### ISSUE THREAD

**Issue by Carcosian-TMG** [cataclysmbnteam/Cataclysm-BN#2778]
### Describe the bug

The game fails to run, the files are executable, and I believe I have all required dependencies.
I have tried installing manually, as well as with the Catapult launcher. This issue only occurs on the experimental builds, as both stable builds have had no issues running.

### Steps To Reproduce

1. Install Debian 11 and GNOME 3.38.5
2. Download and unpack cbn-linux-tiles-x64-2023-05-08-1025.tar.gz
3. Run cataclysm-launcher

### Versions and configuration

-OS: 64-bit Debian 11, with GNOME version 3.38.5
-Game version: Cataclysm-BN experimental build 2023-05-08-1025
-Graphics version: Tiles
-In-game language: English
-Loaded mods: N/A

**Comment by scarf005** [comment]
could you paste terminal output after running `./cataclysm-launcher`

**Comment by Carcosian-TMG** [comment]
> could you paste terminal output after running `./cataclysm-launcher`?

./cataclysm-tiles: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./cataclysm-tiles)
./cataclysm-tiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./cataclysm-tiles)
./cataclysm-tiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./cataclysm-tiles)
./cataclysm-tiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./cataclysm-tiles)
./cataclysm-tiles: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./cataclysm-tiles)

Is this a dependency I've missed or something?

**Comment by Carcosian-TMG** [comment]
Ah, I see, I'm missing a C++ library.

**Comment by scarf005** [comment]
were you able to play the game after installing required libraries?

**Comment by Disonantemus** [comment]
Using `cataclysm-launcher` of each version:

- [Curses version](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/download/cbn-experimental-2023-09-30-0544/cbn-linux-curses-x64-2023-09-30-0544.tar.gz) work's no problem.
- [Tiles version](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/download/cbn-experimental-2023-09-30-0544/cbn-linux-tiles-x64-2023-09-30-0544.tar.gz), my **ArchLinux** (fully updated) needs the following packages (maybe, the other ones, I did have previously installed) to run:
  - sdl2_mixer
  - sdl2_ttf
- In [CDDA](https://aur.archlinux.org/packages/cataclysm-dda-git), these are the optional dependencies (Tiles version):
  - freetype2
  - sdl2_image
  - sdl2_mixer
  - sdl2_ttf

---  

- I think it's better if you put dependencies in README, DOCS or in the launcher script, to not just installing with trial an error, one by one. It's not so hard, but is better to not get those errors.
- Other idea it's to look in the other CDDA (Tiles version) of your distro, to know what is missing.

---

OS: Arch Linux x86_64
Kernel: 6.5.3-arch1-1
Resolution: 1920x1080
CPU: Intel i7-4790 (8) @ 3.600GHz
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
Memory: 2315MiB / 15936MiB
