### ISSUE TITLE
Crash when try to remove certain NPCs clothes

### ISSUE THREAD

**Issue by fgdfgfthgr-fox** [cataclysmbnteam/Cataclysm-BN#281]
# Describe the bug
The game crash if you try to help NPC sort out his/her clothes by removing certain clothes (only in some case).

# Steps To Reproduce

1.Open a new game with an initial NPC
2.Break his/her arm/leg, and give him/her a splint.
3.Wait for his/her arm/leg to heal.
4.Try remove the splint.
5.Game crash.

# Versions and configuration
 - OS: Windows 10
 - Game Version: 1204717
 - Graphics version: Tiles
 - Ingame language: Chinese (Simplified)
 - Mods loaded: Magiclysm
 -->

# Additional context
[Save File.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5720435/Save.File.zip)
[config.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5720433/config.zip)

**Comment by tyrael93** [comment]
I can also attest this, the game segfaulted after trying to remove a diver's watch from an NPC. 
I didn't have magiclysm enabled.

**Comment by olanti-p** [comment]
This seems to happen consistently with the last item in the 'Sort armor' menu.

`leftListIndex` here is equal to `tmp_worn`'s size, and that causes `draw_mid_pane(...)` to receive invalid iterator
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/fb0d38066bbcef07c1fa4aea2ced5ef906b91586/src/armor_layers.cpp#L616

**Comment by tyrael93** [comment]
Yeah, I can also confirm it was the last item when I removed it.
