### ISSUE TITLE
Translation error in ja.po

### ISSUE THREAD

**Issue by AniDemi** [cataclysmbnteam/Cataclysm-BN#2816]
### Describe the bug

On line 239626 and 239627 there are two different colors used, they're supposed to be the same.
`color_dark_gray` and `color_gray`. `color_gray` also does not exist.

### Steps To Reproduce

Go to line 239626 in ja.po translation file. Witness the error.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/60388907/19409fda-995c-4c02-a660-03477afb691d)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/60388907/9b2a3a96-b9eb-43d8-9b81-d261a9999327)

### Versions and configuration

- OS: Windows
    - OS Version: 11
- Game Version: 1043c57b7e [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges]
]

**Comment by scarf005** [comment]
i think this needs to be fixed on transifex.

**Comment by olanti-p** [comment]
Fixed it on Transifex, should be in game after next sheduled translation update.
