### ISSUE TITLE
[E]xamine does not fallback to using lockpicks on locked doors when the player has no prying tool

### ISSUE THREAD

**Issue by Wreckstation** [cataclysmbnteam/Cataclysm-BN#282]
# Describe the bug

Using [E] on a locked door only checks for prying. If you have no prying tool you get "if only you had a prying tool..." despite the lock being able to be lock picked and the player has lockpicks in their inventory.

# Steps To Reproduce

1. Find locked door that can be lockpicked and pried open
2. [E]xamine with no prying tool but with any other kind of lockpick in the inventory

# Expected behavior

Game tries to pick the door's lock instead

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: fb0d380 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    sees-player icon, retrodays [sees_player_retro],
    No Filthy Clothing [no_filthy_clothing],
    No Lifting Reqs [disable_lifting],
    Prevent Zombie Revivication [no_reviving_zombies],
    Arcana and Magic Items [Arcana],
    Mythical Martial Arts [MMA],
    Manual Bionic Installation [manualbionicinstall]
]

**Comment by olanti-p** [comment]
Same goes for fingerpick bionic

**Comment by Drugitechnik** [comment]
Reproducable as of today.
