### ISSUE TITLE
Difficult to ascertain vending machine prices on a small screen

### ISSUE THREAD

**Issue by FickDiddler** [cataclysmbnteam/Cataclysm-BN#2820]
### Describe the bug

On a mobile screen, the prices are not always visible, due to the prices being listed at the very bottom of the description page.

### Steps To Reproduce

1. Open up CBN on Android.
2. Check the vending machines.

### Screenshots

![vend](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/132725333/42fcf42c-450b-400d-8bd5-0e3b4c0cf52d)

### Versions and configuration

Android x32 Latest Version

**Comment by scarf005** [comment]
we could change the topmost display from
`Money left: ${MONEY}`
to
`Money left: ${MONEY} - ${COST} = ${MONEY_LEFT}`

**Comment by FickDiddler** [comment]
> we could change the topmost display from `Money left: ${MONEY}` to `Money left: ${MONEY} - ${COST} = ${MONEY_LEFT}`

Apparently in older versions of CDDA, the price was listed next to the item on the desc page.
https://user-images.githubusercontent.com/11132525/35749045-4672364a-0861-11e8-9e0a-5380ed403239.png
