### ISSUE TITLE
MAIN MENU in different layout

### ISSUE THREAD

**Issue by FickDiddler** [cataclysmbnteam/Cataclysm-BN#2821]
### Describe the bug

Not sure if it's my fault, but for some reason all the MAIN MENU things are scrambled. The Options menu used to be second to the top, but now it is in the middle, and the debug menu is second to bottom, when it was originally just bottom.

### Steps To Reproduce

1. Open up CBN on android.
2. Check out MAIN MENU by double tapping screen.

### Screenshots

![menu](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/132725333/930ed31b-33b5-45da-b053-fbb512115970)

### Versions and configuration

Latest Android x32

**Comment by scarf005** [comment]
regression caused by #2672

**Comment by FickDiddler** [comment]
Is there anyway to turn it back? Maybe a fresh install? Thanks for such a quick response!

**Comment by scarf005** [comment]
you could try builds older than 05-10 as this PR appears starting from build 05-11
https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2023-05-10-2304

**Comment by scarf005** [comment]
it needs to be kept open as the UI issue is unresolved
