### ISSUE TITLE
Autodoc cannot localize anesthetic

### ISSUE THREAD

**Issue by Xindage** [cataclysmbnteam/Cataclysm-BN#2852]
### Describe the bug

I took some anesthetic with me to remove some faulty bionic at the hospital, but it cannot locate the anesthetic to start the operation

### Steps To Reproduce

1. Have an autodoc.
2. Have anesthetic.
3. Cant operate both to remove or install (same on npcs)

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/6380147/21bdc92e-9f52-4399-8ae1-41bc324deef6)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/6380147/02337c17-1ee9-4ae3-a70c-318efddeba51)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: f773ca0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Aftershock [aftershock],
    Generic Guns [generic_guns]
]

### Additional context

I decided to upload my save as example.
[Nickelsville.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/11523372/Nickelsville.zip)

**Comment by Xindage** [comment]
it requires anesthetic kit but the interface wont show me this.

**Comment by chaosvolt** [comment]
Seems like it'd be reasonable to tweak the UI to refer to that, ye.
