### ISSUE TITLE
Less spawn rate

### ISSUE THREAD

**Issue by waveyl** [cataclysmbnteam/Cataclysm-BN#287]
# Is your feature request related to a problem? Please describe.
I can get most things easily. For example, library alwaws spawn all books, Military base always spawn all tools and guns, turret always drop thousands of bullet,  can't use up. This spawn way is lack of surprise, and the collection progress is too short.
# Describe the solution you'd like
Less spawn rate.

**Comment by Firestorm01X2** [comment]
> turret always drop thousands of bullet

It was dealt already.

I suppose, other parts has to be done manually via spawn editing.
