### ISSUE TITLE
Wasps attacking from different z-level

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#2890]
### Describe the bug

With 3d vision OFF walking on a clearing when suddenly getting attacked from unseen assailant. 
Couldn't retaliate and attacker was very fast and nearly killed my character.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/72284934/ed044fba-df55-4444-89aa-3092d13ce980)
Found out that it was a wasp when climbing on roof.
Wasps shouldn't be able to attack through z-levels when 3d vision is off.

### Steps To Reproduce

1. Turn 3d vision off.
2. Make a new character, reveal the map, find a wasp nest on second z-level of the map
3. Teleport on the ground level at the location of the wasp nest
4. Wait until they attack you.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f2e61a7 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Cataclysm++ [Cata++],
    Prevent Zombie Revivication [no_reviving_zombies],
    XL clothing [XL_clothing]
]

**Comment by Krwak** [comment]
Edited how to reproduce the problem. Have to teleport to a wasp nest.
Wasp nests used to spawn on ground level but now they seem to spawn on second z-level only and maybe this is why the problem appeared now.

**Comment by chaosvolt** [comment]
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3295 should now fix this.
