### ISSUE TITLE
Using a construction zone to remove grass over shrubs creates fence posts

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#2904]
### Describe the bug

If you use a construction zone to remove grass, and the zone lands on shrubs, those shrubs will turn into fence posts. If done over moss, then they build crafting spots.

### Steps To Reproduce

1. Start a construction zone of remove grass over grass, then drag it over shrubs and possibly moss.
2. Use Zone activities to start the construction, and watch as they turn into something they shouldn't.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/2258898d-6d42-485f-b893-5676fdb39add)

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Professional for Workstations build 19045
- Game Version: 5b815d9 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Lones Soda mod [coke_flavors],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    Chorus's Gear [Chorus_Weapons],
    Chorus's CBMs [Chorus CBMs],
    Chorus's Martial Arts [Chorus_MA],
    Chorus's Primitive Living [Chorus Primitive],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food]
]

### Additional context

I haven't tested this on other invalid constructions to see if there's a limit or a method to this madness, but its possible any invalid construction will make the wrong thing.

**Comment by OrenAudeles** [comment]
Confirmed on 2bc98a87d5 very weird
- Before `remove grass` construction zone application
![Screenshot from 2023-10-10 03-58-33](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/8597997/5ce0cf68-b67b-4241-bb85-541a2d2f53b3)
- After `remove grass` construction zone application
![Screenshot from 2023-10-10 03-56-50](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/8597997/0a7ef72c-d773-402f-98db-ab7ecde06729)

Builds wire fence if character if tools/ingredients available
Builds wooden post if character is tools/ingredients available

If tools/ingredients are not available will not attempt to do more than remove grass and tag firewood spots
