### ISSUE TITLE
Craft with UPS conversion tools 

### ISSUE THREAD

**Issue by Troll-Miki** [cataclysmbnteam/Cataclysm-BN#297]
# Describe the bug

Tools do not work with bionic energy in the crafting menu

# Steps To Reproduce

1. Take character with bionic power and CBM: Internal Unified Power System. 
2. Toggle on CBM.
3. Instal "UPS conversion mod" in gunsmith repair kit
4. Try for craft weapon mod with kit 

# Expected behavior

I wanna use my bionic power for craft.

P.S. If CBM ON you will consume bionic power, but you need charged UPS for start craft

# Screenshots

Craft with kit and 250 bio energy
![image](https://user-images.githubusercontent.com/76564476/103161210-1f76a080-4800-11eb-95fc-b98a30847419.png)

Craft with kit and UPS
![image](https://user-images.githubusercontent.com/76564476/103161275-14704000-4801-11eb-961d-96672f9faffc.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: b2eece3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by Coolthulhu** [comment]
Should be fixed in a5ae6e58ef15d5610646098c1ac0821fb27774c8
