### ISSUE TITLE
AoE cone ammo spreads damage across all bodyparts when used on players and NPCs, rendering them ineffective

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#2989]
### Describe the bug

Per Coolthulhu's request, split https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2791 into two separate issues.

In a nutshell, while the visual display mentioned is being worked on at present, the bigger issue balance-wise is that AoE attacks from ammo divide total damage up across all body parts. This works fine when used against monsters, since code-wise they only count as having a single body part, but against characters it breaks down.

Even when used at point-blank range, where the AoE cone shows the effect as only a single tile wide, it divides up the damage so that every valid part takes scratch damage.

### Steps To Reproduce

1. Shoot an NPC point-blank in the face with birdshot.
2. Observe they took a tiny amount of damage across all bodyparts, instead of taking a modest amount of damage to the torso or head.

### Screenshots

Damage spread out across all parts:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/be0d9118-e5ff-4d78-a8b5-d35fd0cf214d)

NPC utterly unamused by buckshot:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/75fde831-6e25-48e9-a44d-ee8ee73078e0)

A second test where I gave it the absolute best odds possible via blasting a bare-ass naked NPC from 1 tile away with all-10 skills, and they still laughed it off:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/fe7dc51f-b9c1-4524-bbaa-dae1c83e3d4e)

These were with buckshot back before the revert PR, results with birdshot will involve less damage overall.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 690f4a4e261 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges]
]

### Additional context

There are a few ways to fix them, but I feel like probably the sanest way is going to require some function to make it so that it determines how many bodyparts are actually hit in some way, likely a mix of aim skill and/or distance to target, with the goal of concentrating it on only one bodypart if you're close enough that the AoE is only a single tile wide at that distance.

**Comment by Coolthulhu** [comment]
Well, it's birdshot. Somewhat low damage is expected.
The "hit all body parts" thing is intended, though it's up to be designed how exactly is the damage spread across them:
* Have per body part "area vs AoE hits", divide damage proportionally
* Hit all body parts for stated damage, making it only effective vs humans and not monsters
* Hit monsters 6 times, to simulate all body parts, making it wreck monsters while still being as weak vs humans
* Proportional with some RNG variation per shot

Point blank not being stronger is intended. It's AoE.
If point blank shotgun blasts are desired, I'd rather have it deal more damage, but then halve it after some distance.

**Comment by chaosvolt** [comment]
> Have per body part "area vs AoE hits", divide damage proportionally

This seems like it could be the mostr reasonable way to do that, as it'd at least front-load more of the damage.

That said I feel like it'd be way saner for it to hit less bodyparts if the shot cone is currently narrow enough to only hit a single monster, possibly alongside either damage falloff at range or with a damage reduction if it passed through monsters previously.

AoE shotshells being able to pass through monsters that take zero damage from it when rifle rounds overpenetrate is also a bit...weird, not like it being unrealistic matters but it does also feel inconsistent. Not the first game to do that admittedly, DoomRL does AoE cones with falloff for shotguns while regular bullets are single projectiles with no overpenetration, and Killing Floor has buckshot that overpenetrates more with the support specialist class (while sharpshooters with big rifle rounds only get overpenetration with crossbows and the AMR).

Also worth noting that this also hinders extending this feature to flamethrowers, because the base damage is so low there that it'll probably shave damage per part down to zero in the end. Though https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2756 and https://github.com/cataclysmbnteam/Cataclysm-BN/issues/2793 are likely bigger blockers to flamethrowers using this, since leaving fire on the ground is where they get their actual damage, plus their handling of different ranges is almost entirely reliant on it being at the weapon level.
