### ISSUE TITLE
Electric grid soldering iron recepie bug

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#3004]
### Describe the bug

Electric grid soldering iron require 3 soldering irons (2 empty and one charged).

### Steps To Reproduce

1) Craft electric grid soldering iron
2) Prepare 2 soldering irons. One empty, one charged
3) Observe, that installation is not possible
4) Prepeare 3 soldering irons (2 empty and one charged). Observe that now installation is possible

### Screenshots

![изображение](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/17512620/29a12571-981f-4a6d-9f9b-fe13eaa6b194)

### Versions and configuration

-

### Additional context

![изображение](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/17512620/75a8540f-0fbe-4f31-9965-5d1f9ba5820b)

Needs confirmation

**Comment by Krwak** [comment]
This one is rather old #2002

**Comment by Firestorm01X2** [comment]
I've edited bug description.
Required 3 soldering irons (1 full and 2 empty) for craft to work.

**Comment by AlecWhite** [comment]
I've track down this problem and it seems to happen in
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/4becfee40c36b83be79d1d9d4c52161c832ade42/src/requirements.cpp#L897-L900

No idea how to solve it without rewriting a bunch of stuff.
