### ISSUE TITLE
when I trade with NPC, the game crash down.

### ISSUE THREAD

**Issue by xibaibai9527** [cataclysmbnteam/Cataclysm-BN#3014]
### Describe the bug

when I trade with NPC, the game crash down.

### Steps To Reproduce

-

### Versions and configuration

cbn-2023-07-09-0737

### Additional context

[config.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/12042578/config.zip)

![2023-07-14_00001](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/19858971/fa3ebdf1-e1aa-40dc-9ac8-f0a44ff41b15)

**Comment by olanti-p** [comment]
Could you upload the save? Looks like the game crashes when NPC tries to evaluate price of some ranged weapon inside vehicle storage, so this may be specific to some item.

**Comment by scarf005** [comment]
related: #3315
