### ISSUE TITLE
[Mods] Food recipes with all ingredients lacking calories creates calorie-less food

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3025]
### Describe the bug

This is purely a mod issue, but having a recipe that calls for a list of ingredients that all lack calories, the resulting food item will have 0 calories instead of defaulting to their defined calories. There isn't any method to either flag the recipe to use the default calorie value and ignore ingredients, or any protection to ensure a resulting food item has calories.

Having an option in the recipe to ignore input and make the default item would be ideal, otherwise adding a code check to the recipe function to ensure if calories is 0 then it uses default.

This is what I get for making a magic recipe to turn dirt and mana into food.

### Steps To Reproduce

1. Use a modded recipe to turn dirt to food.
2. Your carrots have the same calories as the air. See screenshot.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/1b189357-a7ee-4556-b284-d33aef9df2e7)

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Pro for Workstations
- Game Version: 1479a17 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Lones Soda mod [coke_flavors],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    Chorus's Gear [Chorus_Weapons],
    Chorus's CBMs [Chorus CBMs],
    Chorus's Martial Arts [Chorus_MA],
    Chorus's Primitive Living [Chorus Primitive],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food]
]

### Additional context

I don't see the need to test this on the latest version because I don't see anyone even knowing about a mod problem this obscure and random. I created an issue nobody thought was possible.

**Comment by olanti-p** [comment]
Have you tried adding `NUTRIENT_OVERRIDE` flag to the resulting item?

**Comment by chaosvolt** [comment]
That would work but they'd need to add custom food items instead of trying to produce vanilla items using modded recipes.

**Comment by RoyalFox2140** [comment]
> That would work but they'd need to add custom food items instead of trying to produce vanilla items using modded recipes.

Or I would need to destructively add nutrient override to every vanilla food item in the game which would cause potential unforeseen consequences.

**Comment by scarf005** [comment]
> Use a modded recipe to turn dirt to food

could you share JSON recipe to to this?

**Comment by RoyalFox2140** [comment]
If you're talking strictly from my mod, then any food recipe that takes transmutation runes were broken until I gave them calories. https://github.com/RoyalFox2140/Essence2200/blob/52b250adac9a46a74f4655ec099666531e3b9de5/Essence2200/Recipes/recipes%20transmutation.json#L663

If you want one to plug into the game though, add this to any recipe json. You can make carrots from rocks now.

  {
    "type": "recipe",
    "result": "carrot",
    "id_suffix": "WithRocks",
    "category": "CC_FOOD",
    "subcategory": "CSC_FOOD_VEGGI",
    "skill_used": "cooking",
    "difficulty": 0,
    "time": "1 s",
    "result_mult": 10,
    "batch_time_factors": [ 80, 2 ],
    "autolearn": true,
    "components": [ [ [ "rock", 2 ] ] ]
  }

**Comment by scarf005** [comment]
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/b0c51772-bf4b-4297-ad86-aa2f1a0ee987)

As predicted, game always calculates nutrients from components unless item has `NUTRIENT_OVERRIDE` flag.
