### ISSUE TITLE
OSX Tiles doesn't open on Mac

### ISSUE THREAD

**Issue by Bosarosa** [cataclysmbnteam/Cataclysm-BN#3032]
### Describe the bug

The installation works, I can drag and drop the game to the applications folder and give the application permission to open but opening it does nothing. Am I missing something? CDDA works fine for Mac but the gameplay is loaded with micromanagement compared to CBN.

### Steps To Reproduce

1. Install the latest osx tiles for MacOS (curses works fine for osx, tiles doesn't.)
2. Drag and drop the app to applications folder
3. Allow cataclysm to open for your Mac
4. Attempt to open directly from your applications folder

### Versions and configuration

Up-to-date Mac 
Any tiles version of CBN

**Comment by scarf005** [comment]
Could you try opening the application from CLI (e.g iterm2)?
```sh
./cataclysm-launcher
```
The error messages would help. It might be that the game misses some runtime dependencies.

**Comment by Bosarosa** [comment]
Tried opening /cataclysm-tiles using the terminal. I'm not sure what I'm doing so apologies if this is not what you're looking for.

/Applications/Cataclysm.app/Contents/Resources/cataclysm-tiles
  Reason: tried: '/Applications/Cataclysm.app/Contents/Resources/libogg.0.dylib' (no such file), '/usr/local/lib/libogg.0.dylib' (no such file), '/usr/lib/libogg.0.dylib' (no such file, not in dyld cache)
zsh: abort      /Applications/Cataclysm.app/Contents/Resources/cataclysm-tiles

**Comment by scarf005** [comment]
thanks for the log. looks like `libogg` dynamic library dependency is missing, could you try installing it?

**Comment by Bosarosa** [comment]
I installed it using homebrew but that doesn't put it in the correct directory unless I can also download CBN using homebrew, it may be a lot for me to ask but do you know of a way to do that? This websites compiling instructions doesn't provide a link to CBN's homebrew download, only CDDA, homebrew also does not provide instructions to install CBN. Otherwise, a more coherent way of downloading  libogg is required and I'm unable to find a solution. Thanks for your help so far.

**Comment by Bosarosa** [comment]
Got it working using homebrews installation of wine.
