### ISSUE TITLE
Bring back the pocket system

### ISSUE THREAD

**Issue by sasichkamega** [cataclysmbnteam/Cataclysm-BN#305]
Because it's cool! You can throw off your backpack before the fight, it's cool! You can put magazines in tactical unloading, speeding up reloading, it's cool! The pocket system is too cool to be removed!

**Comment by Coolthulhu** [comment]
BN was forked before pockets system and will not include explicit pockets.
There may be a backpack drop feature in the future, but it will not use pockets.

**Comment by grigoriynikolaev** [comment]
> BN was forked before pockets system and will not include explicit pockets.
> There may be a backpack drop feature in the future, but it will not use pockets.

Thank go... I mean, Coolthulhu!
