### ISSUE TITLE
Wasps attacking directly from above even without 3d vision

### ISSUE THREAD

**Issue by RodriguesCIA** [cataclysmbnteam/Cataclysm-BN#3052]
### Describe the bug

What says on the tin, if wasps are flying on the Z level above, there's the chance they will start stinging your character that will not even know where the attacks are comming from, with no escape but climbing to kill the wasps or getting a roof over your head.

### Steps To Reproduce

Get a wasp over your character head. I think it must be literally on top of the character, because it is not as common as wasps themselves. I presume the character ended up walking below a flying a wasp, causing the attacks.

### Versions and configuration

Latest experimental + PR

**Comment by Krwak** [comment]
duplicate #2890

**Comment by scarf005** [comment]
also closing in favor of #2890, thank you @RodriguesCIA for the bug report nonetheless. also @Krwak, big thanks for managing duplicate issues.
