### ISSUE TITLE
I can make a website for the game

### ISSUE THREAD

**Issue by RodrigoWebDev** [cataclysmbnteam/Cataclysm-BN#3062]
### Is your feature request related to a problem? Please describe.

Hi, I'm a web developer and I can make a website for Cataclysm Bright Nights, with easy navigation, download button, links for things like donation and with easy maintenance using markdown(no need for database or back-end code), then it just need to be hosted in a service like Netlify or Surge for free

I really love this game, and I want it to reach more people, and one step is a cool website with an easy way to download, images, trailer and informations on how to contribute

### Describe the solution you'd like

Create a website

**Comment by scarf005** [comment]
there were ideas for making an website (#12 #1702) but they never got traction. having an official page would be great!

**Comment by Firestorm01X2** [comment]
Feel free to ask any question  in BN discord:
https://discord.gg/XW7XhXuZ89

We've can provide you with logos and pictures as well.

**Comment by RodrigoWebDev** [comment]
@Firestorm01X2 @scarf005 Can I create a repository for the site with my account? I can give you all with permissions to write, or do you have another idea on how to start?

**Comment by scarf005** [comment]
Of course, tho it might be a good idea to state that the page is unofficial.

**Comment by Firestorm01X2** [comment]
> @Firestorm01X2 @scarf005 Can I create a repository for the site with my account? I can give you all with permissions to write, or do you have another idea on how to start?

It is better to develop site as you see fit since currently do not have exact requirements. 
Permissions will be good because we can help you with something or edit something if you are busy.



> the page is unofficial.

I think we can make it official with no problems. It easily discussable.

**Comment by Firestorm01X2** [comment]
@Coolthulhu pinging.

**Comment by Coolthulhu** [comment]
Would be great!

You mean "make" as in "set up" or "create in a deployable state, but without actual deployment"? You probably have more experience with free services than I do, but I believe we could do the deployment on our own, if needed.

I love the idea of using markdown, should make it easy to repost the contents of our github wiki.

**Comment by RodrigoWebDev** [comment]
Great! I will do it in my free time and share with you all here

**Comment by scarf005** [comment]
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/af9a4b26-2d0a-4952-a40f-e9b9374f2643)

would it be okay if i do the documentation part first? i've been experimenting [with starlight] (https://starlight.astro.build) recently and it'll be finished in next few days.

**Comment by scarf005** [comment]
Hi, thanks for the interest in creating an website for the game. however, the issue's gone stale and we've already opened <https://docs.cataclysmbn.org>, thus we'll close the issue for not planned. please let us know if it should be reopened.
