### ISSUE TITLE
Legacy, unnecessary and spaghetti code.

### ISSUE THREAD

**Issue by DraculaRus** [cataclysmbnteam/Cataclysm-BN#31]
Game repository contains questionable files and directories. I am not-professional-at-all programmer and i highly doubt about it, but some things make me suspicions: 
https://github.com/cataclysmbnteam/Cataclysm-BN/tree/upload/utilities/building-utility Is this still being used?
https://github.com/cataclysmbnteam/Cataclysm-BN/tree/upload/CMakeModules I never used such frameworks, so i don't know, but shouldn't it be on local machine only?
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/lgtm/cpp-queries/c-style-math-functions.ql I have no idea what is it. Probably that's a problem itself.
https://github.com/cataclysmbnteam/Cataclysm-BN/tree/upload/doxygen_doc text files, separate folder. One of files ".h"
I also suspicions about high amount of python files. As it's interpretable, and i wonder how it works and what does it do.
It's may look not important, but the more it simple, the more people will may contribute to the project.

**Comment by Coolthulhu** [comment]
> https://github.com/cataclysmbnteam/Cataclysm-BN/tree/upload/utilities/building-utility

It's probably fine to delete this one, I'll look into it.

> https://github.com/cataclysmbnteam/Cataclysm-BN/tree/upload/CMakeModules

I'll check, but from the looks of it, it should be in the repo. The modules are for specific libraries that aren't always easy to find by the framework.

> https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/lgtm/cpp-queries/c-style-math-functions.ql

It's a script for a code tidiness check, specifically checking if the code uses C++ math functions and not the ones ported from C. I have this check enabled in the build system, so it's still useful.

> https://github.com/cataclysmbnteam/Cataclysm-BN/tree/upload/doxygen_doc

That's for building the docs that automatically describe things like benefits of high stat, effects of skill and so on.

I am not using it right now, but would like to set it up some day.

> I also suspicions about high amount of python files. As it's interpretable, and i wonder how it works and what does it do.

In general, `tools` directory is not something a regular contributor would be concerned with.

It's for maintenance of the project: cleaning up the jsons, generating changelog details from commit messages, cleaning up sources to ensure fast compilation. Most of those files are only executed manually, when needed.

The only tool that is executed automatically is in `tools/format`: it styles jsons.

**Comment by Coolthulhu** [comment]
I don't see this resulting in any changes soon. Cleanup would be nice, but there is nothing obvious to be done here.
