### ISSUE TITLE
Hyper-Metabolism doesn't do anything

### ISSUE THREAD

**Issue by DireLemming** [cataclysmbnteam/Cataclysm-BN#312]
Characters with hyper-metabolism currently become full and throw up the same as a character without the mutation when overeating. Enabling the mutation doesn't prevent this either.

# Steps To Reproduce

1, Make a character with Chimera threshold and Hyper-Metabolism
2. Eat until full
3. You'll get the normal overeating message and become full/vomit if you continue eating.

# Expected behavior

Hyper-Metabolism is meant to prevent vomiting from overeating and convert the excess nutrition into healing.

# Screenshots

# Versions and configuration

- OS: Windows 7
- Game Version: b2eece3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Comment by olanti-p** [comment]
Should be fixed by #1292
