### ISSUE TITLE
Submit a bug report on Github debug button fails to generate report

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3128]
### Describe the bug

When pressing the debug option to open github to file a report, it correctly opens the window but then reports that it fails, and doesn't fill out the report details, it adds OS version game version and then fails.

I have no idea if this happens without mods, but I can investigate that too if needed.

### Steps To Reproduce

1. Use my my mod list and game version.
2. Activate the function.
3. It fails.

### Versions and configuration

- OS: Windows
    - OS Version: Win 10 Pro for Workstations 64 bit build 19045
- Game Version: e01f656 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Urban Development [Urban_Development],
    Project: Pack Rat [Jake's_Squirrel_mod]
]

### Additional context

 DEBUG    : Failed to open URL: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/new?labels=bug&template=bug_report.yml&versions-and-configuration=-%20OS%3A%20Windows%0A%20%20%20%20-%20OS%20Version%3A%2010.0%202009%0A-%20Game%20Version%3A%20e01f656%20%5B64-bit%5D%0A-%20Graphics%20Version%3A%20Tiles%0A-%20Game%20Language%3A%20English%20%5Ben_US%5D%0A-%20Mods%20loaded%3A%20%5B%0A%20%20%20%20Bright%20Nights%20%5Bbn%5D%2C%0A%20%20%20%20Elevated%20bridges%20%5Belevated_bridges%5D%2C%0A%20%20%20%20Craftable%20Gun%20Pack%20%5Bcraftgp%5D%2C%0A%20%20%20%20Alternative%20Map%20Key%20%5Balt_map_key%5D%2C%0A%20%20%20%20Fuji%27s%20Military%20Profession%20Pack%20%5Bfuji_mpp%5D%2C%0A%20%20%20%20Arcana%20and%20Magic%20Items%20%5BArcana%5D%2C%0A%20%20%20%20Craftable%20Bullet%20Casings%20%5BCasingCrafting%5D%2C%0A%20%20%20%20MST%20Extra%20%5BMST_Extra%5D%2C%0A%20%20%20%20Tankmod%3A%20Revived%20%5BTankmod_Revived%5D%2C%0A%20%20%20%20Essence%202200%20%5BEssence2200%5D%2C%0A%20%20%20%20Essence%202200%20Tweaks%20%5BFoxTweaks%5D%2C%0A%20%20%20%20Nonperishable%20Overhaul%20%5BNonperishable_Overhaul%5D%2C%0A%20%20%20%20No%20Addictions%20%5BNo_Addictions%5D%2C%0A%20%20%20%20Limit%20Fungal%20Growth%20%5Blimit_fungal_growth%5D%2C%0A%20%20%20%20Disable%20NPC%20Needs%20%5Bno_npc_food%5D%2C%0A%20%20%20%20Urban%20Development%20%5BUrban_Development%5D%2C%0A%20%20%20%20Project%3A%20Pack%20Rat%20%5BJake%27s_Squirrel_mod%5D%0A%5D%0A
Attemped command was: explorer "https://github.com/cataclysmbnteam/Cataclysm-BN/issues/new?labels=bug&template=bug_report.yml&versions-and-configuration=-%20OS%3A%20Windows%0A%20%20%20%20-%20OS%20Version%3A%2010.0%202009%0A-%20Game%20Version%3A%20e01f656%20%5B64-bit%5D%0A-%20Graphics%20Version%3A%20Tiles%0A-%20Game%20Language%3A%20English%20%5Ben_US%5D%0A-%20Mods%20loaded%3A%20%5B%0A%20%20%20%20Bright%20Nights%20%5Bbn%5D%2C%0A%20%20%20%20Elevated%20bridges%20%5Belevated_bridges%5D%2C%0A%20%20%20%20Craftable%20Gun%20Pack%20%5Bcraftgp%5D%2C%0A%20%20%20%20Alternative%20Map%20Key%20%5Balt_map_key%5D%2C%0A%20%20%20%20Fuji%27s%20Military%20Profession%20Pack%20%5Bfuji_mpp%5D%2C%0A%20%20%20%20Arcana%20and%20Magic%20Items%20%5BArcana%5D%2C%0A%20%20%20%20Craftable%20Bullet%20Casings%20%5BCasingCrafting%5D%2C%0A%20%20%20%20MST%20Extra%20%5BMST_Extra%5D%2C%0A%20%20%20%20Tankmod%3A%20Revived%20%5BTankmod_Revived%5D%2C%0A%20%20%20%20Essence%202200%20%5BEssence2200%5D%2C%0A%20%20%20%20Essence%202200%20Tweaks%20%5BFoxTweaks%5D%2C%0A%20%20%20%20Nonperishable%20Overhaul%20%5BNonperishable_Overhaul%5D%2C%0A%20%20%20%20No%20Addictions%20%5BNo_Addictions%5D%2C%0A%20%20%20%20Limit%20Fungal%20Growth%20%5Blimit_fungal_growth%5D%2C%0A%20%20%20%20Disable%20NPC%20Needs%20%5Bno_npc_food%5D%2C%0A%20%20%20%20Urban%20Development%20%5BUrban_Development%5D%2C%0A%20%20%20%20Project%3A%20Pack%20Rat%20%5BJake%27s_Squirrel_mod%5D%0A%5D%0A"

 FUNCTION : open_url
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\url_utility.cpp
 LINE     : 26
 VERSION  : BN e01f656

**Comment by scarf005** [comment]
could you create a new world with default set of mods, then try to generate report? I have a grim feeling that the URL is too long to be processed...

**Comment by RoyalFox2140** [comment]
> could you create a new world with default set of mods, then try to generate report? I have a grim feeling that the URL is too long to be processed...

 DEBUG    : Failed to open URL: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/new?labels=bug&template=bug_report.yml&versions-and-configuration=-%20OS%3A%20Windows%0A%20%20%20%20-%20OS%20Version%3A%2010.0%202009%0A-%20Game%20Version%3A%20e01f656%20%5B64-bit%5D%0A-%20Graphics%20Version%3A%20Tiles%0A-%20Game%20Language%3A%20English%20%5Ben_US%5D%0A-%20Mods%20loaded%3A%20%5B%0A%20%20%20%20Bright%20Nights%20%5Bbn%5D%0A%5D%0A
Attemped command was: explorer "https://github.com/cataclysmbnteam/Cataclysm-BN/issues/new?labels=bug&template=bug_report.yml&versions-and-configuration=-%20OS%3A%20Windows%0A%20%20%20%20-%20OS%20Version%3A%2010.0%202009%0A-%20Game%20Version%3A%20e01f656%20%5B64-bit%5D%0A-%20Graphics%20Version%3A%20Tiles%0A-%20Game%20Language%3A%20English%20%5Ben_US%5D%0A-%20Mods%20loaded%3A%20%5B%0A%20%20%20%20Bright%20Nights%20%5Bbn%5D%0A%5D%0A"

 FUNCTION : open_url
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\url_utility.cpp
 LINE     : 26
 VERSION  : BN e01f656

Only BN was loaded.

**Comment by scarf005** [comment]
i see.
1. do you use 32-bit Windows?
2. could you open `CMD.exe` on your windows then type this command to check if this correctly opens?
```
start "" "https://github.com/cataclysmbnteam/Cataclysm-BN/issues/new?labels=bug&template=bug_report.yml&versions-and-configuration=-%20OS%3A%20Windows%0A%20%20%20%20-%20OS%20Version%3A%2010.0%202009%0A-%20Game%20Version%3A%20e01f656%20%5B64-bit%5D%0A-%20Graphics%20Version%3A%20Tiles%0A-%20Game%20Language%3A%20English%20%5Ben_US%5D%0A-%20Mods%20loaded%3A%20%5B%0A%20%20%20%20Bright%20Nights%20%5Bbn%5D%0A%5D%0A"
```

**Comment by RoyalFox2140** [comment]
I am on Windows 10 Pro, 64 bit. the version is in the report. This command correctly triggers in CMD without even running it as administrator mode.

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/9b239383-5afa-4e45-b3ed-d547d8bd2f8e)

**Comment by scarf005** [comment]
alright. my guess is in c++ WIN32 and WIN64 is both defined for windows, and we check 32bit one first, so regardless 32bit or 64bit it always resolves to 32bit first
