### ISSUE TITLE
Vestigial code oddities

### ISSUE THREAD

**Issue by YakumoChen** [cataclysmbnteam/Cataclysm-BN#318]
# Describe the bug
Some unfinished stuff still exists from the main repository at the time of forking

By no means a comprehensive list and I'll probably add more later

~~-heat packs do nothing and have no use, cant be used for basic cooking or disassembled~~
-various foods that taste different when not default temperature like ice cream have no way to modify
-the first few PRs of cloth sheet tailoring have not been reverted (tailor basements and some arm clothing recipes)
-several defunct recipes requiring "cutting 2" when no clear items exist with that quality (notably survivor helmets have no alternative to craft)

**Comment by olanti-p** [comment]
To add to the list:
* migrating activities to `activity_actor` https://github.com/CleverRaven/Cataclysm-DDA/issues/40013 (long-term and C++)
* The body part migration https://github.com/CleverRaven/Cataclysm-DDA/pull/39068 (big and C++)
* Mall cleanup https://github.com/CleverRaven/Cataclysm-DDA/pull/40102, https://github.com/CleverRaven/Cataclysm-DDA/pull/40391 (json, should be easy)
* `ui_adaptor` migration (the only one remaining is `target_ui`, which is buggy and needs a refactor anyway)
* `player` -> `Character` migration (in BN it's [Move NPC and Avatar classes into components of Player class](https://github.com/cataclysmbnteam/Cataclysm-BN/projects/2#card-42078631))
* modernizing measurement units in json https://github.com/CleverRaven/Cataclysm-DDA/issues/36110

**Comment by Firestorm01X2** [comment]
About malls.
![malls](https://user-images.githubusercontent.com/17512620/104580902-e5662500-566e-11eb-9054-2c37649aea54.jpg)

Looks malls needed extra things

**Comment by YakumoChen** [comment]
Arm armor recipes in general seem to have inflated times comparably even if they don't directly use the cloth sheet crafting. Plate vambraces for example have a 15 hour forge time, dissimilar to greaves which have a 3 hour forging.

**Comment by Coolthulhu** [comment]
I plan to take on the body part migration system after I'm satisfied with #322.
I tried to port it once, but it's huge and I ran into million conflicts. It will take some time.

**Comment by olanti-p** [comment]
> heat packs do nothing and have no use, cant be used for basic cooking or disassembled

Solved by #372

> various foods that taste different when not default temperature like ice cream have no way to modify

Seems to have been cleaned up in #2607, ice cream and such should no longer depend on coldness for morale

> the first few PRs of cloth sheet tailoring have not been reverted (tailor basements and some arm clothing recipes)

Cleaned up in #810 and #859

> several defunct recipes requiring "cutting 2" when no clear items exist with that quality (notably survivor helmets have no alternative to craft)

"Cutting 2" is the toolset bionic, but you're right as that was not clearly communicated. However, I'm searching the recipes right now and it looks like all recipes as of 639a0e975d6620ab4037c5541a0ed9151daba46f have been switched to cutting 1, so this is no longer an issue.
