### ISSUE TITLE
NO_BREATHE does not apply poison immunity

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3193]
### Describe the bug

NO_BREATHE was meant to apply poison immunity to zombies according to Magiclysm documentation, but it never worked on our side. We need a new flag for adding poison immunity as none exists. This has been reported on the discord and I'm bringing it over to discuss a solution.

I propose NO_POISON to be added and given to select zombies and monsters, including acid ones, necromancers, any that do poison attacks such as nurses. My reasoning for this is so we can allow enemies who don't breathe to still take poison damage as there will be examples of this come up given enough time. 

One example: It has some form of functioning gas mask or filtration system in its lungs/throat. This can be cyborgs or zombie soldiers. Poison via spell or weapon would still apply reasonable as it penetrates the skin.

### Steps To Reproduce

1. Use any BIO damage spell on a zombie. It will damage them. I have no idea if gases work or not, but maybe this needs investigation as well. Necrotic gaze was used in testing.
2. This is guaranteed to work on any recent game version, it's never worked correctly and I know nobody's touched this yet.

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Pro for Workstations
- Game Version: 24a08bf [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations]
]

**Comment by RobbieNeko** [comment]
For consistency's sake (and the fact that Bio damage isn't *necessarily* poison), I'd suggest BIOPROOF or something similar for the flag.

I definitely agree with the need for a flag, since we already have True as a damage type for any situations that should be unable to be resisted.

**Comment by RobbieNeko** [comment]
Although hmm, now I realize that it sounds like the original author of Magiclysm agreed with the fact that NO_BREATHE shouldn't be what blocks Bio damage in the first place, and he intended on rewriting the damage function to fix that issue, alongside issues of cold damage actually using heat resistance, and heat damage catching things on fire. Yet later he mentions the zombies being immune to it as a part of Necrotic Gaze's balance... curious.

**Comment by RobbieNeko** [comment]
it would certainly be an interesting idea for (most) of the zombies to be immune to Bio damage (or at least resistant to it). T'would be unique, at the very least. After all, we really don't need "True Damage" __*and*__ "Damage that can't be blocked or resisted" (which is the entire gimmick of True damage)
