### ISSUE TITLE
[FEATURE REQUEST] Urban Jungle

### ISSUE THREAD

**Issue by ImportTaste** [cataclysmbnteam/Cataclysm-BN#326]
I feel like CDDA is at its best when you're having to survive in the urban areas. Even when you tweak the numbers to reduce the amount of wilderness by as much as possible (city size maxed, city spacing to 0) you still get some pretty huge chunks of outdoor areas that you can turtle up and play caveman in.

I would really like if there were a setting or an in-repo mod to not generate any of the large outdoor areas whatsoever (with the largest being something like a city park) so that the world you play in is an urban, concrete jungle in every direction.

**Comment by Coolthulhu** [comment]
This would probably require a mod that redefines many overmap specials. Most of them require specific distances from cities.
Some overmap specials are necessary - central lab, for example.

Covering the entire map with an infinite city would probably require a separate overmapgen, sharing only some of the features with the existing one.

**Comment by ImportTaste** [comment]
I figured it was something like that, unfortunately. Will you do it?

**Comment by Coolthulhu** [comment]
It won't happen soon without someone helping, but may happen eventually.
I'd like to upgrade the citygen someday and it might be possible to allow it to become infinite.

**Comment by SzQ1** [comment]
I know it's old but when you set city size to 6 or lower and city spacing 0 the patches of outdoor areas are much smaller, the smaller the city size the smaller the patches.

**Comment by ImportTaste** [comment]
> I know it's old but when you set city size to 6 or lower and city spacing 0 the patches of outdoor areas are much smaller, the smaller the city size the smaller the patches.

It's still nowhere near the cityscape I'd like to play in. There will still be some outdoor areas that are just strategically safer no matter what. Being locked in a city environment would be so much fun.

**Comment by Coolthulhu** [comment]
Planned, but won't happen soon due to work needed to implement.
Closing as stale.
