### ISSUE TITLE
android build failure after inclusion of `std::filesystem`

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#3280]
https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/6320334183/job/17162700684

android build fails since #3270 becaues NDK doesn't support C++17 filesystem

thankfully DDA has a solution to this: https://github.com/CleverRaven/Cataclysm-DDA/pull/64305

**Comment by olanti-p** [comment]
This should have been caught by the Android build check, but it didn't run for some reason
https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/6312551327/job/17138831394?pr=3270
