### ISSUE TITLE
killing npcs bork the game

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#3286]
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/b34ced00-57c3-41b1-ac8c-91451f78a4e9)

_...nice._

_Originally posted by @scarf005 in https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3282#issuecomment-1736718297_
            

caused by #3282, I must've done something terrible to caching logic

**Comment by chaosvolt** [comment]
Suffering. :D
![270869178-5c87d7da-bb5c-4840-ade8-170921a8de5b](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/90f2c763-4f41-4baf-9cff-1c42cd3443b4)
![270869494-4f190831-fb92-4674-bbb6-d3674a764c41](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/ed058d37-c3b6-4173-b754-b64d21c045f5)

**Comment by cbnbugfix2** [comment]
I do not know the codebase, but the changes look good to me.
