### ISSUE TITLE
M202A1 FLASH crashes the game.

### ISSUE THREAD

**Issue by cinornu** [cataclysmbnteam/Cataclysm-BN#3288]
### Describe the bug

When a vehicle is adjacent to player and there is a turret in the field of view, equipping M202A1 FLASH crashes game. I'm attaching the save file because debug.log doesn't have any logs with that error, and crash.log hasn't been created.
The only part of this process where other mods are involved is the numbers for the M74 rockets... maybe.

Additionally, BPG and MoT are my custom mods, I don't think there is anything relevant to this issue, but I can send you the relevant links if you need them.

I don't speak English very well, so I used a translator :(

### Steps To Reproduce

1. Move to a distance where turret is in view.
2. Move (Large? But not a default vehicle) vehicle to a distance adjacent to player.
3. Equip M202A1 FLASH.
4. game crashes (no message, no logs...)

### Screenshots

![DED2](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/55832850/c2b33a7f-f6cf-41b4-99a1-317e84dacb6f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 5f4e2eb [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    밝은 밤 [bn],
    NPC 욕구 제거 [no_npc_food],
    영양수치 단순화 [novitamins],
    철도역 금지 [No_Rail_Stations],
    고가 다리 [elevated_bridges],
    Arcana and Magic Items [Arcana],
    불페큘라의 추가 지형 및 몬스터 [Lowfieldmonster],
    C.R.I.T. 확장팩 [crt_expansion],
    프로젝트: 다람쥐 [Jake's_Squirrel_mod],
    DIY weaponry [DIY_weaponry],
    매직클리즘 [magiclysm],
    anti-fungal gear [anti_fungal_gears],
    AZF의 모드 [AZF],
    Croppable Rice [Rice_Mod_kor],
    Expanded Archery [ExArch],
    Makeshift Items Mod* [makeshift__],
    Pneumatic fun [pneumo_fun],
    날이 너무 더워요  [p_cooler],
    총기 제조 팩 [craftgp],
    Arcana/C.R.I.T. Patchmod [Arcana_Crit_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Mining Mod [Mining_Mod],
    뉴 잉글랜드 지팡이술 [NE_Staff_arts],
    Patch뉴 잉글랜드 지팡이술_Arcana [NE_Staff_arts_arcana],
    Patch뉴 잉글랜드 지팡이술_magiclysm [NE_Staff_arts_magiclysm],
    임시 타일 추가 모드 [desu_cdda_tile_add],
    허브01 지하실 되살리기 모드 [Revive_hub01_basement],
    Blazemod - Vehicle Additions Pack* [blazemod__],
    Overhaul Tileset [Overhaul Tileset],
    도그밋의 인벤토리 [dogmeat_mod],
    총기 리밸런싱 +@ [SF_Weapons],
    폭발 좀비 제거 [No_Explosive_Zombies],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    better cataclysm [better_cataclysm],
    Faster Stamina Regen [stamina_regen_buff],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    가혹한 세상 [Dontstarve],
    해수면 더 많이 낮추기 [piss_river],
    기술 성장 비례 능력 성장 [StatsThroughSkills],
    더 좋은 민첩스탯 [dexbuff],
    더러운 옷 금지 [no_filthy_clothing],
    들어올리기 제한 해제 [disable_lifting],
    민첩할수록 빠르게 [speedydex],
    살해 수 반영 능력 성장  [stats_through_kills],
    온도 디버프 감소 [reducedtempeffect],
    좀비 부활 방지 [no_reviving_zombies],
    진균 성장 제한 [limit_fungal_growth],
    표적 돌연변이 [TaMu_BnKo],
    도시 개발 [Urban_Development],
    지도 기호 수정 [alt_map_key],
    기괴하고도 강력한 장비들 [BPG],
    모드 타일 오버홀 [MOT]
]

### Additional context

[error_debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/12734802/error_debug.log)

No crash.log files!

save file https://www.dropbox.com/scl/fi/vcxn1gstvt53lc3b4jyqg/NONO-ONON.zip?rlkey=x76mu9mq3i4v64vsyktn1nu8m&dl=0

**Comment by scarf005** [comment]
> 필요한 모드가 없어 세이브 파일이 로드 불가한데, `data/mods` 폴더도 통째로 압축해서 올려주시겠어요?
 
Could you also zip your entire `data/mods` directory? Mod requirements are preventing the save from loading.

**Comment by cinornu** [comment]
@scarf005 https://www.dropbox.com/scl/fi/ik9nifluyaoc1i4hmcpzd/report_mods.zip?rlkey=j6wk2zbdg7vmv0q6x8cgq12lp&dl=0

여기 있습니다.

**Comment by scarf005** [comment]
> 감사합니다. 내일 확인해보겠습니다.

 Thank you. I'll check them tomorrow.

**Comment by scarf005** [comment]
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/22ce527b-5b69-4f5f-bd9e-6514647454bb)

> #3293 이슈와 동일한 이유로 튕기는 것 같습니다.

related: #3293
