### ISSUE TITLE
Sheathing knives incorrectly reports raising cutting skill

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3290]
### Describe the bug

Sheathing knives a lot will incorrectly report raising cutting skill in your message log. NOTE I did this in an item with a max of 200 knives. That may or may not affect the Issue and I will link the code here so you can reproduce my item if necessary.

https://github.com/RoyalFox2140/Essence2200/blob/a145196515aedcca9030138a708949450ed81b31/Essence2200/Items/magic.json#L313

### Steps To Reproduce

1. Get knife sheath.
2. Create a macro. to sheath a knife I ensured the sheath was my top interact for items worn and used: a, right arrow, and 3 enters
3. Optional: If using a normal knife sheath create a macro to unsheath and then resheath the blade in your hand.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/b30af29e-a038-490f-a3c2-6cf1e8c60504)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/5f02b4bb-2755-4bb6-9407-330f4079627f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 24a08bf [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Battle Maid Redux [battle_maid],
    No Acid Zombies [No_Acid_Zombies],
    C.R.I.T. Expansion [crt_expansion]
]

### Additional context

I find a new obscure edge case problem every time I do something stupid with my mod.

**Comment by RoyalFox2140** [comment]
After testing I believe it happened because I was using a macro to sheath about 7 knives per second for an extended period of time.

**Comment by RoyalFox2140** [comment]
https://discord.com/channels/830879262763909202/830916329053487124/1156432131246018603 Thid was the character in question. With no relics or artifacts, it was a fresh test run of knife sheathing

**Comment by chaosvolt** [comment]
Weird, not sure what the cause could be code-wise then.

**Comment by RoyalFox2140** [comment]
I haven't messed with using macros in the game since this issue. If it ever happens again I'll reopen but this is probably a mistake.
