### ISSUE TITLE
MSYS2 builds failing from failed include of <SDL.h>

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#3299]
### Describe the bug

PRs are showing build failures on the `Cataclysm Windows build (MSYS2) / Build (pull_request)` build run, reporting the following error:
```
 In file included from src/cata_tiles.h:23,
                 from src/animation.cpp:29:
src/sdl_wrappers.h:15:13: fatal error: SDL.h: No such file or directory
   15 | #   include <SDL.h>
      |             ^~~~~~~
compilation terminated.
```

Compiling in VS2019 works fine and our actual releases seem to be unaffected, so no idea what this is.

### Steps To Reproduce

1. Yeet a PR out and observe the buildbot's findings.
2. Alternatively, try to compile in MSYS2.

### Screenshots

@RoyalFox2140 provided this fine example of suffering:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/94b9643a-b03f-46cc-8370-023e8aa42532)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.450 (2004)
- Game Version: 8545b76 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

**Comment by RoyalFox2140** [comment]
OS: Windows 10 Pro for Workstations 64-bit (10.0, Build 19045)

This guide was followed exactly to the letter. https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/doc/src/content/docs/en/dev/guides/building/msys.md

I used this command to attempt compiling.
make -j$((`nproc`+0)) CCACHE=1 RELEASE=1 MSYS2=1 DYNAMIC_LINKING=1 SDL=1 TILES=1 SOUND=1 LANGUAGES=all LINTJSON=0 ASTYLE=0 RUNTESTS=0

 It was attempted on this branch of Cataclysm and failed.
 https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3300

**Comment by olanti-p** [comment]
The build worked fine on version 8f340530e0701a96d36d8b357e7df3c4a03ff237, and it's broken starting from version 8e6dd605da22ac6a69a1c37b596f8f910d70d272, but there were only JSON changes between the 2 builds, which leads me to believe something changed on MSYS2's end.

**Comment by olanti-p** [comment]
GitHub runner updated between the 2 builds (from [20230918.1.0](https://github.com/actions/runner-images/blob/win19/20230918.1/images/win/Windows2019-Readme.md) to [20230924.1.0](https://github.com/actions/runner-images/blob/win19/20230924.1/images/win/Windows2019-Readme.md)), might be relevant.

**Comment by olanti-p** [comment]
Commit 353d70054e2fcab0e0bb964e58dc0d161369cd1f built successfully despite no changes on our part, which means it was an upstream MSYS issue.
