### ISSUE TITLE
Turrets shoot through the walls

### ISSUE THREAD

**Issue by ShaggyGiorno** [cataclysmbnteam/Cataclysm-BN#33]
Game version: 397

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: Aftershock

I've managed to get to the labs, only to be greeted by a turret trying to shoot me through the walls without making any contact with it. In addition, my companion seems to know what monsters are ahead of us, or even in some different location altogether.

After removing Aftershock, turrets seem to calm down, but my companion still seems to know what kind of monsters are ahead of us.

**Comment by Coolthulhu** [comment]
Could you provide a save?

**Comment by ShaggyGiorno** [comment]
https://mega.nz/file/My5khSrA#1z2pkyZg8ggbcNViTx7QuGyqAD1RM5UWhdVZzcaKd5g

**Comment by Coolthulhu** [comment]
Alright, reproduced reliably.
I grabbed a fix from mainline DDA and it seemed to fix it. Can't find the exact PR so credit goes to anonymous.
The newest version should no longer have the bug.

Details: vision cache used a hashing formula that didn't work on z-levels below 0.

**Comment by anothersimulacrum** [comment]
Credit goes to olanti-p, https://github.com/CleverRaven/Cataclysm-DDA/pull/41430
