### ISSUE TITLE
Trading with friendly npc crashes the game

### ISSUE THREAD

**Issue by cinornu** [cataclysmbnteam/Cataclysm-BN#3315]
### Describe the bug

Just a heads up that I used a translator first. I don't speak English very well :(

Friendly NPCs will offer to trade all of the Player faction's items in nearby stashes, but if the amount of these items becomes too large, trading will not work and game will crash.

about... 127 different type items..?

### Steps To Reproduce

1. put a lot of different types of items in your stash. Not quantity, but lots of "kinds".
2. Try "e: let's trade items" to a friendly NPC.
3. CRASH!

### Screenshots

![trading](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/55832850/0b402d36-4372-4d0d-bbd8-01c06421ecd2)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 61c1386 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    밝은 밤 [bn],
    NPC 욕구 제거 [no_npc_food],
    영양수치 단순화 [novitamins],
    철도역 금지 [No_Rail_Stations],
    고가 다리 [elevated_bridges],
    좀비 부활 방지 [no_reviving_zombies],
    진균 성장 제한 [limit_fungal_growth]
]

### Additional context

[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/12767538/debug.log)

no crash.log :(

save files : https://www.dropbox.com/scl/fi/gewv8te0rdbc9524ta4hd/trading_bugs.zip?rlkey=mjm72rdtub8vtj1b8gh454x23&dl=0

**Comment by scarf005** [comment]
[crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/12774889/crash.log)

looks like `gun_mode` may be null

**Comment by scarf005** [comment]
아직 패치 (#3329)가 적용된 게 아니어서, 적용되면 이슈도 동시에 닫히게 되요

**Comment by cinornu** [comment]
> 아직 패치 (#3329)가 적용된 게 아니어서, 적용되면 이슈도 동시에 닫히게 되요

앗 알겠습니다

**Comment by KheirFerrum** [comment]
Is this still a problem or did #3368 fix it?

**Comment by scarf005** [comment]
confirmed that it works in latest experimental.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/d64f68e6-77e7-4bac-9ad0-beb099195576)

**Comment by scarf005** [comment]
...wait, it segfaults

**Comment by scarf005** [comment]
```
 DEBUG    : Tried to get gun modes for non-gun 40mm pipe launcher

 FUNCTION : std::map<gun_mode_id, gun_mode> item::gun_all_modes() const
 FILE     : /home/scarf/repo/cata/Cataclysm/src/item.cpp
 LINE     : 7842
 VERSION  : BN 1c153718ab5e
```

this is getting very curious. investigating...
