### ISSUE TITLE
Hauling liquids causes hauling mode to not turn off automatically

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3316]
### Describe the bug

Attempting to haul water activates hauling, but it does not turn off when you fail to pick up a liquid, and go into empty tiles

### Steps To Reproduce

1. Break Toilet, activate hauling.
2. Move around

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/a0f5f9eb-0a47-4b0c-b305-86f2ec5f799d)

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Pro for workstations
- Game Version: cd7556b [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food]
]

**Comment by joveeater** [comment]
This bug is present on upload as well.

**Comment by olanti-p** [comment]
After some additional testing, turns out hauling does not turn off in many situations where it should, e.g.:
* Moving into deep water
* Jumping over ledges
* Getting punched by a hulk (and no, hauled items don't follow the character)
