### ISSUE TITLE
detonating barrel bombs throws errors

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3317]
### Describe the bug

The two errors will be in additional information verbatim. One is "position called on active improvised barrel bombs without a position" and the other is "Called attempt_detach in an object without a location"

Game does not crash. The explosion still worked, and I'm still able to play.

### Steps To Reproduce

1. Spawn barrel bomb and lighter, go into debug invincibility but stand far away
2. Detonate.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/9f975f72-ff2b-49cd-bfe2-6897b0850639)

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Pro for workstations
- Game Version: cd7556b [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food]
]

### Additional context

DEBUG    : position called on [active improvised barrel bombs] without a position

 FUNCTION : position
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\game_object.cpp
 LINE     : 158
 VERSION  : BN cd7556b
 
 DEBUG    : Called attempt_detach on an object without a location

 FUNCTION : attempt_detach
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\game_object.cpp
 LINE     : 78
 VERSION  : BN cd7556b

**Comment by joveeater** [comment]
Fixed by latest commits.
