### ISSUE TITLE
Sort Armor menu does not allow armor sorting

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3319]
### Describe the bug

This is hard to convey with images. When I open Sort Armor, I can hit Enter to select an item to sort up and it gets indented on my UI, but when I press up to move it above other armors it moves which item is indented but does not move the item I had selected.

### Steps To Reproduce

1. Go into Sort Armor
2. Attempt to sort one armor above or below another.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/e81084b4-a8e7-41e3-bff3-c64d2ae13cce)

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Pro for workstations
- Game Version: cd7556b [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food]
]

**Comment by joveeater** [comment]
Fixed by latest commits.
