### ISSUE TITLE
Be able to edit the mods of a savefile

### ISSUE THREAD

**Issue by rafaelkb** [cataclysmbnteam/Cataclysm-BN#333]
# Is your feature request related to a problem? Please describe.

 I'm always frustrated when i want to add a mod and i cant. i need to make another "world" and add everything again.

# Describe the solution you'd like

Be able to edit the mods of an existing savefile on the main menu.

**Comment by Coolthulhu** [comment]
You can edit the mod list of the save manually.
A UI for this might be useful, though.

**Comment by rafaelkb** [comment]
Yes! The UI is what im talking about.

Em sáb, 23 de jan de 2021 6:32 PM, Coolthulhu <notifications@github.com>
escreveu:
