### ISSUE TITLE
Make crows eat bodies

### ISSUE THREAD

**Issue by rafaelkb** [cataclysmbnteam/Cataclysm-BN#334]
# Is your feature request related to a problem? Please describe.

The world would feel more alive if there was for example, crows eating the bodies that the player left behind.

# Describe the solution you'd like

After the player left a bodie, after two or three days crows would appear and eat the flesh, leaving only the bones behind.
of course this would need to spawn crows, since there are not a lot of crows in the world.

# Additional context

It would be interesting to add vultures.

i dont know how this would work, maybe use the same "timer" that bodies have before they rot.

this would be simple to add but it would give an incredible atmosphere to CBN.

**Comment by Coolthulhu** [comment]
Sounds really specific. A bit like rotting food spawning cockroaches.

If there were population dynamics for critters, having scavengers prefer locations with corpses in them would be cool, but I'd rather not have it done biogenesis style, with corpses spawning critters.

Also, roaches and flies are more "zombie themed" than crows.

**Comment by rafaelkb** [comment]
do you remember the walking dead? if there´s zombies there should be tond of crows. I think. can we make it toggable?

**Comment by Coolthulhu** [comment]
Rather than an extra toggle just for this, I'd rather see it as an extension of "rots into critters" system, with corpses having their own "rot spawn group".

**Comment by Coolthulhu** [comment]
Closing as stale
