### ISSUE TITLE
Enable/disable bionic slots 'feature'

### ISSUE THREAD

**Issue by BrassECT** [cataclysmbnteam/Cataclysm-BN#336]
99% of the reason I stopped playing C:DDA was the technologically ignorant metagame limitation of 'bionic slots'. Finding BN a few weeks back and getting into it rekindled the joy of playing (heavily modded) 0.D, particularly due to the vastly improved mutation system over the original's wishy washy mechanics. However in my current run now going on 65~ hours, CBM's are excruciatingly rare (using a .50 item spawnrate to replicate a 28 Days Later scenario) in a painfully isolated city. Having found, and after a bunch of tinkering, installed an autoclave to a rooftop frame along with scavenging, then factory resetting a few CBM's, it was a dismal surprise opening the bionics menu to see the slot system in use. At the time I quit playing the original, that was the biggest reason for player hatred, even among those that didn't utilize it.

I do not have the [cbm_slots] mod active, nor do I know if it is possible (or how to) manually edit the system out. Is there a workaround for this?

**Comment by Coolthulhu** [comment]
Almost certainly Aftershock.
Three options:
* Don't play with Aftershock
* Edit `data/mods/Aftershock/options.json` - this has to be done every update and won't warn you if you don't remember, though
* Create a mod that disables slots and include it after Aftershock

The last one would probably be the most convenient in the long run.
There's a hidden, undocumented feature: if you include a mod directory in `saves/[save name here]/mods/`, it will be automatically loaded, although it won't show up in the scrolling list of mods at start.

**Comment by BrassECT** [comment]
Confirmed after I checked current active mods: Aftershock is in use and the problem. Started a new world and save without Aftershock, no bionic slots system. I greatly appreciate the help!
