### ISSUE TITLE
Moving onto deployed stepladders teleports you down and through the floor

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3366]
### Describe the bug

If you go up a ladder, then get off and go onto a tile that has a stepladder below it, you just got teleported down a Z level through the floor and onto the stepladder.

### Steps To Reproduce

1. Go up ladder.
2. Go into a floor tile that has a stepladder below it.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/2bc17dbb-f40a-4dfc-b86d-68d97fa55a74)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/90a369e2-e2bb-4abd-80aa-849ed32ec25f)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 61c1386 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Urban Development [Urban_Development],
    Cataclysm++ [Cata++],
    C.R.I.T. Expansion [crt_expansion],
    Battle Maid Redux [battle_maid]
]

**Comment by scarf005** [comment]
aww, it's not a feature, it's a bug

#3141

**Comment by RoyalFox2140** [comment]
> aww, it's not a feature, it's a bug
> 
> #3141

I can't use the stepladder to go up but the stepladder teleports me down through the floor though.

**Comment by scarf005** [comment]
i think it's caused by ~~me~~ movement code not checking for floors on auto-ladder
