### ISSUE TITLE
Adult magazine can't be used for morale if illiterate

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3374]
### Describe the bug

The adult magazine "Playboy" can't be used if illiterate. I don't need to spell out what you're using it for and that you don't read it for the articles. Perhaps it can give less morale if you can't read, due to not being able to read the "articles".

### Steps To Reproduce

1. Take illiterate trait
2. Find "Playboy"
3. Can't read it.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/ee2e94e8-51e7-4e53-9e47-d2251b5dcd1b)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 61c1386 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Urban Development [Urban_Development],
    Cataclysm++ [Cata++],
    C.R.I.T. Expansion [crt_expansion],
    Battle Maid Redux [battle_maid]
]

**Comment by Unrepentant-Atheist** [comment]
Well...I'm not sure if it's a bug...I mean....can't comprehend pictures....
