### ISSUE TITLE
Gas turbines should have a diet.

### ISSUE THREAD

**Issue by yagalone** [cataclysmbnteam/Cataclysm-BN#3383]
### Is your feature request related to a problem? Please describe.

The weights of the gas turbines are far too high. 
For example, the V-22 turbine weight around 450 Kg in real life, versus more than 3 tons in game.

This makes the gas turbines a bad choice, especially for weight-constrained helicopters.

### Describe the solution you'd like

Using real life equivalents, the turbines should weight :
- 142kg for the small one (Weight of the widespread General Electric CT58-110-1 turbine, rated at 1350 hp - the closest equivalent of the small turbine I could find)
- 206kg for the medium one (Weight of the General Electric T700-GE-701D turbine, used on several Apaches and Blackhawk variants and rated at 1944hp)
- 446 kg for the large one (Approximative weight of the Rolls Royce Allison T406-AD-400 mounted on the Osprey)

### Additional context

Very simple patch, 3 lines of json to edit. I'll make the PR later.
```[tasklist]
### Tasks
```

**Comment by scarf005** [comment]
maybe simplifying weights could be good, e.g
- small: 150kg
- medium: 200kg
- large: 500kg

**Comment by yagalone** [comment]
Sure, the figures I found are already approximations from somewhat dubious sources (Wikipedia and www.jet-engine.net)

**Comment by chaosvolt** [comment]
While you're at it, let me know if you find anything for steam turbines. I recall trying to look up estimates for turbines in the 500 kW range (IRL steam turbine outputs vary a LOT and I simply biggest an output value that'd be a good contrast with the existing engines) but don't recall if the sources I found were decent. They all did seem to lean even heavier than gas turbines though.

**Comment by yagalone** [comment]
Good idea!

Steam engines are trickier because references for *mobile* ones (the one optimized for weight) are around one century old.
Modern steam turbines used on power stations are probably more optimized for reliability, ease-of-maintenance and efficiency, weight being a secondary concern.

There's the same issue for the gas turbines : Helicopter gas turbines are far lighter than ground based gas turbines. For example, the AGT1500, the 1500 hp gas turbine of the M1 Abrams, weight more than a ton (https://en.wikipedia.org/wiki/Honeywell_AGT1500)
It's difficult to find detailled data on currently in use military systems (what a surprise there), but I guess that this figure probably include the heavy armor of the turbine compartment, and the turbine itself is probably more resilient than helicopter turbines.
There might also be some efficiency optimizations that are worth the extra weight on a rolling system but not on a flying one.

I'll try to find some data on steam turbines by checking datasheet of old steam trains. Early industrial age tech should properly mimic the "homemade" version of steam turbines.

I'm starting to wonder if the turbine should be split in several categories : Light turbines, optimized for low weight but less efficient and flimsier and heavy-duty turbines optimized for durability and efficiency, but weighting a lot.
Don't know if it would be useful, no idea if players really use turbines a lot...

**Comment by Unrepentant-Atheist** [comment]
I'm not a fan of numbers like 142, 206, 446. -> 150 , 210/200, 450.

**Comment by yagalone** [comment]
> I'm not a fan of numbers like 142, 206, 446. -> 150 , 210/200, 450. Leave the realism part to CDDA 😄

It was an easy jab... :laughing: 
I'll use 150 / 200 / 450... 

First researchs on the steam turbine front are not very good. Most of the datasheet I've found don't even mention the weight (a very secondary consideration indeed), and the few weight mentionned are on the multi-ton range. For example, [this one](https://www.howden.com/en-gb/products/steam-turbines/steam-turbine-base) weight 4.5 tons for a power equivalent to the small gas turbine. Marine turbines fares [no](https://www.mhi.com/group/mhimme/company/lib/cp_catalogue_e.pdf#page=13) [better](https://global.kawasaki.com/en/mobility/marine/machinery/steam_turbine.html?wovn=fr) on the power to weight ratio.
And those figures are only for the turbine itself, without the boiler included in the abstracted steam turbine of the game.

I think this is one of the case where gameplay should take precedence over realism.

**Comment by chaosvolt** [comment]
Yeah, finding good numbers for steam turbines is hard. I went with shaving it down to 700 kg for now, probably not realistic but will scale better with other turbines, to have it be heavy due to the water but decently fuel-efficient.

**Comment by Krwak** [comment]
I was trying to solve this issue a year ago. #1692

**Comment by yagalone** [comment]
> I was trying to solve this issue a year ago. #1692

Woops, sorry. I didn't checked the pull requests, only the tickets before opening this one...

**Comment by chaosvolt** [comment]
Hecc, I didn't notice that PR either. @.@
