### ISSUE TITLE
Bikes looks weird

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#339]
# Describe the bug
Bikes looks wierd

# Steps To Reproduce
Observe the bikes.
It looks weird.

# Expected behavior
Add support for:
Bikes
https://github.com/CleverRaven/Cataclysm-DDA/pull/41780
https://github.com/CleverRaven/Cataclysm-DDA/pull/42110

https://github.com/CleverRaven/Cataclysm-DDA/pull/42477
https://github.com/CleverRaven/Cataclysm-DDA/pull/46889

https://github.com/CleverRaven/Cataclysm-DDA/commit/2e6244803b774b30cafa75dbd33a4f355c8294ba#diff-78b32260eb1c0afa6de74846f3f7e2ac98614c36c83fb2a8fb6b3aaeb83eda3c

And bicycles.

vp_basketsm_bike_rear
vp_wheel_bicycle_rear
vp_wheel_bicycle_or_rear

# Screenshots
![16116678274040](https://user-images.githubusercontent.com/17512620/106025885-41529400-60da-11eb-924b-b8d5db4accdf.png)

# Versions and configuration

**Comment by Firestorm01X2** [comment]
TODO:
Проберить жука

**Comment by acepleiades** [comment]
I think when writing the JSON for the rotations of rear bicycle wheels, the person that did it flipped the rotations.
Are you sure this is not a tileset issue?

**Comment by Firestorm01X2** [comment]
> 
> 
> I think when writing the JSON for the rotations of rear bicycle wheels, the person that did it flipped the rotations.
> Are you sure this is not a tileset issue?

There was issue long time ago:
https://github.com/CleverRaven/Cataclysm-DDA/issues/34098

**Comment by Firestorm01X2** [comment]
CleverRaven#41780
CleverRaven#42110

CleverRaven#42477
CleverRaven#46889

**Comment by Coolthulhu** [comment]
Is it still a thing?
