### ISSUE TITLE
Suggested loot for Mi-go buildings

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#341]
# Is your feature request related to a problem? Please describe.

A big criticism I've heard about the Mi-go encampments and so on is that there's very little to motivate players to actually interact with them. They're damagingly hot places full of toxic vapors and dangerous Mi-go that have no loot in them. Yes, you can rescue prisoners and get some NPC followers but that's not much of a reward for end game level content. Especially given the number of players who don't like to play with NPC's at all. The mi-go surgeons imply to me that they took the human prisoners to experiment on so why not add some chemicals they were planning to use on the prisoners that would have mutagenic qualities? Base them off the qualities of Jabberwok blood but with mutagenic effects from other mutation trees. I'm thinking a random choice of ones from the fish tree (Deep Ones), cephalopod tree (Cthulhu), and possibly slime and/or insect tree for generic alien wierdness.

# Describe the solution you'd like

Like the description says add some mysterious chemicals to the Mi-go locations survivors can use to gain mutations. Possibly multiple test tubes like 2-4 since raiding these areas seems a bit harder than killing a Jabberwok and eating it's heart.

# Describe alternatives you've considered

This is really a pretty binary choice. I suppose vials of standard mutagenic serums could be used instead but the idea of mysterious chemicals an unspoiled player wouldn't know the effect of until used seems more fun. And the number available to loot is negotiable depending on what devs feel is balanced.

**Comment by Coolthulhu** [comment]
Old feature request. Closing as stale.
