### ISSUE TITLE
A problem with monster kittens

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#342]
# Describe the bug

Unsure if this is stemming from a mod or the core game, the error does not mention a mod. I'm getting the error: " DEBUG    : both into and into_group defined for monster mon_cat_kitten

 FUNCTION : void MonsterGenerator::check_monster_definitions() const
 FILE     : src/monstergenerator.cpp
 LINE     : 1202
" for all breeds of kitten. 

# Steps To Reproduce
Start a new game, error messages pop up

# Expected behavior
No error message about monster kittens.
# Versions and configuration

<!-- Please complete the following information; you can now go to:
    - "Main menu (ESC) > Debug Menu > Info > Generate game report" to generate this report.
    - Please update your OS version with a more precise version.

 - OS: Windows 10
 - Game Version: d3db13b
 - Graphics version: tiles
 - Ingame language: English
 - Mods loaded: 
 "dda",
 "no_npc_food",
 "magiclysm",
 "bow_opness",
 "XEAS",
 "a_mutated_arsenal",
 "bsam",
 "camping_tools",
 "growable-pots",
 "homemade_fungicide",
 "makeshift",
 "makeshift_engine_hoist_mod",
 "Power_Armor_Additions",
 "mutant_animals",
 "mutant_insects",
 "even_more_mutations",
 "mutant_npcs",
 "WHALEYHAIR1",
 "zets_hair_extensions_undead",
 "P_Caches",
 "morlock_village",
 "blazemod",
 "deoxymod",
 "shrub_mod",
 "growable-potsUDP",
 "Graphical_Overmap",
 "MagiclysmUDP",
 "mutant_animalsUDP",
 "mutant_insectsUDP",
 "AbrahmsRecipes1",
 "fuji_mpp",
 "Mutation_Changes1",
 "stats_through_kills",
 "StatsThroughSkills",
 "blaze_extension_M"

<!-- Add any other context about the problem here.

This seems like it should be an easy fix, it just takes someone who knows if it's the "into" or "into_group" entry that needs deleted.

**Comment by Proxiehunter** [comment]
Not sure why Versions and configuration is blank. This one I tried to fill out manually and it's still blank instead of what I wrote.

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: d3db13b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Make bows great again [bow_opness],
    XEAS [XEAS],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    Broken Admin's Makeshift Items [bsam],
    Camping tools [camping_tools],
    Garden Pots [growable-pots],
    Homemade Fungicide [homemade_fungicide],
    Makeshift Items Mod [makeshift],
    Makeshift engine hoist [makeshift_engine_hoist_mod],
    Power_Armor_Additions [Power_Armor_Additions],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Even More Mutations [even_more_mutations],
    Mutant NPCs [mutant_npcs],
    Whaleys Hair Mod [WHALEYHAIR1],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Caches [P_Caches],
    Morlock Village [morlock_village],
    Blazemod - Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Shrub it off [shrub_mod],
    Garden Pots - UndeadPeople Tileset [growable-potsUDP],
    Graphical Overmap [Graphical_Overmap],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mutant Animals - UndeadPeople Tileset [mutant_animalsUDP],
    Mutant Insects - UndeadPeople Tileset [mutant_insectsUDP],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    Fuji's Military Profession Pack [fuji_mpp],
    Mutation Changes Snofielf [Mutation_Changes1],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Vehicle Additions Additions [blaze_extension_M]
]

**Comment by anothersimulacrum** [comment]
All information between `<!--` and `-->` will not be displayed, those are html comments.

**Comment by Coolthulhu** [comment]
I'm almost certain it's one of the mods.

**Comment by Proxiehunter** [comment]
> I'm almost certain it's one of the mods.

If I can locate which mod it is do you know if it's the "into" or "into_group" that should be deleted?

**Comment by Coolthulhu** [comment]
That depends on the intent. Probably "into". But it may be possible that there is no "into", because the mod defined only "into_group". In this case, "into" has to be added and set to a null value, most likely "mon_null".
