### ISSUE TITLE
☂️ Armor coverage UI issues

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#3422]
### Describe the bug

This. This thing.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/6658b29e-9bec-4193-8908-7862bb2e4ede)

In a nutshell:
1. The numbers aren't aligned properly *ewwww*
2. Average coverage is kinda really gonna be useless 90% of the time. Even if coverage actually varies, a high average means absolutely nothing to the player if it's because the limbs have perfect coverage but the vitals are highly exposed, or vice-versa.
3. Large volume of redundant information anytime we have an item that doesn't actually vary its encumbrance and coverage percent 

What needs to be fixed for this, in order:
1. Fix the spacing on the display info weh!
2. Either axe average coverage because it's going to be not really that useful to the player most of the time, or else only display it if the actual average is different from all of the values for each body part (though as noted above that's both the only case where it's worth displaying but also the case where it's the most worthless to the player).
3. If all bodyparts have the exact same info, don't display a detail view for every single part. Just show a "everything has this" line instead.
 3a. Addition to the above, in theory we could even make the detail view even better by grouping all examples found of identical values, e.g. if the torso and head has 100% coverage while the arms and hands have 90% coverage, find some (hopefully not ugly) way to say "head, torso: 100" followed by "arms, hands: 90"

### Steps To Reproduce

Exist in a build after and look at the description screen for any armor item, mainly anything that covers more than one body part.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.450 (2004)
- Game Version: 2bc98a8 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Elevated bridges [elevated_bridges],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Mining Mod [Mining_Mod],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Faster Stamina Regen [stamina_regen_buff],
    Manual Bionic Installation [manualbionicinstall],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

DDA had an issue for exactly this problem way back when, with thanks to @x-qq: https://github.com/CleverRaven/Cataclysm-DDA/issues/59820

The UI shown in the issue OP is somehow even shittier than the version we've ended up with but still, ick. Some of it it seems is due to breathability which mercifully we don't have, but in any case it predictably got closed as invalid because since then they've managed to make their armor UI even more inefficient and hideous: 
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/a27dc5d6-3762-4e10-8120-674e5ce6ae5b)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/2ebf5fd2-7c24-4f1d-ab35-9be9ca16ec98)

Jesus fuckmothering christ I have to pagedown through that and take two separate screenshots to get all that and I've got DDA maximized on a 1920x1080 monitor what in the infinite hells
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/30cd1340-1e47-477b-ae28-ff2076919ecc)

```[tasklist]
### Tasks
- [ ] https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3436
- [ ] https://github.com/cataclysmbnteam/Cataclysm-BN/issues/3435
```

**Comment by scarf005** [comment]
```
  @
.-#-.
 / \
 . .
```
ASCII person goes brrrrrr
