### ISSUE TITLE
Sort Armor menu defaults to right foot instead of whole body

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#3423]
### Describe the bug

This...seems (?) to be another obscure casualty of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2776 because I can't think of anything else that could cause this, but when you hit the `+` menu it's now defaulting to viewing the right foot instead of showing the entire body.

### Steps To Reproduce

1. Start up the game.
2. Hit `+`,
3. Sell your right foot pics on onlyfans I guess.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/597293e9-83e1-4ae1-a0f6-558bff535340)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.450 (2004)
- Game Version: 2bc98a8 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Elevated bridges [elevated_bridges],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Mining Mod [Mining_Mod],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Faster Stamina Regen [stamina_regen_buff],
    Manual Bionic Installation [manualbionicinstall],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/17c08de7-1d98-46de-a98b-d691075251ac)

**Comment by scarf005** [comment]
wait, now it got worse

**Comment by chaosvolt** [comment]
I cri, I knew I should've checked out the branch and compiled-tested it to be sure. XD
