### ISSUE TITLE
Unable to generate a starting location Experiment cell in a radius of 3 overmaps

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#343]
As the title says. Lab challenge lab patient start. Kicks me back to the main menu when trying to start a new game. Trying again with a new world works. The error says to please report it.

# Steps To Reproduce

Start a new lab challenge attempt to start in a cell. Sometimes works sometimes generates the error message and kicks you back to the main menu without starting.

# Expected behavior

Should work every time.

# Versions and configuration

<!-- Please complete the following information; you can now go to:
  
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: d3db13b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Make bows great again [bow_opness],
    XEAS [XEAS],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    Broken Admin's Makeshift Items [bsam],
    Camping tools [camping_tools],
    Garden Pots [growable-pots],
    Homemade Fungicide [homemade_fungicide],
    Makeshift Items Mod [makeshift],
    Makeshift engine hoist [makeshift_engine_hoist_mod],
    Power_Armor_Additions [Power_Armor_Additions],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Even More Mutations [even_more_mutations],
    Mutant NPCs [mutant_npcs],
    Whaleys Hair Mod [WHALEYHAIR1],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Caches [P_Caches],
    Morlock Village [morlock_village],
    Blazemod - Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Shrub it off [shrub_mod],
    Garden Pots - UndeadPeople Tileset [growable-potsUDP],
    Graphical Overmap [Graphical_Overmap],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mutant Animals - UndeadPeople Tileset [mutant_animalsUDP],
    Mutant Insects - UndeadPeople Tileset [mutant_insectsUDP],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    Fuji's Military Profession Pack [fuji_mpp],
    Mutation Changes Snofielf [Mutation_Changes1],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Vehicle Additions Additions [blaze_extension_M]
]

**Comment by Proxiehunter** [comment]
Not sure why Versions and configuration is blank, I copy pasted the report generated by the game itself.

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: d3db13b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Make bows great again [bow_opness],
    XEAS [XEAS],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    Broken Admin's Makeshift Items [bsam],
    Camping tools [camping_tools],
    Garden Pots [growable-pots],
    Homemade Fungicide [homemade_fungicide],
    Makeshift Items Mod [makeshift],
    Makeshift engine hoist [makeshift_engine_hoist_mod],
    Power_Armor_Additions [Power_Armor_Additions],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Even More Mutations [even_more_mutations],
    Mutant NPCs [mutant_npcs],
    Whaleys Hair Mod [WHALEYHAIR1],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Caches [P_Caches],
    Morlock Village [morlock_village],
    Blazemod - Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Shrub it off [shrub_mod],
    Garden Pots - UndeadPeople Tileset [growable-potsUDP],
    Graphical Overmap [Graphical_Overmap],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mutant Animals - UndeadPeople Tileset [mutant_animalsUDP],
    Mutant Insects - UndeadPeople Tileset [mutant_insectsUDP],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    Fuji's Military Profession Pack [fuji_mpp],
    Mutation Changes Snofielf [Mutation_Changes1],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Vehicle Additions Additions [blaze_extension_M]
]

**Comment by chaosvolt** [comment]
So I'm looking into this in a PR, and getting this issue even after some changes I made to make lab spawning a LOT more robust, and in a world with no extra mods at all. So this is not a problem caused by your massive mod list.

After a half-dozen tries I got these errors shortly followed by yet another failure to start:
```
 DEBUG    : Lab type mismatch for lab at (22,120,-3)

 FUNCTION : operator ()
 FILE     : C:\Users\Vincent\Documents\GitHub\Cataclysm-BN\src\overmap.cpp
 LINE     : 1713
 VERSION  : BN e3dd54f77f-dirty
```
```
 DEBUG    : Couldn't find lab for point (22,120,-3) on overmap (3,2)

 FUNCTION : operator ()
 FILE     : C:\Users\Vincent\Documents\GitHub\Cataclysm-BN\src\overmap.cpp
 LINE     : 1816
 VERSION  : BN e3dd54f77f-dirty
```
