### ISSUE TITLE
Add ability to build standard walls, aka t_wall

### ISSUE THREAD

**Issue by sired22** [cataclysmbnteam/Cataclysm-BN#3467]
### Is your feature request related to a problem? Please describe.

So you can't build the standard walls you see everywhere, in the JSON they are called 't_wall'. you can paint and remove them, but you can't build them.

### Describe the solution you'd like

Using the materials in 'wall_deconstruction_results' found in 'deconstruction.json' add a recipe to 'construction.json' to allow the building of the most standard wall.

**Comment by mythosmod** [comment]
It appears this is already in the latest version under "Build Standard Wall"

  {
    "type": "construction",
    "id": "constr_wall",
    "group": "constr_wall_standard",
    "category": "CONSTRUCT",
    "required_skills": [ [ "fabrication", 3 ] ],
    "time": "30 m",
    "qualities": [ [ { "id": "HAMMER", "level": 2 } ], [ { "id": "SAW_W", "level": 2 } ] ],
    "components": [ [ [ "wood_sheet", 1 ], [ "wood_panel", 2 ] ], [ [ "2x4", 6 ] ], [ [ "nail", 40 ] ] ],
    "pre_special": "check_empty",
    "post_terrain": "t_wall"
  },

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/91185016/2c03b691-1b83-4fe7-b826-6d1369677b92)

**Comment by mythosmod** [comment]
Ah yes, here is the PR for it https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3478

**Comment by chaosvolt** [comment]
Yee, PR just didn't link to this issue is all. :>
