### ISSUE TITLE
☂️ make rags lag less

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#3487]
## Summary

Make items hoarded a lot stackable to reduce lag

## Process

1. change `type` to `AMMO`
2. give it an `ammo_type` of `components`
3. give it an `count` of `1`
4. additionally add `abstract` and use `copy-from`

```[tasklist]
### Item Ids
- [x] rag
- [x] rag_bloody
- [x] disinrag
- [x] nylon
- [x] superglue
- [x] plastic_chunk
- [x] string_6
- [x] 2x4
- [x] nomex
- [x] felt_patch
- [x] leather
- [x] fur
- [x] faux_fur
- [x] neoprene
```

```[tasklist]
### Now that they're stacked
- [ ] Simplify ropes?
- [x] Write a script so i don't have to manually do this stuff
```

**Comment by sired22** [comment]
nylon
superglue
plastic_chunk

**Comment by scarf005** [comment]
sadly `glass_sheet` can't be stacked rn because it breaks many tests, which i think is related to vehicle parts.
