### ISSUE TITLE
Mapgen gon' kaput in build 2023-10-24-0030

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#3496]
### Describe the bug

Same char, same template, same mods, same world. Build [build 2023-10-24-0030](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2023-10-24-0030) where the mapgen is absolutely out of whack.

![mapgen_fucked](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/f020b22a-4081-4e24-b59b-772b3e5cdb65)

Same char, same template, same mods, same world, how I know my mapgen to usually work: Build [Cataclysm-BN experimental build 2023-10-23-2242](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2023-10-23-2242)

![mapgen_ok](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/3a479fa0-ef57-4827-a0fd-b3775dc84ea1)

The difference between these 2 screenshots seems to be the mod Urban_Development from CDDA:BN . It just keeps on generating towers and towers and towers, endless number of towers in between some houses. Other mods generate some stuff sprinkled here and there, otherwise Urban_Development takes the reins.

### Steps To Reproduce

1. Make world with different builds
2. Wonder what's gone wrong....

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 4958da0 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots],
    Elevated bridges [elevated_bridges],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    PKs Rebalancing [PK_REBALANCE],
    Secronom [secronom],
    Secronom+ Lore Expansion [secronom_lore_expansion],
    C.R.I.T. Expansion [crt_expansion],
    Sierra Madre [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    Nechronica Redux [Nechronica_Redux],
    Magiclysm [magiclysm],
    Really Dark Skies [realdarkskies],
    Arcana and Magic Items [Arcana],
    Project: Pack Rat [Jake's_Squirrel_mod],
    Add Bandits Extended+ [GOV_BANDITS_KAI_R],
    More Bandits, Testing version [More_Bandits],
    More Dangerous Encounters [More_Dangerous_Encounters],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Magiclysm Revamp and Additions [magicrevamp],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Urban Development [Urban_Development],
    Morlock Village [morlock_village],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/C.R.I.T. Patchmod [Arcana_Crit_Patch],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Really Dark Skies plus Arcana [realdarkskies_Arcana_patchmod],
    Really Dark Skies plus Cataclysm++ [realdarkskies_CATA_patchmod],
    Really Dark Skies plus Aftershock [realdarkskies_aftershock_patchmod],
    Really Dark Skies plus PKs Rebalancing [realdarkskies_PK_REBALANCE_patchmod],
    Really Dark Skies plus Secronom [realdarkskies_secronom_patchmod],
    Really Dark Skies plus C.R.I.T. [realdarkskies_CRIT_patchmod],
    Really Dark Skies plus Bio-Synth Robot Expansion [realdarkskies_gekkobots_patchmod],
    Really Dark Skies plus magiclysm [realdarkskies_magiclysm_patchmod],
    Really Dark Skies plus Morlock Village [realdarkskies_morlock_village_patchmod]
]

**Comment by chaosvolt** [comment]
Uh, ya got an actual description of what the problem is, or you just want us to guess? Because if you make me resort to guessing all I've got is "mapgen creating cities of different sizes" and that's gonna get closed for being works as intended.

**Comment by Vollch** [comment]
I'm guessing it's about amount of towers. Urban development trying to spawn "-1"(i.e. max int) of towers. And new mapgen doesn't hesitates giving them all.

**Comment by Unrepentant-Atheist** [comment]
The mapgen is totally bonkers. 2nd one is how I know the map gen to works with my mods, 1st one is where everything is out of whack.
