### ISSUE TITLE
[CI] Tests not run when marking draft PR as ready

### ISSUE THREAD

**Issue by olanti-p** [cataclysmbnteam/Cataclysm-BN#3500]
For draft PRs, some of the tests are skipped. But when the PR is marked as ready, the missing tests won't automatically run unless another commit is pushed. This is a rather subtle issue that lets some compilation bugs through and can break the builds for other PRs.

Expected behavior: When PR is marked as ready, all tests are run.

**Comment by scarf005** [comment]
ow, this sure is unexpected. will check how DDA handles it later.

**Comment by scarf005** [comment]
fixed by #3924
