### ISSUE TITLE
Segfault when starting a fresh install of releases 1274 and 1276 on Windows 10 x64

### ISSUE THREAD

**Issue by Ishindri** [cataclysmbnteam/Cataclysm-BN#353]
# Describe the bug

When starting cataclysm-tiles.exe, the program fails to launch and instead throws a segmentation fault. This happens with completely fresh, just extracted copies of the game, on releases 1274 and 1276. The issue does **not** occur on release 1271.

# Steps To Reproduce

Start cataclysm-tiles.exe.

# Expected behavior

Game opens to main menu.

# Versions and configuration

 - OS: Windows 10 Pro, 64-bit
 - Game Version: precompiled builds 1274 (cataclysmbn-1274-win64-tiles.zip) and 1276 (cataclysmbn-1276-win32-tiles.zip)
 - Graphics version: Tiles
 - Ingame language: n/a
 - Mods loaded: n/a

# Additional context

I tried 1276 on a second machine running Windows 10 Enterprise x64 and got the same segfault error. debug.log and crash.log zips for both versions are attached.

[1274-win64-logs.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5955233/1274-win64-logs.zip)
[1276-win32-logs.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5955241/1276-win32-logs.zip)

**Comment by olanti-p** [comment]
Can't PR a fix right now, but the game should copy `fontconfig.json` from `data` folder to `config` and rename it to `fonts.json` if the file does not exist. Doing this manually fixes the crash.

Also, maybe move `fontconfig.json` from `data` to `data/raw`, where other clean config files are?

**Comment by Coolthulhu** [comment]
Pushed a quick fix for now. A bit ugly because I catch a runtime exception.

**Comment by Ishindri** [comment]
Confirmed that build 1278 has resolved the issue.
