### ISSUE TITLE
No item sorting with build 2023-11-04-0144

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#3542]
### Describe the bug

Sorting seems to be....new? Confusing? Sorted by?

### Steps To Reproduce

1. Kill stuff
2. Loot stuff
3. Be confused by new sorting
4. ???
5. Don't profit

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/f3377e9a-6677-4e9c-b119-7b63794c629e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 7ed3776 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Elevated bridges [elevated_bridges],
    PKs Rebalancing [PK_REBALANCE]
]

**Comment by olanti-p** [comment]
Can confirm, it used to sort by category, but now it displays in the "natural order" like the `V` menu does (i.e. the order in which items are stored in the memory).
