### ISSUE TITLE
Moving items from vehicle inventory causes debug prompt

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#3545]
### Describe the bug

I tried to move some short cordage rope from 1 vehicle inventory to another attached vehicle inventory. Shopping cart with an extra travois attached from it. Done this with the inventory managment window, NOT pick up from cart, drop off at travois. Moved rope from shopping cart to travois when these prompts happend.

After the move if I wanted to `g` from the travois or shopping cart I'm bombarded with

```10:34:04.212 ERROR DEBUGMSG : D:\a\Cataclysm-BN\Cataclysm-BN\src\locations.cpp:59 [where] Attempted to get the where of a fake item
10:34:06.401 ERROR DEBUGMSG : D:\a\Cataclysm-BN\Cataclysm-BN\src\locations.cpp:59 [where] Attempted to get the where of a fake item
10:34:06.401 ERROR DEBUGMSG : D:\a\Cataclysm-BN\Cataclysm-BN\src\rot.cpp:52 [temperature_flag_for_location] Invalid item location 0
10:34:06.754 ERROR DEBUGMSG : D:\a\Cataclysm-BN\Cataclysm-BN\src\locations.cpp:59 [where] Attempted to get the where of a fake item
 
10:34:06.754 ERROR DEBUGMSG : D:\a\Cataclysm-BN\Cataclysm-BN\src\locations.cpp:59 [where] Attempted to get the where of a fake item
10:34:06.754 ERROR DEBUGMSG : D:\a\Cataclysm-BN\Cataclysm-BN\src\rot.cpp:52 [temperature_flag_for_location] Invalid item location 0
```

### Steps To Reproduce

1. Have a shopping cart vehicle
2. Add a travois to the shopping cart
3. Open inventory management window
4. Left window shopping cart
5. Right window travois
6. Select rope in left window
7. Move with `shift+m` (everything)

See prompts

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/4fb3ca05-cfee-40c4-9c24-9aa82ad394b0)

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/fdfa9903-91df-4be0-af34-dbfe78e141da)

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/45357db9-581c-4ca7-97c2-100676509451)

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/8801f60a-eebe-4a9e-94fe-bf9aa8553b0d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 497c99f [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    Elevated bridges [elevated_bridges],
    PKs Rebalancing [PK_REBALANCE],
    Urban Development [Urban_Development]
]

### Additional context

https://pastebin.com/ZeCV249E

**Comment by AniDemi** [comment]
Can confirm that this error exists, it worked the first time but when I tried a second time it didn't work and I got the same 3 errors the OP got, on top of that the item that caused the error can no longer be picked up
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/60388907/e53db445-1193-4140-b972-713b11cadb14)

**Comment by AniDemi** [comment]
More testing, this bug seems to only occur after something has been recently installed. If you save and quit and reenter the game the error will not occur, and even items that have already been stuck there will no longer throw errors and can be moved. 

While the bug is active you can sometimes move items, but that creates copies in your inventory while the one in the cart remains, but if you put it back into the cart the amount will increase, and if you do the save quit method of fixing it, you now have potential for infinite duplication
