### ISSUE TITLE
Naturally spawned turrets do not fire at player

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#3548]
### Describe the bug

_organic turrets_ (not debug spawned) do not fire at players.

### Steps To Reproduce

1. teleport to nearby science lab/anywhere with naturally spawned turrets
2. stand nearby.
3. turret recognizes player character but does not open fire.
4. this behavior only happens on naturally spawned turrets.

### Screenshots

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/d41b2e26-3362-480d-9b2f-21cf07a4c6dd

above: debug spawned turret (shoots)
below: naturally spawned turret (does not shoot)

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 23.10; Release: 23.10; Codename: mantic; 
- Game Version: fbafa0c6eea9 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Magiclysm [magiclysm]
]

### Additional context

[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13256733/debug.log)

**Comment by olanti-p** [comment]
Another weirdness: if you teleport into a military bunker, you'll be shot at, but if teleport a few OMTs away and walk to it, then smash the door open and walk in, the turrets won't shoot either.

**Comment by olanti-p** [comment]
@scarf what's up with version string fbafa0c6eea9, it's not a valid commit hash?
