### ISSUE TITLE
Game wiped every container in my base clean in my save

### ISSUE THREAD

**Issue by WarriorKingBob** [cataclysmbnteam/Cataclysm-BN#3563]
### Describe the bug

Something happened while I was moving items using using advanced inventory controls. One of the error is about fake items. After I ignored the bugs, I realized that all of the items that act as a container got cleaned out of its contents. This includes battery charges, equipment that uses batteries, content in jars, and ammo in magazines and belts etc.

### Steps To Reproduce

Unknown. I do not know what even caused the issue. I was trying to move items from my mobile base to the ground using advanced inventory controls when the errors popped up. 

### Screenshots

![cataclysm-tiles_eynqmDYVNH](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/6170954/68d2e944-3c98-492b-91a4-d6a32c81f33f)

### Versions and configuration

Experimental Build 2023-11-04-2304

### Additional context

Unfortunately, as this ruined my save since I saved after encountering the bug, I decided to delete my character and start a new playthrough with some mods I've been wanting to try. I can no longer reproduce the issue. Hopefully this is just some random thing that happened.

**Comment by scarf005** [comment]
i think this is probably related to #3556
