### ISSUE TITLE
Guns don't reload at all

### ISSUE THREAD

**Issue by Anthraxmkv** [cataclysmbnteam/Cataclysm-BN#3564]
### Describe the bug

Reloading of guns and mags doesn't work at all/
```
 DEBUG    : invalid arguments to ACT_RELOAD

 FUNCTION : void activity_handlers::reload_finish(player_activity*, player*)
 FILE     : src/activity_handlers.cpp
 LINE     : 2020
 VERSION  : BN 03cb7f7
```

### Steps To Reproduce

1. Find a gun and mag for it, some ammo
2. Try to reload both mag and the gun
3. Non-critical, but bad error — no reload with error message.

### Versions and configuration

[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13259146/debug.log)

**Comment by AniDemi** [comment]
Can confirm this bug exists. This bug seems to also extend to all items that can be reloaded, I tested it with an arc welder and soldering iron. Unloading seems to work fine.
