### ISSUE TITLE
Unable to generate valid starting location with mods and "The last delivery" scenario

### ISSUE THREAD

**Issue by IriaSomobu** [cataclysmbnteam/Cataclysm-BN#36]
- Game version: commit 5f652ac558b5dadc07e0b29237bc5bb38c0b479b
- Operating system: any
- Tiles or curses: any
- Mods active: *see "Steps to reproduce"*

### Steps to reproduce the behavior
Create new world with ~~mods shown on "Step 1"~~ default modlist, create character with "The last delivery" scenario and try to start the game.

| Step 1 | Step 2 | Step 3 |
| ---- | ---- | ---- |
| ![image](https://user-images.githubusercontent.com/17745136/90317040-43aba200-df2f-11ea-84dd-0f806eb89a19.png) | ![image](https://user-images.githubusercontent.com/17745136/90317042-4efecd80-df2f-11ea-9bc1-2dda394cd08c.png) | ![image](https://user-images.githubusercontent.com/17745136/90317051-57ef9f00-df2f-11ea-8582-4bbc10a77621.png) |

N.B. the issue seems inconsistent: I was able to reproduce it only twice (tried 12 new worlds so far). 

Edit: Anon on 2ch.hk says that he can reproduce this bug with 1:5..1:10 rate too (two crashes in 13-14 attempts).
Edit 2: It seems that only scenario matters: anon got this error on default modlist (cata + disable needs) and default character with "The last delivery" scenario.

**Comment by iillyyaa2033** [comment]
Corresponding issue in upstream: https://github.com/CleverRaven/Cataclysm-DDA/issues/35376

**Comment by Coolthulhu** [comment]
This may be related to city sizes. The scenario requires a gas station, which requires 4-12 distance from a city and a road connection.

Gas station is supposed to be guaranteed, but the special placement system is terrible at guaranteeing anything.
