### ISSUE TITLE
Error when asking NPC to use single bandage wielded by character

### ISSUE THREAD

**Issue by olanti-p** [cataclysmbnteam/Cataclysm-BN#3608]
### Describe the bug

Asking NPC to use single bandage wielded by player character results in debugmsg:
```
01:44:37.958 ERROR DEBUGMSG : C:\code\cata\a\src\character.cpp:2876 [i_rem] did not found item bandage to remove it!
```

The bug does NOT occur when there are more than 1 bandages in the stack.
The bug does NOT occur when the bandage is in the inventory.
The bug can be reproduced with antiseptic powder.

### Steps To Reproduce

1. Load provided save: [cbn_bug_npc_bandage.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13313482/cbn_bug_npc_bandage.zip) OR follow step 2
2. (Setup) Spawn NPC, befriend them, spawn monster so it'd injure them, spawn and wield 1 bandage
3. Chat with NPC -> `I want you to use this item` -> bandage in hands
4. Be greeted with the error message
5. NPC thanks you for the item, and in "examine wounds" menu it can be seen that they _did_ apply the bandage

### Versions and configuration

Game version 1c153718ab5ebddf00e83394a51c48692a338b4b

### Additional context
Related to / similar to #3609

**Comment by joveeater** [comment]
Fixed by #3628.
