### ISSUE TITLE
Food perishes at wrong rates

### ISSUE THREAD

**Issue by olanti-p** [cataclysmbnteam/Cataclysm-BN#3610]
### Describe the bug

Food perishes at wrong rates.
And item with 1 day of shelf life may disappear after 10 minutes or remain unchanged for days depending on order in which perishable items were dropped.

### Steps To Reproduce

1. Debug spawn `raw brains` and `raw potato`
2. Drop raw brains, then drop raw potato in another tile
3. Wait for 10-15 minutes
4. See that raw brains disappeared
5. Debug spawn `raw brain` and drop it where it used to be
6. Wait for 24 hours
7. Nothing happens

### Versions and configuration

Game version 1c153718ab5ebddf00e83394a51c48692a338b4b

### Additional context

May be a resurrection of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2250#discussion_r1273931257

**Comment by scarf005** [comment]
possibly fixed by #3639 + #3642.
