### ISSUE TITLE
[Suggestion] Permanent effects from spells

### ISSUE THREAD

**Issue by Lorith** [cataclysmbnteam/Cataclysm-BN#362]
# Is your feature request related to a problem? Please describe.
I was looking into trying to recreate the old granade with spells.  Unfortunately, spells can only produce effects that are temporary.  Similarly, it is impossible to produce permanent debuffs with spells.

# Describe the solution you'd like
If a spell has the permanent flag, allow it to produce effects that are permanent.

**Comment by olanti-p** [comment]
Implemented in #538.
Permanence has been moved from effect appliers to effect_type, so now any effect of permanent type will be permanent regardless of `PERMANENT` spell flag or specified duration.
