### ISSUE TITLE
"MOUNTED_GUN" flag requires standing inside mountable terrain

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3644]
### Describe the bug

The flag "MOUNTED_GUN" requires users to stand near mountable furniture, such as a table or dirt mound. However it doesn't work correctly. It currently requires standing on such terrain. Amusingly, this means you can shoot this gun inside a window. The flag needs overhaul. 

The error message also reports it needs you to stand near said furniture.

### Steps To Reproduce

Use a weapon with "MOUNTED_GUN", this includes the mark 19 grenade launcher.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/8c84423c-509e-4ec8-97be-46e4278d1830)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 0.4 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Battle Maid Redux [battle_maid],
    No Acid Zombies [No_Acid_Zombies],
    C.R.I.T. Expansion [crt_expansion],
    Cataclysm++ [Cata++],
    Disable NPC Needs [no_npc_food]
]

**Comment by chaosvolt** [comment]
So, main issue is the code for this only checks if the terrain or vehiclepart at your position has the relevant flag, while the message description implies you just need to be next to the right terrain.

Far as I can tell, `find_furnitures_or_vparts_with_flag_in_radius` is exactly what we want? I tested it though and only apparent problem so far is it doesn't like the fact that `m` in `ranged::gunmode_checks_weapon` is a const, and I don't recall how you un-const that sorta thing.

**Comment by RoyalFox2140** [comment]
Maybe need to change the description then. Not sure what to do with this flag at all.

**Comment by chaosvolt** [comment]
That'd be an alternative if I can't figure out a good fix for this, yeah. Will see I guess.
