### ISSUE TITLE
Lasers get fouled and can be mended, firing an unlubricated laser crashes to desktop

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3645]
### Describe the bug

All lasers get fouled, even with the flags "NON-FOULING" and "NEEDS_NO_LUBE" defined. Also, lasers who get mended to remove fouling but without lubricant gain unlubricated status.

Attempting to fire a laser rifle that was mended without being lubricated will crash the game.

Tested with both an A7 laser rifle in vanilla and with one of the lasers from my mod. Both behave incorrectly.

### Steps To Reproduce

1. Use the A7 laser rifle.
2. Check fouling.
3. Mend the fouling.

### Screenshots

![](https://cdn.discordapp.com/attachments/830916329053487124/1173145065057689610/image.png?ex=6562e37b&is=65506e7b&hm=1d83ba82f67c6906336591b3cf107a0c7f6984cd51dec434d0a110ab17f1ccfb&)

![](https://cdn.discordapp.com/attachments/830916329053487124/1173145250819227648/image.png?ex=6562e3a7&is=65506ea7&hm=60ca8fb787f3df65eba52c6c3d6eb1e0047392946ab5b038257331d4b76a805d&)

![](https://cdn.discordapp.com/attachments/830916329053487124/1173145312752316476/image.png?ex=6562e3b6&is=65506eb6&hm=0db88cb43f4021a1197764dbcad932f5cc7bf69a78bccffdeb6382c6ea4b86d4&)

![](https://cdn.discordapp.com/attachments/830916329053487124/1173145560824434748/image.png?ex=6562e3f1&is=65506ef1&hm=ef95d5262161d9ca823e0be3b32c804c56042bbe3ace3593647b562f0a5fe597&)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 0.4 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 [Essence2200],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Battle Maid Redux [battle_maid],
    No Acid Zombies [No_Acid_Zombies],
    C.R.I.T. Expansion [crt_expansion],
    Cataclysm++ [Cata++],
    Disable NPC Needs [no_npc_food]
]

**Comment by scarf005** [comment]
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/463bc555-9595-4fb9-9d7e-8fff9b7cbfcd)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/92e14d74-beec-4dc1-b4a9-d81ff472a528)
was able to reproduce the issue following same steps.
