### ISSUE TITLE
Fermenting vat's state not reset correctly on emptying

### ISSUE THREAD

**Issue by YeOldeMiller** [cataclysmbnteam/Cataclysm-BN#3710]
### Describe the bug

When filling a container from a finished fermenting vat, the following error message appears:
```
 DEBUG    : Attempting to erase something from a vector with more than 1 active iterator

 FUNCTION : erase
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\location_vector.cpp
 LINE     : 294
 VERSION  : BN 0f8ea67
```

Then when trying to examine the vat afterwards:
```
 DEBUG    : fvat_full was empty!

 FUNCTION : fvat_full
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\iexamine.cpp
 LINE     : 3077
 VERSION  : BN 0f8ea67
```

### Steps To Reproduce

1. Set a fermenting vat to produce anything.
2. Wait for it to finish.
3. Have a container large enough to hold all of the product (up to 50L)
4. Finish brewing and empty out the vat
5. Observe the first error
6. Examine the vat
7. Observe the second error

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: 0f8ea67 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Limit Fungal Growth [limit_fungal_growth],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Custom Tweaks [Custom_Tweaks]
]

**Comment by AlecWhite** [comment]
I can't replicate it with the latest version, used vodka wort and steel jerry can.

**Comment by YeOldeMiller** [comment]
```
 DEBUG    : Attempting to erase something from a vector with more than 1 active iterator

 FUNCTION : location_vector<T>::iterator location_vector<T>::erase(location_vector<T>::const_iterator, detached_ptr<T>*) [with T = item]
 FILE     : src/location_vector.cpp
 LINE     : 294
 VERSION  : BN 1ca7353
```
```
 DEBUG    : fvat_full was empty!

 FUNCTION : void iexamine::fvat_full(player&, const tripoint&)
 FILE     : src/iexamine.cpp
 LINE     : 3077
 VERSION  : BN 1ca7353
```
Definitely still happens for me. Remember you have to fully empty the vat to trigger the error, which may or may not happen with a jerry can since it holds less than 50L.

**Comment by AlecWhite** [comment]
Will try again with a drum. Also fun fact, it took me over 30 IRL minutes to "wait" the time it took the vat to ferment the vodka(5 ingame hours).

**Comment by YeOldeMiller** [comment]
UPD: the first error seems to not be unique to fermenting vat, it also happens with wooden kegs and, I suspect, any liquid containers in furniture form when they are fully emptied.

**Comment by scarf005** [comment]
> Will try again with a drum. Also fun fact, it took me over 30 IRL minutes to "wait" the time it took the vat to ferment the vodka(5 ingame hours).

i think it's possible to debug skip time to ferment items quickly
