### ISSUE TITLE
Unable to find and assign mission target s_air_term

### ISSUE THREAD

**Issue by tjlaxs** [cataclysmbnteam/Cataclysm-BN#3730]
### Describe the bug

First run after building the game from upload-branch. Run into a missing mission target.

### Steps To Reproduce

1. Create character with mission: `MISSION_ASSASSINATION`

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2715 (22H2)
- Game Version: 0f770090f4 [64-bit]
- Graphics Version: Tiles
- LAPI Version: <none>
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

### Additional context

Debug log:
>  DEBUG    : Unable to find and assign mission target s_air_term.
> 
>  FUNCTION : std::optional<coords::coord_point<tripoint, coords::origin::abs, coords::scale::overmap_terrain> > find_or_create_om_terrain(const tripoint_abs_omt&, const mission_target_params&)
>  FILE     : src/mission_util.cpp
>  LINE     : 238
>  VERSION  : BN 0f770090f4

If I understood correctly it seems like this _s_air_term_ doesn't exist anywhere.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/json/npcs/missiondef.json#L842

**Comment by chaosvolt** [comment]
Dafuq? It's still in the JSON right here: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/json/overmap/overmap_special/specials.json#L6890

@Vollch may have done something in their overmap generation code that's causing a scenario mission to no longer be able to find locations, possibly?

**Comment by Vollch** [comment]
I can't actually reproduce it, but looking at code i think i see how that's possible.
When game can't find goal it firstly spawn in:
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/0f770090f4ffdd0c116f37707d57ebcc1d44d2ab/src/mission_util.cpp#L195
And then searches for exact OMT:
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/0f770090f4ffdd0c116f37707d57ebcc1d44d2ab/src/mission_util.cpp#L201
(Later on it'll try to spawn special once again, giving second chance to spawn special properly, and dodge debug message)

And here the catch - `place_special` doesn't accept and process `find_params` which among other thing specifies min range. So, apparently it's possible that it'll spawn special too close to find it later. That seems to be very old bug.

**Comment by Vollch** [comment]
And yeah, i actually reproduced it at x0 specials:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/544763/95ffe1e5-62b3-4654-ab34-0e2a303bd598)
Game spawned 2 airports, but they too close for `"min_distance": 45` requirements, which gave me same error.
