### ISSUE TITLE
Vending Machines don't display all of their content

### ISSUE THREAD

**Issue by SophiaAtelier** [cataclysmbnteam/Cataclysm-BN#3734]
### Describe the bug

After buying all of the items in the vending machine the machine will shutdown. However if you check the exact same machine again there might be more items. You can then buy them and check again until the machine is actually empty

### Steps To Reproduce

Have only noticed with subway vending machine (haven't seen other ones in game to try yet)
1. Buy all the items in the vending machine
2. Vending machine will beep and shutdown
3. Examine vending machine again
repeat steps 1-3 until the vending machine is actually empty

### Versions and configuration

OS: Linux Mint 21.2
Game Version: 0.4 Stable
Terminal
Ingame Language: English
Default mods

**Comment by ekaratzas** [comment]
This is not reproducible for me on top of rev 8163b201cbb879f7a219e877edea0c9aa525d007

* Found couple of vending machines in gambling den
* bought what they had
* beep and shutdown
* examine again - they are actually empty and can't buy anything

**Comment by scarf005** [comment]
will close the issue for now. please reopen the issue if it persists.
