### ISSUE TITLE
No MSVC builds are being created

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#3740]
### Describe the bug

See title. We don't have any. They fail for some reason, I'll link that reason from a few pulls.

https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/6964653137/job/18952202185?pr=3739
https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/6962208660/job/18945430012?pr=3709

### Steps To Reproduce

1. Open any pull. Literally any. Change anything.
2. Start the workflow.
3. It won't work.

### Versions and configuration

Not applicable.
This is the last MSVC build. https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/cbn-experimental-2023-11-18-0038
This is the last pull that successfully generated MSVC https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3672

**Comment by chaosvolt** [comment]
Additionally, compiled builds in VS2019 are failing to work right and hitting an access violation for reasons I suspect are related.
