### ISSUE TITLE
charges not depleting in rock forges / clay kilns (possibly other tools)

### ISSUE THREAD

**Issue by Valikdu** [cataclysmbnteam/Cataclysm-BN#3754]
### Describe the bug

When crafting a recipe that involves a Rock Forge or a Clay Kiln (both vanilla constructions), charges of charcoal are not depleted from them.

### Steps To Reproduce

1. Have a BN version later than experimental 2023-11-03-0512
2. Build a rock forge / clay kiln and load them with charcoal
3. Craft a recipe that uses either of these as a tool (ex. a scythe for the rock forge or a clay jug for the clay kiln)
4. No charcoal will be used up

### Screenshots

n/a

### Versions and configuration

Game version: tried most versions after 2023-11-03-0512 including the current one (2023-11-24-0037)
Mods: Kenan's mod pack

**Comment by RoyalFox2140** [comment]
This is still an issue as of current version.
