### ISSUE TITLE
Flu shot doesn't work

### ISSUE THREAD

**Issue by mkikt4743** [cataclysmbnteam/Cataclysm-BN#376]
# Describe the bug

Flu shot doesn't work

# Steps To Reproduce

Take a flu shot
Message log says 'you empty'
Vaccinated effect is not given/active

# Expected behavior

Flu shot saves you from the flu for a year

# Versions and configuration

 - OS: Windows
    - OS Version: 10.0 2004
- Game Version: 077f3e6 [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I've got a lot of mods installed, but I doubt that affects it since they aren't loaded

**Comment by Proxiehunter** [comment]
It's noted [here](https://github.com/cataclysmbnteam/Cataclysm-BN/wiki/Changes-so-far) that BN "Removed random cold and flu" so presumably there's no flu to protect against. It could instead be made to boost the health stat but I understand they're thinking of reworking that as well. Right now it seems to be a source of a syringe.
