### ISSUE TITLE
False positive test failures due to Power Armor Soldier staritng equipment

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#3813]
### Describe the bug

new_character_test.cpp occasionally fails in PR testing with:
```
(~[slow] ~[.],starting_items)=> -------------------------------------------------------------------------------
(~[slow] ~[.],starting_items)=> ../tests/new_character_test.cpp:103
(~[slow] ~[.],starting_items)=> ...............................................................................
(~[slow] ~[.],starting_items)=> 
(~[slow] ~[.],starting_items)=> ../tests/new_character_test.cpp:191: FAILED:
(~[slow] ~[.],starting_items)=>   REQUIRE( failures.empty() )
(~[slow] ~[.],starting_items)=> with expansion:
(~[slow] ~[.],starting_items)=>   false
(~[slow] ~[.],starting_items)=> with message:
(~[slow] ~[.],starting_items)=>   power_armor_soldier ANTIFRUIT PROF_MILITARY  power_armor_helmet_light:
(~[slow] ~[.],starting_items)=>   Couldn't wear it.`
```

Problem here is, when you actually select that profession in-game, they spawn with all their outfit and have no trouble taking off and putting back on their starting items.

This also prevented me from giving them a canteen in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3778 since it complained about the canteen. I'd marked it as not auto-equiping so the test shouldn't have been complaining at all, the character was starting with their canteen in inventory as expected.

### Steps To Reproduce

Make PRs. It just seems to happen sometimes at random.

### Versions and configuration

Version info for branch that https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3811 is in, which currently has this test failure:
```
- OS: Windows
    - OS Version: 10.0.19041.450 (2004)
- Game Version: 34d1bf82cc87 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn]
]
```

**Comment by scarf005** [comment]
I'm not 100% sure but judging by that it only fails on Mac, this may be related: https://github.com/apple/foundationdb/issues/1862

**Comment by chaosvolt** [comment]
Update: this might be caused by Aftershock making UPS wearable, which with the power armor soldier causes all their gear to fail to spawn except their UPS, leaving them naked with just the UPS on spawn.

If so then https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3797 should fix it.
