### ISSUE TITLE
Flashlight loses assigned inventory letter when turned on/off

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#3818]
### Describe the bug

When turning a flashlight on and then back off again, it tends to lose its assigned letter. Obviously a problem if your habit (like mine) is to assign it to `f` to turn it on and off quickly.

### Steps To Reproduce

1. Spawn in a flashlight and assign it a hotkey using `=`.
2. Turn it on and back off again.
3. It should now suddenly no longer have its hotkey, but will typically regain it when turned back on, only to lose it again after turning it off.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/ae010c6d-02f5-4db1-81bb-bdd8997a2db7)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/91634875-8d27-46c5-adb8-b7e0a183854b)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/7e58d4c2-6eda-4c0b-b3e3-237da7f0efdd)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.450 (2004)
- Game Version: d7e62b5 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Elevated bridges [elevated_bridges],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Mining Mod [Mining_Mod],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Faster Stamina Regen [stamina_regen_buff],
    Manual Bionic Installation [manualbionicinstall],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by chaosvolt** [comment]
Hmm. Has anyone made any progress on looking into this? It's almost certainly related to item identity.

**Comment by Kaylakaze** [comment]
This seems to be a somewhat recent bug since my current play through (I tend to play the game for a while every year or so and then not play for many months) is the first time I've encountered this bug.

**Comment by yay855** [comment]
I've been having this same issue with toggled items, like the smartphone. I can confirm it's basegame.
