### ISSUE TITLE
Low temperature in Spring must be investigated.

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#383]
# Describe the bug
I've seen a t least 2 reports about low temperature in Spring. It must be investigated.

> Вот результатики разных персонажей:
> 1. Слесарь Дон, стандартный старт в убежище на полностью стандартных настройках. Мир без модов, версия - 1379 ака предпоследняя для Винды 64. Результат - -58 практически на всех конечностях (где была теплее одежда там выше)
> 2. Версия 1385, Винда 64. Лесоруб Уильмс, в целом ок кроме ног (-40), рта (-30) и ладоней.
> 3. Опять же таки последняя версия для Винды, начинаю за жертву душа. Как ни странно у него температура не такая адовая - везде - 36.
> 
> В целом какая-то странная хрень получается. Так или иначе дело не в модах. 

> Here are the results for the different characters:
> 1. Locksmith Don, standard hideout start at completely standard settings. A world without mods, version - 1379 aka the penultimate for Windows 64. Result - -58 on almost all limbs (where the clothes were warmer there)
> 2. Version 1385, Windows 64. Woodcutter Wilms, generally ok except for legs (-40), mouth (-30) and palms.
> 3. Again, the latest version for Windows, I start for the sacrifice of the soul. Oddly enough, his temperature is not so hellish - everywhere - 36.
> 
> In general, some kind of strange crap turns out. One way or another, it's not about mods. 

![16148727954473](https://user-images.githubusercontent.com/17512620/109994761-abd0a280-7d1e-11eb-9175-570ab1f4b4ee.png)
![16148727954432](https://user-images.githubusercontent.com/17512620/109994765-aecb9300-7d1e-11eb-9109-a37d651b9dfc.png)
![16148727954381](https://user-images.githubusercontent.com/17512620/109994767-aecb9300-7d1e-11eb-9418-b563a7267a0c.png)
![16148727954360](https://user-images.githubusercontent.com/17512620/109994770-affcc000-7d1e-11eb-8c8d-85bca6a393cc.png)

**Comment by Firestorm01X2** [comment]
Confirmed. Something is strange.
Temperature PRs for reference.
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/301
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/301

**Comment by Firestorm01X2** [comment]
Temperature itself base on thermometer seems fine. But if feels cold for player for some reason.
![screenshot 2021-03-04 001](https://user-images.githubusercontent.com/17512620/109998710-9198c380-7d22-11eb-8fa3-6f37222e824c.png)

**Comment by Proxiehunter** [comment]
> 
> 
> Temperature itself base on thermometer seems fine. But if feels cold for player for some reason.
> Default surivvor. Default start.

Converting that temperature to Fahrenheit which I'm used to using that appears to be only 41 degrees. Pretty chilly for anything not properly covered. Doesn't look like they start with the winter coat and winter boots they once did (haven't played a standard survivor in a very long time) so I would expect them to feel uncomfortably chilly when at that temperature for prolonged periods. Now if the game started warning you about frost nip or frost bite I'd think that was a bug because those temperatures are too high for that to be an issue, but not by much.
