### ISSUE TITLE
Bike Racks are starting to bug out and permanently meld the mounted vehicles to the main vehicle

### ISSUE THREAD

**Issue by Relgar** [cataclysmbnteam/Cataclysm-BN#3867]
### Describe the bug

At some point, vehicles mounted via bike racks will no longer be unloaded from the main vehicle. I will typically see the below error, which doesn't necessarily mean the vehicle is bugged then, but after a while, it occurs. You will know the vehicle is stuck when it has no 'name'.

### Steps To Reproduce

1. Create main vehicle with bike rack
2. Create candidate vehicle to be mounted
3. Load the candidate onto the main vehicle - at this point you may get the below error:

>  DEBUG    : Attempted to resolve invalid location_ptr
> 
>  FUNCTION : T* location_ptr<T, error_if_null>::get() const [with T = item; bool error_if_null = true]
>  FILE     : src/location_ptr.cpp
>  LINE     : 136
>  VERSION  : BN 428d071

4. Attempt to unload vehicle. If you still see the vehicle's name, all is fine. If you no longer see the vehicle's name (this seems to happen after a few days of being loaded into the bike rack), you can no longer unload it and must disassembly the parts individually.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/84274761/cf8988b7-8a94-4655-9c76-faea42e677e6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 428d071 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    BioCo Content [bioco],
    CBM Equipment [CBM_Arms],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Garden Pots [growable-pots],
    Gourmand's Graces [Gourmand'sGraces],
    Makeshift Items Mod [makeshift],
    More Makeshift Stuff [makeshift_stuff],
    Wild Living [WildLiving],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - Mods Extension [MMA_Mods_Extension],
    Even More Mutations [even_more_mutations],
    More Survivor Stuff [more_survivor_stuff],
    NPC Recruitment Options [recruitment_options],
    Thog's Things [Thogs_Things],
    Thog's Vehicles [Thogs_Vehicles],
    THRESHOLD [add_mutant],
    Alternative Basement Layouts [basement_extension],
    Caches [P_Caches],
    More Locations [more_locations],
    Morlock Village [morlock_village],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Ships From Oa Additional Buildings [Ships],
    Urban Development [Urban_Development],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Shrub it off [shrub_mod],
    Aftershock - Easydocs [AFS_Easydocs],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    No Addictions [No_Addictions],
    No Filthy Clothing [no_filthy_clothing],
    No Lifting Reqs [disable_lifting],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Targeted Mutations [TaMu]
]

**Comment by Ignaramico** [comment]
i recall something similar happening if you repair the vehicle while being in the rack (or if you tried modifying too, sometimes even if it was the main vehicle)
