### ISSUE TITLE
UPS devices preference external sources of power

### ISSUE THREAD

**Issue by Relgar** [cataclysmbnteam/Cataclysm-BN#3900]
### Describe the bug

UPS devices, such as mp3 players, will prefer to drain power from external sources of power (i.e. UPS or CBMs providing UPS power) before draining their own, when it should be the opposite.

### Steps To Reproduce

1. Have mp3 player or other UPS energy requiring tool
2. Have external source of UPS power like a UPS or CBM
3. Turn on tool, it will keep at constant full power while your external source drains

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 428d071 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    BioCo Content [bioco],
    CBM Equipment [CBM_Arms],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Garden Pots [growable-pots],
    Gourmand's Graces [Gourmand'sGraces],
    Makeshift Items Mod [makeshift],
    More Makeshift Stuff [makeshift_stuff],
    Wild Living [WildLiving],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - Mods Extension [MMA_Mods_Extension],
    Even More Mutations [even_more_mutations],
    More Survivor Stuff [more_survivor_stuff],
    NPC Recruitment Options [recruitment_options],
    Thog's Things [Thogs_Things],
    Thog's Vehicles [Thogs_Vehicles],
    THRESHOLD [add_mutant],
    Alternative Basement Layouts [basement_extension],
    Caches [P_Caches],
    More Locations [more_locations],
    Morlock Village [morlock_village],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Ships From Oa Additional Buildings [Ships],
    Urban Development [Urban_Development],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Shrub it off [shrub_mod],
    Aftershock - Easydocs [AFS_Easydocs],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    No Addictions [No_Addictions],
    No Filthy Clothing [no_filthy_clothing],
    No Lifting Reqs [disable_lifting],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Targeted Mutations [TaMu]
]

**Comment by scarf005** [comment]
related: #1605

**Comment by chaosvolt** [comment]
I think the solution I mused upon in that PR might be good:
1. Add two new item flags: `UPS_COMPATIBLE_OFF` and `UPS_COMPATIBLE_ON`
2. Change UPS charging code so that it also charges items with the `UPS_COMPATIBLE_ON` flag.
3. Replace the current UPS flag on all mundane appliances (i.e. stuff that's implied to only use UPS because they're meant to be things you can plug in to charge) with `UPS_COMPATIBLE_OFF`.
4. Code in a use_action that brings up a menu filtering for items with either of the new flags, and set it so making a selection toggles between the two flags.
5. Add this new use action to UPS and advanced UPS.

**Comment by chaosvolt** [comment]
I went a slightly different route in the form of a use action on the devices themselves, but: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4775
