### ISSUE TITLE
Make z-levels mandatory

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#3907]
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/760736fb-32e0-4cb3-80e1-e20e1cda162d)

this was agreed on poll in https://github.com/cataclysmbnteam/Cataclysm-BN/discussions/3533

**Comment by Zireael07** [comment]
What is the impact of Z levels on performance? I quite frequently use CDDA as a timewaster on low spec machines (old computers, old Android phones)

**Comment by chaosvolt** [comment]
From what I've seen so far impact is rather low. For mobile devices tileset is the biggest roadblock (too big a total size traditionally would hit RAM limits), while in general cases NPCs have been the biggest lag inducers (and right now there aren't any cases where a location has large numbers of NPCs spread across z-levels, the most infamous locations prefer to stack their NPCs on a single level).

**Comment by Zireael07** [comment]
BTW Draw performance optimization for z-levels just dropped in CDDA: https://github.com/CleverRaven/Cataclysm-DDA/pull/70301

**Comment by Qrox** [comment]
I believe BN uses a different 3D view implementation from DDA so that probably won't apply.
