### ISSUE TITLE
Autodocs in a location without a roof still claim you are looking at the ceiling

### ISSUE THREAD

**Issue by EkarusRyndren** [cataclysmbnteam/Cataclysm-BN#3914]
### Describe the bug

While having the Sensory Dulling CBM installed, you will regardless of the state of the location the bed is installed in receive a message about focusing on a stain on the ceiling. This includes being in a car that lost a roof or if you just spawn a bed in a field. (The discord wanted me to post this)

Minimum, should probably know if you're not under a roof. Max effort know what kinda roof you're under (cave, car, lab, etc)

### Steps To Reproduce

Spawn an autodoc in a field
Attempt to install a bionic while having the sensory dulling CBM
Receive message.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: c5e21d5 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Prevent Zombie Revivication [no_reviving_zombies],
    Aftershock [aftershock],
    Fewer Farms [Fewer_Farms],
    Tankmod: Revived [Tankmod_Revived],
    MSX Fake Snow [UDP_BN_FAKE_SNOW],
    Faster Stamina Regen [stamina_regen_buff]
]

**Comment by chaosvolt** [comment]
Making the message more generic would also work. :>

**Comment by Relgar** [comment]
Agree with CV, this shouldn't require programming logic to fix.
