### ISSUE TITLE
The letters are truncated in the Look Around pane.

### ISSUE THREAD

**Issue by ektjhh** [cataclysmbnteam/Cataclysm-BN#3945]
### Describe the bug

I'm not an English speaker.
The letters are truncated in the Look Around panel.
ex) Lightning: brigt, Hydrangea bush > brightea bush
Look at the first screenshot: 'brightass' is very strange. lol
And is 'Cursor At' a necessary feature?
I preferred the old version without Cursor At.
But if other users need it, I think it's fine to have it.

### Steps To Reproduce

Move the mouse cursor with the Look Around feature enabled.

### Screenshots

![9](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/154313291/2bb74766-1f47-4654-8adc-c67f552aca80)
![10](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/154313291/ec0050ab-7311-486b-98ba-dbb6d531159f)
![11](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/154313291/c52cef69-a98f-45dd-b6dc-67294a4de69b)

### Versions and configuration

[Cataclysm-BN experimental build 2023-12-18-0040] > [cbn-windows-tiles-x64-msvc-2023-12-18-0040.zip]
language : I use Korean. However, I have the same problem in the English version.
Windows 10, 64bit

**Comment by scarf005** [comment]
caused by #3902
