### ISSUE TITLE
MacOS Ventura

### ISSUE THREAD

**Issue by Woit** [cataclysmbnteam/Cataclysm-BN#3957]
### Describe the bug

App not started

### Steps To Reproduce

Download latest (cbn-osx-tiles-x64-2023-12-22-0038.dmg  in my case) release and try to open

### Versions and configuration

Mac M1 Ventura 13.6.3

### Additional context

[cataclysm-tiles-2023-12-23-025320.txt](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13757226/cataclysm-tiles-2023-12-23-025320.txt)

**Comment by RoyalFox2140** [comment]
For a possible related error, see the Discord. https://discord.com/channels/830879262763909202/830916451517857894/1188015286335570021

An error report from the link I provided:

Last login: Sat Dec 23 17:30:09 on ttys002
/Applications/Cataclysm.app/Contents/Resources/cataclysm-tiles ; exit;          
aaronhera-singh@Aarons-MacBook-Air ~ % /Applications/Cataclysm.app/Contents/Resources/cataclysm-tiles ; exit;
dyld[9537]: Library not loaded: /usr/local/Cellar/glib/2.78.0/lib/libglib-2.0.0.dylib
  Referenced from: <4FC2021A-5B40-32F2-BFD3-7B83A81CDC68> /Applications/Cataclysm.app/Contents/Resources/libgthread-2.0.0.dylib
  Reason: tried: '/usr/local/Cellar/glib/2.78.0/lib/libglib-2.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/glib/2.78.0/lib/libglib-2.0.0.dylib' (no such file), '/usr/local/Cellar/glib/2.78.0/lib/libglib-2.0.0.dylib' (no such file), '/usr/local/lib/libglib-2.0.0.dylib' (no such file), '/usr/lib/libglib-2.0.0.dylib' (no such file, not in dyld cache)Library not loaded: @loader_path/../../../../opt/libogg/lib/libogg.0.dylib
  Referenced from: <590E5E3F-D64D-3B35-9100-AB196E9782F7> /Applications/Cataclysm.app/Contents/Resources/libsndfile.1.dylib
  Reason: tried: '/Applications/Cataclysm.app/Contents/Resources/../../../../opt/libogg/lib/libogg.0.dylib' (no such file), '/usr/local/lib/libogg.0.dylib' (no such file), '/usr/lib/libogg.0.dylib' (no such file, not in dyld cache)Library not loaded: /usr/local/Cellar/libvorbis/1.3.7/lib/libvorbis.0.dylib
  Referenced from: <E8E1AD4C-5AF8-3BA1-B039-79C67E8AEE2E> /Applications/Cataclysm.app/Contents/Resources/libvorbisfile.3.dylib
  Reason: tried: '/usr/local/Cellar/libvorbis/1.3.7/lib/libvorbis.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/libvorbis/1.3.7/lib/libvorbis.0.dylib' (no such file), '/usr/local/Cellar/libvorbis/1.3.7/lib/libvorbis.0.dylib' (no such file), '/usr/local/lib/libvorbis.0.dylib' (no such file), '/usr/lib/libvorbis.0.dylib' (no such file, not in dyld cache)
zsh: abort      /Applications/Cataclysm.app/Contents/Resources/cataclysm-tiles

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by scarf005** [comment]
this may be related to: #2309

**Comment by RoyalFox2140** [comment]
The mac version in this release contains a possible fix to the missing libraries but it requires a mac user to report the issue is solved. https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/2024-07-11

**Comment by Woit** [comment]
@RoyalFox2140 Mac M1 Sonoma 14.5 - Works great!
