### ISSUE TITLE
Underslung guns disable their main weapon when they run out of ammo

### ISSUE THREAD

**Issue by Relgar** [cataclysmbnteam/Cataclysm-BN#3966]
### Describe the bug

If you have an underslung gun and fire until it is out of ammo, you will not be able to switch fire modes back to your main weapon until you either remove the mod or insert ammo back into your underslung weapon.

### Steps To Reproduce

1. Attach underslung weapon (say shotgun) to your main gun with ammo. You can also skip this step and step 2 by attaching an empty weapon.
2. Switch fire modes to the underslung weapon and fire until out of ammo
3. Get errors about being out of ammo when you press 'f', which stops you from changing fire modes

### Screenshots

![Underslung](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/84274761/fc26b586-3f32-40c0-913e-a455c5cd0594)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 428d071 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    BioCo Content [bioco],
    CBM Equipment [CBM_Arms],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Garden Pots [growable-pots],
    Gourmand's Graces [Gourmand'sGraces],
    Makeshift Items Mod [makeshift],
    More Makeshift Stuff [makeshift_stuff],
    Wild Living [WildLiving],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - Mods Extension [MMA_Mods_Extension],
    Even More Mutations [even_more_mutations],
    More Survivor Stuff [more_survivor_stuff],
    NPC Recruitment Options [recruitment_options],
    Thog's Things [Thogs_Things],
    Thog's Vehicles [Thogs_Vehicles],
    THRESHOLD [add_mutant],
    Alternative Basement Layouts [basement_extension],
    Caches [P_Caches],
    More Locations [more_locations],
    Morlock Village [morlock_village],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    Ships From Oa Additional Buildings [Ships],
    Urban Development [Urban_Development],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Shrub it off [shrub_mod],
    Aftershock - Easydocs [AFS_Easydocs],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    No Addictions [No_Addictions],
    No Filthy Clothing [no_filthy_clothing],
    No Lifting Reqs [disable_lifting],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Targeted Mutations [TaMu]
]

**Comment by borsek** [comment]
Confirmed - this is annoying with underbarrel GLs too. The workaround is to use the change fire mode shortcut key (L by default, but I could be wrong). It should be able to switch. CDDA does not have this problem, so might find a portable solution there.
