### ISSUE TITLE
Selecting Shelter 3 varients in an Evac shelter start still results in random location.

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#398]
When starting in an evac shelter and you press / to select starting location you are given the option between random location, shelter three variants, and vandalized shelter three variants. If you select shelter three variants the location seems to still be random resulting in starts in vandalized shelters.

# Steps To Reproduce

1: Create a variety of characters that should start in shelter 3 variants.

2: Note that the locations still seems to be randomized resulting in some but not all of them starting in vandalized shelters when those should not be valid starting locations for the character. In some cases there has been a non-vandalized shelter within a very close walking distance and visible on the map at spawn so it's not a case of no vandalized shelters being available.

Bug first reported a month ago [here](https://www.reddit.com/r/cataclysmbn/comments/lfs2o1/evacuee_shelter_vandalized/) and still present as of build 1385. I have not updated to 1399 because the changes in that build do not appear to effect me since I play in English and they seem unlikely to effect the bug. Builds past that do not currently have a 64 bit Windows version available for me to use so I have not updated to those either but they do not mention changes that should effect this bug.

# Expected behavior

Selecting Shelter 3 Variants means never starting in a vandalized shelter. 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 926f0b4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    anti-fungal gear [anti_fungal_gears],
    Broken Admin's Makeshift Items [bsam],
    Garden Pots [growable-pots],
    Homemade Fungicide [homemade_fungicide],
    Makeshift engine hoist [makeshift_engine_hoist_mod],
    Makeshift Items Mod [makeshift],
    More Makeshift Stuff [makeshift_stuff],
    Power_Armor_Additions [Power_Armor_Additions],
    Mutant NPCs [mutant_npcs],
    Caches [P_Caches],
    Morlock Village [morlock_village],
    Blazemod - Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Shrub it off [shrub_mod],
    Garden Pots - UndeadPeople Tileset [growable-potsUDP],
    Graphical Overmap [Graphical_Overmap],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mutation Changes Snofielf [Mutation_Changes1],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock],
    Whaleys Hair Mod [WHALEYHAIR1],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Bootleg Walkers [Bootleg_Walkers],
    Salvaged Robots [Salvaged_Robots],
    Jury-Rigged Robots [jury_rigged_robots],
    Bootleg Walkers - UndeadPeople Tileset [Bootleg_WalkersUDP],
    Modular Turrets with No Blacklist - UndeadPeople Tileset [modular_turrets_no_blacklist_UDP],
    Miscellaneous Magiclysm Expansions [demon_spider_a]
]

**Comment by ZhilkinSerg** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/41095
