### ISSUE TITLE
Initiating A Trade Request With A Merchant Causes The Items Around Them To Disappear/Despawn

### ISSUE THREAD

**Issue by DrPariah** [cataclysmbnteam/Cataclysm-BN#3980]
### Describe the bug

Items in the immediate vicinity of a merchant (trash can next to them, filing cabinet behind them, etc.) disappear/despawn if you initiate a trade request with the merchant. First noticed this with mods on a build earlier this month, but recreated it in vanilla with the merchant at the Refugee Center.

### Steps To Reproduce

1. Create a world and set items to 10.00 so you can see this in action (still happens on lower settings, this is just to make sure you see items in the vicinity first).
2.  Create a new character, select Safe Place, and have them spawn in the Refugee Center.
3. Teleport into the merchant's chamber. Note the items that spawn in the filing cabinet and the trash can.
4. Talk to the merchant and ask to trade. The merchant will display items.
5. Exit the trade and leave the dialogue with the merchant.
6. Note that the items in the filing cabinet and trash can are gone. They did not migrate to the merchant's vendor list.

### Screenshots

![Enrique Bond __04-56-45_Central Standard Time](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/64315339/d3f7731d-c78f-448f-a1c7-460aa8e580e2)
![Enrique Bond __04-57-19_Central Standard Time](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/64315339/b97fb91b-ffe2-4576-af37-528fff91fd98)

Before and after.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 278b433 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

### Additional context

This doesn't exactly look like intended behavior. Haven't checked all the PRs, dunno if anyone messed with traders recently.

**Comment by scarf005** [comment]
may be related to #3386 
cc @OrenAudeles
