### ISSUE TITLE
Using "R"ead spellbooks or scrolls causes segmentation fault

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#40]
Attempting to use the  `R`ead command when an item with the `learn_spell` use action causes the game to crash with a segmentation fault. This applies whether the item in question is in your inventory or on the ground close enough to be accessed.

Choosing to `a`ctivate under either of these conditions works as normal, and the spellbooks can be researched from as normal. Also tested a standard book, a martial arts manual, and simply bringing up the read menu in general to ensure it wasn't something less specific.

# Steps To Reproduce

1. Start a world with Magiclysm or any other content mod making use of `learn_spell` items.
2. Spawn a spell scroll or spellbook, such as A Beginner's Guide to Magic, Scroll of Fireball, etc.
3. Press activate key to confirm its presence and use action shows on the menu as normal.
4. Press read key, triggering segfault.

# Expected behavior

Populating the read menu as is standard for normal books and martial arts manuals, or else only populating the activate menu as was the case when spellbooks were initially added.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 5f652ac [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context

[crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5120114/crash.log)

The feature that added support for reading spellbooks was first added by: https://github.com/CleverRaven/Cataclysm-DDA/pull/37560

Did a test in a recent build of DDA as well and couldn't reproduce it there, unsure what might be different to cause it here.

**Comment by Coolthulhu** [comment]
I have changed book reading when implementing recipe learning, so it's probably BN specific.

**Comment by chaosvolt** [comment]
Hopefully it's easy enough to find the cause.

**Comment by Coolthulhu** [comment]
It wasn't actually BN specific, it's undefined behavior that causes a crash in BN, but doesn't cause it in DDA.
The crash happens because the menu tries to read skill type of a book, but if the item is not a book, it doesn't have a book skill type, so a null is read, causing the crash.

Workaround for now: disabled 'R'eading spellbooks that aren't books.
