### ISSUE TITLE
Port  Mark overmap location if player drops favorited item

### ISSUE THREAD

**Issue by Incroppism** [cataclysmbnteam/Cataclysm-BN#4015]
### Is your feature request related to a problem? Please describe.

This feature is convenient because I almost lost my hiking backpack after dropping it somewhere then forgetting to pick it up then having to use the list all items feature to find it

### Describe the solution you'd like

https://github.com/CleverRaven/Cataclysm-DDA/pull/62299

When you dropped a favorited item it should leave an autonote on the map.

### Additional context

If this didnt work or you guys dont like how it works, maybe make it behave like remembered vehicles as suggested by Almantuxas on Discord.

**Comment by RobbieNeko** [comment]
Just noting down my intent to work on porting this as my first C++ PR (though unfortunately I lack the power to become assignee)
