### ISSUE TITLE
New characters retain dead state from previously deceased characters

### ISSUE THREAD

**Issue by Relgar** [cataclysmbnteam/Cataclysm-BN#4022]
### Describe the bug

If you die to heat (i.e. lava pits), your next character you make while in the program will still retain 'scorching' temperature, and take damage to your limbs as if you were still on fire / melting.

### Steps To Reproduce

1. Make a character die due to heat (bottom of mine starts are quickest)
2. Create a new character in the menu
3. Your new character is still melting

### Versions and configuration

Experimental 2023-12-28, no mods

**Comment by scarf005** [comment]
> Experimental 28/12/2023, no mods

~~please use the glorious [iso8601 date format](https://en.wikipedia.org/wiki/ISO_8601#Calendar_dates)~~

**Comment by scarf005** [comment]
## On same save

### With death prompt

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/5b8b3563-f817-478c-8ea8-78df2559ce8a

### Without death prompt

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/468d9d87-bbd6-4313-8dad-fdfb39381f3b

## When visiting another world

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/ef151673-7f09-4fc0-ba6e-eb833b53e94c

i think it's related to player status not correctly reset after death
