### ISSUE TITLE
Central Lab map generation is broken and does not generate stairs downward

### ISSUE THREAD

**Issue by Zilenan** [cataclysmbnteam/Cataclysm-BN#4029]
### Describe the bug

The first floor of Central labs seem to generate like this, with four special rooms on each side of this crosshair-looking shape, but there's one problem: it never generates stairs leading downward, and likewise, floors below the first do not generate stairs going up   either. 
![firstfloor](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/105184154/4e228b87-fbba-4b3b-a94d-0b244e397cb6)
![what](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/105184154/1732be85-b70f-42df-91c2-407704b7ba90)

I've tested this with two different central labs in my playthrough and both had a first floor that had the same shape for the floor, but with different rooms. I have a mod installed in this playthrough called Hydroponics which can add Hydroponics special rooms to lab generation, so I tested another world without that mod and it was the same problem. Normal labs seem to be completely fine as far as generation goes, it's JUST central labs.

### Steps To Reproduce

1. Generate a world
2. Find the central lab
3. It never generates stairs downward

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: 3abde26 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

The game report above is not the save I first encountered this, it's a completely vanilla default settings world I generated and reproduced the same problem in, however.

**Comment by scarf005** [comment]
cc @Vollch
