### ISSUE TITLE
Central Lab's stair error

### ISSUE THREAD

**Issue by Restar-JS** [cataclysmbnteam/Cataclysm-BN#4037]
### Describe the bug

1. Use upstair 
2. Stair sends character to water pool

### Steps To Reproduce

Since it's mapgen Issue, hard to reproduce.

I attached save file.

### Screenshots

<img width="960" alt="스크린샷 2024-01-01 004752" src="https://github.com/cataclysmbnteam/Cataclysm-BN/assets/150272259/aba66687-04e4-4960-8aaf-a08d9714eb7d">
<img width="960" alt="스크린샷 2024-01-01 004746" src="https://github.com/cataclysmbnteam/Cataclysm-BN/assets/150272259/0bcc2ec4-87da-4a25-97d1-2580ac7b4dba">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.2861 (23H2)
- Game Version: 0.5 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    밝은 밤 [bn],
    프로젝트: 다람쥐 [Jake's_Squirrel_mod],
    Arcana and Magic Items [Arcana],
    애프터쇼크 [aftershock],
    매직클리즘 [magiclysm],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    NPC 욕구 제거 [no_npc_food],
    영양수치 단순화 [novitamins],
    좀비 부활 방지 [no_reviving_zombies],
    살해 수 반영 능력 성장  [stats_through_kills],
    표적 돌연변이 [TaMu_BnKo],
    민첩할수록 빠르게 [speedydex],
    더 좋은 민첩스탯 [dexbuff],
    기술 성장 비례 능력 성장 [StatsThroughSkills],
    AZF의 모드 [AZF],
    Croppable Rice [Rice_Mod_kor],
    기괴하고도 강력한 장비들 [BPG],
    허브01 지하실 되살리기 모드 [Revive_hub01_basement],
    도그밋의 인벤토리 [dogmeat_mod],
    진균 괴물 제거 [No_Fungi],
    철도역 금지 [No_Rail_Stations],
    MSX 가짜 눈 [UDP_BN_FAKE_SNOW]
]

### Additional context

[LOT.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13801597/LOT.zip)

You can also check this problem other stair at (-5, 272, 105) in this save file.

**Comment by Vollch** [comment]
This one also should be fixed with #4040
