### ISSUE TITLE
Refilling water from dirty container makes clean one dirty

### ISSUE THREAD

**Issue by Restar-JS** [cataclysmbnteam/Cataclysm-BN#4038]
### Describe the bug

Refilling water container(clean) with water in dirty one makes dirty.
But using unload(u) doesn't make this error.

### Steps To Reproduce

1. Press "r" to refill your water container from dirty one.
2. See your container get dirty.

3. Press "u"to unload water in dirty container
4. Put water in your clean one.
5. See it stays clean.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.2861 (23H2)
- Game Version: 0.5 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    밝은 밤 [bn],
    NPC 욕구 제거 [no_npc_food],
    영양수치 단순화 [novitamins],
    철도역 금지 [No_Rail_Stations],
    좀비 부활 방지 [no_reviving_zombies],
    진균 성장 제한 [limit_fungal_growth]
]

### Additional context

[Test.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13801649/Test.zip)

**Comment by ElonSatoshi** [comment]
Isn't this how it works in real life?

It sounds like unloading the dirty water into the clean water and having the clean water remain clean is the real bug here.

**Comment by Restar-JS** [comment]
I mean container, not water.

2024년 2월 1일 (목) 오후 4:57, ElonSatoshi ***@***.***>님이 작성:

**Comment by Restar-JS** [comment]
Refilling clean water from dirty container (which has clean water) makes
clean "container" dirty.

But unload clean water from dirty container and put it clean container, it
doesn't make problem.

I attached save file and instruction on there. Just follow it than you can
understand.

2024년 2월 1일 (목) 오후 5:10, Jaesung Han ***@***.***>님이 작성:
