### ISSUE TITLE
Using grid welder causes the player to not be able to reach nearby materials

### ISSUE THREAD

**Issue by Dueu** [cataclysmbnteam/Cataclysm-BN#405]
# Description of the bug

Some days ago my Pull Request #379 was merged. I tested briefly and it seems that worked fine, what I didn't test was actual crafting with it. While the grid welder it's in crafting reach it causes to the player to not be able to reach nearby materials to craft something, this includes recipes that doesn't use any kind of charges like wheat seeds.

# Steps To Reproduce

1. Place the arc welder within crafting range
2. Try to craft something (the crafting menu will tell you that all requirements to craft that item are check)
3. At least one material will not be able to be retrieve from a pile of items causing the missing item popup to appear

![2](https://user-images.githubusercontent.com/52106307/111875200-5aa7ec00-8977-11eb-99b5-68dfaada30ef.PNG)
This happened while trying to craft clean water.

![3](https://user-images.githubusercontent.com/52106307/111875356-1a953900-8978-11eb-9da8-9472768338fb.PNG)
This happened while trying to craft a katana.

![4](https://user-images.githubusercontent.com/52106307/111875370-3698da80-8978-11eb-9027-a28be52146f2.PNG)
And this is the wheat seeds example I mentioned earlier.

Note: Even if you choose the option "yes" no item is consume and the popup comes back.

# Versions and configuration

- OS: Windows 10
- Game Version: 474de4c
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: [dda, BL9_100monres, aftershock, Arcana, crt_expansion, magiclysm, craftgp, incinerator, MST_extra, DinoMod, Cata++, MMA, blazemod, no_npc_food, stats_through_kills]

**Comment by Coolthulhu** [comment]
Had this bug before, with ovens. I was pretty sure I fixed it, but it looks like it sneaked in again somehow.

**Comment by Coolthulhu** [comment]
Oh right, I never actually fixed it, I just failed my testing to ensure it works.
Fixed now: https://github.com/cataclysmbnteam/Cataclysm-BN/commit/39ed52df76adbd519b12e07253da029b484aad8f

**Comment by Dueu** [comment]
Okay thanks, I was coding the some others electric tools to be place installable as well. Expect a PR soon.
