### ISSUE TITLE
Burdock is unobtainable

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#4065]
### Describe the bug

We have a plant and item for burdock, but it doesn't spawn in vanilla. I only noticed in No Hope and rural biome mod. 
Wild herbs reference containing burdock as well. We don't even have any pulls that mention this, it was never obtainable in our fork outside of mods, but tons of items exist in mainline for it.

We have fried burdock, burdock wine, cooked burdock, burdock tea, and other items. I expect it to be obtainable instead of removed and will likely fix it myself. Issue created for visibility and so I don't forget about it and to ensure it gets done.

### Steps To Reproduce

1. Check the code and you will notice 0 references to spawn "f_burdock" outside of No Hope and rural biome mod
2. Faction camps in spring can forage for it. Also a single itemgroup contains raw burdock. That's it.

### Versions and configuration

All versions since Bright Nights existed as a fork. This issue has been around for years.

**Comment by Lamandus** [comment]
The regional map JSON, I used for forest changes is the one you need. If you like, you can add that line.

**Comment by RoyalFox2140** [comment]
To quote the Discord, I was mostly leaving the issue open because wild vegetables state they can be burdock and I don't know if add or remove here. We could migrate burdock into wild vegetables and remove the single recipe, I was mainly considering if it had a unique property and never got around to doing the research for it or fixing it after I fixed rural region mod and no hope's regional map data.
