### ISSUE TITLE
Crash when NPC is mining 

### ISSUE THREAD

**Issue by RaynaWasTaken** [cataclysmbnteam/Cataclysm-BN#407]
The game seems to crash with a segway fault whenever an NPC has finished mining a tile.
This also happens without any mods loaded, vanilla game only.

# Steps To Reproduce

1. Load the provided savegame. (The NPC has already been instructed to mine and a zone has been set up, the NPC has no other instructions besides mining)
2. wait for 2-3 hours.
3. The game will crash

# Expected behavior

the NPC mines the designated tiles and drops the mined items on the floor

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 474de4c [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda]
]

Savefile and crashlog are provided below.

[Save.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/6177390/Save.zip)
[crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/6177391/crash.log)

**Comment by olanti-p** [comment]
Possible fix CleverRaven#44841 + CleverRaven#46020
