### ISSUE TITLE
Can't skin multiple human corpses

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#4094]
### Describe the bug

Upon trying to skin a single human corpse, it works. Upon trying to batch skin 4, they no longer have skin to take. What? 

### Steps To Reproduce

1. Try to skin a man.
2. Try to skin 4 men.
3. See what happens.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/868c6f7c-cabd-4658-b0e1-d2c7a9acfc06)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/8424f8af-09c4-4172-a772-c62de47f66fd)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/7c5b449c-0fe5-4e82-9630-b22d7819b55d)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 0.5 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 BN [Essence2200_BN],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Cataclysm++ [Cata++],
    Teleportation [teleportation_tech]
]

### Additional context

Why is it that I'm the only one who gets owned?

**Comment by Ignaramico** [comment]
just to state it  since OP didnt mention it, it happens the same with the organs when you want to batch the action
