### ISSUE TITLE
Crash when throw dynamite to zombie soldier swarm.

### ISSUE THREAD

**Issue by junk1497** [cataclysmbnteam/Cataclysm-BN#4108]
### Describe the bug

I threw the dynamite where zombie soldier swarm under searchlight, and it exploded and crashed.

### Steps To Reproduce

Go to FEMA camp on LEVEL 0, -80, 163 and throw dynamite on zombie soldier gathered under searchlight

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3086 (22H2)
- Game Version: v0.5.2 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

### Additional context

[crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13931234/crash.log)
[톰.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13931270/default.zip)

**Comment by scarf005** [comment]
updated save folder which directly starts from FEMA camp: [crash.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/13931446/crash.zip)

**Comment by scarf005** [comment]
cc @joveeater @DeltaEpsilon7787
