### ISSUE TITLE
Smoked meat ejects itself from smoking rack

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#4109]
### Describe the bug

When a smoking rack finishes smoking meat, the smoked meat is kindly informed it's loitering, and ejects itself from the smoking rack onto the floor. This happened while I was crafting next to it, much to my audible "WTF?"

"Why I say old chap, kindly move on now that you're well and truly smoked."

### Steps To Reproduce

1, Smoke some chunks of meat. In my case it was 23 chunks of meat exactly, and it only contained the minimum required charcoal.

### Screenshots

I could give you one, but it has no context without recording a video.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: db0b411 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Arcana and Magic Items [Arcana],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 BN [Essence2200_BN],
    Essence 2200 Tweaks [FoxTweaks],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Cataclysm++ [Cata++],
    Teleportation [teleportation_tech],
    No Filthy Clothing [no_filthy_clothing],
    OMT Resources [omt_resources],
    Flowing Water [flowing_water]
]

**Comment by DrPariah** [comment]
Can confirm this happens. Easy to reproduce. It's pretty funny, TBH.

Sent from Yahoo Mail on Android 
 
  On Sun, Jan 14, 2024 at 3:36 PM, ***@***.***> wrote:   


Describe the bug

When a smoking rack finishes smoking meat, the smoked meat is kindly informed it's loitering, and ejects itself from the smoking rack onto the floor. This happened while I was crafting next to it, much to my audible "WTF?"

"Why I say old chap, kindly move on now that you're well and truly smoked."

Steps To Reproduce

1, Smoke some chunks of meat. In my case it was 23 chunks of meat exactly, and it only contained the minimum required charcoal.

Screenshots

I could give you one, but it has no context without recording a video.

Versions and configuration
   
   - OS: Windows      
      - OS Version: 10.0.19045.3448 (22H2)

   - Game Version: db0b411 [64-bit]
   - Graphics Version: Tiles
   - LAPI Version: 2
   - Game Language: English [en_US]
   - Mods loaded: [   
Bright Nights [bn],   
Craftable Gun Pack [craftgp],   
Alternative Map Key [alt_map_key],   
Fuji's Military Profession Pack [fuji_mpp],   
Arcana and Magic Items [Arcana],   
Craftable Bullet Casings [CasingCrafting],   
MST Extra [MST_Extra],   
Tankmod: Revived [Tankmod_Revived],   
Essence 2200 BN [Essence2200_BN],   
Essence 2200 Tweaks [FoxTweaks],   
Nonperishable Overhaul [Nonperishable_Overhaul],   
No Addictions [No_Addictions],   
Limit Fungal Growth [limit_fungal_growth],   
Disable NPC Needs [no_npc_food],   
Simplified Nutrition [novitamins],   
Cataclysm++ [Cata++],   
Teleportation [teleportation_tech],   
No Filthy Clothing [no_filthy_clothing],   
OMT Resources [omt_resources],   
Flowing Water [flowing_water]   
]

Additional context

No response

**Comment by scarf005** [comment]
_it's not a bug, it's a feature!_
~~smokers are toasters~~


wluld the expected behavior be to keep the smoked items inside?

**Comment by Ignaramico** [comment]
> _it's not a bug, it's a feature!_ ~smokers are toasters~
> 
> wluld the expected behavior be to keep the smoked items inside?

well, they did before, although i dont see a problem unless there is a mob near with the eat food flag/special tbh

**Comment by RoyalFox2140** [comment]
> _it's not a bug, it's a feature!_ ~smokers are toasters~
> 
> would the expected behavior be to keep the smoked items inside?

Yes because either you've tied chunks of raw meat to the smoker or you've skewered it. That meat has to stay on the rack somehow during the smoking process, It doesn't just fall off. I'm fine with a way to smoke meat that automatically ejects it somehow but an automation update should require machines and electricity. A guy in the woods isn't teaching their smoking racks not to allow meat to loiter.

**Comment by Unrepentant-Atheist** [comment]
Uuuh....so...you're saying...I don't have to manually remove the contents from the smoking rack after smoking anymore?

What y'all complaining about???

**Comment by Lamandus** [comment]
This bug is a feature now

**Comment by chaosvolt** [comment]
This seems kinda premature. Is it convenient? Yeah I guess, but it still seems very janky. Plus this almost CERTAINLY speaks to potential lingering code weirdness that might have yet-to-be-discovered side effects.

**Comment by Lamandus** [comment]
It is very convenient, since you reduce multiple key presses and can craft with it
