### ISSUE TITLE
[BUG] Light information covers other text in the sidebar

### ISSUE THREAD

**Issue by tinkerng** [cataclysmbnteam/Cataclysm-BN#4140]
### Describe the bug

When hovering over a tile, the light information (bright, dark etc) eats other text in the interface. Only affects experimental (I've noticed it a few days ago, but can't pinpoint the update causing the change). No problems in stable.

### Steps To Reproduce

In a new or existing game, in experimental, detach the cursor and hover over a tile. The bug happens with different fonts/sizes, but Terminus size 20 was used for the screenshots.

### Experimental

![experimental-character](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/90969776/69aa7201-4d43-4d54-9d6d-5f7aec470b2f)

![experimental-raspberry](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/90969776/65fd8507-1ed5-4745-ab4a-29c3791065e0)

![experimental-underbrush](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/90969776/65ab7a64-e098-4b3b-bab7-e5fefba6f8f4)

### Stable (Working)

For comparison, the same screenshots taken in the 0.2 stable:

![stable-character](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/90969776/d9cf0e16-e9f1-4545-81f9-a9e4653e2a36)

![stable-raspberry](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/90969776/e25b5f1e-2b11-49be-9071-c6fb3d7d3fd9)

![stable-underbrush](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/90969776/333425f2-c845-47ae-9274-4f2668373b87)

### Versions and configuration

- OS: Linux 6.1.67
- Game Version: f5cccb87df
- Graphics version: Tiles
- Ingame language: English
- Mods: Just the defaults

**Comment by scarf005** [comment]
related: #3945
