### ISSUE TITLE
Skills trained by books are hidden on max skill level

### ISSUE THREAD

**Issue by Relgar** [cataclysmbnteam/Cataclysm-BN#4146]
### Describe the bug

When you have a high number of skill books available to read, some will start blanking out on what they can teach you and whether you have recipes yet to learn.

### Steps To Reproduce

1. Have a lot of books you can learn from or have learned from.
2. Shift + R

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/84274761/92414507-8d6d-4032-ad8c-9f4d47c5e776)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 0cc7b16 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 1
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    Mythical Martial Arts [MMA],
    Aftershock - Easydocs [AFS_Easydocs],
    Manual Bionic Installation [manualbionicinstall],
    No Addictions [No_Addictions],
    No Filthy Clothing [no_filthy_clothing],
    No Lifting Reqs [disable_lifting],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

**Comment by NerdPunkFu** [comment]
This isn't related to the number of books. BN does this when you have reached 10 in a skill. Here you seem to have reached 10 in fabrication and cooking. It's still a bad feature since it obfuscates information useful to the player, e.g. when looking for appropriate skill books for your NPC companions.
