### ISSUE TITLE
Abnormal behavior with transforms_into terrain

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#415]
# Describe the bug

Harvested underbrush left within the reality bubble, or generally any terrain that relies on `transforms_into` for seasonal transitions, will be left in its state well past the expected season length's worth of time needed for it to transform.

# Steps To Reproduce

1. Harvest underbrush in two areas, one within the reality bubble and one outside it.
2. Remain in the area for over a season's worth of time, depending on one's current season length setting.
3. Even having saved and loaded the game, the underbrush within your reality bubble should remain harvested, while those outside the reality bubble should be regrown.

# Expected behavior

Seasonal transitions updating properly within the reality bubble, or at worst regarding a save/load cycle to update them.

# Screenshots

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 2826c1f [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

# Additional context

This was first found with terrain from a mod that is constructed in a transforms_into state. After checking the JSON and further observation vanilla terrain seems to be affected as well, and following observations from @Coolthulhu pinned down the likely cause. Following this issue being fixed I'll make sure to retest that there isn't anything else affecting constructed `transforms_into` terrain separate from `transforms_into` terrain created by an `examine_action`, but that'll be something solely for me to worry about, since no constructable transforming terrain exists in vanilla.

Most of the findings on how this actually works (or rather, how it doesn't work and why) are thanks to Coolthulhu's observations on the relevant code during a conversation on the modder's discord. Relevant parts in particular to follow.

Suspected area in `transforms_into` code:
```
    if( season_of_year( calendar::turn ) != season_of_year( last_touched ) ||
        time_since_last_actualize >= calendar::season_length() ) {
        ter_set( p, ter.transforms_into );
    }
```

Following this, Coolthulhu looked at what `last_touched` looks like:
```
const time_point last_touched = calendar::turn - time_since_last_actualize;
```
> time_since_last_actualize is reset to current turn every single time the map is loaded into bubble.
> Meaning that if you want it to refresh, you need not to load it for a whole season after harvesting it.

Also worth noting though:
> It's actually map::restock_fruit, but that's like the only function that uses transforms_into.

**Comment by Coolthulhu** [comment]
Wait, false alarm. A really stupid mistake on my part: it's not `&&`, but `||`, so the actual condition is "season changes OR more than season passed since last update".
Now, it's still wrong because the latter part can cause a mid-season update, but it's nowhere near as wrong as my initial idea.

**Comment by chaosvolt** [comment]
Ah, odd. When I get home I need to see about doing some tests of my own to see if the behavior observed affects underbrush or not. Stuff came up and I hadn't yet had the chance to explore the full extent of the behavior here beyond what Chrom found from their tinkering with it.

**Comment by chaosvolt** [comment]
Implemented two tests to see how it behaves.

First test, I built an empty beehive and foraged through underbrush, then advanced time through debug repeatedly, saving and loading after hitting a season's length, having remained within the reality bubble the entire tijme. Even after advancing into autumn and repeating the save/load test, neither the underbrush nor the beehive had transformed.

Second test in a fresh start, I built and empty beehive and foraged through underbrush. Then, I waited a full season's worth of time while remaining in the area. Saving and loading after reaching the first day of summer revealed no change in the underbrush or the beehive. Just in case I continued, waiting until it was day 5 of summer (I had started on day 2 of spring if I recall, with 14-day season lengths), then saved, then loaded. Even after this, the underbrush remained harvested, and the beehive remained at the "empty beehive" stage.

Third test, this time a direct followup after loading from the second test. Walked due north until I hit a wall, making my reality bubble well away from where I did the second test, then walked back down south until I returned to my test site. Still no change. For good measure I did a save and load at the test site, and still no change.

Fourth test, again following from the third test. After loading back in to find nothing had changed, I walked back up to the building up north, saved and loaded there, then walked back down to the test site. Still no change. Finally I saved and loaded at the test site after all this, and no dice.

It having been a bit under a a season and a half after the foraging and construction, something definitely feels off in the wakwe of all these tests.

Game report for these tests:
```
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: d9db2c6 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    MST Extra [MST_Extra]
]
```

**Comment by Coolthulhu** [comment]
I was wrong about the mid-season update: it should never happen because the season will be different anyway, so it always updates on next season.

> First test, I built an empty beehive and foraged through underbrush, then advanced time through debug repeatedly, saving and loading after hitting a season's length

It's almost expected that everything will stay the same.
Saving updates the `last_touched` on all loaded submaps.

For update, you'd need to wait a season, teleport away, then teleport in.
This is because all the full-map updates happen on `actualize`, which happens on load (load into bubble, not necessarily from disk). Same for rotting food disappearing - this also only happens on `actualize`.

It would be possible to have something like `on_season_changed` event, but until there is something like fortress mode, it's low priority.

So far it seems that the bug could be summarized as:
Saving the game updates the `last_changed` of all the submaps in bubble, but doesn't call `actualize`.

**Comment by chaosvolt** [comment]
> For update, you'd need to wait a season, teleport away, then teleport in.

Then shouldn't have have been triggered by test four? Over a season had passed, the map was offloaded, then the map was loaded back in. The only functional difference was I walked instead of teleported, right?

**Comment by Coolthulhu** [comment]
> Then shouldn't have have been triggered by test four? Over a season had passed, the map was offloaded, then the map was loaded back in.

Alright, it should.
I re-read `map::saven` and it's "save changes in preparation for unload from `map`", so just when it goes out of the bubble, not "save to disk".

I thought about why does it need to update `last_touched` on unload and it has some cases where it is desirable:
* Funnels fill both in the bubble and on retroactive update
* Cosmetic fields (blood etc.) decay both in bubble and retroactively

So `last_touched` should be bumped.
The simplest solution would be to do a plant transform check right before saving the submap. Farmed plants don't need it since they store their own data in an item.

**Comment by chaosvolt** [comment]
Ah, hopefully that goes well then.
