### ISSUE TITLE
Hazardous waste sarcophagus has no roof

### ISSUE THREAD

**Issue by 0Monet** [cataclysmbnteam/Cataclysm-BN#4189]
### Describe the bug

The hazardous waste sarcophagus has no roof.
I expect a proper roof, not that.

### Steps To Reproduce

1. Go to the roof of the hazardous waste sarcophagus.
2. See the lack of roof.

### Screenshots

<img width="960" alt="no_roof" src="https://github.com/cataclysmbnteam/Cataclysm-BN/assets/146018959/b7368c57-4114-457e-94c0-0187c5871cbb">

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: f7842d4 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

**Comment by RedPine91** [comment]
It's odd for there to be no roof above the sewage pipes.

**Comment by RedPine91** [comment]
I'm inexperienced, but I took a look at the mapgen for this location.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/main/data/json/mapgen/hazardous_waste_sarcophagus.json

There's no explicit code for a roof.  Instead, it seems certain furniture automatically has a roof generated over it.  This furniture list, apparently, doesn't include the following "terrain": "t_sewage_pump", "t_sewage_pipe", "t_grate", "t_sewage".  

Changing the above terrain to automatically generate a roof would probably mess up outdoor locations that use these furniture, such as open sewers (unless they have a flag that prevents roof generation?).  

I'm guessing the best solution is to explicitly add a fully furnished roof to this location.

**Comment by RedPine91** [comment]
To implement a roof:

A roof would have to be added.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/0b5331a036ddc3ec30ab26828c9db84467d53fd4/data/json/mapgen/hazardous_waste_sarcophagus.json#L5

The roof would need to be spawned.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/0b5331a036ddc3ec30ab26828c9db84467d53fd4/data/json/overmap/overmap_special/specials.json#L1153

The roof would need to be recognized as an overmap tile.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/0b5331a036ddc3ec30ab26828c9db84467d53fd4/data/json/overmap/overmap_terrain/overmap_terrain_waste_junk.json#L84

For compatibility, also add the overmap tile for the alternate map key mod.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/0b5331a036ddc3ec30ab26828c9db84467d53fd4/data/mods/Graphical_Overmap/go_overmap_terrain_waste_junk.json#L110

I don't plan on working on this anytime soon, but if anyone's interested, these are the relevant files.
