### ISSUE TITLE
Turn off mp3 / music log spam

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#4190]
### Is your feature request related to a problem? Please describe.

Not a problem, but the log is spammed with music:

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/60fd3db2-1b63-4f66-a52e-7bfa8856790a)

### Describe the solution you'd like

Would be nice to be able to toggle the log spam off.

**Comment by RedPine91** [comment]
'+1

1) Simple solution: Reduce the frequency of the music log.
2) Simple solution: Option to reduce or eliminate the music log.
3) Moderate solution: The music log should only trigger when turning the MP3 on/off, getting deafened/undeafened, etc.  
4) Complex solution: The music log is given a flag that disables it when performing long tasks.  This flag could then be applied to other forms of logspam, such as NPCs.

My favorite is option 3.
