### ISSUE TITLE
BIO_IMMUNE is missing a JSON flag definition and errors if defined in the game

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#4261]
### Describe the bug

Whenever @scarf005 did https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3225 we needed a flag for monsters to be immune to biological damage it wasn't realized by any involved parties that BIO_IMMUNE exists in character.cpp but doesn't have a json flag definition so it errors out on usage. This seems like a minor fix but it's also fairly confusing that character and monster has separate flag names for the same effect. I think ideally we would migrate all damage immunity flags to be named the same, but for now we need a flag definition for BIO_IMMUNE.

I'm leaving a note here that refactoring all of the immunity flags in character.cpp is most ideal to avoid confusion about using the wrong flag.

### Steps To Reproduce

1. Check character.cpp for "BIO_IMMUNE"
2. Check monster.cpp for "BIOPROOF"
3. Check flags.json for "BIO_IMMUNE"

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/c9a772b6-e412-443d-b9f8-ac28fe801d91)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/bd84a4a8-261c-4b92-b016-7cf078b4410c)

### Versions and configuration

OS: Windows
OS Version: 10.0.19045.3448 (22H2)
Game Version: https://github.com/cataclysmbnteam/Cataclysm-BN/commit/ed1f287b503ccee2e01895015c1c87e5f8fcf643 [64-bit]
Graphics Version: Tiles
LAPI Version: 2
Game Language: English [en_US]
Mods loaded: [
Bright Nights [bn],
Craftable Gun Pack [craftgp],
Alternative Map Key [alt_map_key],
Fuji's Military Profession Pack [fuji_mpp],
Craftable Bullet Casings [CasingCrafting],
MST Extra [MST_Extra],
Tankmod: Revived [Tankmod_Revived],
Essence 2200 BN [Essence2200_BN],
Essence 2200 Tweaks [FoxTweaks],
Nonperishable Overhaul [Nonperishable_Overhaul],
No Addictions [No_Addictions],
Limit Fungal Growth [limit_fungal_growth],
Disable NPC Needs [no_npc_food],
Simplified Nutrition [novitamins],
OMT Resources [omt_resources],
Flowing Water [flowing_water],
No Filthy Clothing [no_filthy_clothing],
Cataclysm++ [Cata++]
]

**Comment by chaosvolt** [comment]
Weird, `EFFECT_BIO_IMMUNE` is properly defined for immunity from effects, just not `BIO_IMMUNE` for immunity from armor.
