### ISSUE TITLE
[Suggestion] Random cold/flu as option

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#427]
I get the reason those were removed, tedium vs. realism, but I liked these 2 small things. Some random cold / flu were nice to have tho. I'd like to have it as an option in settings :).

**Comment by Coolthulhu** [comment]
I don't like random diseases like those, but if someone were to submit a clean PR, I'd accept it.
My acceptance criteria:
* Written as `static` function(s) or functions in a namespace. Not dumped as another method of the bloated `player`/`Character` classes like it was before.
* Enabled through a mod.

Ideally, it would be just a mutation/spell/whatever that periodically rolls for infection, but that might not be possible without updating spell code to enable that. It would be a good update, but I don't know how easy/hard it would be.

**Comment by Unrepentant-Atheist** [comment]
I'm fine with it being enabled by a mod, either way as long as I can get some random flu or cold. :)

**Comment by Coolthulhu** [comment]
Unlikely to happen any time soon. I wouldn't accept a hardcoded implementation for something like this, meaning it would require a JSON-driven periodic event system.
