### ISSUE TITLE
Bug: No Seed Farming Crash persists

### ISSUE THREAD

**Issue by RedPine91** [cataclysmbnteam/Cataclysm-BN#4274]
### Describe the bug

Trying to farm with No Seed still crashes the game, even after a recent patch.

### Steps To Reproduce

1. Find a pre-existing farm with fully grown crops.
2. Place a "No Seed" zone over the crops to harvest them automatically.
3. Using auto farm crashes the game.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 0b5331a [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    Arcana/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Cars to Wrecks [cars_to_wrecks],
    Folding Parts pack [deoxymod],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    Faster Stamina Regen [stamina_regen_buff],
    Necropolis Actually Findable [necro_find],
    No Lifting Reqs [disable_lifting],
    SpeedyDex [speedydex]
]

### Additional context

 DEBUG    : invalid recipe id ""

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\recipe_dictionary.cpp
 LINE     : 65
 VERSION  : BN 0b5331a

**Comment by ekaratzas** [comment]
Hey @RedPine91. I see in your report that the git revision you are using is 0b5331a036ddc3ec30ab26828c9db84467d53fd4 .

However the recent fix came in at a newer revision, 05cb72e4e1a30e1a625921f35736e057bff6bac1 .

Could you please try a newer build?

**Comment by RedPine91** [comment]
Odd. Maybe I need to reinstall the CATA launcher?  I swear I've updated.

**Comment by RedPine91** [comment]
![Catacurrent](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/30212969/167b36d5-8c44-42c3-a2a1-f2b72168ea0e)
![Catanotcurrent](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/30212969/07b3487b-c941-40f3-bdb1-bf79799cc695)
Must be a launcher issue.  My bad!
