### ISSUE TITLE
Acid and Fire Protection on Armors Does Not Work

### ISSUE THREAD

**Issue by RobbieNeko** [cataclysmbnteam/Cataclysm-BN#4275]
### Describe the bug

Acid and Fire armor values do not work properly and remain 0

### Steps To Reproduce

Load into a release after 02-07 (including 02-07)
Look at any armor that should have non-zero values for these
Be immensely confused as to why your turnout suit has no fire protection

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/30732426/0bd1d2f0-dcd4-4b6a-91f0-28125deb73b6)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/30732426/c0cb1a84-1c92-4d38-ae64-8acabf64cf90)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 02e1090 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

This is the data for 02-07, but the same issue is present in all versions afterwards

### Additional context

Thanks to MisterWytt for bringing this to Chaosvolt and I's attention

**Comment by chaosvolt** [comment]
Cause is suspected to be: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3930
