### ISSUE TITLE
Windows MSVC builds not building pt.3

### ISSUE THREAD

**Issue by End3r991** [cataclysmbnteam/Cataclysm-BN#4276]
### Describe the bug

Since the 83ac7d2 (2024-02-28) release Windows MSVC builds not building :/

### Steps To Reproduce

Devs try build, builds not building

### Versions and configuration

OS: Windows
OS Version: 10.0.19045.4046 (22H2)
Game Version: https://github.com/cataclysmbnteam/Cataclysm-BN/commit/02e1090ea87707c41f106745fcc6e3f4cec7b7b0 [64-bit]
Graphics Version: Tiles
LAPI Version: 2
Game Language: []
Mods loaded: [
Bright Nights [bn],
Disable NPC Needs [no_npc_food],
Simplified Nutrition [novitamins],
No Rail Stations [No_Rail_Stations],
Prevent Zombie Revivication [no_reviving_zombies],
Limit Fungal Growth [limit_fungal_growth]
]

**Comment by chaosvolt** [comment]
Android builds also might be fucked. This time I tried re-running all failed runs and it didn't fix it like last time.

**Comment by scarf005** [comment]
https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/8104679345/job/22155904948#step:12:165

wonder why `msgfmt` is missing

**Comment by Unrepentant-Atheist** [comment]
https://stackoverflow.com/questions/9500898/compiler-error-msgfmt-command-not-found

https://unix.stackexchange.com/questions/516669/msgfmt-not-found-though-msgfmt-is-installed-via-package-manager

**Comment by scarf005** [comment]
both are linux solution. in this case, the error is coming from windows buildbot.

**Comment by SurFlurer** [comment]
I believe it's caused by an upgrade in git version ( from 2.43.0 to 2.44.0 ) in github's runner image.

DDA's solution: https://github.com/CleverRaven/Cataclysm-DDA/pull/72031
