### ISSUE TITLE
Extreme lag near malls at map shift with electric grids enabled

### ISSUE THREAD

**Issue by olanti-p** [cataclysmbnteam/Cataclysm-BN#430]
# Describe the bug
Walking near malls produces extreme (6-8s) lag on every map shift (every 12 tiles).

# Steps To Reproduce
1. Enable "Electric grid testing"
2. Find a mall
3. Teleport near it
4. Try walking in a straight line

# Expected behavior
No lag

# Screenshots
Single map shift
![image](https://user-images.githubusercontent.com/60584843/113137667-7f307d80-922d-11eb-81dc-84bcd76e2112.png)
The same `overmapbuffer::electric_grid_at()` shows up taking 97% when looking at the map through "Display overmap electric grids" debug tool.

# Versions and configuration
Build 1528 (15dce595572d265a33be57d0edaa04f5c016928d), compiled on Windows 10 x64 with Visual Studio. The only mod is Aftershock (it greatly increases mall spawn rate).

**Comment by Coolthulhu** [comment]
> The same overmapbuffer::electric_grid_at() shows up taking 97% when looking at the map through "Display overmap electric grids" debug tool.

At the moment, `overmapbuffer::electric_grid_at()` does not cache the grid, but rebuilds it from adjacency information.
That is, it does a flood fill over the grid.

**Comment by olanti-p** [comment]
Fixed by #500
