### ISSUE TITLE
negative armor resistances on windows mxe build

### ISSUE THREAD

**Issue by MisterWytt** [cataclysmbnteam/Cataclysm-BN#4300]
### Describe the bug

After the `2024-03-03` update that fixed the Fire/Acid resistances, it made a nasty side effect of giving certain items negative resistances. Seems to be mainly with watches, but I don't know which other items are affected by this.

### Steps To Reproduce

1. Open Game.
2. Find a Watch (Smart Watch and Diver's Watch is what I've seen)
3. Be amazed that you are over negative 2 billion vulnerable to all the main resistances except Fire and Acid.

### Screenshots

![Resistance](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/46728252/04d433f1-2578-4689-9759-b1c48830efee)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 8bb6364 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

**Comment by chaosvolt** [comment]
Most notably, it seems to do this depending on build.

`cbn-windows-tiles-x64-2024-03-04`:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/690464c8-a61f-4b5b-836c-e2de9c28ed3d)

`cbn-windows-tiles-x64-msvc-2024-03-04`:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/11582235/6040d072-b7d1-4274-953d-0213af807294)

**Comment by scarf005** [comment]
> After the 3-3-24 update

~~_there's no 3-3-24 but [`2024-03-03` release](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/tag/2024-03-03). please use the superior date format, [YYYY-mm-dd](https://en.wikipedia.org/wiki/ISO_8601)_~~

---

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/09b42fb9-d82c-4fb8-9031-49bd1d9092d4)

tested on linux 64bit, looks like an MXE issue.

**Comment by chaosvolt** [comment]
Good news at least, tested making watches cover the full body in the affected version and I don't explode, so it's not literally negative protection.

**Comment by Darigar** [comment]
Windows v0.6.0 still effective.
also for haipins, belts (and ammo belts for weapons), earrings, rings, stethoscope (and surely more)

**Comment by vitalyo7** [comment]
Made a fix for the calculation, will submit a PR for it.
Long story short: Zero thickness items were return NaN for the armor values. Now they should return 0.
PPS: Because of NaN some compilers would handle the result differently, hence why MSYS was impacted but others were not.
