### ISSUE TITLE
Crash every time I open the Wear menu

### ISSUE THREAD

**Issue by TheAmazingDaito** [cataclysmbnteam/Cataclysm-BN#4302]
### Describe the bug

Exactly as the title says, every time I press shift + w to wear something, the game crashes. Doesn't matter which start I pick or character archetype.

### Steps To Reproduce

1. Load the game.
2. Press shift + w
3. The game crashes

### Versions and configuration

- OS: Windows 11
- Game Version: BN 2024-03-04

### Additional context
UPDATE: I forgot to mention that I'm using the [Cataclysm++ Mod](https://github.com/Noctifer-de-Mortem/nocts_cata_mod)
[Immokalee.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/14500099/Immokalee.zip)
[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/14500106/debug.log)
There was no crash.log file generated.

**Comment by MargarineMastodon** [comment]
[crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/14500196/crash.log)

**Comment by TheAmazingDaito** [comment]
> [crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/14500196/crash.log)

Sorry, I'm new to this. What do I do with the file?

**Comment by TheAmazingDaito** [comment]
I'm currently disabling different mods until I narrow down if one is causing the problem.
