### ISSUE TITLE
Realtime turn progression without movement costs

### ISSUE THREAD

**Issue by neuks** [cataclysmbnteam/Cataclysm-BN#431]
# Is your feature request related to a problem? Please describe.
Currently, when realtime turn progression is turned on, even though the monsters and NPCs are moving in intervals, when the character moves, extra movement cost is still applyed, so that the monster's movement is accelerated at the time, which makes the 'realtime mode' less realtime.

# Describe the solution you'd like
Could there be a way to turn the character's movement cost off in 'Realtime turn progression' mode, so that it becomes more like other RPGs which movement is even between the character and mosters, and appears more natural.

# Additional context
This is just my own opinion that I came about playing in the 'Realtime turn progression' mode, just a small suggestion, but if it could be implemented, or through a seperate Realtime option switch, the game could be more fun.

Thanks dudes.

**Comment by Coolthulhu** [comment]
"Realtime" mode is barely supported. A more correct name would be "forced turn end", as this is the only thing this "mode" does.
The only real use for realtime I see would be a hypothetical fortress mode.
