### ISSUE TITLE
Negative calories on some of the food recipes

### ISSUE THREAD

**Issue by Lamandus** [cataclysmbnteam/Cataclysm-BN#4317]
### Describe the bug

On some recipes, it shows negative calories.

### Steps To Reproduce

Maybe it has something to do that my character has meat intolerant? Can't say how reproducable it is.

### Screenshots

![grafik](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/b1eb2dc9-c2cd-4c46-93fc-217cca2d769c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3235 (23H2)
- Game Version: 0ae5651ad67b [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    meins [meins],
    Prevent Zombie Revivication [no_reviving_zombies]
]

**Comment by RobbieNeko** [comment]
Also experienced, and on a character that has no intolerances. 

_Negative calorie honey sandwhich_
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/30732426/f7120209-1ff6-4b4b-96cc-ac3d110a65cd)

**Comment by Lamandus** [comment]
![grafik](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/0f5a6155-7548-4be6-ab3f-8ceaf8d5f2f9)
Flour already has something with negative calories.

**Comment by Lamandus** [comment]
the items themselves are fine when spawned, so there has to be a problem with something while crafting maybe?

**Comment by RobbieNeko** [comment]
Having checked, all of the ingredients for flour have normal calories (at least from the spawn menu)

**Comment by Lamandus** [comment]
I will check the files if I find something with negative calories, a json check

**Comment by Lamandus** [comment]
no files seems to use negative calories, so I will just remove ingredients until the bad one shows up (I suspect rice bran)
