### ISSUE TITLE
64bit MSCV not building

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#4322]
### Describe the bug

64bit msvc experimental releases are not being build.

### Steps To Reproduce

1. Check the release page
2. See no 64bit msvc build
3. Cry

### Versions and configuration

No info since there's no....game?

**Comment by chaosvolt** [comment]
Good news, seems it was a one-off error again and re-running the job fixed it: https://github.com/cataclysmbnteam/Cataclysm-BN/releases
