### ISSUE TITLE
Activating "Simplified Nutrition" mod causes a ranch quest to become incompletable

### ISSUE THREAD

**Issue by NerdPunkFu** [cataclysmbnteam/Cataclysm-BN#4350]
### Describe the bug

The third quest for the ranch nurse requires the player to collect 200 multivitamin pills. However, the "Simplified Nutrition" or no vitamins mod included in the repo prevents multivitamins from spawning.

### Steps To Reproduce

1. Make new game with the "Simplified Nutrition" mod.
2. Search various locations like grocery stores, hospitals and pharmacies.
3. Find no multivitamins, thus making completing the third nurse quest in the ranch impossible.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: dd8cf05 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    No Fungal Monsters [No_Fungi],
    Arcana and Magic Items [Arcana],
    BL9-100%-monster-resilience-version [BL9_100monres],
    Cataclysm++ [Cata++],
    C.R.I.T. Expansion [crt_expansion],
    Magical Nights [MagicalNights],
    Teleportation [teleportation_tech],
    Aftershock [aftershock],
    Steampunk Mod [steampunk_arcanum],
    Advanced Technologies [advtech],
    Bionics Systems Recipes [bio_recipes],
    Craftable Gun Pack [craftgp],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Pneumatic fun [pneumo_fun],
    Beta National Guard Camp [national_guard_camp],
    Morlock Village [morlock_village],
    Caches [P_Caches],
    Blazemod - Vehicle Additions Pack [blazemod],
    Mutant NPCs [mutant_npcs],
    NPC Recruitment Options [recruitment_options],
    Merchant Mod [Merchant],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Necropolis Actually Findable [necro_find],
    Stats Through Kills [stats_through_kills],
    Targeted Mutations [TaMu],
    Manual Bionic Installation [manualbionicinstall],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/C.R.I.T. Patchmod [Arcana_Crit_Patch],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Magical Nights Patchmod [Arcana_MagiclalNights_Patch],
    Tankmod: Revived [Tankmod_Revived],
    Roadheader and other mining vehicles [Heavy miners],
    Project: Pack Rat [Jake's_Squirrel_mod]
]
OS: Windows 10

**Comment by KheirFerrum** [comment]
We should probably also reduce the number of vitamin pills required, because that's a _lot_ of fucking pills.
