### ISSUE TITLE
The chemists sells drugs in prescription bottles which do not exist in Bright Nights

### ISSUE THREAD

**Issue by NerdPunkFu** [cataclysmbnteam/Cataclysm-BN#4351]
### Describe the bug

Some of the things the chemists sells in bulk through the dialog tree spawn inside a prescription bottle. However, since it's not a valid item in Bright Nights, this causes a recurring error message. Specifically aspirin, antibiotics and antifungals are affected.

### Steps To Reproduce

1, Go to the chemist NPC
2. Buy some aspirin, antibiotics or antifungal drugs from him
3. Enjoy the error message :P

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: dd8cf05 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    No Fungal Monsters [No_Fungi],
    Arcana and Magic Items [Arcana],
    BL9-100%-monster-resilience-version [BL9_100monres],
    Cataclysm++ [Cata++],
    C.R.I.T. Expansion [crt_expansion],
    Magical Nights [MagicalNights],
    Teleportation [teleportation_tech],
    Aftershock [aftershock],
    Steampunk Mod [steampunk_arcanum],
    Advanced Technologies [advtech],
    Bionics Systems Recipes [bio_recipes],
    Craftable Gun Pack [craftgp],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Pneumatic fun [pneumo_fun],
    Beta National Guard Camp [national_guard_camp],
    Morlock Village [morlock_village],
    Caches [P_Caches],
    Blazemod - Vehicle Additions Pack [blazemod],
    Mutant NPCs [mutant_npcs],
    NPC Recruitment Options [recruitment_options],
    Merchant Mod [Merchant],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Necropolis Actually Findable [necro_find],
    Stats Through Kills [stats_through_kills],
    Targeted Mutations [TaMu],
    Manual Bionic Installation [manualbionicinstall],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/C.R.I.T. Patchmod [Arcana_Crit_Patch],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Magical Nights Patchmod [Arcana_MagiclalNights_Patch],
    Tankmod: Revived [Tankmod_Revived],
    Roadheader and other mining vehicles [Heavy miners],
    Project: Pack Rat [Jake's_Squirrel_mod]
]
OS: Windows 10

### Additional context

Oh, and the black powder he sells is inside a 3L jar even though it's 10L of powder. Must be some spatial distorting black magic he uses or something.

**Comment by chaosvolt** [comment]
Nah, items spawned by quests and dialogue can be set to spawn in a container, like how a lot of drugs spawn in small plastic bottles and the like, flour in cardboard boxes, etc. The error is because the DDA version cites an item ID that doesn't exist, because they decided they needed to add minute permutations of small plastic containers for maximum flavor I guess.

**Comment by Lamandus** [comment]
Is the chemist a vanilla NPC?

**Comment by scarf005** [comment]
> Is the chemist a vanilla NPC?

they're ported in #3917.
