### ISSUE TITLE
Land mines explosive content inconsistent with power and weight compared to grenades and real life equivalents

### ISSUE THREAD

**Issue by NerdPunkFu** [cataclysmbnteam/Cataclysm-BN#4381]
### Describe the bug

In game land mines yield 75 units of composition b while grenades yield 200. In testing they did similar amount of damage and even though their other components are the same, the land mines also weight almost 6 times more than grenades do.

IRL offensive grenades have less explosives in them than land mines do. For comparison, [M67 grenades](https://en.wikipedia.org/wiki/M67_grenade), which are the most common grenades in US service, have contains 180g of composition b in them while [M16A2 anti-personnel mines](https://en.wikipedia.org/wiki/M16_mine) have 601g charges and [claymore anti-personnel mines](https://en.wikipedia.org/wiki/Claymore_mine) have 680g charges. The mines use different explosives(TNT or C4), but the explosive effect is still significantly more than a grenade. A smaller "toepopper" mine also exists in US inventory, [the M14](https://en.wikipedia.org/wiki/M14_mine) which only has 29g of explosives and weighs a total of 99g. The in-game landmines seem to have a weight(2.4kg) in-between that of claymores(1.6kg) and M16s(4.1kg) which suggest an explosive charge more in line of what they have.

I suggest that the amount of composition b in-game land mines yield is increased in line with real world examples and their in game weight(around 600 composition b or equivalent seems about right). The crafting recipe for making your own mines actually doesn't even take actual explosives, aside from gunpowder which isn't as effective, so they should be added. Fuel, shotgun shells, grenades and other garbage in the crafting recipe should be removed entirely and if nails or bearings are to be used for fragmentation then those need to be added to the disassembly recipe as well.

In the long term land mines(and grenades while we're at it) should be properly expanded to reflect real life equivalents. Currently their effect is hardcoded, but in the future M14 mines that harm only your legs, M16 mines that pop up and blow up in your face and claymores that are triggered by tripwire or -laser should shoot a blast of frag at you should be added. In addition, anti-tank mines that only blow up when a vehicle or character in power armor(most AT mines are set off when somewhere over a 100kg pressure is applied to the fuze so a particularly heavy character might have a chance to set one off) moves over it but have significantly more explosive power should be implemented.

### Steps To Reproduce

Get a mine and grenade and compare. Maybe let them blow up in your face too.

### Screenshots

Land mine and grenade info in-game:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/83405359/30dc2346-4e64-4366-b02a-5eb2146f8c52)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/83405359/b7fe2e9b-b7b3-48eb-b65e-1154b8f08d33)

Damage tests with the same character without any clothing on, but with some Bionic armor:
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/83405359/b08c7876-7cf0-4bbc-aff7-2e93523e7c96)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/83405359/22f60a26-22a4-46f6-81dc-e77f7a15ef9a)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: dd8cf05 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    No Fungal Monsters [No_Fungi],
    Project: Pack Rat [Jake's_Squirrel_mod],
    Arcana and Magic Items [Arcana],
    BL9-100%-monster-resilience-version [BL9_100monres],
    Cataclysm++ [Cata++],
    C.R.I.T. Expansion [crt_expansion],
    Magical Nights [MagicalNights],
    Teleportation [teleportation_tech],
    Aftershock [aftershock],
    Steampunk Mod [steampunk_arcanum],
    Advanced Technologies [advtech],
    Bionics Systems Recipes [bio_recipes],
    Craftable Gun Pack [craftgp],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Pneumatic fun [pneumo_fun],
    Beta National Guard Camp [national_guard_camp],
    Morlock Village [morlock_village],
    Caches [P_Caches],
    Blazemod - Vehicle Additions Pack [blazemod],
    Mutant NPCs [mutant_npcs],
    NPC Recruitment Options [recruitment_options],
    Merchant Mod [Merchant],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Necropolis Actually Findable [necro_find],
    Stats Through Kills [stats_through_kills],
    Targeted Mutations [TaMu],
    Manual Bionic Installation [manualbionicinstall],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/C.R.I.T. Patchmod [Arcana_Crit_Patch],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/Magical Nights Patchmod [Arcana_MagiclalNights_Patch],
    Tankmod: Revived [Tankmod_Revived],
    Roadheader and other mining vehicles [Heavy miners]
]

### Additional context

Here are my fixed crafting recipe and disassembly recipe for land mines. For crafting I added bone glue, changed the fragmentation element to be the same as the scrap loaded 00 shot recipe just 10x to be in line with what it was before, got rid of all that random nonsense that were useable as explosive and instead used the same lists as other explosives used equivalent in amount to 600 composition b and lastly I added the option to use fuses for landmines since for example the M16 mine uses a black powder fuse(there should be a mechanism to light it when stepped on so maybe a "makeshift fuze" item should be added that is made of fuse and some method to light it e.g. flint and steel). For disassembly I just increased the composition b amount to 600 and added bearings as frag.

```
{
    "type": "recipe",
    "result": "landmine",
    "category": "CC_OTHER",
    "subcategory": "CSC_OTHER_TRAPS",
    "skill_used": "traps",
    "skills_required": [ "mechanics", 3 ],
    "difficulty": 5,
    "time": "10 m",
    "reversible": true,
    "book_learn": [ [ "manual_traps_mil", 5 ] ],
    "qualities": [ { "id": "SCREW", "level": 1 } ],
    "components": [
      [ [ "superglue", 1 ], [ "bone_glue", 1 ], [ "duct_tape", 75 ] ],
      [
        [ "scrap", 3 ],
        [ "steel_chunk", 1 ],
        [ "canister_empty", 1 ],
        [ "clay_canister", 1 ],
        [ "can_food_unsealed", 1 ]
      ],
      [
        [ "scrap", 10 ],
        [ "nail", 100 ],
        [ "bb", 200 ],
        [ "solder_wire", 100 ],
        [ "platinum_small", 40 ],
        [ "gold_small", 40 ],
        [ "bearing", 50 ],
        [ "lead", 70 ],
        [ "silver_small", 70 ],
        [ "bismuth", 70 ],
        [ "shrapnel", 40 ]
      ],
      [ [ "volatile_explosive", 75, "LIST" ], [ "stable_explosive", 75, "LIST" ], [ "military_explosive", 75, "LIST" ] ],
      [ [ "delay_fuze", 1 ], [ "fuse", 1 ] ]
    ]
}
```

```
{
    "type": "uncraft",
    "result": "landmine",
    "skill_used": "fabrication",
    "difficulty": 4,
    "time": "50 s",
    "qualities": [ { "id": "SCREW", "level": 1 } ],
    "components": [ [ [ "delay_fuze", 1 ] ], [ [ "canister_empty", 1 ] ], [ [ "bearing", 50 ] ], [ [ "chem_compositionb", 600 ] ] ]
}
```

**Comment by scarf005** [comment]
makes sense, could you open a pull request based on suggested changes?

**Comment by NerdPunkFu** [comment]
> makes sense, could you open a pull request based on suggested changes?

Done #4389
