### ISSUE TITLE
VS compiling broken

### ISSUE THREAD

**Issue by Wad67** [cataclysmbnteam/Cataclysm-BN#44]
# Describe the bug

sdl_wrappers.h has includes for legacy SDL outside the if/else block

# Steps To Reproduce

Follow COMPILING-VS-VCPKG.md
Get SDL.h related errors

# Expected behavior

Following COMPILING-VS-VCPKG.md should work

# Additional context

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/61bbfc8ee69ebd6792219761f4acde020f373e0b/src/sdl_wrappers.h#L19-L21

**Comment by Firestorm01X2** [comment]
I have same issue. I've dig main repo and dound this:
https://github.com/CleverRaven/Cataclysm-DDA/issues/41506
https://github.com/CleverRaven/Cataclysm-DDA/issues/41894
https://github.com/CleverRaven/Cataclysm-DDA/pull/41908

I have suspision that it is related.

**Comment by Firestorm01X2** [comment]
However commenting:
 #include "SDL.h" 
 #include "SDL_image.h" 
 #include "SDL_ttf.h" 
Works also,

**Comment by Firestorm01X2** [comment]
Scracth that- I've forgot to set Working directory.
![screenshot 2020-09-12 001vs](https://user-images.githubusercontent.com/17512620/92977446-bf006500-f495-11ea-855e-2a3c7214c4a1.png)

After coomenting
#include "SDL.h"
#include "SDL_image.h"
#include "SDL_ttf.h"
Gae build and working with debug in Visual studio

**Comment by Firestorm01X2** [comment]
@Coolthulhu this issue probably can be closed now.
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/53

**Comment by Coolthulhu** [comment]
As far as I recall, if in a PR you write something like "Fixes #issue" (one line), it automatically close the issue when merged.
