### ISSUE TITLE
Consume Menu (E) Closes After Consuming an Item

### ISSUE THREAD

**Issue by yay855** [cataclysmbnteam/Cataclysm-BN#4423]
### Describe the bug

Unlike in prior versions, the (E)at menu now closes itself after eating or using a single thing.

### Steps To Reproduce

1. Press E to open consume menu.
2. Use item in consume menu
3. Item in consume menu is used, consume menu closes

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 68bf13e [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Elevated bridges [elevated_bridges],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Aftershock [aftershock],
    No Acid Zombies [No_Acid_Zombies],
    No Explosive Zombies [No_Explosive_Zombies],
    No Fungal Monsters [No_Fungi]
]

**Comment by scarf005** [comment]
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/2a5ed52e-397c-466e-9636-d752ffdbb18c

I was unable to reproduce the issue, were there any changes in graphic options? maybe the issue might be OS specific?

**Comment by Lamandus** [comment]
I have a rather samey problem. The menu doesn't close, but it won't show up. It is still there, but isn't shown, can be reproduced with "yes / no " prompt messages, for example, deep water. You can't move, can press the hotkeys tho.

**Comment by Lamandus** [comment]
can also be reproduced with auto travel on the map, prompt will not show up every time, maybe 66% of times.  
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/56e872af-ad96-4bca-a59e-4279e7904b3a)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/e7f3bb68-f500-4725-a1f3-095bf5aef521)

**Comment by Lamandus** [comment]
#4414 seems to be the problem. I get in contact with scarf.

**Comment by scarf005** [comment]
does the issue persist after disabling vsync (and restarting)?
