### ISSUE TITLE
Latest experimental fails to launch on MacOS Sonoma (14.3)

### ISSUE THREAD

**Issue by kaebiene** [cataclysmbnteam/Cataclysm-BN#4443]
### Describe the bug

The latest experimental threw errors pertaining to missing a .dylib needed for launching:
libjxl_cms.0.10.dylib

```
dyld[56142]: Library not loaded: @rpath/libjxl_cms.0.10.dylib
  Referenced from: <FF607BC3-6CBC-39F6-ACAE-45C05F4238C1> /Applications/Cataclysm BN 2024 Apr/Cataclysm.app/Contents/Resources/libjxl.0.10.dylib
  Reason: tried: '/Applications/Cataclysm BN 2024 Apr/Cataclysm.app/Contents/Resources/../lib/libjxl_cms.0.10.dylib' (no such file), '/usr/local/lib/libjxl_cms.0.10.dylib' (no such file), '/usr/lib/libjxl_cms.0.10.dylib' (no such file, not in dyld cache)

```
I fixed this on my end by installing the universal variant of libjxl ([MacPorts](https://ports.macports.org/port/libjxl/details/)) and copy-pasting the lib to Cataclysm.app/Contents/Resources, but this most likely isn't ideal for every player. 

This is my first bug report, so apologies if I'm missing any information!

### Steps To Reproduce

1. Start Cataclysm.app
2. App appears on dock and instantly closes
3. Start cataclysm-tiles within Cataclysm.app
4. Missing dylib error

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 14.3.1; Build: 23D60; 
- Game Version: 69fcc9c [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn]
]
- arm64

**Comment by micheldebree** [comment]
Same here with the official 0.6.0 release

**Comment by univeous** [comment]
If you're using Apple silicon, I believe the latest macOS arm version solves this issue
Try [this](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/download/2024-06-06/cbn-osx-tiles-arm-2024-06-06.dmg)

**Comment by micheldebree** [comment]
Yup that works! Thanks


> If you're using Apple silicon, I believe the latest macOS arm version solves this issue Try [this](https://github.com/cataclysmbnteam/Cataclysm-BN/releases/download/2024-06-06/cbn-osx-tiles-arm-2024-06-06.dmg)
