### ISSUE TITLE
Crash when walking away from a dying NPC

### ISSUE THREAD

**Issue by Soadreqm** [cataclysmbnteam/Cataclysm-BN#45]
Game version: 6c92546 (64-bit)

Operating system: Windows 10 Pro N 2004

Tiles or curses: Tiles

Mods active: Dark Days Ahead, No Rail Stations

### Expected behavior
No crash

### Actual behavior
Game crashes, producing logfile [crash.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5164160/crash.log)

### Steps to reproduce the behavior
Load savefile [crash.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/5164148/crash.zip) and walk south. Happens every time for me, though the amount of steps I need to take varies. I think the actual trigger is the NPC dying outside my field of view - it doesn't happen if I hang around and wait for the zombies to kill her, and then walk away.

**Comment by Coolthulhu** [comment]
The save was very helpful.
The issue is NPC burning while prone. It would hit a fake bodypart that exists to make code simpler, but should not actually be hit.
