### ISSUE TITLE
Eatable stuff with zero calories gets auto eaten

### ISSUE THREAD

**Issue by VissValdyr** [cataclysmbnteam/Cataclysm-BN#4521]
### Describe the bug

This goes out to @chaosvolt since he did the latest changes in the auto eat behavior.

Sausage casings are getting eaten even when they don't have a nutritional value.

### Steps To Reproduce

1. Drop sausage casings into auto eat zone
2. Look how the player eats it without reason.

### Screenshots

![Screenshot_20240424-213240_Cataclysm BN (experimental)](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167661460/ab489c0c-3403-427c-9505-e67059ff0b59)
![Screenshot_20240424-213329_Cataclysm BN (experimental)](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167661460/63af4e1a-a98c-4f10-8b0c-ce2908a989b3)

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-G960F; Release: 10; Incremental: G960FXXUHFVG4; 
- Game Version: 017122d [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Lootzones [Lootzone],
    No Filthy Clothing [no_filthy_clothing]
]

### Additional context

Suggested fix: ignore anything that has a calories value of 0.

**Comment by RoyalFox2140** [comment]
Items with 0 calories and no vitamins should not be classified as food in the JSON. You can use rocks, soil, and any other valid item for food recipes and the game will not care beyond mentioning something is made of soil (which itself can be ignored via nutrient override flag on food). 

Any valid cooking item like sausage casings should be classified as a different item category like spare parts, and the type switched to generic, it will still work for cooking. If some have calories and some don't based on what its made from (gut casings versus paper casings) then you can add the unsafe consume flag so it won't be auto eaten at 0 calories.

**Comment by VissValdyr** [comment]
> Items with 0 calories and no vitamins should not be classified as food in the JSON. You can use rocks, soil, and any other valid item for food recipes and the game will not care beyond mentioning something is made of soil (which itself can be ignored via nutrient override flag on food).
> 
> Any valid cooking item like sausage casings should be classified as a different item category like spare parts, and the type switched to generic, it will still work for cooking. If some have calories and some don't based on what its made from (gut casings versus paper casings) then you can add the unsafe consume flag so it won't be auto eaten at 0 calories.

Yes, but seeds fell into the same problem, it is considered eatable, so it will be eaten, even with no bonus for the player, to avoid it, we should consider adding the rule if zero calories, no auto eat.

**Comment by RoyalFox2140** [comment]
Seeds really shouldn't be edible at all either since that's a noob trap.
