### ISSUE TITLE
Butchery yield needs to be capped

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#4523]
### Describe the bug

Butchery yields is based on butchering quality which is good, but it has no cap to yield. With high enough quality you can gain more products than the creature weighs.

### Steps To Reproduce

1. Use a test item with a ridiculous butchering quality
2. Find something to butcher
3. Do it.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/805e45b0-660a-4abe-8272-cb2d2063243d)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/a57a3e69-5a04-4f18-9eb7-dbe8a4c842ed)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/112293514/8f070a8c-7e75-43b0-b4e9-64803aa3636b)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3448 (22H2)
- Game Version: 35a8baa [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 BN [Essence2200_BN],
    Essence 2200 Tweaks [FoxTweaks],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    OMT Resources [omt_resources],
    Flowing Water [flowing_water],
    No Filthy Clothing [no_filthy_clothing],
    Cataclysm++ [Cata++],
    No Wasps [No_Wasps]
]

**Comment by VissValdyr** [comment]
Butcher quality is only affecting negative numbers. Butcher quality only affects speed. @Coolthulhu said so years ago.

**Comment by VissValdyr** [comment]
But maybe for the low values we thing are adequate (till 50), so breaking it for the sake of breaking it... Not sure if it should be considered to be a bug then

**Comment by RoyalFox2140** [comment]
A cap is essentially required because any bionics like the surgical scalpels, or any fictitious new item or furniture we add to increase butchery speed via high butchering quality is going to cause issues with preservation of mass, we could never add an Auto-Butcher furniture that gives 100% yield and in half the time of a human because there is no cap at 100%. (That is ignoring other limitations with power tools not using charges when used as a tool.)

A cap should also be one of the easiest changes to make so futureproofing the code here is worthwhile. We can't reasonably expect to always use 50 butchering quality for the remainder of the project.
