### ISSUE TITLE
Stretchy arm dragonfly naiad.

### ISSUE THREAD

**Issue by Dracque** [cataclysmbnteam/Cataclysm-BN#4544]
### Describe the bug

The monster's description mentions that "its folded lower jaw changed into something resemblig a barbed spear" which I assume means it uses said lower jaw to do reach attacks.
Yet in game the message log says the naiad uses its arm to attack from a distance.

+ Typo : resemblig -> resembling

### Steps To Reproduce

1. Create character.
2. Find or spawn a dragonfly naiad.
3. Move to two tiles away from it.
4. Wait for the reach attack.
5. Check message log.

### Screenshots

![Emil _2024-04-28_11-03-22_+0100](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/23fafbdb-0712-4ccc-925c-265c7a0d8b43)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 777e9d0 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Cataclysm++ [Cata++],
    Arcana and Magic Items [Arcana],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    MST Extra [MST_Extra],
    Disable NPC Needs [no_npc_food],
    Limit Fungal Growth [limit_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Faster Stamina Regen [stamina_regen_buff],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived]
]

**Comment by RoyalFox2140** [comment]
I tried looking at this a few days ago and I think it's because stretch attacks have a hardcoded attack message to reference the arm.
