### ISSUE TITLE
Remove LIGHTFUR and SCALES mutation from the CHIMERA.

### ISSUE THREAD

**Issue by Vektor01A** [cataclysmbnteam/Cataclysm-BN#4567]
### Is your feature request related to a problem? Please describe.

Mutations LIGHTFUR and SCALES are listed in the game code as chimera mutations.
![1](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/158268813/9febd123-323e-4b92-bf7a-1bab15386345)
![4](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/158268813/fba3bc17-e3ae-4376-8b86-822bd58e2ebf)
But CHIMERA alrde have her PATCHSKIN.
![2](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/158268813/5250f820-8984-483c-9fa7-993469c0c563)
Because of this, they alternate when you mutating.
![5](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/158268813/17d0d883-5d97-439d-a9ef-ec8f0accd833)

### Describe the solution you'd like

All you need to do to fix this is to delete CHIMERA from LIGHTFUR and SCALES.
![3 5](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/158268813/7b8f998f-961c-4f2a-b02d-6a1da6f355ea)
![4 5](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/158268813/8c37e71a-370f-412c-9294-c2a113f56789)
And then the problem will go away.

**Comment by VissValdyr** [comment]
Since you went into the code, why weren't you PRing it? We are happy to find more contributers all the time.

**Comment by VissValdyr** [comment]
> > Since you went into the code, why weren't you PRing it? We are happy to find more contributers all the time.
> 
> Kindly don't do the DDA "fix it yourself" thing when someone opens an issue for us, thanks.
> 
> As for actually fixing this, I might PR a fix when I get the chance. Question though, would it be more interesting to have it just straight-up remove fur and scales from the mutation catergory, or would it be better to allow chimera to still mutate fur or scales at random initially, but then ensure that it will always progress to the patchwork mutation afterwards? I assume that's what's supposed to be happening with that trait but its current config lacks the required prereq and `changes_to` hooks to create a one-way relationship.

It was rather a "hey, you seem to find the problem, if you want you can PR it yourself and we will happily assist you in the progress, if there are any problems. If not, anyone else can do it."

Don't expect the worst in people, all the time...

**Comment by chaosvolt** [comment]
You need to work on your phrasing. We don't need to scare off a new contributor with your confrontational wording.

I've already got the PR up, so we're done here unless you have anything relevant to add, such as whether it'd be better to remove the mutations from that category entirely vs chaining them as the PR currently does.
