### ISSUE TITLE
alt-Keys don't work in Build 1605

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#457]
# Describe the bug

alt-Keys disabled in build 1605 but not 1602.

# Steps To Reproduce
1. Download build 1605 and 1602
2. Start games
3. Go to Keybind and try alt+ctrl+Q (or right alt + Q) for @ .
4. Doesn't work in 1605, works in 1602.

# Expected behavior

alt-Keys should work in both builds

**Comment by Zireael07** [comment]
Probably side effect of https://github.com/cataclysmbnteam/Cataclysm-BN/pull/455 which was supposed to prevent accidental alt-tabbing out of game.

**Comment by Unrepentant-Atheist** [comment]
Still present in Build 1626

**Comment by Unrepentant-Atheist** [comment]
Ah man, still there with Build 1659
