### ISSUE TITLE
Metal charcoal kiln is not better than its rock counterpart

### ISSUE THREAD

**Issue by 0Monet** [cataclysmbnteam/Cataclysm-BN#4581]
### Describe the bug

The metal charcoal kiln has the same capacity (125 liter for the tile) and the same charcoal yield as the rock charcoal kiln, which is not good because the metal charcoal kiln is supposed to have a higher capacity due to the 4 metal tank (60L) it uses in its construction, and a better yield.

Also, its only positive point is that the most expensive element of its construction (metal tank (60L)) takes only 2 minutes to make, which doesn't make sense on the other hand.

### Steps To Reproduce

1. Build metal and rock charcoal kilns.
2. Put the same amount of wood in both (like two logs).
3. Wait 6 hours.
4. They yield the same quantity of charcoal.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: fba1da1 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

**Comment by VissValdyr** [comment]
We also have a charcoal kin as a craft recipe (2 liter one), that needs a reconsideration as well

**Comment by VissValdyr** [comment]
About the rock vs. Metal comparison. Rock one is a lot easier to craft. So no one will ever consider to make the metal one. We need to make the metal one more usable, either making it a 60 l version instead, so it just needs a 60 l barrel (from the roof of the evac) to jumpstart. Maybe need hammering to make holes (or hand drill, but that is a rather late item to get). And it would be a good alternative to the rock version. Using only fabrication 1 for example. It is inferior to the rock version, but easier to acquire.

**Comment by RoyalFox2140** [comment]
@chaosvolt Fixed in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4929 when metal kilns can now hold 4 logs and rock ones 3 logs, unless we want to buff them further.

**Comment by chaosvolt** [comment]
![image](https://github.com/user-attachments/assets/4485571e-d083-4108-8f8b-094663139037)
