### ISSUE TITLE
Some regular animals drop "raw mutant offal" when butchered.

### ISSUE THREAD

**Issue by Dracque** [cataclysmbnteam/Cataclysm-BN#4610]
### Describe the bug

Seen animals with no sign of mutation (be it sprite or description) give mutant offals when butchered. Cougars, as seen in attached screenshot, and coyotes are the two I've noticed so far.

### Steps To Reproduce

1. Create a character.
2. Find/spawn wild non mutant wildlife.
3. Kill and field dress or butcher corpses.

### Screenshots

![Capture d'écran 2024-05-08 112530](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/2bc0e8ba-2e2e-468e-b15a-83f29e45a7c9)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 8dbe849 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Cataclysm++ [Cata++],
    Arcana and Magic Items [Arcana],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    MST Extra [MST_Extra],
    Disable NPC Needs [no_npc_food],
    Limit Fungal Growth [limit_fungal_growth],
    Stats Through Kills [stats_through_kills],
    Faster Stamina Regen [stamina_regen_buff],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived]
]

**Comment by VissValdyr** [comment]
Can you reproduce it without mods?

**Comment by Dracque** [comment]
Done as requested.

World's mods folder.
![Capture d'écran 2024-05-08 130810](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/72c3a300-d2b9-42fe-aa6b-ded5deb98aa6)

Spawned animals, likely missed some.
![Benny Goodson _2024-05-08_10-56-48_+0100](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/8f4d252f-2ed8-44eb-9679-e66bc3a9d462)

Used "field dress" on all corpses (character had 2 survival and used a folding knife).
Wolf, boar, cougar and one of the two coyotes gave "raw mutant offal". 
![Capture d'écran 2024-05-08 125818](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/68804eca-199a-4fd7-903a-226c63eb4029)

**Comment by VissValdyr** [comment]
@chaosvolt wasn't there a change lately for drops?

**Comment by chaosvolt** [comment]
Found the cause, @Zlorthishen's mutant animal PR added a redundant copy of `mammal_fur`: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4474/files#diff-1a85327b5ba4804e532347a5353fac3438330f350b454555569692f6c0a808b3R291
