### ISSUE TITLE
Barely any clear weather.

### ISSUE THREAD

**Issue by Dracque** [cataclysmbnteam/Cataclysm-BN#4620]
### Describe the bug

Not certain if it's intended or not (or if I've gotten very poor luck).

It was previously possible to semi-reliably raid towns at night with 8 perception or less and no night vision trait by waiting for both clear weather and a good moon phase (the closer to full moon the better).  With current weather it is often some form of drizzle or rain which counts as cloudy and prevents characters from benefiting from the added view range given by moon phases.

### Steps To Reproduce

1. Create a character with 8 perception or less.
2. Wait for night and compare cloudy vs fair view range.
3. Repeat 2 a few times with a day or two of interval to observe how the view range changes with the moon's phase.

### Screenshots

Weather map example.
![Capture d'écran 2024-05-10 153027](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/7c9a81f7-5eb5-4e29-ad5c-ca10ba902339)
8 Perception (Cloudy; wearing safety glasses (5 eye encumbrance)).
![Capture d'écran 2024-05-10 155144](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/0e08d567-52cb-4b60-9b0e-70855d0b99f0)
Same character with clear weather (shown as Fair).
![Capture d'écran 2024-05-10 155557](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/4890b819-7ca4-44a9-9417-19a5107971c2)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: d4e621e [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Lamandus** [comment]
Yeah, that's quite bad luck. Sometimes you really have a big cloud hanging over you. On one save it is the same for me, cloudy nearly all the time. On another I have a lot of Fair and even sunny weather. Maybe in a few in-game days weather clears up for you. If it persists for a in-game week or so, maybe we should tinker with the numbers once more.

**Comment by Lamandus** [comment]
![Screenshot_20240512_045021_Cataclysm BN (experimental)](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/540c9049-b127-4cc6-81c7-95b953fc3401)

This is my weather now.

**Comment by Dracque** [comment]
I submitted the bug report after being unable to night raid from start of the game (spring 15) to late summer (after summer 20 or 25). Granted the area of the map I explored was small (town was within view of what is revealed on spawn).

If there's a way to quickly pass days in the debug menu I could try passing a month or two a few times to see how the weather evolves.

As for moon phase, I don't know if it's possible to know exactly which one it is (regular game or with debug).
In the screenshot I've shown I'd guess it's not full, maybe a bit more then halfway close to full moon.

**Comment by Lamandus** [comment]
to see the moon phase, you need to add the "moon phase" info to your sidebar. `}` 
![grafik](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/a0b8d436-76d0-41de-8943-99c8286587e5)
you need to switch `moon `on. You can also use the classic sidebar which includes a lot of info in a small area.

**Comment by Dracque** [comment]
Took two screenshots on another character, date is Spring 28.

Mod list.
![Capture d'écran 2024-05-12 122412](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/2f536788-fe85-42bd-af7b-6aae61a678a5)
Debug weather map.
![Capture d'écran 2024-05-12 121945](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/2ad5c3c5-9f2b-44ec-83c4-6ee74dcef200)
Map without weather.
![Capture d'écran 2024-05-12 122029](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/2a7fc92c-7c64-4b1f-9c5d-9f3aff8ff4c3)

**Comment by Lamandus** [comment]
yeah, I get you. On my main save it went from
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/8655a330-ab44-4585-a603-9960157f51c0)
to
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/0d4c5086-62d6-4c22-9da1-e329700dacc2)

I see if I can calm it down a bit, maybe reducing the humidity again just a bit.
