### ISSUE TITLE
Some of the manager missions in the occupied lumbermill are broken

### ISSUE THREAD

**Issue by 0Monet** [cataclysmbnteam/Cataclysm-BN#4651]
### Describe the bug

The first mission, which requires to collect 3 drive belts, doesn't remove them from @ inventory once it's completed.
Same with the 6 blankets mission.
Also, mission rewards are, at best, miserable.

### Steps To Reproduce

1. Go to the occupied lumbermill.
2. Do the missions.
3. Required items (except nails) are not removed.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: 6e620bf [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

**Comment by RoyalFox2140** [comment]
![image](https://github.com/user-attachments/assets/14d8cefc-de78-4e6e-bccb-70e30b794b27)
Well the JSON looks normal, I don't know if it's a problem with JSON definitions for the mission or if its a greater bug with MGOAL_FIND_ITEM_GROUP which was added in the PR, so I'll assume it's the mission type.

**Comment by 0Monet** [comment]
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4758 solved this issue.
