### ISSUE TITLE
A sewage alligator can cause zombie infection.

### ISSUE THREAD

**Issue by BROtania** [cataclysmbnteam/Cataclysm-BN#4667]
### Describe the bug

A sewage alligator can cause zombie infection, with a high chance, but it's not a zombie in the descriprion.

### Steps To Reproduce

getting attacked by an alligator. It's will be zombie infection with a big chance.

### Versions and configuration

Any version (last is [2024-05-15])

**Comment by chaosvolt** [comment]
Bite wounds are just that, normal infections rather than a special zombie virus. The real question I assume instead is whether their infection chance needs tuning?

**Comment by BROtania** [comment]
> Bite wounds are just that, normal infections rather than a special zombie virus. The real question I assume instead is whether their infection chance needs tuning?

As far as I remember, the infection can only be brought by zombies

**Comment by Ignaramico** [comment]
i always thought the infected status was brought by chance by a bite/scratch special attack, hence the alligator has a chance to give it

**Comment by RoyalFox2140** [comment]
Only two types of zombies actually have an infection chance coded. 3 spiders and the croc can all cause infections.
