### ISSUE TITLE
Electric grid equipment lacks the integrated toolset as an alternative tool.

### ISSUE THREAD

**Issue by cyborg29x** [cataclysmbnteam/Cataclysm-BN#467]
# Describe the bug

The electric grid equipment (battery, solar panel, cable connector, etc) lacks the integrated toolset as a viable alternative to the soldering iron.

# Steps To Reproduce

Open the construction menu (*), search for "Install Solar Panel" and notice that there is only the soldering iron as the required tool.

# Expected behavior

The integrated toolset, and possibly also the arc welder and its makeshift version with an increased energy cost, should also be a viable alternative, as they are used interchangeably elsewhere.

# Screenshots

![solarpanel](https://user-images.githubusercontent.com/22873153/114731529-bcbafd80-9d39-11eb-8670-19869d8b10ab.PNG)

# Versions and configuration

Windows 7 SP1,
Build 2826C1F,
Tiles, with UndeadPeople tileset,
English,
Mods loaded: ["dda", "aftershock", "crt_expansion", "M.A.G.Armory", "mutant_npcs", "psychiclysm", "XEAS", "AAA", "adv_gear", "advtech", "anti_fungal_gears", "ArmUpPAUtil", "ArmUpSurvEx", "arsenal_breach", "bioco", "bsam", "camping_tools", "CBM_Arms", "SD_Magcrafting", "craftgp", "ExArch", "Gourmand'sGraces", "guncotton", "homemade_fungicide", "incinerator", "Medieval_Mod_Reborn", "modern_weapon", "More_Armors", "makeshift_stuff", "MST_Extra", "Power_Armor_Additions", "pressure_weapon", "homestead", "private_defense", "apex", "rf_food_keeper", "futurearmory", "beamswordmod", "rubber_band_sheath", "SWPB", "thermal_ups", "WildLiving", "Cata++", "ks_variety_pack", "convenientconstructions", "even_more_mutations", "food_irradiator", "Mining_Mod", "more_survivor_stuff", "basement_extension", "P_Caches", "Dorf_Life", "More_crops", "morlock_village", "No_Rail_Stations", "Graphical_Overmap", "TaMu", "stats_through_kills", "no_cbm_slots", "stamina_pool_buff", "EngineeringEssentials", "no_npc_food", "novitamins", "speedydex"]

# Additional context

I have fixed it locally by simply editing construction.json, replacing **"tools": [ [ [ "soldering_iron", 20 ] ] ],** with **"tools": [ [ [ "soldering_iron", 20 ], [ "toolset", 20 ] ] ],"** , seems to be working as intended.

**Comment by olanti-p** [comment]
Seems to have been fixed at some point, on version 937decd3 solar panels and similar allow both integrated toolset and grid soldering irons.
