### ISSUE TITLE
Acid ants' anthills can't be differentiated from regular anthills.

### ISSUE THREAD

**Issue by Dracque** [cataclysmbnteam/Cataclysm-BN#4670]
### Describe the bug

Checked a little under 30 overmap tiles for acid anthills after not seeing any in my past few games and didn't find any. Turns out both anthills now share the same name and overmap symbol (and graphic).

This make it impossible to tell the difference from the map and requires getting close enough for some of the ants to load. Reverting acid ants' anthills to their previous name and look when viewed on the map would greatly help.

### Steps To Reproduce

1. Create a character.
2. Open debug menu and select Map then reveal map.
3. Search for "anthill" on map.
4. Open debug menu and select Teleport then teleport - adjacent overmap.
5. Repeat steps 2 to 5 several times.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3593 (23H2)
- Game Version: de968c9 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Limit Fungal Growth [limit_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

**Comment by 0Monet** [comment]
Acid anthills still appear, they're just named % (in brown) anthill on the overmap which is strange as they used to be % (% in green) sulfurous anthill or something like that.

**Comment by Dracque** [comment]
Guess that's on me for just relying on the map and not checking by teleporting close.
Thank you for pointing out the change.

Should I open a different issue to request to have acid ants' anthills reverted to their previous colour and name while closing this one ?

**Comment by chaosvolt** [comment]
Looks like the root problem is the actual anthill part on the surface got converted to use the same overmap terrain when mutable overmap specials were added.

Opening a new one or renaming this one and editing the OP text is fine, whichever you'd prefer.

**Comment by chaosvolt** [comment]
And got a fix PR up :3

**Comment by Dracque** [comment]
Many thanks.
