### ISSUE TITLE
Decouple Mana system from CBM power system.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#471]
# Is your feature request related to a problem? Please describe.
If you have Magiclysm (or Arcana, can't remember) and use the Mana system AND have CBM power, you can either have CBM power OR mana, not both. I've been told it's "hardcoded" right now.

# Describe the solution you'd like
Decouple Mana system from CBM power system. Right now if you have CBM power, you need to drain it in order to have any mana at all to be used for spells.

Orr.....add a CBM that allows "Mana" to be used from CBM power, but that's unrealistic. I don't see why you can't be a Fireball throwing bio-weapon.

# Describe alternatives you've considered
None, since none exist

**Comment by Lorith** [comment]
It actually is not due to either mod, but rather due to the code written to allow magiclysm to exist.  Code can be seen here: https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/src/magic.cpp#L1424 -- cbm power is a straight reduction on your mana cap.

**Comment by Unrepentant-Atheist** [comment]
I don't get the logic behind it...but oh well...

**Comment by DoctorGoat** [comment]
This needs to be modified anyway, maybe to an external_option on top of that. There's a Magiclysm attunement that makes it 75% of the cost (biotek). 

And then there's people who don't want the effect at all who could use the external option, as well as one of the magiclysm expansion mods disabling attunements being like thresholds (that unfortunately breaks the altar in dda last time I tried and I had to patch the c++)

**Comment by olanti-p** [comment]
Resolved by #2404
