### ISSUE TITLE
Debug message during regular play: Item mutant_bug_hydrogen_sacs was loaded with charges, but can not have any!

### ISSUE THREAD

**Issue by jornvandebeek** [cataclysmbnteam/Cataclysm-BN#4730]
### Describe the bug

I was doing a vanilla playthrough on a recent nightly build (world/save was generated on that same build). A debug message popped up, walking around near some giant wasps. "Item mutant_bug_hydrogen_sacs was loaded with charges, but can not have any!"

If this is something that's easy to investigate and solve as a first issue for me, let me know and I'll take a stab at it.

### Steps To Reproduce

Unsure, I have stopped playing to make this report.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: b088cbc [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

### Additional context

[save.zip](https://github.com/user-attachments/files/15540220/save.zip)

This is the relevant message from debug.log
---
 DEBUG    : Item mutant_bug_hydrogen_sacs was loaded with charges, but can not have any!

 FUNCTION : io
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\savegame_json.cpp
 LINE     : 2303
 VERSION  : BN b088cbc

**Comment by chaosvolt** [comment]
A while back I saw this message with endochitin, which I think https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4707 may have fixed? If so, making them stackable should solve it.
