### ISSUE TITLE
broken_turret cannot be dissasembled

### ISSUE THREAD

**Issue by CV514** [cataclysmbnteam/Cataclysm-BN#474]
# Describe the bug

`broken_crows_m240` (and it's variation) have copied parameters from `broken_turret` and inherent ingame description "A broken turret.  Much less threatening now that it's laid limp on solid ground.  **Could be gutted for parts.**"

But there is no disassembly/uncraft recipe defined for `broken_turret` in `recipe_deconstruction.json` so it couldn't be gutted for parts; in fact, you can't do anything with it, only pick up and put it back.

# Steps To Reproduce

Find* or spawn some broken or inactive CROWS turret and try to butcher or disassembly it.

# Expected behavior

Should be gutted for parts.

# Versions and configuration

 - OS: Windows 10
 - Game Version: e53ed38
 - Graphics version: Tiles
 - Ingame language: Russian/English
 - Mods loaded: [ dda ]

# Additional context

*CROWS turret defined in the `obsolete.json`; as I understand, this is for mod compatibility? If so, at least Tankmod Revived use those for mapgen, and everything works fine - except ability to disassemble them. Also, it can be fixed with activation of Generic Guns since disassembly recipe is [present](https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/data/mods/Generic_Guns/recipes/recipes_deconstruction.json) there.

**Comment by Firestorm01X2** [comment]
> *CROWS turret defined in the `obsolete.json`; as I understand, this is for mod compatibility?
CROWS was completely remmoved and replaced with new turrets:
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/149

**Comment by Firestorm01X2** [comment]
Still disassembly/uncraft recipe defined for broken_turret should be added.

**Comment by Firestorm01X2** [comment]
Ok. `broken_turret` is generic. Problem is not there. Thing is - with obsolatating CROWS turrets their decontruction recepies were obsolated as well. It is in `recipe_obsolete.json`. For example `broken_crows_m240uncraft`.
That is why is is not acessible for CROWS turrets.

**Comment by Firestorm01X2** [comment]
@Coolthulhu , what should we do in that case? Is it mod author responsibilty on resoring uncraft recepies or should we  improvise something ourself?

**Comment by Coolthulhu** [comment]
I'd go with mod author responsibility here. The best we can do on our side is changing the description of generic broken turret to "it is a bug if you see it" and changing the turret to abstract, if it isn't already. If possible, it would be better to have no description at all, so that it debugmsgs on mods that fail to add a proper description.

The obsolete recipe will be removed someday.
