### ISSUE TITLE
Insects can no longer be skinned.

### ISSUE THREAD

**Issue by Dracque** [cataclysmbnteam/Cataclysm-BN#4741]
### Describe the bug

At some points insects could be skinned to loot the chitin without having to fully butcher or dissect the corpse. Option was no longer available around the time insects could be field dressed for organs if I'm not mistaken.

### Steps To Reproduce

1. Create a character with a butchering tool.
2. Find (or spawn) and kill some insects.
3. Butcher corpse.
Repeat the three above steps in 5.x stable.

### Screenshots

Current (or at least recent) build.
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/b95d0ba3-7a21-44b5-85f3-f46da1f91543)
Stable 5.2
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/167656683/2cc40e20-49a8-4e3c-bfa1-862534bee4ef)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3593 (23H2)
- Game Version: f4aaffd [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Limit Fungal Growth [limit_fungal_growth],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

Noticed it two or more weeks ago but forgot to report it asap.

**Comment by scarf005** [comment]
cc @chaosvolt

**Comment by chaosvolt** [comment]
Ah yeah, it was set to count as bone instead of skin by earlier PRs it seems.
