### ISSUE TITLE
Wrong total storage of equiped items

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#475]
According to "disorganised", it's not supposed to reduce total usable volume but be 10% slower at retrieving the stuff in the latest build. But...

Storage according to my equipped items:
![image](https://user-images.githubusercontent.com/3938423/115111998-8d97cc80-9f83-11eb-84d8-311cb7c6f898.png)
Actual usable storage:
![image](https://user-images.githubusercontent.com/3938423/115112013-98526180-9f83-11eb-89ad-4411ea628d01.png)

# Steps To Reproduce
1. Have Disorganised-Mutation
2. Equip  backpacks and stuff

# Expected behavior
Correct usable storage

# Side Note
Probably similar bug with "Pack Mule" mutation. Haven't checked.

# Game Log

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: e53ed38 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Arcana and Magic Items [Arcana],
    PKs Rebalancing [PK_REBALANCE],
    Blazemod - Vehicle Additions Pack [blazemod],
    Ascension [winning_dda],
    Aftershock [aftershock],
    Cataclysm++ [Cata++],
    C.R.I.T Expansion Mod [crt_expansion],
    <color_light_green>Real Dark Skies</color> [realdarkskies],
    DinoMod [DinoMod],
]

**Comment by Coolthulhu** [comment]
One of the mods must be modifying the description. The core version of the trait says it's 40% volume reduction and it is not overwritten by any of the mods in repo.
