### ISSUE TITLE
Iteminfo can't be scrolled in crafting menu

### ISSUE THREAD

**Issue by Lamandus** [cataclysmbnteam/Cataclysm-BN#4765]
### Describe the bug

Crafting menu items can't be scrolled as they used to be. Chaosvolt already got info 

### Steps To Reproduce

See above.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/33199510/54253bf7-43f0-4044-a7de-04e95d4621d4)

### Versions and configuration

https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4713
Is at fault. Version before it works fine. That one containing this one has the error.

**Comment by KheirFerrum** [comment]
Should be resolved by #4802

**Comment by Lamandus** [comment]
Yes, it works now. Thank you
