### ISSUE TITLE
Tinder has be manually placed each time a fire is started

### ISSUE THREAD

**Issue by Relgar** [cataclysmbnteam/Cataclysm-BN#4818]
### Is your feature request related to a problem? Please describe.

As per title, tinder has to be manually placed in the area to light the fire when you want to start one. This is really tedious, especially because you make tinder by the hundreds, and not accidentally lighting your whole stack on fire means you need to manually transfer 1 out of the stack each time.

### Describe the solution you'd like

Selecting one out of a stack from any of the below, ideally all of them:

- the nearby firewood source zone
- the player's inventory
- anywhere within the set crafting component distance

**Comment by chaosvolt** [comment]
This applies specifically to fire drills and flint, yeah. Ideally, I'd like for firewood zones to sort in such a way that they prioritize items in it that have the `TINDER` flag as the first thing to pick if the chosen firestarting tool requires tinder, but then push them down to the bottom of the list if the fire is already going.

If anyone can find the functions involved in pulling the contents of a firewood source, please do link them here.

**Comment by Relgar** [comment]
This looks like the one:

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/1d6b2c31e8b8b61632875b57f9f619f3eccac02d/src/activity_item_handling.cpp#L3365

**Comment by chaosvolt** [comment]
Hmm, I'll have to tinker with the code sometime to see if it can be tweaked like that...

**Comment by Relgar** [comment]
It may also be worth suggesting which tools tinder is required to work with, because I don't think it's mentioned anywhere.

Although now that I think about it, having a lighter immediately light a log on fire also sounds like it should have tinder in between.

But then we might be on a slippery slope to needing kindling next, before small fuelwood and finally large fuelwood. Could be a bit too simulationisty.

**Comment by Ignaramico** [comment]
wait what, since when you had to put tinder manually to make a fire? especially for fire drills, i remember them being usable as lighters (just a bit more time consuming)
