### ISSUE TITLE
Remove the "voice is muffled" effect from having mouth encumbrance.

### ISSUE THREAD

**Issue by cyborg29x** [cataclysmbnteam/Cataclysm-BN#487]
# Describe the bug

Wearing equipment that adds encumbrance to the mouth area causes the sound of your character's yelling (both speech and just a wordless yell) to be muffled.

# Steps To Reproduce

1. Wear a heavy survivor mask.
2. Attempt to yell and notice both the warning that appears in the log and the unexpectedly low sound volume in the sidebar.
3. Take off the mask and repeat step 2.
4. Notice the lack of warning and the quite audible sound now produced.

# Expected behavior

While this is an expected behavior from a realism perspective, i personally believe that it adds nothing to the gameplay because this specific action is entirely at the discretion of the player, and thus requires more actions than it otherwise should (remember to take off any masks and scarves -> yell -> remember to put them back on again as opposed to just producing an audible sound regardless of worn equipment).

# Screenshots

![muffled](https://user-images.githubusercontent.com/22873153/115961475-6fdfdf80-a50e-11eb-8387-9486ce6f0d15.PNG)

# Versions and configuration

Windows 7 SP1,
Build 2826C1F,
Tiles, with UndeadPeople tileset,
English,
Mods loaded: ["dda", "aftershock", "crt_expansion", "M.A.G.Armory", "mutant_npcs", "psychiclysm", "XEAS", "AAA", "adv_gear", "advtech", "anti_fungal_gears", "ArmUpPAUtil", "ArmUpSurvEx", "arsenal_breach", "bioco", "bsam", "camping_tools", "CBM_Arms", "SD_Magcrafting", "craftgp", "ExArch", "Gourmand'sGraces", "guncotton", "homemade_fungicide", "incinerator", "Medieval_Mod_Reborn", "modern_weapon", "More_Armors", "makeshift_stuff", "MST_Extra", "Power_Armor_Additions", "pressure_weapon", "homestead", "private_defense", "apex", "rf_food_keeper", "futurearmory", "beamswordmod", "rubber_band_sheath", "SWPB", "thermal_ups", "WildLiving", "Cata++", "ks_variety_pack", "convenientconstructions", "even_more_mutations", "food_irradiator", "Mining_Mod", "more_survivor_stuff", "basement_extension", "P_Caches", "Dorf_Life", "More_crops", "morlock_village", "No_Rail_Stations", "Graphical_Overmap", "TaMu", "stats_through_kills", "no_cbm_slots", "stamina_pool_buff", "EngineeringEssentials", "no_npc_food", "novitamins", "speedydex"]

# Additional context

**Comment by Proxiehunter** [comment]
Does it also muffle Shouter, Screamer, and Howler mutations? I've been thinking it might be a good idea to add gags to mitigate those mutations at the expense of having to take them out to speak to NPC's and mouth encumbrance (and maybe a mood boost if your character has the masochist trait) but wasn't sure if that was doable but this makes it sound like it might be.

**Comment by cyborg29x** [comment]
![teleport](https://user-images.githubusercontent.com/22873153/115996700-4b503a00-a5d8-11eb-885f-ce0ee9c9a503.PNG)

It would appear that it does muffle the sound produced by those mutations. I have tested it on a new character in a vanilla save and several "voice muffled" warnings appeared while i waited. I suppose that it's best to leave this effect as-is then, otherwise it wouldn't be coherent (manual yelling goes through masks but not involuntary mutation actions).

**Comment by Drugitechnik** [comment]
This is feature working as intended. There are other ways of producing sounds if your equipment muffles you.
