### ISSUE TITLE
Unloaded ammo belt doesn't disappear

### ISSUE THREAD

**Issue by Soadreqm** [cataclysmbnteam/Cataclysm-BN#49]
# Describe the bug

Unloading a 5.56x45mm ammo belt leaves behind an empty ammo belt item, in addition to the bullets and ammo belt linkage. It has volume 0.001L, and weighs 0.00kg. It can be reloaded to fill it back up, but as ammo belt linkage can be applied to create a new ammo belt, there's no reason for it to exist.

# Steps To Reproduce

1. Obtain 5.56x45mm ammo belt with ammo
2. Unload ammo belt
(Not tested with other types of ammo belt.)

# Expected behavior

The ammo belt is destroyed, broken up into bullets and belt linkage.

# Versions and configuration

- OS: Windows 10 Pro N 2004
- Game Version: 6c92546 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Firestorm01X2** [comment]
Rerlated to:
https://github.com/CleverRaven/Cataclysm-DDA/pull/43367
?
