### ISSUE TITLE
monster attacks <npcname>

### ISSUE THREAD

**Issue by LyleSY** [cataclysmbnteam/Cataclysm-BN#491]
# Describe the bug

Log shows <npcname> when a dino is attacked, not the monster name as expected

# Steps To Reproduce

1. Start a world with DinoMod enabled
2. Spawn a zombie and a Nodosaur next to each other
3. Watch the log

# Expected behavior

Dino should be named as expected in the log

# Screenshots

TBD

# Versions and configuration

 - OS: Mac
 - Game Version: Newest BN
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: DinoMod

**Comment by olanti-p** [comment]
Can reproduce, caused by #434
