### ISSUE TITLE
Scaling factor x2 and x4 resets language to English

### ISSUE THREAD

**Issue by natovan** [cataclysmbnteam/Cataclysm-BN#495]
# Describe the bug
Scaling factor restores language to English. In some places language is correct, like in logo in main menu and MOTD.
It was in DDA but was closed: https://github.com/CleverRaven/Cataclysm-DDA/issues/48255

# Steps To Reproduce
1. Change language to something different from English
2. Change scaling factor to x2 or x4
3. Restart to apply changes
4. Language changed back to English

# Expected behavior
Language doesn't change

# Versions and configuration
e53ed38

win10 x64 tiles no mods

**Comment by Zireael07** [comment]
For reference, it seems to have been something to do with SDL version used: https://github.com/CleverRaven/Cataclysm-DDA/issues/48255#issuecomment-808975668
