### ISSUE TITLE
Recipes don't use liquids from containers in vehicles.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [cataclysmbnteam/Cataclysm-BN#4953]
### Describe the bug

Recipe don't seem to use liquids stored inside vehicle containers.

### Steps To Reproduce

1. Have Vehicle
2. Have Roof-Mounted 200L Tank + Water in it
3. Use cooking recipe that needs water
4. ???
5. Don't profit
6. Be sad.

### Screenshots

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/913b5e9e-ea50-4f7c-b427-66cbcd990d40)
![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/3938423/53967fe9-858c-49c0-bacf-e247ef2a84a9)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4598 (22H2)
- Game Version: 6ad69e6 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots],
    Elevated bridges [elevated_bridges],
    Teleportation [teleportation_tech],
    Cataclysm++ [Cata++],
    Aftershock [aftershock],
    PKs Rebalancing [PK_REBALANCE],
    Secronom [secronom],
    Secronom+ Lore Expansion [secronom_lore_expansion],
    C.R.I.T. Expansion [crt_expansion],
    Sierra Madre [sierra_madre],
    Bio-Synth Robot expansion [gekkobots],
    Nechronica Redux [Nechronica_Redux],
    The Arcology Mod [arcology],
    Really Dark Skies [realdarkskies],
    Arcana and Magic Items [Arcana],
    Magical Nights [MagicalNights],
    Manic Magical Nights [ManicMagicalNights],
    Project: Pack Rat [Jake's_Squirrel_mod],
    Add Bandits Extended+ [GOV_BANDITS_KAI_R],
    NPC Increased Location Spawns Combined [npc_increased_location_comb],
    More Bandits, Testing version [More_Bandits],
    More Dangerous Encounters [More_Dangerous_Encounters],
    Morlock Village [morlock_village],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/C.R.I.T. Patchmod [Arcana_Crit_Patch],
    Arcana/Magical Nights Patchmod [Arcana_MagiclalNights_Patch],
    Really Dark Skies plus Arcana [realdarkskies_Arcana_patchmod],
    Really Dark Skies plus Cataclysm++ [realdarkskies_CATA_patchmod],
    Really Dark Skies plus PKs Rebalancing [realdarkskies_PK_REBALANCE_patchmod],
    Really Dark Skies plus Secronom [realdarkskies_secronom_patchmod],
    Really Dark Skies plus C.R.I.T. [realdarkskies_CRIT_patchmod],
    Really Dark Skies plus Bio-Synth Robot Expansion [realdarkskies_gekkobots_patchmod],
    Really Dark Skies plus Morlock Village [realdarkskies_morlock_village_patchmod],
    Really Dark Skies plus Magical Nights [realdarkskies_MagicalNights_patchmod],
    Really Dark Skies with reviving Xenoids [realdarkskies_reviving_xenoids],
    Even More Mutations [even_more_mutations],
    Mutant NPCs [mutant_npcs],
    Psychiclysm [psychiclysm],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Salvaged Robots [Salvaged_Robots],
    Bug's life [Bug's life],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    DinoMod [DinoMod],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Really Dark Skies plus DinoMod [realdarkskies_Dino_patchmod]
]

**Comment by chaosvolt** [comment]
You need to install a faucet over the container.

**Comment by Unrepentant-Atheist** [comment]
Oooh, that's new then. Thanks.
