### ISSUE TITLE
Undiscoverable Access shaft

### ISSUE THREAD

**Issue by fgdfgfthgr-fox** [cataclysmbnteam/Cataclysm-BN#499]
# Describe the bug
In the save file provided below, you will notice that there is no tile called "access shaft" at level 0. Central lab still gets generated and you can still find the manhole cover on the tile where the access shaft would be.

I don't really know, unable to replicate this bug.

# Expected behavior
There should be a tile in the forest that's grey in colour with Graphical_Overmap, and called "access shaft" instead of a simple forest.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 403b0e8 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    C.R.I.T 扩展 [crt_expansion],
    大魔法 [magiclysm],
    余波未尽 [aftershock],
    自制枪械包 [craftgp],
    神话武术 [MMA],
    移除火车站 [No_Rail_Stations],
    替换小地图图标 [alt_map_key],
    图形版大地图 [Graphical_Overmap],
    移除真菌类怪物 [No_Fungi],
    Fuji的军事职业Mod [fuji_mpp],
    No Lifting Reqs [disable_lifting],
    Old Mutations [Old_Mutations],
    技能提升属性 [StatsThroughSkills],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    手动安装生化插件 [manualbionicinstall]
]

# Additional context
Save file:
[Hello World.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/6405046/Hello.World.zip)

**Comment by Coolthulhu** [comment]
OK, I found it: it's the `alt_map_key` mod, which is redefining the tile name and symbol to forest.
Should be an easy fix.
