### ISSUE TITLE
Endless vehicle collision with the ground

### ISSUE THREAD

**Issue by CV514** [cataclysmbnteam/Cataclysm-BN#504]
# Describe the bug

As in the tittle, spamming the log and producing a lot of lag.

# Steps To Reproduce

1. Go somewhere high.
2. Spawn welding rig cart.
3. Push it down.
4. Observe.

Or

1. Go to the military outpost/some other overmap specials where damaged vehicles could spawn at different Z-levels.
2. Probably they will generate lag and noise; this is how I found that. It depends, as I can see, if they spawn with wheels or not - spawning without wheel set will result in this issue.

# Expected behavior

Silence, please. 

# Screenshots

![SMASH](https://user-images.githubusercontent.com/60776130/116898199-e8a21280-ac57-11eb-80de-72cf213542e6.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 403b0e8
 - Graphics version: Tiles
 - Ingame language: Russian / English
 - Mods loaded: [ a lot of them; happens even with just dda]

# Additional context

This issue is already fixed in CDDA, probably we could use that too with necessary code checks https://github.com/CleverRaven/Cataclysm-DDA/commit/c9800ae3ea6f833e44327aac808b1a00e0f35d23

Also, for testing, be advised that with soundpack this noise will multiply gain of crashing sound by extreme amount, lower your volume.

**Comment by scrubs2009** [comment]
+1
Had this with a spawn in the bioweapon lab. It was getting so bad it lagged the game. Eventually I determined it was the welding rig and teleported over to smash it.
