### ISSUE TITLE
General Build Matrix tests are failing in all pull requests

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#5081]
### Describe the bug

Three tests have been constantly failing withing the first couple minutes for every recent PR. This is bad because the constant wave of false positives makes it harder to spot a real test failure that might mean something important has broken.

### Steps To Reproduce

Make a pull request.

### Screenshots

![image](https://github.com/user-attachments/assets/150740a2-e524-4a12-b422-b21a64b7168d)

### Versions and configuration

Not an in-game issue and affecting PRs themselves, so version info is irrelevant here.

### Additional context

The contents of each respective test failure seem to be pretty much the same for all affected PRs:
1. https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/10106986611/job/27950047200?pr=5077
2. https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/10106986611/job/27950047580?pr=5077
3. https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/10106986611/job/27950047747?pr=5077

It's hard to spot what the logs are actually complaining about. @scarf005 said they've got a PR in the works to fix that?
![image](https://github.com/user-attachments/assets/170cb974-7a68-42b6-ab1b-c6beb1fdde5c)

**Comment by scarf005** [comment]
it's been happening since the executable name change PR. we haven't noticed it as these workflow has been not running due to issues.

**Comment by chaosvolt** [comment]
Ah, hmm. Any idea where else the executable name needs updating?

**Comment by scarf005** [comment]
i'll check it today.

**Comment by chaosvolt** [comment]
We missed one: https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/10124634860/job/28000279234?pr=5090
