### ISSUE TITLE
Passive animals run away from the player too much

### ISSUE THREAD

**Issue by AlecWhite** [cataclysmbnteam/Cataclysm-BN#5113]
### Is your feature request related to a problem? Please describe.

Birds, deers and other small animals run away too fast to the edge of the reality bubble and keep running away at a speed higher than what the average player can run and without resting/using stamina.
This turns hunting anything other than dogs and other less fearful animals near impossible.

### Describe the solution you'd like

Would be good to have animals fear less the player, have stamina or some other way to facilitate hunting.

**Comment by Ignaramico** [comment]
i always thought you were meant to hunt them at night or to get them into a forest so the trees block the sight and they stopped running, but yeah with normal cheap ranged weapons they are hard to hunt, you need rifles
