### ISSUE TITLE
Hickory nut Ambrosia is impossibly dense

### ISSUE THREAD

**Issue by Reclusive-reptile** [cataclysmbnteam/Cataclysm-BN#5114]
### Describe the bug

Hickory nut ambrosia is denser than steel.

### Steps To Reproduce

Look at hickory nut ambrosia

### Screenshots

![Cataclysm_ Bright Nights - b8fa279 7_30_2024 6_11_21 PM](https://github.com/user-attachments/assets/1c96d526-ac28-4d1c-9e70-6699058c8c2e)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: b8fa279 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Elevated bridges [elevated_bridges],
    Craftable Gun Pack [craftgp],
    No Rail Stations [No_Rail_Stations],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi]
]

**Comment by RoyalFox2140** [comment]
Portions 10. The problem is the UI doesn't properly convey the volume/weight of one portion.

![image](https://github.com/user-attachments/assets/0a7bdb0a-3df4-4423-973b-436c857163a5)

**Comment by Reclusive-reptile** [comment]
That is still 1Kg for 250mL of what is essentially sweetened nut milk. There is some thing very wrong with the JSON.

**Comment by scarf005** [comment]
feel free to open a PR.

**Comment by RoyalFox2140** [comment]
No. The debug menu also displays it as portions 4. 
![image](https://github.com/user-attachments/assets/d90dd369-7f68-439c-bf0b-9e529a74088f)
 It's 254 grams and 250 milliliters for one serving.

**Comment by chaosvolt** [comment]
So, here's what we missed that I just spotted.
> It's 254 grams and 250 milliliters for one serving.

The thing I just spotted is it's not 250 ml per serving. Because there's no separate stack size defined, the volume is divided by the default number of `charges` in the comestible, unlike weight which is always per single unit. So that means it's 254 grams per 62.5 ml.

So dividing the weight by ~4 should be a dead simple fix.

**Comment by scarf005** [comment]
i hate charges division behavior aaaahhhhhhh

**Comment by chaosvolt** [comment]
Oh, I'm glad I checked the recipe BEFORE actually committing my "dead simple fix" because the recipe takes 10 units of water and outputs 10 units of ambrosia, so the expected solution is actually to set a stack size of 1, not to edit the weight.
