### ISSUE TITLE
Crash when attempting to wield underbarrel shotguns

### ISSUE THREAD

**Issue by DoubleBullfrog** [cataclysmbnteam/Cataclysm-BN#5132]
### Describe the bug

Attempting to wield an underslung shotgun, masterkey shotgun, or RM121 aux shotgun will cause the game to immediately crash.

### Steps To Reproduce

1. Spawn an underbarrel shotgun and attempt to wield it.
2. The game crashes.

### Versions and configuration

Windows 10 - bc3c7dc 2024-08-01 - Tiles - English - Default Mods

### Additional context

[crash.log](https://github.com/user-attachments/files/16474025/crash.log)
[debug.log](https://github.com/user-attachments/files/16474026/debug.log)
[DEBUG.zip](https://github.com/user-attachments/files/16474032/DEBUG.zip)

**Comment by chaosvolt** [comment]
Hecc, can confirm. Also happens with M203, whether loaded or unloaded. My rough guess is it's something specifically about gunmods that can be fired as guns, acting up when trying to wield them on their own.

**Comment by chaosvolt** [comment]
Call stack when done in compiled test build, dunno if anyone can do anything useful with this:
![image](https://github.com/user-attachments/assets/4eaf738f-62d8-445a-bd6d-9a2f19d04bde)
