### ISSUE TITLE
 Connect a cable item to the vehicle, it will be copied.

### ISSUE THREAD

**Issue by CfallenK** [cataclysmbnteam/Cataclysm-BN#5155]
### Describe the bug

When you connect the heavy-duty cable, heavy duty table, and jumper cable items to the vehicle, they are installed in the vehicle parts but remain in the inventory.

### Steps To Reproduce

1. Connect the cable to vehicle A.
2. Connect the connected cable to vehicle B as well.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4651 (22H2)
- Game Version: e47cad4 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn]
]

**Comment by scarf005** [comment]
hi, this seems to be duplicate of #5122.
