### ISSUE TITLE
Some martial arts techniques were missed by rapid strike rework

### ISSUE THREAD

**Issue by RobbieNeko** [cataclysmbnteam/Cataclysm-BN#5169]
### Describe the bug

Several martial arts styles are still using the old style of rapid-strike techniques.
In particular:
Panzer Kunst (from Mythical Martial Arts), Boxing, Barbaran Montante, Snake Kung Fu, and Centipede Kung Fu

### Steps To Reproduce

1. Download recent release
2. See what rapid strike is supposed to be based on rework PR
3. See that the styles mentioned above don't have the updated technique

### Versions and configuration

latest release

### Additional context

Creating issue on behalf of Cdru in the Discord, who admits that "I suck at Github".

rapid strike rework PR for reference: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4516

**Comment by RoyalFox2140** [comment]
As I posted on the Discord we opened Pandora's box by re-allowing the animal martial arts to spawn their books again. All 5 of them need an audit eventually as they aren't supposed to spawn and thus have been unmaintained for years.

At some point we're all going to have to sit down and do a full rebalance of all the arts.
