### ISSUE TITLE
Riot Turret spawns are not locked to a set amount in prisons, and will spawn a ludicrous amount in high spawnrate worlds

### ISSUE THREAD

**Issue by mkikt4743** [cataclysmbnteam/Cataclysm-BN#519]
# Describe the bug

Riot turrets spawn like hell in high spawnrate worlds. Underlined each one in screenshot below.

# Steps To Reproduce

Set spawnrate to 5 -> teleport to a prison

# Expected behavior

Riot turrets should be fixed spawns like lab turrets, roadblocks etc

# Screenshots

![image](https://user-images.githubusercontent.com/56452763/117893294-23273300-b288-11eb-8db1-01e740c6ac41.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: fbf53c7 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Drugitechnik** [comment]
This layout is no longer in game. New layout doesnt have this issue.
