### ISSUE TITLE
Fingerpick CBM does not work, does not allow cancelling action

### ISSUE THREAD

**Issue by Soadreqm** [cataclysmbnteam/Cataclysm-BN#52]
Attempting to use the fingerpick CBM on a locked door does not open it, and instead gives the following error:

> DEBUG    : lockpick item location lost
>
> FUNCTION : void activity_handlers::lockpicking_finish(player_activity*, player*)
> FILE     : src/activity_handlers.cpp
> LINE     : 2565

The lockpicking action will then continue until interrupted by something external (such as an enemy coming into view), giving the same error every turn. It cannot be cancelled by pressing a key, and the door will never open.

# Steps To Reproduce

1. Start a bionic thief in an un-vandalized evac shelter
2. Attempt to pick the lock on the stairs to the roof

# Expected behavior

Door opens, power is consumed

# Versions and configuration

- OS: Windows 10 Pro N 2004
- Game Version: cfead08 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Firestorm01X2** [comment]
Looks like it is related to:
https://github.com/CleverRaven/Cataclysm-DDA/issues/39740
That was closed by:
https://github.com/CleverRaven/Cataclysm-DDA/pull/39857

**Comment by olanti-p** [comment]
As a note, there were some changes to lock picking activity on top of that fix: CleverRaven#40824, CleverRaven#41155.
But, given BN's focus towards simplification of some game mechanics, it might be simpler to just get rid of the activity (introduced in CleverRaven#39409)

**Comment by Firestorm01X2** [comment]
Thank you. Looks like lastest (https://github.com/CleverRaven/Cataclysm-DDA/pull/41155) is way to go since in cover it all.

**Comment by Firestorm01X2** [comment]
@Coolthulhu Looks like I've missed  Bufixes tag again. 

This issue can be closed.
