### ISSUE TITLE
You can still get the Quick Pain Recovery mutation from mutagen

### ISSUE THREAD

**Issue by mkikt4743** [cataclysmbnteam/Cataclysm-BN#520]
Despite Quick Pain Recovery being disabled and not showing up in the character screen, you can still mutate it while drinking mutagen (not tested with more specific stuff or serums)

Drink a lot of mutagen
Eventually you will see the message about getting the Quick Pain Recovery mutation or one of that line of mutations
Check @ screen
Notice that the mutation doesn't show up
Check debug screen and notice you have the mutation

# Expected behavior

If disabled since it doesn't work, shouldn't be able to get it w/o debug.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: fbf53c7 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    XEAS [XEAS],
    Pneumatic fun [pneumo_fun],
    Magiclysm [magiclysm],
    No Magic Class Exclusiveness [no_magic_exclusiveness],
    Nuclear .50 Mod [nuclear_ball],
    Homestead Instruments Inc. [homestead],
    Private Defense [private_defense],
    RF food keeper [rf_food_keeper],
    Wild Living [WildLiving],
    CIVILIAN POWER ARMOR [CIVILIANPOWAAA],
    Advanced Gear [adv_gear],
    Cataclysm++ [Cata++],
    Alternative Map Key [alt_map_key],
    Vampiric Stuff [vamp_stuff],
    Arcana and Magic Items [Arcana],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Dorf Life [Dorf_Life],
    Caches [P_Caches],
    No Rail Stations [No_Rail_Stations],
    Morlock Village [morlock_village],
    Water Towers [water_towers],
    Compatible Add Bandits [GOV_BANDITS],
    Faster Stamina Regen [stamina_regen_buff],
    Blazemod - Vehicle Additions Pack [blazemod],
    Vehicle Additions Additions [blaze_extension_M],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    No Fungal Monsters [No_Fungi]
]
I've got a helluva lot of mods. However, this mutation is still in base game, and none of these mods SAY they affect mutagen. I will chug mutagen on a debug world with the basegame mods only tommorow, and comment on this PR.

**Comment by Coolthulhu** [comment]
It's not affecting mutagen that does it, it's affecting traits. Mods that add new categories often overwrite traits because the author typically doesn't know how to use `"copy-from"` to add new categories to a trait.
I suspect it's one of the vampiric mods. CRIT mod has vampiric stuff and it caused problems by overwriting things.

**Comment by mkikt4743** [comment]
Okay. I will test today to be sure, and then make a bug report on Kenan's pack if it's only an issue there. My apologies.

**Comment by Coolthulhu** [comment]
Anything new?

**Comment by mkikt4743** [comment]
Ah hell, I don't have any time anymore to check this out, it's probably the mods.
