### ISSUE TITLE
Instant death on spawning if using hp_adjustment JSON

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#5222]
### Describe the bug

I died instantly on spawning. For @KheirFerrum 

### Steps To Reproduce

1. I first created a character on wilderness start with an hp adjusting trait, see below information, but I backed out before accepting my character
2. I chose Wizards retreat in Magical Nights and accepted, I had no mutations.
3. I died. Likely the negative 150 hp adjustment from a trait was setting my max hp to 0 because it was carrying over that data despite me not leaving chargen menus.

### Screenshots

![image](https://github.com/user-attachments/assets/b2b7aa2e-0a10-4508-8674-6ef72db2a500)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4529 (22H2)
- Game Version: f92bad0 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Cataclysm++ [Cata++],
    Essence 2200 BN [Essence2200_BN],
    Essence 2200 Tweaks [FoxTweaks],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    OMT Resources [omt_resources],
    Flowing Water [flowing_water],
    No Filthy Clothing [no_filthy_clothing],
    No Wasps [No_Wasps],
    Item Category Overhaul [Item_Category_Overhaul]
]

**Comment by KheirFerrum** [comment]
Can't recreate, need a step by step of selection, backing out, etc. If mutation is modded, write out what the mutation's JSON is so I don't have to dig through the mods.

**Comment by RoyalFox2140** [comment]
Must be max health related. I further tested with just my mod and settings mod. 

I pick Nightwalker which uses "hp_adjustment": 250, I go and change my height and start location from shelter to vandalized shelter, game asks if I'm sure I want to play this character, I back out, choose survivor, then accept. I lose every limb in my body and all blood vaporizes.  I linked the mutations, if it isn't related to hp adjustment then it may be related to other hp adjusting things I do.

Extreme fatigue sets hp adjustment to -150 which might be setting my max health to 0 when I'm running a survivor as its effect is offset by the +250 hp adjustment to make a positive 100 bonus, with the idea you remove it later. That means the -150 is being applied on turn 1 and instantly setting hp to max 0 which instantly kills the player. If it only triggers from my mutations then negative hp adjustment mutations are applied even if you aren't selecting them.

https://github.com/RoyalFox2140/Essence2200/blob/main/Essence2200_BN/Mutations/mutations.json
![image](https://github.com/user-attachments/assets/3e3a02e7-9520-4c42-84bb-65265bdd6b39)
