### ISSUE TITLE
Reinforced glass is stronger than walls

### ISSUE THREAD

**Issue by Kodiologist** [cataclysmbnteam/Cataclysm-BN#5239]
### Describe the bug

`t_reinforced_glass` is described as "Still weaker than other types of walls", but it has `str_min` 80, much more than `t_wall`'s `str_min` of 30, and more than enough to prevent one from smashing it with e.g. a sledgehammer.

### Steps To Reproduce

n/a

### Versions and configuration

8db8a67f48ce6e166e0ebf4c359ffd63c5c862fb

**Comment by RoyalFox2140** [comment]
t_wall is wood though. I can punch through drywall IRL and I don't weight lift. What would be more ideal is if we represented half destroyed t_wall where the drywall was gone but the wood framing remained. I don't know about how strong bulletproof glass is to a sledgehammer, but I'm not sure if this is inaccurate.

**Comment by Kodiologist** [comment]
I don't know if it's the behavior of the terrain that's wrong, or just the description; but at any rate, "weaker than other types of walls" is to me a confusing way to describe `str_min` 80.

**Comment by RoyalFox2140** [comment]
I'll update the description to remove mention of it being weaker than other types of walls. If you're curious about how this performs I found a field test.

https://www.youtube.com/watch?v=xLV2Nd77lmY

**Comment by Kodiologist** [comment]
Okay, fair enough.
