### ISSUE TITLE
Antiseptic soaked rags and cotton balls still seem to be bugged.

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#5260]
### Describe the bug

While the fix [here](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5244) corrected the cotton balls and rags that were vanishing using antiseptic soaked rags or antiseptic soaked cotton balls through (a)ctivate to disinfect wounds still uses two antiseptic soaked rags or two antiseptic soaked cotton balls when it should be using _one_ per use. 

The benefit of antiseptic soaked rags and cotton balls is _supposed_ to be that you can disinfect twice (if using rags) or eight times (if using cotton balls.) with only _one_ unit of antiseptic. (Note that using cotton balls used to only give you _four_ uses of antiseptic per dose when the recipe used 4 cotton balls. May want to revert to antiseptic soaked cotton balls using _four_ cotton balls when you fix this. Or have it use eight cotton balls and _two_ units of antiseptic. Eight used of antiseptic for only one unit is kind of nuts.) Using two per use means that antiseptic soaked rags instead of just pouring from the bottle onto your wound no longer has any benefit and using antiseptic soaked cotton balls has a quarter of the benefit it _should_ have.

### Steps To Reproduce

1: Wound character

2: Make antiseptic soaked cotton balls or rags

3: (a)ctivate in order to disinfect _a single wound location_

4: Notice that _two_ antiseptic soaked rags or antiseptic soaked cotton balls have been used to apply antiseptic _once_

5: Lament over wasted antiseptic

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 81437bd [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn]
]

### Additional context

Save file attached.

[TEST.zip](https://github.com/user-attachments/files/16770049/TEST.zip)

**Comment by RoyalFox2140** [comment]
This is hardcoded and I really can't find how. After I changed "used_up_item" nothing happened.

**Comment by Proxiehunter** [comment]
I suppose a dirty quick fix until it can be figured out would be to make the recipes produce twice as many as they should (or leave antiseptic soaked cotton balls the same if going with my suggestion to nerf it to either only making four cotton balls or using two shots of antiseptic).

**Comment by RoyalFox2140** [comment]
OH this has to be fixed now, if it's doing things and we don't understand why, that has unforeseen consequences. There shouldn't be two comestibles in the game that just use two of itself every use without us understanding why.
