### ISSUE TITLE
Mac installer still says DDA

### ISSUE THREAD

**Issue by LyleSY** [cataclysmbnteam/Cataclysm-BN#527]
# Describe the bug

This is the current look and feel of the Cataclysm BN installer on Mac:

![image](https://user-images.githubusercontent.com/26608431/118648971-f48de880-b7b0-11eb-9790-d138eebbbb2b.png)

# Steps To Reproduce

1. Download the DMG installer on Ma
2. Open it and look at it

# Expected behavior

BN logo on background, maybe change the filename to Cataclysm BN (I do this manually since I keep both installed like an absolute lunatic)

# Versions and configuration

 - OS: Mac
 - Game Version: Lates
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: None
 

# Additional context

NA

**Comment by LyleSY** [comment]
The situation is improving:
<img width="630" alt="Screen Shot 2021-06-14 at 8 42 12 PM" src="https://user-images.githubusercontent.com/26608431/121976107-21520300-cd51-11eb-9e71-5d0ed348e6fd.png">

**Comment by olanti-p** [comment]
Should be fixed by the linked PR.
