### ISSUE TITLE
Gas and incendiary grenades do not work

### ISSUE THREAD

**Issue by puyebu** [cataclysmbnteam/Cataclysm-BN#5294]
### Describe the bug

After activating and throwing gas/incendiary grenades nothing happens as seen in the attached video below.

### Steps To Reproduce

1. Activate item.
2. Throw item.
3. Nothing happens.

### Screenshots

[CBN Grenades FAIL.webm](https://github.com/user-attachments/assets/3ff215e2-03d1-4311-a0da-274662c706c0)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: EndeavourOS; Description: EndeavourOS Linux; Release: rolling; Codename: rolling; 
- Game Version: cbd6d2c [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Limit Fungal Growth [limit_fungal_growth]
]

**Comment by RoyalFox2140** [comment]
I just reproduced. 
![image](https://github.com/user-attachments/assets/fed23ca6-ac14-46f1-8d03-67147f67ccde)

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Bazzite; Description: Bazzite 40 (FROM Fedora Kinoite); Release: 40; Codename: Holographic; 
- Game Version: 1d106ac [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 BN [Essence2200_BN],
    Essence 2200 Tweaks [FoxTweaks],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    OMT Resources [omt_resources],
    Flowing Water [flowing_water],
    No Filthy Clothing [no_filthy_clothing],
    No Wasps [No_Wasps],
    Essence 2200 + Magical Nights [Magical_Nights_2200],
    Item Category Overhaul [Item_Category_Overhaul],
    Magical Nights [MagicalNights],
    Fox's Revisions mod [FoxRevisions],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Prevent Zombification [no_zombify]
]

**Comment by RoyalFox2140** [comment]
This bug is absent from August 10th release. Unfortunately related to https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5188
![image](https://github.com/user-attachments/assets/c07104a8-de70-4fc0-8488-15c939ad3bda)
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Bazzite; Description: Bazzite 40 (FROM Fedora Kinoite); Release: 40; Codename: Holographic; 
- Game Version: 2681c9a [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

**Comment by scarf005** [comment]
@KheirFerrum could you check this issue?

**Comment by RoyalFox2140** [comment]
I've notified Kheir in Discord, it's being investigated.

**Comment by RoyalFox2140** [comment]
@scarf005 Please test this. It's working on Windows latest. This may be linux specific.

**Comment by RobbieNeko** [comment]
![image](https://github.com/user-attachments/assets/640e74b8-490d-45b1-84bb-9290512c89db)
Can also confirm
- OS: Linux
    - Kernel version: 6.10.6; Distributor ID: Fedora; Description: Fedora Linux 40 (KDE Plasma)
- Game Version: fc4699e [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Item Category Overhaul [Item_Category_Overhaul]
]

**Comment by RobbieNeko** [comment]
Upon testing, the various gas grenades appear to work perfectly fine for me. Incendiaries do not, however
