### ISSUE TITLE
Many windows inherit their deconstruct from t_window

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#5324]
### Describe the bug

I was trying to get into a gun store when I deconstructed the alarmed window with metal bars. What? Why? Because `t_window_bars_alarm` inherits `deconstruct` field from `t_window` And to make this worse so does a lot of other reinforced windows.

### Steps To Reproduce

1. Find any window you shouldn't be able to deconstruct with a hammer and screw driver, such as reinforced ones.
2. Commit Deconstruct Furniture

### Screenshots

![image](https://github.com/user-attachments/assets/ea5f8fc8-4d16-4017-b277-ef8b8e183fbf)
![image](https://github.com/user-attachments/assets/a5b0e340-e5ee-4bbc-b8fe-2bd69de842fe)
![image](https://github.com/user-attachments/assets/db5face2-d363-43fd-88c9-5386f970deaa)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Bazzite; Description: Bazzite 40 (FROM Fedora Kinoite); Release: 40; Codename: Holographic; 
- Game Version: 1d106ac [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Craftable Gun Pack [craftgp],
    Alternative Map Key [alt_map_key],
    Fuji's Military Profession Pack [fuji_mpp],
    Craftable Bullet Casings [CasingCrafting],
    MST Extra [MST_Extra],
    Tankmod: Revived [Tankmod_Revived],
    Essence 2200 BN [Essence2200_BN],
    Essence 2200 Tweaks [FoxTweaks],
    No Addictions [No_Addictions],
    Limit Fungal Growth [limit_fungal_growth],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    OMT Resources [omt_resources],
    Flowing Water [flowing_water],
    No Filthy Clothing [no_filthy_clothing],
    No Wasps [No_Wasps],
    Fox's Revisions mod [FoxRevisions],
    Item Category Overhaul [Item_Category_Overhaul],
    Cataclysm++ [Cata++]
]

### Additional context

https://youtu.be/6M-NkQAo-3E?t=21

**Comment by chaosvolt** [comment]
Good news, while many windows do this, the only ones where this really fucks anything up are the barred windows (oddly, only one variant, others are self-defined) and basic boarded-up windows. All the rest are standard easily-shattered windows, so. >:D
