### ISSUE TITLE
Bring over CBM crafting from Aftershock to main

### ISSUE THREAD

**Issue by mkikt4743** [cataclysmbnteam/Cataclysm-BN#535]
# Is your feature request related to a problem? Please describe.
Don't really wanna have to run aftershock and get char creation bothered as well as more junk I can't craft, only reason I run it is for CBM crafts
# Describe the solution you'd like
Move CBM crafts back to main

# Describe alternatives you've considered
Make aftershock less bloaty or have CBM crafts be separate mod

# Additional context

Figure it should be simple enough

**Comment by mkikt4743** [comment]
Mainly because Aftershock forces CBM slots.

**Comment by Mom-Bun** [comment]
If you wish to have craftable CBMs in main line, you'll probably need to cut out some of the special high-tech stuff and give it a unique recipe that makes sense because the current items used in its recipe is exclusive to aftershock, and I feel like those items, even if BNs is in the future, are way too sci-fi for BNs.

**Comment by mkikt4743** [comment]
Yeah, can't say I've run aftershock recently enough to see what stuff is needed. My mistake. I'll look into the pre-fancy stuff recipes and see if they look balanced.

**Comment by Lorith** [comment]
Could also dig up the recipes from when crafting was allowed in mainline, https://github.com/CleverRaven/Cataclysm-DDA/pull/25108 and https://github.com/CleverRaven/Cataclysm-DDA/pull/33131 and maybe more, not sure, but those two came up quickly in a search.

**Comment by mkikt4743** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/25108 https://github.com/CleverRaven/Cataclysm-DDA/pull/33131 both contain the original recipes, to my memory. Another welcome movement to main code would be the Solar Panels CBM.

**Comment by Coolthulhu** [comment]
Worth considering. But I don't see a good reason to keep an issue open for it. No one volunteered to do it for a while, so it looks like it won't happen soon.

Closing as stale.

**Comment by Zireael07** [comment]
Might be worth having a project or issue listing 'stable but worth doing' things?

**Comment by Coolthulhu** [comment]
Project could be good, I guess. I'll start one.
