### ISSUE TITLE
Crafting with ingredients in bathtub doesn't work

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#541]
A bathtub with water will not provide said water for purposes of crafting.

**Comment by mkikt4743** [comment]
This could also include fluids in kegs, water heaters, et cetera, since afaik they use the same code.

**Comment by Coolthulhu** [comment]
Bathtubs are even referred to as kegs in some menus.
Kinda funny that you can store 4 different liquids in 4 different tiles of same bathtub.
