### ISSUE TITLE
Rationalize Split Rail Fence recipe

### ISSUE THREAD

**Issue by narkiel** [cataclysmbnteam/Cataclysm-BN#5454]
### Is your feature request related to a problem? Please describe.

The current recipe for Split Rail Fences calls for:
2 pointy sticks or 2 wooden spears
4 planks
20 nails

This seems to fly in the face of what a split rail fence actually _is_.  For example:
![Split-Rail-Fence-at-parking-area-2048x1346](https://github.com/user-attachments/assets/d8712f49-c18c-43e0-80cf-ea80269d9482)
![bc17259941e925ddd5ef442fa3a99f17](https://github.com/user-attachments/assets/2abe18e3-d154-40ae-9a04-78d4b05a0497)
![2rail-Post-and-Rail-Basking-Ridge-NJ](https://github.com/user-attachments/assets/7ccb5631-b2dd-4b20-bde2-c6beff66c1c5)

This problem is exacerbated by the fact that _all_ fences require nails, requiring innawoods players to build full-blown walls just for a basic livestock enclosure.

### Describe the solution you'd like

Change the required components to something like 4 logs, or 2 logs and 2 long sticks.  Optionally, add a tool requirement for 1 chiseling (eg stone chisel or better)

### Additional context

Alternative solution:
Add some kind of wattle fence recipe

**Comment by RoyalFox2140** [comment]
2 logs are big, so 2 logs and a chisel works. You can split the logs in half after all. I'll handle this in a little bit.
