### ISSUE TITLE
Translation templates aren't pushed to transifex

### ISSUE THREAD

**Issue by scarf005** [cataclysmbnteam/Cataclysm-BN#5462]
## Situation

![image](https://github.com/user-attachments/assets/452b18fb-e4de-4d0b-8a20-fb23548def3d)

it was reported in [discord](https://discord.com/channels/830879262763909202/1093580823351001098/1289919496949338114) that transifex templates hasn't been updated since last week (2024-09-22).

## Root cause

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/a0a43466014e49e210ddb4b9f6c29410ef59f560/.github/workflows/push-translation-template.yml#L6-L9

this was due to `push-translation-template` workflow depending on workflow named `Experimental Release`, which hasn't been addressed in #5400 where it did not replace all usages of `experimental` to `nightly` (CC @RobbieNeko).

## Solution

rename to `Nightly Release` but i'd like to find more robust solution (e.g are there id field in workflow?)

**Comment by RobbieNeko** [comment]
Oops.

In my defense, I didn't realize that the translations had a build process / workflow that depended on releases, and I also was rather focused on the actual building.

At least it's just a simple change?
