### ISSUE TITLE
Lighting a molotov cocktail causes it to disappear

### ISSUE THREAD

**Issue by Soadreqm** [cataclysmbnteam/Cataclysm-BN#5464]
### Describe the bug

A lit molotov will vanish one turn after it was lit. Since lighting a molotov takes nonzero time, most times it just disappears instantly.
If you manage to light a molotov in less than one second, so that a turn does not pass, the molotov remains in inventory and can be thrown as normal.

Molotov cocktail should not vanish until after you throw it, and it should generally cause a burst of fire when it does so.

### Steps To Reproduce

1. spawn molotov
2. apply molotov
3. where is the molotov?

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Pro N
- Game Version: ed4d9fb [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Item Category Overhaul [Item_Category_Overhaul]
]

### Additional context

![stalin_censorship_1](https://github.com/user-attachments/assets/2daea2e5-a9a8-4daa-9270-e69e1c2bf5c4)
 Molotov is the one with the glasses, on the left. He is NOT supposed to be the one who disappears.

**Comment by RoyalFox2140** [comment]
May be related https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5297

**Comment by RoyalFox2140** [comment]
I set initial and max charges to 5 on the molotov. It fixed nothing.

Sometimes it disappears after 5 charges are used, and sometimes I can store them on the floor, they never detonate in either case unless thrown.

**Comment by RoyalFox2140** [comment]
![image](https://github.com/user-attachments/assets/ffe5f89c-8f23-4dd6-abcd-f1bd4b848059)

**Comment by RoyalFox2140** [comment]
Btw molotovs quenched by rain don't stop being lit. They're still throwable. This is probably why I store lit molotovs on the floor.
