### ISSUE TITLE
Giant slug gets corroded by acid field

### ISSUE THREAD

**Issue by pherixu** [cataclysmbnteam/Cataclysm-BN#5469]
### Describe the bug

the fd_acid field type is set to the correct immunity (acidproof) and the giant slug has the correct acidproof flag as well, but the slug gets corroded by it's own acid trail. 

### Steps To Reproduce

>spawn giant slug
>wait for it to move
>hover over slug to see "corroded[5]"

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4169 (23H2)
- Game Version: v0.6.0 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth]
]

**Comment by scarf005** [comment]
could you check this happens on latest nightly?

**Comment by pherixu** [comment]
i just checked and the bug is fixed on nightly, what was the fix?

**Comment by scarf005** [comment]
seems to be fixed by #4618.
