### ISSUE TITLE
Missing beehive's crafting recipe

### ISSUE THREAD

**Issue by Fruitybite** [cataclysmbnteam/Cataclysm-BN#5486]
### Describe the bug

There is no way to craft a beehive, which is required to construct an empty beehive.
@chaosvolt mainlined lots of things from MST Extra in #5468, but maybe just forgot to import the beehive's recipe.

### Steps To Reproduce

1. Try to craft a beehive in craft menu.
2. There is no recipe yet.

### Versions and configuration

- OS: Windows 10
- Game version: 415f721
- Graphics version: Tiles
- Ingame language: Korean
- Mods loaded: None

**Comment by chaosvolt** [comment]
Gwuh, I thought I did but I forgot. D:
