### ISSUE TITLE
Picking up a grenade dropped by a monster causes detatched ptr error

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#5508]
### Describe the bug

Picking up grenades dropped by zombie soldiers and the like is causing the following error on highlighting it to pick up:
```
 DEBUG    : Attempted to resolve invalid detached_ptr

 FUNCTION : get
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\detached_ptr.cpp
 LINE     : 57
 VERSION  : BN 606c81e
```

Oddly, grenades debugged in seem to be fine? I also tested the smoke bomb also dropped by a zombie soldier and no issue, just the grenade itself is being fucky.

### Steps To Reproduce

1. Spawn a grenade.
2. Drop it on the ground.
3. Use `g` to try and pick it up. Observe it works fine.
4. Spawn a bunch of zombie soldiers and debug-kill them.
5. Try to pick up a grenade off one of their bodies, it go error.

### Screenshots

Smoke bomb works fine...?
![image](https://github.com/user-attachments/assets/7e6b40c6-490d-4bf3-8c04-ed5ba6d104ea)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.450 (2004)
- Game Version: 606c81e [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn]
]

**Comment by chaosvolt** [comment]
I just noticed: the nades have a `none` in them but the smoke bombs don't:
![image](https://github.com/user-attachments/assets/c65f931d-bfb7-4caf-8e22-d8ea1deff88f)

Possibly related to https://github.com/cataclysmbnteam/Cataclysm-BN/issues/5396 ???

**Comment by ZChris13** [comment]
this is #5396, yes
