### ISSUE TITLE
Rose hip jam has unnecessary underscore

### ISSUE THREAD

**Issue by narkiel** [cataclysmbnteam/Cataclysm-BN#5539]
### Describe the bug

If you contruct rose hip jam, it presents as "rose_hip jam"

### Steps To Reproduce

1. Spawn some rosehips, a container, and a cooking tool
2. Craft jam

### Screenshots

![rose_hip](https://github.com/user-attachments/assets/80a3b9fe-a59f-4257-aa89-7d1dc4467af7)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2965 (22H2)
- Game Version: 73412f3 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Item Category Overhaul [Item_Category_Overhaul],
    innawoods [innawoods],
    Pride Flags for BN [pride_flags],
    Prevent Zombification [no_zombify],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Manual Bionic Installation [manualbionicinstall],
    No Fungal Monsters [No_Fungi],
    No Monsters [Only_Wildlife]
]

**Comment by chaosvolt** [comment]
Goofy ahh copypaste, easy fix at least. :>

**Comment by chaosvolt** [comment]
Mildly less easy fix since it turned out every single comestible that varies based on what fruit it was made with has this typo. XD
