### ISSUE TITLE
Bolts should not be able to pierce through stone walls

### ISSUE THREAD

**Issue by smackdabinthemiddle** [cataclysmbnteam/Cataclysm-BN#5552]
### Describe the bug

In this particular case I was using an aluminum broadhead bolt from "Stronger archery" mod.

### Steps To Reproduce

1. Get pneumatic bolt rifle.
2. Get bolts.
3. Try to shoot at wall until it pierces.

### Screenshots

![375077199-fee32c1d-b121-466b-8bae-7e02bf12c5e1](https://github.com/user-attachments/assets/d72277e2-44cd-4bda-af8b-1c060b288b9b)
![image](https://github.com/user-attachments/assets/347e0009-568e-4114-ba19-9e2e40d782c6)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 04636f6 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Item Category Overhaul [Item_Category_Overhaul],
    Arcana and Magic Items [Arcana],
    BL9-100%-monster-resilience-version [BL9_100monres],
    Cataclysm++ [Cata++],
    Secronom [secronom],
    Secronom+ Lore Expansion [secronom_lore_expansion],
    Essence 2200 BN [Essence2200_BN],
    C.R.I.T. Expansion [crt_expansion],
    Sierra Madre [sierra_madre],
    Lones Atomic additions [lones atomic additions],
    Lones Translocator Gates [translocator_gates],
    Aftershock [aftershock],
    Lones Wearable UPS [lones_UPS],
    Add Bandits Extended+ [GOV_BANDITS_KAI_R],
    Battle Maid Redux [battle_maid],
    Bio-Synth Robot expansion [gekkobots],
    Chorus's Arcana Addon [Chorus Arcana Addon],
    Chorus's Gear [Chorus_Weapons],
    Chorus's CBMs [Chorus CBMs],
    Chorus's Martial Arts [Chorus_MA],
    Chorus's Primitive Living [Chorus Primitive],
    Chorus's Starts [Chorus_Starts],
    Essence 2200: Imperial Invasion [ImperialInvasion],
    Fallout New England [fallout],
    Magical Nights [MagicalNights],
    More Dangerous Encounters [More_Dangerous_Encounters],
    Nechronica Redux [Nechronica_Redux],
    Steampunk Mod [steampunk_arcanum],
    Sudo's Requiem [Sudo Requiem],
    Teleportation [teleportation_tech],
    UnderrailMetro Mod [underrailmetro_mod],
    Wild Living [WildLiving],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    Adurnsyl's Assorted Arms and Armour [AAA],
    Advanced Gear [adv_gear],
    Advanced Technologies [advtech],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    anti-fungal gear [anti_fungal_gears],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Arsenal Breach [arsenal_breach],
    Artyoms' Gun Emporium - Reloaded [Arts' Guns],
    Bens GF recipes [Tolerate_This],
    BioCo Content [bioco],
    Bionic Space Expander [Bionic_Space_Expander],
    Bionics Systems Recipes [bio_recipes],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Bootleg Walkers [Bootleg_Walkers],
    Cataclysm: Second Chance [expansion_tefnut],
    CBM Equipment [CBM_Arms],
    CIVILIAN POWER ARMOR [CIVILIANPOWAAA],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Craftable Gun Pack [craftgp],
    Culinary Days Ahead [culinary_days_ahead],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Expanded Archery [ExArch],
    Gourmand's Graces [Gourmand'sGraces],
    Growable Garden Pots [growable-pots],
    Growable Various Plants Flowerpot (uekibati) mod [Uekibati_mod],
    Homemade Fungicide [homemade_fungicide],
    Icecoon's Arsenal [ew_pack],
    Large capacity storage CBMs [eps_cbm],
    Make a Lot of Items [Make_a_Lot_of_Items_Mod],
    Makeshift Items Mod [makeshift],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Metal materials [metal_elemental],
    MOD to grow tea leaves [More tea leaf],
    More Armors [More_Armors],
    More Makeshift Stuff [makeshift_stuff],
    More Survivor Notes [more_survive_notes],
    MST Extra [MST_Extra],
    Mythological Replicas [nw_pack],
    Nimian Manufacture Guns [NM_wpns],
    Pipe Revolver Rifles [pipe_revolver_mod],
    Pixel's Various Fuckery [Pix's Shit],
    Pneumatic fun [pneumo_fun],
    Project APEX [apex],
    Ricky's Future Armory [futurearmory],
    Rivtech Beam Swords [beamswordmod],
    Survivor's Lost item [Survivors_Lost_item],
    Survivor crowbar [surv_crowbar],
    The Glory Of Cereal! [CerealMod],
    The Vermilion Mod [VermilionMod],
    Thermal Electric UPS [thermal_ups],
    Blazemod - Vehicle Additions Pack [blazemod],
    vorpal weapons [vorpal_weapons],
    Whaleys Collectables [collectablemod],
    XEAS [XEAS],
    Xeno's SAS4 weapons pack [Xeno_SAS4],
    ZSFIXED_C:DDA Extra Professions & Gears [ZSFIXED_cddaxp],
    Bug's life [Bug's life],
    DinoMod [DinoMod],
    Draco's Dog Mod [DracoDogMod],
    Draco's Pig Mod [DracoPigMod],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Salvaged Robots [Salvaged_Robots],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch],
    Arcana/C.R.I.T. Patchmod [Arcana_Crit_Patch],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    Arcana/DinoMod Patchmod [Arcana_Dinomod_Patch],
    Arcana/Magical Nights Patchmod [Arcana_MagiclalNights_Patch],
    Mythical Martial Arts [MMA],
    CDDA Variety Pack [ks_variety_pack],
    Compatible Ninja MOD [Ninja],
    Hydroponics [hydroponics],
    Jury-Rigged Robots [jury_rigged_robots],
    Merchant Mod [Merchant],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    Sarcophagi Access [sarcophagi_access],
    Tekitou Map Commercial Overhaul [tekitoumap],
    Thog's Stuff [Thogs_Stuff],
    THRESHOLD [add_mutant],
    Wandering Masters [wandering_masters],
    Wield Wild Weapons [WIELD_WILD_WEAPONS],
    Alternative Basement Layouts [basement_extension],
    Animatronic Monsters [Animatronic_monsters],
    Caches [P_Caches],
    Dorf Life [Dorf_Life],
    More Locations [more_locations],
    Morlock Village [morlock_village],
    Nuclear Power Plant [NPP],
    Ships From Oa Additional Buildings [Ships],
    Trailer Parks [trailerpark],
    Water Towers [water_towers],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Folding Parts pack [deoxymod],
    Tankmod: Revived [Tankmod_Revived],
    Roadheader and other mining vehicles [Heavy miners],
    Shrub it off [shrub_mod],
    Visible car roof [Visible_car_roof],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    MSX Fake Snow [UDP_BN_FAKE_SNOW],
    Faster Stamina Regen [stamina_regen_buff],
    Fuji's Military Profession Pack [fuji_mpp],
    Gunslinger Mod [MkMaxxi's Gunslinger Mod],
    Necropolis Actually Findable [necro_find],
    No Addictions [No_Addictions],
    No Filthy Clothing [no_filthy_clothing],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Stronger archery [bow_opness],
    Targeted Mutations [TaMu],
    Vehicle Additions Additions [blaze_extension_M],
    The Arcology Mod [arcology]
]

**Comment by Proxiehunter** [comment]
> >uses a mod that gives ammo massive damage multipliers >uses it in the fork where bows don't have single-digit damage values >is surprised when the 55-damage pneumatic bolt driver can punch through stone walls (80-160 damage reduction) when fed bolts that've been modded to more than double the weapon's damage and tack on 20 arpen
> 
> Ranged bash info can definitely use some potential sanity-checking places for some terrain/furniture could use a buff or a nerf, but we can't really balance against third-party mods that easily. In this particular example, stone walls can already negate anything up to .30-06 AP, I can't start seeing wallbangs in testing until I break out the .50 cal.
> 
> With respect to vanilla crossbows, I can confirm that several of them get just enough oomph to sometimes (not 100%) zip through stone walls when fed bodkin bolts specifically, which have a hefty 50% armor multiplier. When fed regular broadheads or even carbon fiber bolts, so far I haven't seen even the heavy crossbow (75 damage, strongest vanilla crossbow) punch through with anything other than bodkins.

And this is why these days before reporting a bug on github I will usually start a test world running no mods the game doesn't start with _by default_ (Bright Nights itself, disable NPC needs, Simplified Nutrition, and item category overhaul) and attempt to duplicate it _there_ before reporting. If a mod is causing it you need to talk to the person maintaining the mod.

**Comment by RoyalFox2140** [comment]
> >uses a mod that gives ammo massive damage multipliers >uses it in the fork where bows don't have single-digit damage values >is surprised when the 55-damage pneumatic bolt driver can punch through stone walls (80-160 damage reduction) when fed bolts that've been modded to more than double the weapon's damage and tack on 20 arpen
> 
> Ranged bash info can definitely use some potential sanity-checking places for some terrain/furniture could use a buff or a nerf, but we can't really balance against third-party mods that easily. In this particular example, stone walls can already negate anything up to .30-06 AP, I can't start seeing wallbangs in testing until I break out the .50 cal.
> 
> With respect to vanilla crossbows, I can confirm that several of them get just enough oomph to sometimes (not 100%) zip through stone walls when fed bodkin bolts specifically, which have a hefty 50% armor multiplier. When fed regular broadheads or even carbon fiber bolts, so far I haven't seen even the heavy crossbow (75 damage, strongest vanilla crossbow) punch through with anything other than bodkins.

Maybe ammo could use some kind of sturdiness value for ranged bash calculations, A rocket not  punching through a wall due to being a frag rocket.
