### ISSUE TITLE
Supply Crate Error

### ISSUE THREAD

**Issue by flesh420** [cataclysmbnteam/Cataclysm-BN#5554]
### Describe the bug

Smashed open supply crate with pipe.

### Steps To Reproduce

Smashed open supply crate with pipe.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 5625f29 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Item Category Overhaul [Item_Category_Overhaul]
]

### Additional context

[debug.log](https://github.com/user-attachments/files/17319793/debug.log)

**Comment by ZChris13** [comment]
this already got fixed, update your game

**Comment by RoyalFox2140** [comment]
I'm not sure what the bug is, but feel free to supply more information and I'll reopen the issue.

**Comment by ZChris13** [comment]
> I'm not sure what the bug is, but feel free to supply more information and I'll reopen the issue.

his debug log looks a lot like #5396 and #5508 to me

**Comment by RoyalFox2140** [comment]
I didn't open the log because there was no information provided to tell me what the poster was saying is the bug we need to fix, however if it's related to null items in grenades in supply drops we fixed that with https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5563
