### ISSUE TITLE
Heavy survivor armor and other survivor gear requires bionics to make. Is this working as intended?

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#557]
# Describe the bug

Heavy survivor armor and a lot of other survivor gear requires cutting 2. As far as I can tell this is _only_ available to characters that have an integrated tool set or from an item that comes from a mod. Is this armor supposed to only be available to cyborgs?

# Steps To Reproduce

Look at the requirements to make survivor gear. Note that some items require cutting 2 to make. Look for something that has cutting 2 besides an extended integrated tool set and fail to find it.

# Expected behavior

Non cyborgs can make the armor.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: bf74cc1 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Hauling Space From Aftershock [aftershock_hauling_space],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Bootleg Walkers [Bootleg_Walkers],
    Camping tools [camping_tools],
    CIVILIAN POWER ARMOR [CIVILIANPOWAAA],
    Flowerpot (uekibati) mod [Uekibati_mod],
    Garden Pots [growable-pots],
    Homemade Fungicide [homemade_fungicide],
    Incinerator [incinerator],
    Large capacity storage CBMs [eps_cbm],
    Makeshift engine hoist [makeshift_engine_hoist_mod],
    Makeshift Items Mod [makeshift],
    MakeshiftCanteen [MSCanteen],
    More Makeshift Stuff [makeshift_stuff],
    Power_Armor_Additions [Power_Armor_Additions],
    Sewing Machine [SM],
    Survivor's Lost item [Survivors_Lost_item],
    Hydroponics [hydroponics],
    Jury-Rigged Robots [jury_rigged_robots],
    More Survivor Stuff [more_survivor_stuff],
    Mutant NPCs [mutant_npcs],
    Wandering Masters [wandering_masters],
    Whaleys Hair Mod [WHALEYHAIR1],
    Caches [P_Caches],
    Blazemod - Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Shrub it off [shrub_mod],
    Tankmod: Revived [Tankmod_Revived],
    Graphical Overmap [Graphical_Overmap],
    Mutation Changes Snofielf [Mutation_Changes1],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

I have considered some of these mods may be the source of the problem but looking directly at the jsons in Bright Nights while I can't find the specific cutting requirements listed I note the entry "toolset" listed in the tools required to make it which I _think_ is referring to the integrated tool set?

Fixes would be to either create something else with cutting 2, lower the cutting requirement, or leave as is with only cyborgs able to construct some survivor gear.

**Comment by Proxiehunter** [comment]
Never mind, that does appear to be one of the mods.

Where do I look in the Bright Nights files to find what qualities I need to make something? If I'd been able to find that readily I wouldn't have made this issue.

**Comment by Coolthulhu** [comment]
> Where do I look in the Bright Nights files to find what qualities I need to make something?

`data/json/recipes`
For me, the best way is to do text search. First find the item by its english name, then find its ID, then find the recipes that use this ID.
Alternatively, have one world without any mods, with one character. You can use crafting menu "unavailable" option (default 'u') to list all recipes.
