### ISSUE TITLE
Fix url_utility.cpp for FreeBSD

### ISSUE THREAD

**Issue by mord0d** [cataclysmbnteam/Cataclysm-BN#5585]
### Describe the bug

I'm not good at explaining things so…

```patch
diff --git a/src/url_utility.cpp b/src/url_utility.cpp
index 6ae3682..45dc845 100644
--- a/src/url_utility.cpp
+++ b/src/url_utility.cpp
@@ -12,6 +12,8 @@ void open_url( const std::string &url )
         "start \"\"";
 #elif defined(__linux__)
         "xdg-open";
+#elif defined(__FreeBSD__)
+        "xdg-open";
 #elif defined(__APPLE__)
         "open";
 #elif defined(__ANDROID__)
```

### Steps To Reproduce

Just try to build BN on FreeBSD.

### Versions and configuration

- Commit: `735126428a254ef2994732399a840bf08e233497`

If something else is makes sense, let me know, I'll add it.

**Comment by scarf005** [comment]
sounds good, could you open a PR directly?
