### ISSUE TITLE
Hitchhikers Guide to the Cataclysm Bright Nigts Edition displays more errors.

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#5592]
### Describe the bug

Was trying to find the most accessible sources for copper scrap so I could make some bronze the other day so I went to the [Hitchhikers Guide to the Cataclysm Bright Nights Edition](https://cbn-guide.mythoscraft.org/) and discovered that [Copper tubing](https://cbn-guide.mythoscraft.org/item/cu_pipe), [scrap copper](https://cbn-guide.mythoscraft.org/item/scrap_copper), and [copper wire](https://cbn-guide.mythoscraft.org/item/cable) all return the error message 

"Error

There was a problem displaying this page. Not all versions of Cataclysm are supported by the Guide currently. Try selecting a different build.

Requested non-string id. Current id is of type: undefined"

### Steps To Reproduce

Go to the links listed above or go to The Hitchhikers Guide to the Cataclysm Bright Nights Edition and search for any of "Scrap Copper" "Copper Tubing" or "Copper Wire". All other items with "Copper" in their name are displaying correctly as of when I checked a few minutes ago. 

### Versions and configuration

Not applicable. The website as I understand pulls the code directly from Github for it's information. 

### Additional context

Posting this here (as well as on _their_ Github) because last time I was seeing this error message it was fixed on this end with [this pull request](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5577) suggesting the same thing or something very similar needs to be done with these and possibly related items.

**Comment by RoyalFox2140** [comment]
We don't develop the guide, the creator isn't even in the Discord as far as I can tell by searching their name. https://github.com/mythosmod/cbn-guide

**Comment by Proxiehunter** [comment]
> We don't develop the guide, the creator isn't even in the Discord as far as I can tell by searching their name. https://github.com/mythosmod/cbn-guide

As I said I reblogged it here because last time the same error was happening it was fixed with the linked PR.. I did _also_ file a bug report on their github but I don't have much hope since that PR also fixed a bug that was reported back in March and not acted on or acknowledged by the maintainer.

**Comment by scarf005** [comment]
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/59f995cc14cd822acd9439c3f4bf4805d944136e/data/json/items/resources/metal.json#L307-L325

scrap copper has its ID defined like other items, so it might be an issue of CBN-guide. until the exact cause is found out to be BN's fault, i believe this issue would be better handled in https://github.com/mythosmod/cbn-guide/issues/17.

> I reblogged it here

please specify the full URL here next time, otherwise github doesn't know these issues are related.
