### ISSUE TITLE
Blood extracted from zombie animals contains human flesh

### ISSUE THREAD

**Issue by Soadreqm** [cataclysmbnteam/Cataclysm-BN#5602]
### Describe the bug

Blood extracted from zombie animals is marked as containing human flesh.
This is somewhat reasonable for blood extracted from human zombies, though it should be noted that other zombie products generally aren't considered human. For zombies that were never human, though, it seems like an obvious error.

Also, if the "human" blood is used to craft mutagen, the mutagen is also marked as containing human flesh. This is presumably working as intended, though it feels a bit odd.

### Steps To Reproduce

1. spawn container, knife and zombie animal (tested with decayed pouncer)
2. kill zombie animal
3. butcher zombie animal, bleed it, and gather at least some of the blood
4. examine tainted blood, it is marked as human

### Screenshots

![cata-2024-10-23-21-08-09](https://github.com/user-attachments/assets/f3aceb96-b841-4b6c-90ca-d15e720c1861)
_Has science gone too far?_

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Pro N
- Game Version: f1d21aeaada [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Item Category Overhaul [Item_Category_Overhaul],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp]
]

**Comment by RoyalFox2140** [comment]
Science never goes far enough :)
