### ISSUE TITLE
Dairy free delux sandwitch made with smoked Veggy sausage counts as having meat in it despite containing NO meat.

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#5613]
### Describe the bug

The Dairy Free Deluxe Sandwich displays the message "The thought of eating this makes you sick" when an herbivore attempts to eat the sandwich, even when the sandwich contains _no_ meat.

I assume this is because the sandwich is tagged as containing flesh even when made with _no_ meat products.  Either the sandwich should only be flagged as containing flesh _if it actually contains flesh_ (similar to how things don't get tagged as containing human flesh if not actually made with humans) or the vegetarian version needs to be it's own recipe that _isn't_ flagged as containing flesh (the "Vegan Deluxe Sandwich" maybe). Not sure which is easier. 

### Steps To Reproduce

1: Make a dairy free deluxe sandwich using veggy sausage (I used smoked, I assume the result would be the same with other versions). 

2: Attempt to eat the sandwich with a character who is an herbivore or has meat intolerance. 

3: The game should inform you that the thought of eating it makes you sick despite the sandwich containing no meat.

### Screenshots

Here you can see it telling you the thought of eating the sandwich will make my character sick.

![image](https://github.com/user-attachments/assets/d1bdc071-ea7d-40e1-8219-4cbff8f17ec1)

Here you can see that the sandwich is made from bread, dehydrated vegetables, seasoned salt, and smoked _veggy_ sausage. All ingredients an herbivore character _should_ be able to eat.

![image](https://github.com/user-attachments/assets/28f675f0-8188-4a6a-9b4c-a37f97c9c42f)

And here I have temporarily turned off my herbivore mutation through the cheat menu to show that the Dairy Free Deluxe Sandwich is superior to the simpler Veggy Sandwich made with smoke veggy sausage by 30 calories and 8 joy. So there's a decent reason to fix this instead of just _not making_ the deluxe version if your character can't eat meat.

![image](https://github.com/user-attachments/assets/2d6001f6-85cf-4e02-b87e-9c5bfef37e00)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: dba7a53 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Limit Fungal Growth [limit_fungal_growth],
    Item Category Overhaul [Item_Category_Overhaul],
    Wild Living [WildLiving],
    Advanced Technologies [advtech],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    anti-fungal gear [anti_fungal_gears],
    Bens GF recipes [Tolerate_This],
    Bionic Space Expander [Bionic_Space_Expander],
    Bionics Systems Recipes [bio_recipes],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Bootleg Walkers [Bootleg_Walkers],
    CBM Equipment [CBM_Arms],
    CIVILIAN POWER ARMOR [CIVILIANPOWAAA],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Culinary Days Ahead [culinary_days_ahead],
    Gourmand's Graces [Gourmand'sGraces],
    Large capacity storage CBMs [eps_cbm],
    More Survivor Notes [more_survive_notes],
    Survivor's Lost item [Survivors_Lost_item],
    Survivor crowbar [surv_crowbar],
    Salvaged Robots [Salvaged_Robots],
    Jury-Rigged Robots [jury_rigged_robots],
    Merchant Mod [Merchant],
    Mutant NPCs [mutant_npcs],
    NPC Recruitment Options [recruitment_options],
    Sarcophagi Access [sarcophagi_access],
    Wandering Masters [wandering_masters],
    Whaleys Hair Mod [WHALEYHAIR1],
    Caches [P_Caches],
    Alternative Basement Layouts [basement_extension],
    Morlock Village [morlock_village],
    Blazemod - Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Shrub it off [shrub_mod],
    Amplified @'s Features [amplified_players_features],
    Hair and Skin Color Cosmetics, UDP and MXotto+ version p10 [mxoudpcosmetics],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    Necropolis Actually Findable [necro_find],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Vehicle Additions Additions [blaze_extension_M],
    Arcana and Magic Items [Arcana],
    Aftershock [aftershock],
    Arcana/Aftershock Patchmod [Arcana_aftershock_Patch],
    No Wasps [No_Wasps],
    Cataclysm++ [Cata++],
    Teleportation [teleportation_tech],
    Arcana/Cata++ Patchmod [Arcana_Cata++_Patch]
]

**Comment by ZChris13** [comment]
similar issues with making sandwiches with cornbread for wheat-free survivors
is there a reason it's not all just inheriting the tags from the ingredients? at a glance, I guess some of the condiments count as junk food and you don't want your sandwich to inherit that

**Comment by chaosvolt** [comment]
It just hasn't been coded in currently. Food items inherit calories and vitamins presently, but materials are still set by the item itself.

**Comment by RoyalFox2140** [comment]
We need to port vitamin based allergies so food material does nothing on allergies and instead food inherits a vitamin that makes people sick. That way we could avoid stuff like gluten by vitamins and we would avoid a lot of these problems. https://github.com/CleverRaven/Cataclysm-DDA/pull/74763
