### ISSUE TITLE
Carbon fiber helmet probably has the wrong protective stats.

### ISSUE THREAD

**Issue by 9SineD** [cataclysmbnteam/Cataclysm-BN#5627]
### Describe the bug

Carbon Fiber Helmet has increased stats compared to Survivor Helmet and other types of Carbon Fiber Armor.

Currently, its performance is slightly better than heavy survivor helmet, with a 1/3 weight difference, and is not consistent with other types of carbon fiber armor or logic. Having looked through PR dedicated to the release of things made of carbon fiber, I also did not find why it is like this.

### Steps To Reproduce

Compare the characteristics of the items.

### Screenshots

![image](https://github.com/user-attachments/assets/b95df71b-5515-4cbd-b453-143675e2e41c)
![image](https://github.com/user-attachments/assets/d52d2ccf-a69d-4e5c-bb79-904ec238e1ed)
![image](https://github.com/user-attachments/assets/3e409206-dc65-433b-a624-117ec969e1d3)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: d08e00a [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Item Category Overhaul [Item_Category_Overhaul],
    Aftershock [aftershock],
    No Hope [no_hope],
    Bionic Slots [cbm_slots]
]

**Comment by chaosvolt** [comment]
It inherits from heavy survivor helms, while all other carbon fiber armor inherits from medieval armor items.
