### ISSUE TITLE
Speedloader chute generates infinite ammo by unloading

### ISSUE THREAD

**Issue by tinybubu** [cataclysmbnteam/Cataclysm-BN#5636]
### Describe the bug

When a shotgun has the Speedloader Chute mod, you can unload infinite shells from it. Whatever shells were loaded before the gun was modded will not be removed when doing the Unload action, yet you receive shells in your inventory. 

The pre-mod shells magically remain stored in the gun even while speedloader tubes function normally.

Expected behavior: Shells should be removed from the shotgun when unloading. Also maybe speedloader tubes would conflict with shells that are already in the gun? I don't know how guns work <3

### Steps To Reproduce

1. Get a shotgun and put shells in it
2. Install speedloader chute mod
3. Unload shotgun to receive shells without actually removing any

### Versions and configuration

- OS: Linux
    - OS Version: Linux Mint 22
- Game Version: 9b1dc65 [64-bit]
- Graphics Version: Curses
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Item Category Overhaul [Item_Category_Overhaul]
]

**Comment by RoyalFox2140** [comment]
![image](https://github.com/user-attachments/assets/8edece40-b2df-44c0-817a-fd3f091bd461)
![image](https://github.com/user-attachments/assets/c3b07385-ffa7-43a6-ad8c-3d9f5e5a291d)
