### ISSUE TITLE
Giving an NPC a laser weapon crashes the game

### ISSUE THREAD

**Issue by Soadreqm** [cataclysmbnteam/Cataclysm-BN#5648]
### Describe the bug

If an NPC is told to wield a laser weapon, or attempts to wield one from inventory, the game crashes.

### Steps To Reproduce

1. acquire a UPS, a battery, an NPC follower and an A7 laser rifle
2. load the UPS and give it to the NPC
3. tell the NPC to use the laser
4. game crashes

### Versions and configuration

- OS: Windows
    - OS Version: Windows 10 Pro N
- Game Version: bea1a3bf721 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Item Category Overhaul [Item_Category_Overhaul]
]

**Comment by scarf005** [comment]
could the crash log be attached?

**Comment by Soadreqm** [comment]
It's supposed to be under /config, right? There isn't one.

**Comment by Coolthulhu** [comment]
It seems to be a divide by zero:
```
Thread 1 "cataclysm-bn-ti" received signal SIGFPE, Arithmetic exception.
0x0000555558332b41 in item::ideal_ranged_dps (this=this@entry=0x55558e87ceb0, 
    who=..., mode=std::optional = {...}) at src/npcmove.cpp:2086
2086	        reload_cost /= magazine_integral() ? 1 : ammo_capacity() / burst_size;
```
