### ISSUE TITLE
Plated leather boots and helmet probably has the wrong protective stats.

### ISSUE THREAD

**Issue by 9SineD** [cataclysmbnteam/Cataclysm-BN#5675]
### Describe the bug

Plated leather boots has increased stats compared to Armored boots and other types of Plated leather armor.

Doubling the performance was hardly expected.

P.S.: After checking, I found out that the statistics of the helmet from the set are also broken, but the statistics of the armor and gloves are in order.

### Steps To Reproduce

Compare the characteristics of the items.

### Screenshots

![image](https://github.com/user-attachments/assets/989f5b77-29e4-4022-b3cf-952ddd7fdd71)
![image](https://github.com/user-attachments/assets/c4d422c8-d514-4a44-96bb-f054c483c34e)
![image](https://github.com/user-attachments/assets/3fbbeeef-38f0-4523-a35a-193e45b3137c)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 7e46150 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Item Category Overhaul [Item_Category_Overhaul],
    Aftershock [aftershock],
    No Hope [no_hope],
    Bionic Slots [cbm_slots]
]

**Comment by ZChris13** [comment]
that's new
it wasn't present in 0d07af0, was it added in #5645 ?

**Comment by 9SineD** [comment]
@ZChris13 

In #5654 the material thickness of the boots was changed/added, I assume that is the reason. The other armor also has a thickness of 8 but their stats are fine.
P.S.: After checking, I found out that the statistics of the helmet from the set are also broken, but the statistics of the armor and gloves are in order.

**Comment by chaosvolt** [comment]
AH! I see the problem. I meant to manually specify ENCUMBRANCE but copy-pasted wrong and made it manually specify material thickness instead.
