### ISSUE TITLE
Gun store windows when missing glass still don't let gas through

### ISSUE THREAD

**Issue by mkikt4743** [cataclysmbnteam/Cataclysm-BN#568]
# Describe the bug

Window frame with metal bars (generally found in gun stores after zeds break all the windows) don't allow gas through, but allow bullets through. Should probably allow gas through to smoke the player or likely NPCs out.

# Steps To Reproduce

Go to gunstore
Break glass
Kill smoker infront of broken window
observe how smoke does not pass through

# Expected behavior
Gasses should pass thru these if bullets can.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: c7a8f2a [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Noticed it because I rush gunstores and sit behind the bars too often , lol

**Comment by Proxiehunter** [comment]
I assume this will also help air it out faster if you shoot a smoker or bloated zombie inside the gun store through a window you or the zombies broke.
