### ISSUE TITLE
Correct minor gramatical error in description of Large Wooden Shield

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#5680]
### Describe the solution you'd like

Large Wooden Shield is described as "_An_ crude wooden tower shield". Grammatically should be "_A_ crude wooden tower shield."

**Comment by scarf005** [comment]
could you please open a PR?

**Comment by ZChris13** [comment]
> could you please open a PR?

is there a tutorial for this, I have some petty grammar fixes to suggest as well

**Comment by scarf005** [comment]
> > could you please open a PR?
> 
> is there a tutorial for this, I have some petty grammar fixes to suggest as well

https://docs.cataclysmbn.org/en/contribute/contributing/

**Comment by Proxiehunter** [comment]
> > > could you please open a PR?
> > 
> > 
> > is there a tutorial for this, I have some petty grammar fixes to suggest as well
> 
> https://docs.cataclysmbn.org/en/contribute/contributing/

Thanks for the link. Having looked at other people's PR's the process of making one looked quite complicated for someone who's main interaction with github has been limited to downloading files and reporting bugs. Between that and being wiped by daily activities and stressors I haven't gotten around to opening the PR for this but the link you gave gets me a step closer. Now I just need some energy and ability to concentrate.

**Comment by scarf005** [comment]
it' really easy, it's as simple as searching https://github.com/cataclysmbnteam/Cataclysm-BN/blob/main/data/json/items/armor/shields.json and clicking `edit this file`
