### ISSUE TITLE
Disassembling a styrofoam cup produces three times more plastic the weight of the cup allows.

### ISSUE THREAD

**Issue by blot-runner** [cataclysmbnteam/Cataclysm-BN#5691]
### Describe the bug

As by the title, disassembling a styrofoam cup (50 grams) produces 2 cardboard (20 grams total) and 2 plastic CHUNKS (100 grams total). I assume the intention was to produce 2 plastic SCRAPS instead (20 grams total, leading to 80% mass recovery, which seems believable given it's a used and discarded piece of trash).

### Steps To Reproduce

1. Create a world with no mods.
2. Create a player.
3. Debug spawn a styrofoam cup.
4. Observe the cup's info stating it can be disassembled into 2 plastic chunks.
5. Disassemble the cup to confirm the resulting plastic chunks weight 100 grams in total (twice the initial item weight and 3.33 times maximum theoretical weight of the plastic in the cup, taking into account the cardboard part).

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5011 (22H2)
- Game Version: 21e4183 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn]
]

**Comment by RoyalFox2140** [comment]
Salvage is usually by weight so I wonder if someone set a manual entry and meant to put it as plastic scrap.

**Comment by RoyalFox2140** [comment]
![image](https://github.com/user-attachments/assets/3ebbedca-7fba-4bfd-8f47-fdb2382ce5e4)
PFFFFFT
