### ISSUE TITLE
comeback of nvgs and infrared goggles into crafts + changes

### ISSUE THREAD

**Issue by Leviathan21** [cataclysmbnteam/Cataclysm-BN#570]
making a return of light amps and infrareds into craft, as much adjucting their stuff

# Describe the solution you'd like
re-add cut crafts into the game, and set the goggles to take space on head instead of eyes when off, as characters keeps them off bay instead of looking through - they dont give any image irl unless on

# Describe alternatives you've considered
make them actually spawn by military facilities and dead zeds

# Additional context
could leave only infrared goggles into crafts, and rename light amps into army nvgs that give a lot more sighting range under darkness, as much light amps win infrareds as they're on the same skill tier

**Comment by Firestorm01X2** [comment]
To solve the issue we need to revert this:
https://github.com/CleverRaven/Cataclysm-DDA/pull/31372
