### ISSUE TITLE
OSX builds broken after PR #5685

### ISSUE THREAD

**Issue by RobbieNeko** [cataclysmbnteam/Cataclysm-BN#5755]
### Describe the bug

OSX builds are not building

This appears to be caused by Apple Clang not supporting initialization of aggregates using items bound in parentheses.

### Steps To Reproduce

Watch Nightly attempt to build

### Screenshots

Offending line:
![image](https://github.com/user-attachments/assets/87c0e4fe-eba4-4a78-b7dc-e1a0d89f498e)
Full error:
![image](https://github.com/user-attachments/assets/eea24127-6d83-4af0-a6ed-e4308497d34b)

### Versions and configuration

Bug has been ongoing since November 17

### Additional context

StackOverflow with a similar error that helped me understand what in particular was going awry: https://stackoverflow.com/questions/70996917/whats-clangs-problem-with-my-code-gcc-and-msvc-think-its-fine

Compiler support for various parts of c++20, see that Apple Clang doesn't support "Parenthesized initialization of aggregates" https://en.cppreference.com/w/cpp/compiler_support/20

**Comment by RobbieNeko** [comment]
I can think of two possibilities here:
1. Change it away from using Apple's eclectically cherry-picked Clang to instead use proper Clang
2. Change the offending line  to satisfy the Apple Clang
I'd imagine 1 is the preferred option?

**Comment by RobbieNeko** [comment]
In an attempt at strategy number 1, I tried switching it to `COMPILER=g++`
Didn't work, came up with the exact same error still
![image](https://github.com/user-attachments/assets/d86c30ae-55d5-428d-b581-9b261a80c151)
![image](https://github.com/user-attachments/assets/edf7c12d-0de9-420f-ab0f-16fb5f48d6de)

**Comment by scarf005** [comment]
> In an attempt at strategy number 1, I tried switching it to `COMPILER=g++` Didn't work, came up with the exact same error still

probably because g++ is aliased to clang++ in mac

```sh
$ g++ --version
Apple clang version 16.0.0 (clang-1600.0.26.4)
Target: arm64-apple-darwin24.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by RobbieNeko** [comment]
Apple, I must say this:
What the actual F*CK

**Comment by RobbieNeko** [comment]
Anyway, thanks for revealing why it was being weird Scarf. Best of luck to whoever next messes with this pile of poor decision-making on Apple's part

**Comment by FriedLongJohns** [comment]
possibly helpful:
https://github.com/actions/runner-images/issues/5287#issuecomment-1080458276
in this comment, they appear to be using brew llvm clang for macOS builds similar to what might be desired here.

**Comment by scarf005** [comment]
related: https://github.com/ThePhD/sol2/issues/1617
