### ISSUE TITLE
Classic view shows incorrect body part for damage amounts. 

### ISSUE THREAD

**Issue by Treah** [cataclysmbnteam/Cataclysm-BN#5778]
### Describe the bug

Health display for body parts is jumbled up in classic view. Compact view shows them correctly. 

### Steps To Reproduce

1. Create player with self aware. 
2. Use debug menu to hurt a body part. 
3. Change view from classic to compact and back and observe change. 

### Screenshots

![Body_Classic](https://github.com/user-attachments/assets/00bff8c6-0abd-4b97-a197-970e838ef48b)
![Body_Compact](https://github.com/user-attachments/assets/846b4369-6a0f-460a-bb62-0a7da23457b5)

### Versions and configuration

09:35:27.267 INFO : Cataclysm BN version 820a9a5 64-bit
09:35:27.267 INFO : C locale on startup: 'en_US.utf8'
09:35:27.267 INFO : C++ locale on startup: 'en_US.utf8'
09:35:27.268 INFO : Detected system UI language as 'en_US'
09:35:27.272 INFO : Set debug classes to: [DEBUGMSG MAIN LUA]
09:35:27.273 INFO : Language set to 'en_US'
09:35:27.273 INFO : C locale set to 'en_US.utf8'
09:35:27.273 INFO : C++ locale set to 'en_US.utf8'
09:35:27.586 INFO : LAPI version: <none>
09:38:21.805 INFO :  GAME REPORT:
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.15; Codename: n/a;
- Game Version: 820a9a5 [64-bit]
- Graphics Version: Curses
- LAPI Version: <none>
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Item Category Overhaul [Item_Category_Overhaul],
    Treah Custom [TreahCustom]

### Additional context

Note: The custom mod listed here does not affect anything related to the UI its simply some alternate recipes and spoil stuff.

**Comment by Treah** [comment]
This is possibly related to the change listed below. I set a branch on my own source and compiling now to see if it fixed the problem. 
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5685

**Comment by Ignaramico** [comment]
does the real dmg/health get jumbled too D:?

**Comment by Treah** [comment]
> does the real dmg/health get jumbled too D:?

No its just a visual bug as opening up the bandage menu shows the correct body part.
