### ISSUE TITLE
Dice are consumed on activation

### ISSUE THREAD

**Issue by ZChris13** [cataclysmbnteam/Cataclysm-BN#5789]
### Describe the bug

One of the recent changes to using items has caused dice to consume themselves upon use

### Steps To Reproduce

obtain any RPG die, activate it to roll it
observe that it has disappeared
if you have multiple, observe that it will consume ~~the entire stack~~ as many as the number it rolled

### Screenshots

![image](https://github.com/user-attachments/assets/02bc90e4-3e71-4cd0-a006-191a3b677f6a)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5131 (22H2)
- Game Version: 08833c3 [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Limit Fungal Growth [limit_fungal_growth],
    Teleportation [teleportation_tech],
    Craftable Gun Pack [craftgp]
]

### Additional context

I collect dice :)
![image](https://github.com/user-attachments/assets/33d95bc7-33ca-4542-9157-8f9a1d82c598)
I am very sad that my stack of seven 20 sided metal dice were consumed :(

**Comment by scarf005** [comment]
cc @KheirFerrum

**Comment by KheirFerrum** [comment]
This is a known bug we inherited. I have no idea why the fuck the iuse was coded the way it was. The iuse should instead return 0 instead if the roll value. I may throw a PR together later today if no one else does. It's basically a single line change.

**Comment by ZChris13** [comment]
this is new, BRB checking which release it happened in

**Comment by ZChris13** [comment]
release 6bbf3ad does not have the bug
release 88c3a84 does have the bug

I guess you knew that it was your PR #5589 that was causing this?

**Comment by KheirFerrum** [comment]
> release [6bbf3ad](https://github.com/cataclysmbnteam/Cataclysm-BN/commit/6bbf3ad9d187f666407069932963f7eca6b1c0c4) (2024-10-17) does not have the bug release [88c3a84](https://github.com/cataclysmbnteam/Cataclysm-BN/commit/88c3a84b863c4d0a104dd8d25f97674badddc122) (2024-10-19) does have the bug
> 
> I guess you knew that it was your PR #5589 that was causing this?

Lol, interesting, had an inkling, but no, I did not. I came across this bug while I was refactoring #5259. Looks like fixing one bug exposed another. The issue here is that iuse action is supposed to return charges to use, this was masked by a separate bug that was causing charges that should be used _not_ being used to begin with.

A fix will be up in a short bit.
