### ISSUE TITLE
Error Item Group: Drugdealer

### ISSUE THREAD

**Issue by Draykan1024** [cataclysmbnteam/Cataclysm-BN#5804]
### Describe the bug

Attempting to create a world with several different mods causes the following error

 DEBUG    : Error: item group "drugdealer" already defined with type "collection"

 FUNCTION : new_character_tab
 FILE     : D:\a\Cataclysm-BN\Cataclysm-BN\src\main_menu.cpp
 LINE     : 918
 VERSION  : BN 118ac20

### Steps To Reproduce

1. Download a mod such as More Armors
2. Create a new world
3. Attempt to create a character or load the world
4. Acquire error

### Versions and configuration

 VERSION  : BN 118ac20

**Comment by Zlorthishen** [comment]
Please try updating the mods from [here](https://github.com/Zlorthishen/BrightNights-Structured-Kenan-Modpack), I fixed that error last month

**Comment by Draykan1024** [comment]
Still has the error even after updating the pack

**Comment by chaosvolt** [comment]
Make sure you're using Zlor's version and not the old Kenan version which is no longer being maintained.

Either way, this issue is out of repo, check what other third-party mods you're using and if it's not in Zlor's modpack, open an issue with the correct repo please.

**Comment by Draykan1024** [comment]
Will confirm for anybody who finds this in the future with the same error, Zlor's fix worked, I just installed it wrong initially.
