### ISSUE TITLE
Mech suit attracting zombies even when it is empty

### ISSUE THREAD

**Issue by Altogolik** [cataclysmbnteam/Cataclysm-BN#582]
# Describe the bug 
На него агрятся мобы даже если он пустой.
Из за этого страдает мое имущество когда я отхожу от него.

# Expected behavior
Я надеюсь на него перестанут агрится зомби и другие существа когда он пустой

# Screenshots
![изображение](https://user-images.githubusercontent.com/48449647/121635301-ad80d380-ca8e-11eb-9502-a685445fae60.png)

# Versions and configuration
версия BN  1999

**Comment by Firestorm01X2** [comment]
Mech suit attracting zombies even then it is empty.

**Comment by chaosvolt** [comment]
Should be fixed by https://github.com/cataclysmbnteam/Cataclysm-BN/pull/4083

Turns out I set it to close https://github.com/cataclysmbnteam/Cataclysm-BN/issues/4030 which was in fact a duplicate of this.
