### ISSUE TITLE
Canned dog food can only be eaten by player

### ISSUE THREAD

**Issue by LyleSY** [cataclysmbnteam/Cataclysm-BN#584]
# Describe the bug

Canned dog food found in houses is eaten by the player when activated. Dog food crafted by the player or debug spawned can be fed to dogs like normal

# Steps To Reproduce

1. Find some canned dog food
2. Try to [a] activate it from the main screen, can't
3. Navigate to the item info in inventory and [a] activate it there
4. You eat your dogfood

# Expected behavior

Works like regular dogfood

# Screenshots

# Versions and configuration

Mac version, recent experimental

# Additional context

Not game breaking

**Comment by olanti-p** [comment]
Can confirm.
It's possible to `U`nload it though, then it works as expected.
