### ISSUE TITLE
Bodypart refactor broke Hide clothing sprites

### ISSUE THREAD

**Issue by RoyalFox2140** [cataclysmbnteam/Cataclysm-BN#5840]
### Describe the bug

I can't press the Hide sprite button on the 12-26 release. This doesn't happen on 12-25. The option is on my menu, but it doesn't work.

Expected Behavior: Pressing H hides your shirt or helmet or pants if you're feeling really wild.
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/5732

### Steps To Reproduce

Go to the armor sorting menu. Hit H on any armor. There's not just a visual indicator per armor but also you'll notice it doesn't render on your character when exiting.

### Screenshots

![image](https://github.com/user-attachments/assets/af9e8a95-830e-4fde-bbfa-30b631a27fb3)
![image](https://github.com/user-attachments/assets/fd4d1704-9eff-40d8-9e18-520ca1d886dc)

Expected results is this third screenshot here:
![image](https://github.com/user-attachments/assets/eccff25c-f615-4078-8281-90d466a46970)

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Bazzite; Description: Bazzite 41 (FROM Fedora Kinoite); Release: 41; Codename: Holographic; 
- Game Version: 87737db [64-bit]
- Graphics Version: Tiles
- LAPI Version: 2
- Game Language:  []
- Mods loaded: [
    Bright Nights [bn],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    No Rail Stations [No_Rail_Stations],
    Prevent Zombie Revivication [no_reviving_zombies],
    Limit Fungal Growth [limit_fungal_growth],
    Item Category Overhaul [Item_Category_Overhaul],
    UDP Redux [udp_redux]
]

**Comment by scarf005** [comment]
related: #5721
