### ISSUE TITLE
Earphones effect persist after turning mp3 off

### ISSUE THREAD

**Issue by Goredell** [cataclysmbnteam/Cataclysm-BN#591]
# Describe the bug

After turning mp3 off effects of "music" and "earphones" are still persist, even after dropping, smashing, disassembling mp3 player or simply waiting. In .sav file those effects are stacked up to ~ 20k turns.

# Steps To Reproduce

1. Find mp3 player
2. Turn it on
3. Spend some time
4. Turn it off
5. Presto! You re technically deaf

# Expected behavior

After turning off mp3 player you lose both "music" and "earphones" effects, right away.

# Screenshots
Effect is intact, despite the fact that I'm already naked
![image](https://user-images.githubusercontent.com/25191435/121774273-67a93580-cb8a-11eb-871e-5050d7599a2b.png)
![image](https://user-images.githubusercontent.com/25191435/121774286-7394f780-cb8a-11eb-9fb5-35b05eb70c91.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: c7a8f2a [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Skills [StatsThroughSkills],
    Bionics Systems Recipes [bio_recipes],
    Armor Up! PA Utilities [ArmUpPAUtil],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Coolthulhu** [comment]
Probably needs a `max_duration`...

**Comment by olanti-p** [comment]
Should be fixed as of release 2023, please re-test.

**Comment by Goredell** [comment]
> Should be fixed as of release 2023, please re-test.

Yeah, seems like i didn't update the game for few days, terribly sorry.

Updated the game, re-checked everything. Seems to work as intended, now.
