### ISSUE TITLE
Random parasites at game start

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#597]
Multiple players reporting getting parasites without reason at game start without any particular reason.

Mod list porbably includes Aftershock and magiclysm, but probably bug is not related to mods.

**Comment by Coolthulhu** [comment]
Would be great if I could get more details.
* Which parasite symptoms
* What did they eat/drink, if anything

It's a high chance that they actually "misdiagnosed" tetanus. You can get tetanus from walking on terrain that hurts you, including rose bushes and rubble.
Also, they can confirm the exact parasite/disease type by activating debug mode (needs a new keybind, it's not bound by default) and waiting a turn. In the messages, they'll get an effect id, possibly buried in other messages (NPCs are noisy in debug mode).

**Comment by Firestorm01X2** [comment]
> 
> 
> Would be great if I could get more details.
> 
>     * Which parasite symptoms
> 
>     * What did they eat/drink, if anything
> 
> 
> It's a high chance that they actually "misdiagnosed" tetanus. You can get tetanus from walking on terrain that hurts you, including rose bushes and rubble.
> Also, they can confirm the exact parasite/disease type by activating debug mode (needs a new keybind, it's not bound by default) and waiting a turn. In the messages, they'll get an effect id, possibly buried in other messages (NPCs are noisy in debug mode).

One of the reports is confirmed tetanus. Lets wait others.

**Comment by Coolthulhu** [comment]
I'll want to remove tetanus because it's very spoiler-heavy and so is removing it (1/3 chance per antibiotic, with message that suggests it doesn't work when it fails), causing more false bug reports than pretty much any other undocumented feature.
It's not "realistic" either, as it has only one stage rather than killing you like "infection".

**Comment by Firestorm01X2** [comment]
I suppose it was cases of  tetanus. So, I am closing it.
