### ISSUE TITLE
Landmine does almost no damage

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#60]
# Describe the bug

Landmines does almost no damage

# Steps To Reproduce

1. Spawn a mine
2. Steop on a mine
3. Get very low damage

Connected issue:
https://github.com/CleverRaven/Cataclysm-DDA/issues/37724
>I believe you should check function trapfunc::landmine() at src/trapfunc.cpp:L605
It clearly uses same explosion() function but uses preset values so I think that landmine probably does not use JSON set values at all.

Confirmed. Landmine triggers:

```
bool trapfunc::landmine( const tripoint &p, Creature *c, item * )
{
    // tiny animals are too light to trigger land mines
    if( c != nullptr && c->get_size() == MS_TINY ) {
        return false;
    }
    if( c != nullptr ) {
        c->add_msg_player_or_npc( m_bad, _( "You trigger a land mine!" ),
                                  _( "<npcname> triggers a land mine!" ) );
    }
    explosion_handler::explosion( p, 18, 0.5, false, 8 );
    g->m.remove_trap( p );
    return true;
}
```
Explosive triggers with hardcoded values
# Screenshots

# Versions and configuration

# Additional context

**Comment by Firestorm01X2** [comment]
@Coolthulhu could at least temporary set hardcoded values to adeqaute values?

**Comment by Coolthulhu** [comment]
Yeah.
Don't make it too insta-killy though. Shouldn't be stronger than a grenade.
Use the `explosion_data` variant of the `explosion_handler::explosion` function, it's much easier to control.
