### ISSUE TITLE
NPC book reading causing debug error popups

### ISSUE THREAD

**Issue by CV514** [cataclysmbnteam/Cataclysm-BN#607]
# Describe the bug

Giving any friendly follower NPC order to read some skill book causing

```
 DEBUG    : Called player::invlet_to_position on NPC (NPC Name)

 FUNCTION : int player::invlet_to_position(int) const
 FILE     : src/player.cpp
 LINE     : 1947
```

# Steps To Reproduce

1. Get some friendly NPC follower (debug speech to 20, debug spawn NPC, convince them to follow)
2. Try to give them instruction to read something
3. See several popups of same error, then game will finally inform you to choose the book or that there is nothing to read at all.

# Expected behavior

NPC should read the book; apparently, they still do even with this error.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: e20b1d1 [64-bit]
- Graphics Version: Tiles
- Game Language: Русский [ru_RU]
- Mods loaded: [
 [dda],
 [no_npc_food]
]

# Additional context

Seems to be happening since 9ae9b73c92f341842e6432d4dfa9662f2c9df7b2 and not specifically break things, but probably should be looked into. Error popup happen regardless of debug level settings.

**Comment by olanti-p** [comment]
> Seems to be happening since 9ae9b73 and not specifically break things

Yeah, it's one of several "should never happen, but it happens anyway, so let's silently report it to the log so no one would ever notice" things I've upgraded to show a popup.
I'll take a look into it tomorrow.
