### ISSUE TITLE
Activity zones shift upon changing z levels

### ISSUE THREAD

**Issue by Wad67** [cataclysmbnteam/Cataclysm-BN#635]
Player activity zones shift over time when traversing z levels

Make some activities zones in a basement, make some trips upstairs to gather stuff.
I have Z levels turned off, maybe this is a contributor?

![image](https://user-images.githubusercontent.com/991507/124126743-56cf4e00-dabe-11eb-8b30-0f45f14772ac.png)

**Comment by ZhilkinSerg** [comment]
Could possibly be related - https://github.com/CleverRaven/Cataclysm-DDA/issues/49309

**Comment by olanti-p** [comment]
> Could possibly be related

They may be.

This issue reproduces only when z levels are turned off, which may be the case in CleverRaven/Cataclysm-DDA#49309 as the author was using 0.E version.

In 0.F, I've got a hitch this issue may screw with placement of non-player zones in rotated multi-z-level buildings (as each generated level rotates the zones regardless of whether they are on the z level that is being generated), but I didn't test nor dig into the code to confirm this as non-player zones are kinda useless atm (https://github.com/CleverRaven/Cataclysm-DDA/issues/49755).
