### ISSUE TITLE
Armor penetration from martial arts doesn't work.

### ISSUE THREAD

**Issue by Broken27** [cataclysmbnteam/Cataclysm-BN#637]
# Describe the bug

Armor Penetration from martial arts doesn't work.

# Steps To Reproduce

Use a martial art+stats than should give you extremely high armor penetration.
Summon a high armor monster, then confirm than your attacks don't cause damage.

(I tested with a variety of styles, modded an unmodded. In the screenshot below you can see 100 Perception Niten (That should give 50 armor penetration) being completely unable to damage a 30 bash/50 cut armor Kevlar Hulk

# Expected behavior

Martial arts should do what they say they do

# Screenshots

![Screenshot - 02_07_2021 , 18_37_28](https://user-images.githubusercontent.com/67008253/124305089-e7f90000-db64-11eb-9559-82fe5c5c94a8.jpg)

# Versions and configuration

Windows 10, using the latest build (2021-06-27-1806)

# Additional context

I discovered this while modding and testing some martial arts of my own.

**Comment by Broken27** [comment]
Edit: This got fixed in dda, someone should migrate the fix.

https://github.com/CleverRaven/Cataclysm-DDA/pull/50132

**Comment by chaosvolt** [comment]
Working on portover PR now.
