### ISSUE TITLE
manhacks weight more than the netto of components 

### ISSUE THREAD

**Issue by Leviathan21** [cataclysmbnteam/Cataclysm-BN#642]
# Describe the bug
manhacks, especially made of grenades and c4, weight excessively too much than the components used
# Steps To Reproduce

1. acquire manhack
2. disassemble and compare
3. The Industrial Revolution and its consequences have been a disaster for the human race.

# Expected behavior

manhacks weight as much as components

# Screenshots

https://cdn.discordapp.com/attachments/854086204579905576/861523373237600266/unknown.png

https://cdn.discordapp.com/attachments/854086204579905576/861523400521678848/unknown.png

# Versions and configuration

 - OS: шindoшs 10
 - Game Version: fresh

**Comment by Relgar** [comment]
No mods? I can't disassemble manhacks by default.

**Comment by Coolthulhu** [comment]
Seems fixed by #1233
