### ISSUE TITLE
Incorrect warning message on installing gunmods to guns with internal magazines

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#649]
# Describe the bug

For weapons with an internal magazine, i.e. loaded with ammo directly instead of a detachable mag, installing gunmods on them displays the "this will force you to need a magazine adapter mod" warning, even for gunmods that don't seem to affect loading.

# Steps To Reproduce

1. Debug spawn in a mosin nagant or other firearm that's loaded directly.
2. Spawn in a shoulder strap, suppressor, whatever else will fit on your gun of choice.
3. Install the gunmod, making note of the warning message shown.
4. Unload and reload the gun to confirm it still accepts cartridges just fine.

# Expected behavior

Message presumably is only intended to appear with specific gunmods, my rough guess is the belt feed adapter or something like that, hard to parse exactly what its intended use case is.

Wording also make me think of how scopes or other mods might hypothetically hinder the use speedloaders with bolt-action weapons, but it seems to be implying the exact opposite far as I can determine.

# Screenshots

Initial screenshot of when I first noticed this:
![image](https://user-images.githubusercontent.com/11582235/124713621-68ea2b80-dec6-11eb-88cd-eed8ff22c5ed.png)

A test screenshot with an M4A1, confirming that it seems unaffected by this:
![image](https://user-images.githubusercontent.com/11582235/124713678-77d0de00-dec6-11eb-837d-985404bb81a3.png)

Then a moist nugget, based on an inkling I had after the M4 turned out fine:
![image](https://user-images.githubusercontent.com/11582235/124713727-84edcd00-dec6-11eb-91fa-dcad339bb835.png)

Finally, testing a different accessory:
![image](https://user-images.githubusercontent.com/11582235/124713761-8dde9e80-dec6-11eb-86f8-1651af2b79d4.png)

# Versions and configuration

```
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 528bb72 [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda],
    Arcana and Magic Items [Arcana],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    MST Extra [MST_Extra],
    Cataclysm++ [Cata++],
    Mining Mod [Mining_Mod],
    Fewer Farms [Fewer_Farms],
    Tankmod: Revived [Tankmod_Revived],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food],
    Faster Stamina Regen [stamina_regen_buff],
    Manual Bionic Installation [manualbionicinstall],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Simplified Nutrition [novitamins]
]
```

# Additional context

I'm still not sure what a magazine adapter mod is in this context, and why a separate gunmod would mandate the installation of a different one, aside from maybe some first stab at a multi-part caliber conversion that requires the player to change the receiver+barrel separate from the magazine well?

**Comment by YourCompanionCube** [comment]
i've also had this when using guns with external magazines (in my case an M16A4)
![image](https://user-images.githubusercontent.com/26364270/132932081-e8f46d58-17e9-4bf0-a907-fe19e7f6c3df.png)
![image](https://user-images.githubusercontent.com/26364270/132932088-fe488e92-f1ec-4fdc-bf72-131b1e34c70e.png)

It appears to happen with any gun that doesn't have an external magazine inserted, not just those that have only internal magazines 

After inserting an empty magazine:
![image](https://user-images.githubusercontent.com/26364270/132932141-2f370423-0eb4-47b5-8aef-6f99e88667d9.png)
