### ISSUE TITLE
More exclusion mod un-obsoleting

### ISSUE THREAD

**Issue by Wreckstation** [cataclysmbnteam/Cataclysm-BN#66]
# Is your feature request related to a problem? Please describe.
Despite having a lot of mods that come with BN, some of them are obsoleted, meaning that they cannot be selected in game unless you edit the jsons themselves to remove their obsolete status. Particularly, I enjoy using exclusion mods. Reenabling them is unlikely to mess up the game since they only stop things from showing up.

# Describe the solution you'd like
Remove the obsolete tags from the proposed exclusion mods:
* No Acid Zombies
* No Explosive Zombies
* No Filthy Clothing
* No Vitamins (I don't know if removing vitamins entirely will be a part of main BN. Some clarification about this would be cool)

# Describe alternatives you've considered
Manually editing each json myself on my local copy, merging the mods into the game and have them toggleable as some debug/world option 

# Additional context
I wanted to submit an issue first to know whether this is the direction that BN was fine with. If so, I am able to edit and make a pull request myself.

**Comment by Firestorm01X2** [comment]
Looks like all of this mod were obsolated as part of that PR:
https://github.com/CleverRaven/Cataclysm-DDA/pull/37272

**Comment by Coolthulhu** [comment]
* No acid/explosive zombies - those are rather small blacklists. Ideally they'd cover more. But if someone is using them, I guess they can be re-enabled.
* No filthy - ideally filthy mechanics would be removed and replaced with something less bad. This mod will need some testing to see it if still works before re-enabling.
* No vitamins - the only "vitamin" that does anything right now is the mutant toxin. This mod could be defaulted for now.

**Comment by Wreckstation** [comment]
re: no acid/explosive zombies: I agree they are rather small, so its fine if they're not added.

I have tested with all of them and confirmed that all of them are functional with the latest release of BN
