### ISSUE TITLE
Rebalance of emcumberance per liter of non-rigid storage items

### ISSUE THREAD

**Issue by chaosvolt** [cataclysmbnteam/Cataclysm-BN#669]
# Is your feature request related to a problem? Please describe.

I was tinkering with trying to free up some weight in my drag cart and space in my inventory by filling up a tool belt with the usual essentials. Then I noticed it had bumped my encumbrance up quite a lot, far more than they gave me just sitting loose in my backpack. Somewhere in the neighborhood of 12 encumbrance for 4 tools, which together gave me an extra 1 encumbrance if dumped in my backpack.

After a fair bit of faffing about, I eventually figured out the root cause. Items defined as non-rigid will increase encumbrance at a set rate, UNLESS a `max_encumbrance` is defined, at a default rate of 4 encumbrance per 1 liter of stuff stored. This count raw `storage`, volume of liquid a wearable container can hold, max volume of all valid holster slots, etc.

I looked at the tool belt and sure enough, it defines a max encumbrance of 42. It starts with 2 encumbrance, can hold 9 liters worth of tools (6 tools, max volume of 1.5 liters each), plus 1 liter of generic storage. In the toolbelt's case, the practical encumbrance rate is thus 4.2 encumbrance per liter stored.

In contrast, the basic backpack holds 10 liters with a max encumbrance of 15, making for 1.5 encumbrance per liter stored. This becomes more efficient for larger backpacks, generally in exchange for larger numbers involved overall. Star examples being the duffel bag at a perfect 1 encumbrance per liter at max capacity, or the giant novelty backpack having about 0.889 encumbrance per liter if filled out.

In general, the main advantage of waterskins, tool belts, and other non-storage-based ways to stow items tends to be in the convenience of freeing up a bit extra space to carry more loot, or to store important items that don't have a dedicated holster-type item like food, drugs, batteries and the like. The question that arises to me, of which I'm not sure, would be about how much encumbrance per liter stored is worth freeing up extra space for loot.

I would be inclined to nudge most non-rigid storage items, those that lack a defined max_encumbrance at least, to be slightly less efficient than the least-efficient backpack that has a defined max_encumbrance. That award goes to makeshift knapsacks, which hold up to 5 liters with a max encumbrance of 9, or 1.8 encumbrance per liter stored.

# Describe the solution you'd like

Trying to shoot for 2 encumbrance per liter stored would probably be a more modest cost to pay for freeing up inventory space that could be used by backpacks. Here's how some of the relevant items would likely be affected by this:
* The toolbelt, being the archetypal example through which I found out about this behavior, would be given a max encumbrance of 20, given it can hold up to 10 liters of stuff.
* The XL holster is the only non-rigid item in holsters.json, and can currently max out at 7 encumbrance. This is 2 more than the fixed encumbrance of back holsters, which can hold a gun that's 7.2 times bigger. It only seems to have a max encumbrance because it's flavored as straps that hold a gun externally, instead of a fully-covering holster. In which case, lowering its base encumbrance to 1 could reflect the reduced amount of material actually present, and give room to assign a max encumbrance of roughly 3.
* The survivor harness is an odd one out that's also implied to have external storage for a firearm, plus pockets to store some things, but is rigid and has fixed encumbrance. Under this scheme I'd presumably make it non-rigid and assign a max encumbrance to it. However, since this is a survivor item and all survivor packs have better efficient than baseline backpacks, one could get away with allowing a max encumbrance of 10-12 for a rating of 1.481-1.778 encumbrance per liter stored, as trying to near 2 encumbrance per liter would make it between 13 and 14 encumbrance.
* Ammo pouches can max out at 17 if storing the bulkiest available ammo, suggesting the largest ammunition would take up 3 liters if filled to the brim. A max encumbrance of 6 would be expected but this is even lower than its base encumbrance of 7. The closely-related chest ammo satchel (for magazines instead) has a fixed 4 encumbrance, and the chest ammo pouch holds less than 1 liter's worth of magazine, it might be reasonable to make most items in ammo_pouch.json have low amounts of fixed encumbrance and count as rigid. This would be consistent with pouches, leather pouches, drop leg pouches, and fanny packs in being items that deal with storage and encumbrance amounts so low that they aren't even worth making non-rigid and assigning a max encumbrance.
* Stone pouches and large grenade pouches are items that break from consistency with all other items in bandolier.json, being non-rigid with no max encumbrance. I'd logically go for making all bandolier-type items use whatever ends up being the solution we pick for ammo pouches, since ammo pouches are bandoliers behavior-wise.
* Spear straps are the only item in sheath.json to count as non-rigid, reasonable as with XL holsters. As with XL holsters I would most likely change it to 1 encumbrance and make 4 its max encumbrance, since it holds 3.5 liters. Ax rings are considered rigid despite not being a typical holster, and can hold up to 3.25 liters, so the may warrant a similar treatment.
* Non-rigid containers like waterskins logically could also be affected. Waterskins are the obvious example, which would likely get max encumbrance values of 2, 3, and 5.
* Oddly, hydration packs count as rigid and have zero encumbrance. As they can store a combined total of 3 liters, expected max encumbrance would be 3.

# Describe alternatives you've considered

1. Baking this rationale into the hardcode is probably doable but would be more of a pain in the ass.
2. I pondered whether or not tool belts still deserve some storage balance-wise if their encumbrance is lowered, but the 20 encumbrance for 10 liters combined total seems like it's reasonably counterbalance that still.
3. Other belts where you clip stuff onto them are currently effectively rigid. Should they be given the same treatment as tool belts, if I do tinker with them?
4. I don't even know where to begin when it comes to survivor belts...

# Additional context

Of the examples mentioned, toolboxes are the most strongly-affected by this and the one where the math on what max encumbrance to give it is the easiest to figure out, so I'd likely start there.

**Comment by Coolthulhu** [comment]
My views:
* Scaling encumbrance with volume usage is a bad mechanic and it would be good to slowly phase it out
* Changing the default (no `max_encumbrance`) penalty is literally just changing one number in hardcode and safe balance-wise
* The scaling of encumbrance with total volume carried is done suboptimally (naively), which is another reason to get rid of it. It probably wouldn't be hard to make it properly optimize the encumbrance, but it might not be worth the effort

For now, if you want a quick fix, 2 encumbrance per liter seems like a safe maximum.

**Comment by chaosvolt** [comment]
So you want me to do a tweak to the hardcode instead as a quickfix, then reduce usage of the mechanic over the long term? I guess I can do that. I'll look for where that value is, but sure.

**Comment by Coolthulhu** [comment]
Seems to be done

**Comment by chaosvolt** [comment]
Seems good, yeah. Though I may want to double-check all the items listed in the OP to see if any of them still deserve a balance pass or not, I'm 90% certain most of the important ones got covered by Lamadus' holster tweaks and by the change to the hardcode value.
