### ISSUE TITLE
[Broken] [Construct] Install Bars Onto Window

### ISSUE THREAD

**Issue by nanohard** [cataclysmbnteam/Cataclysm-BN#670]
While attempting to test a bugfix I found that I could not `Install Bars Onto Window` via the construct menu due to the recipe requiring `window` or `window without curtains`. At no point does either of those exist while constructing any type of window.

# Steps To Reproduce
1. Construct `Empty Window`
2. Cannot `Install Bars Onto Window` because the window is `empty window` and not `window`

# Expected behavior
At any point after constructing a window the player should be able to add bars.

# Screenshots
https://i.imgur.com/psmBQ7X.png

# Versions and configuration
Commit 458e37f

# Additional context
Should be able to build bars on:
- `empty window`
- `empty metal window frame`
- `window without curtains`
- `taped window`
- `boarded up window`
- `reinforced boarded up window`
- ... any terrain that has `window`

**Comment by SzQ1** [comment]
You can `Install Bars Onto Window` after you `Tear down the curtains` then the window is `window without curtains`. As well as when constructing second stage of `build window` entry the result is `window without curtains`.
My soulution would be to change 
`"pre_terrain": "t_window",`
in
`    "id": "constr_window_bars",
    "description": "Install Bars Onto Window",`
to
`    "post_terrain": "t_window_empty"`
I will try to remember to make such PR maybe.

**Comment by SzQ1** [comment]
#715 a small fix
