### ISSUE TITLE
[Item] Makeshift Battery Charge Station

### ISSUE THREAD

**Issue by nanohard** [cataclysmbnteam/Cataclysm-BN#674]
New item `Battery Charge Station` to charge electric car batteries.
This may already exist, but a DDA player mentioned that it's not a thing in DDA. May exist but unimplemented? I'll have to check.

# Describe the solution you'd like
A way to charge electric car batteries.

# Additional context
Recipe:
- solar panel
- jumper cables
- 2 wires
- ?

Based on my IRL experience it takes 36 hours to charge a car battery from dead to full on trickle charge using a bought car charger. More time for makeshift?

**Comment by Kaylakaze** [comment]
There are plenty of ways to charge electric car batteries, including the solar panel. Is it just that you're wanting a simple way to start a car with a dead battery? Or a solar power-based battery charger item?

**Comment by nanohard** [comment]
Oh, okay. Thanks for the info. Closing issue.
