### ISSUE TITLE
NPC with bow equipped and arrows in inventory using bow for mele only.

### ISSUE THREAD

**Issue by Proxiehunter** [cataclysmbnteam/Cataclysm-BN#675]
Told NPC to use a short bow and gave them simple wooden small game arrows. NPC is smacking zombies with the bow.

Expected behavior

NPC fires bow.

Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 458e37f [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Hauling Space From Aftershock [aftershock_hauling_space],
    Alexs Mutant Power Armor [a_mutated_arsenal],
    Armor Up! PA Utilities [ArmUpPAUtil],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Bootleg Walkers [Bootleg_Walkers],
    Camping tools [camping_tools],
    CIVILIAN POWER ARMOR [CIVILIANPOWAAA],
    Flowerpot (uekibati) mod [Uekibati_mod],
    Garden Pots [growable-pots],
    Homemade Fungicide [homemade_fungicide],
    Incinerator [incinerator],
    Large capacity storage CBMs [eps_cbm],
    Makeshift engine hoist [makeshift_engine_hoist_mod],
    Makeshift Items Mod [makeshift],
    MakeshiftCanteen [MSCanteen],
    More Makeshift Stuff [makeshift_stuff],
    Power_Armor_Additions [Power_Armor_Additions],
    Sewing Machine [SM],
    Survivor's Lost item [Survivors_Lost_item],
    Hydroponics [hydroponics],
    Jury-Rigged Robots [jury_rigged_robots],
    More Survivor Stuff [more_survivor_stuff],
    Mutant NPCs [mutant_npcs],
    Wandering Masters [wandering_masters],
    Whaleys Hair Mod [WHALEYHAIR1],
    Caches [P_Caches],
    Pneumatic fun [pneumo_fun],
    Blazemod - Vehicle Additions Pack [blazemod],
    Folding Parts pack [deoxymod],
    Shrub it off [shrub_mod],
    Tankmod: Revived [Tankmod_Revived],
    Graphical Overmap [Graphical_Overmap],
    Mutation Changes Snofielf [Mutation_Changes1],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    LSM Content Pack [LSM_Content],
    Integrated Fusion Blaster [Integrated_Fusion_Blaster]
]

Additional context

NPC has no skill in archery. Possibly why? Still think they would give using the bow properly a try.

**Comment by nanohard** [comment]
lol that's funny to imagine watching.
Yeah, it seems you're spot on for the reason; looks like this is the culprit for preference of attack type.
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/src/npcmove.cpp#L1356-L1417

**Comment by Proxiehunter** [comment]
Well damn. I handed them a bow because I don't have the tools to make a crossbow and I wanted them to have a ranged option to replace the rifle I took away so they wouldn't bring the hordes down on me shooting an unsilenced rifle.

**Comment by nanohard** [comment]
Can you look at the log (hopefully you have a `debug.log`) and search for `is trying an alternate attack`, `is trying to shoot someone`, and `is trying a melle attack` ("melle" is a typo in the code, so search for it that way)

**Comment by anothersimulacrum** [comment]
Those types of messages will not be shown anywhere unless debug mode is enabled - and nobody has it enabled because it's super spammy.

**Comment by nanohard** [comment]
So I just had the same issue, due to my NPC not having the proper strength (12) to use the composite bow.

**Comment by KheirFerrum** [comment]
Should be fixed by #1705, as it contains the fix for NPCs and ranged weapons.

**Comment by scarf005** [comment]
please reopen the issue if #1705 does not fixes it.
