### ISSUE TITLE
Tetanus infection can only be removed by default antibiotics

### ISSUE THREAD

**Issue by Firefox13** [cataclysmbnteam/Cataclysm-BN#678]
# Describe the bug

The tetanus infection is removable by consuming antibiotics but there's a check for consuming only standard medium-strength antibiotics, you cannot cure tetanus by consuming destragon or atreyupan.

# Steps To Reproduce

1. Make a player without infection immune trait or thick-skinned traits
2. Infect yourself with tetanus by walking into nearest rose bush repeatedly. There's no message for it so use blood analysis CBM to see when you get it
3. Consume destragon and atreyupan in industrial quantities to fight off tetanus.
4. Cry as it doesn't help, consume default antibiotics and see the muscle spasms to go away.

# Expected behavior

Tetanus should have a chance(lower and bigger respectively) to go away when consuming atreyupan and destragon, too.

# Screenshots

![изображение](https://user-images.githubusercontent.com/57810301/126051423-f5d154f5-2086-40c0-a171-1b9f8d254162.png)

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 458e37f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

The check for treating tetanus infection in iuse.cpp is tied to consuming default antibiotic only

**Comment by Proxiehunter** [comment]
If this gets fixed I wonder if the same fix can be applied to the NPC quest where they'll only accept default antibiotics.

**Comment by Firefox13** [comment]
> 
> 
> If this gets fixed I wonder if the same fix can be applied to the NPC quest where they'll only accept default antibiotics.

Reminded me of the ranch quest where they ask for blankets and accept only default ones, not down-filled ones

**Comment by nanohard** [comment]
Regular antibiotic has a 1/3 chance to succeed. Should strong have 1/1 and weak 1/6?
