### ISSUE TITLE
[Bug][Scenario] Helicopter Crash scenario insta-death

### ISSUE THREAD

**Issue by nanohard** [cataclysmbnteam/Cataclysm-BN#684]
# Describe the bug
Scenario `Helicopter Crash` can take several tries to get a character that actually lives through the procgen crash.

# Expected behavior
Always live through the crash.

# Versions and configuration
Commit 458e37f

# Additional context
Perhaps add a limit on crash damage?

**Comment by SzQ1** [comment]
It's my favourite scenario and to me it seems that currently you die a lot more than couple months ago. Most starts end up with instant death.

**Comment by nanohard** [comment]
It think this is where the bug lies, but have failed to fix it. Will have to leave it to someone that knows better.

https://github.com/cataclysmbnteam/Cataclysm-BN/blob/upload/src/start_location.cpp#L403-L406

```c++
    for( const bodypart_id &bp : u.get_all_body_parts() ) {
        if( bp == bodypart_id( "head" ) || bp == bodypart_id( "torso" ) ) {
            continue;// Skip head + torso for balance reasons.
        }
```
