### ISSUE TITLE
Smartphone ups stay on without charge

### ISSUE THREAD

**Issue by LucioFurnari** [cataclysmbnteam/Cataclysm-BN#688]
The smartphone is still on, even if it does not have charges
and it does not let me turn it off because it indicates that it has no charge

![imagen](https://user-images.githubusercontent.com/85850293/126086007-ff724206-3d17-4c61-8b07-2cdc30d4161b.png)

**Comment by scarf005** [comment]
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/d94c7092-9c93-460c-b95b-91cd44fb84c8

could not reproduce in latest experimental.
