### ISSUE TITLE
rundown on postapoc guns of past versions, their return and changes around

### ISSUE THREAD

**Issue by Leviathan21** [cataclysmbnteam/Cataclysm-BN#690]
generally since dda nerfclowns went on craftable guns and phased them out, it would be something to return them back and refurbish to fit their own roles around:

Heavy rail rifle - the first entry and the biggest, its probably the most "Why" weapon to make around, but since its sandbox and after going past mid game, there is no reasons "why" just "why not" its stupidous firepower moving down walls in a line is really a total overkill as there is nothing requiring such violence except mechs, jabberwocks and player characters, it was something least known while being overpowered to its limit and very requiring, but teching to it was its own sort of achievement to make due to extreme requirements of 10 in electronics, 7 in mechanics and 2 in computers on top of it. Honestly, since it was least known and is hard to craft, it would be more a rare weapon like plasmagun or 12mm railgun, kept in labs and military facilities as by the time player goes there, the need to get this thing on hand phases out with .50 bmg snipers and launchers on hand. 
Otherwise, it would be cool to make return as late-game thing to craft or acquire, and make entire achievement out of it

Ferromagnetic rail life - same thing, least destructible, still generates a mess. Could make a return as weapon of moderate power instead firing rebars at extreme speed with a trail, but minus the boom and fires and gibs and mess but impaling targets with large armor piercing piece of sharp rebar. If its really ass, it could make a return instead of pneumatic rifle shooting rebars, like one in fallout
https://fallout.fandom.com/wiki/Railway_rifle_(Fallout_3)

Coilgun - "Hard to make, plentiful and cheap ammo, and silent - people will want this thing." - in game files. Low damage, eats ups, no shot sound and very armor piercing, essentially HK MP7 for nerds. Shiny thing for character who already has high electrical skills, pointless for character without as by the moment they acquire the skills and means of ups as by the time teching it they would outlive any need in shiny coilguns. Could make a comeback as sort of assault rifle or silent smg, so it would see a use besides grind weapon

Homemade rocket launcher - allahu akbar thing, falls under the same category as heavy railgun - ass to make, and one made practically is pointless since there isnt really much wanting to eat a incendiary rocket after an otherwordly aberration, colossal horde of zombies or player characters. Could be a more common guest in books about explosives of any sort, so it would be a lot more accessible to make since it does not appears with skill. Otherwise, its really just to fun thing around

Homemade flamethrower - in reality, these are perfectly crafteable by hand without much concern besides personal safety. In game, these are not very useful on practice besides setting fungaloids, large unkillable zeds and refugee center on fire. In old versions, it was a lot easier to craft, and so instead it could have skills upped to make one or become a recipe in one of books, and be rich on malfunctions ranging from leaking fuel to suddenly setting the user's ass on fire.

Helsing - the apex of crossbows, this mofo quickly became the to-go for every survivor to have, and even quicker earned a status of grind weapon to clear cities with or to use overall with bolts accessible, and outgunning all the crossbows with being able to pre-load all the 8 shots with decent damage output. Instead of doing the DDA way with either tuning to the uselessness or removing it outright, it could weight a lot instead, and run its own clips like in metro2033 where the weapon originates of.
The weapon itself, running out the sum of components, would weight 4.7 kg approximary unloaded - another 3 kg loaded with a barrel clip thing full of metallic bolts.  Counting that the player once hitting the mid- or end game has at least 25 kg of gear, and 50 kg to carry max, the Helsing would take at least 14 kg itself, making it a specialized weapon to carry around for silent ops than all-round looting, or something a local gigachad survivor would carry around this hefty thing. Instead of loading bolts by one, it would use detachable clip, just like in metro2033, accepting only them and disabling a reload of bolts into weapon directly as in metro2033 concepts the weapon isnt really meant to do it, as much following up with prolonged reload. That, or an air pump mechanic, to make it essentially a "night raider" kind of weapon than a grind tool

Tikhar - the buddy of Helsing, this totally silent weapon sadly never found its use for many players besides being a town cleaner thing taking same spot as ruger-22, but worse, even if hitting harder. Yet i had a lot of fun before night raiding with it or taking stealth approach by bandit camps, as killing them without noise in few turns was golden. it could make a return as weapon serving its original role as it was in metro2033 - being a stealth weapon that is very unwieldy in open confrontation, but is perfect for stealth approach, having amped damage with steel bearings up to 32, but harder time reloading, taking at least 600 moves to load a tube of balls and pump the air tank.

**Comment by Firestorm01X2** [comment]
My unfinished PR for the reference: https://github.com/cataclysmbnteam/Cataclysm-BN/pull/109

**Comment by Leviathan21** [comment]
outside of that, the game is in need of more, gimmick-y postapoc guns made by hand or refurbished from already existing, like Abzats that was already in the game for some time in past versions

**Comment by SzQ1** [comment]
IMO those weapons would do good as mainlined mod, not as vanilla. Even for that they need quite a revision and balancing. To make it properly and consistently I suggest to create a googlesheet with all those weapons and their stats and descriptions.

**Comment by Coolthulhu** [comment]
As per design document, restoration is not much different from addition from scratch. If someone wants to add a futuristic or improvised gun based on the removed ones, go for it. But have a solid gameplay niche for it.

Closing as stale.
