### ISSUE TITLE
[Request] Search yield in disassemble menu

### ISSUE THREAD

**Issue by Kaylakaze** [cataclysmbnteam/Cataclysm-BN#691]
# Is your feature request related to a problem? Please describe.
It can be a challenge trying to find an item to disassemble so that you can get the component you need for something else.

# Describe the solution you'd like
Similar to searching in the crafting screen, allow the player to use "y:" to search the yield column instead of searching by item. For example, "y:power converter" to get a list of all items that could yield a power converter on disassembly.

**Comment by olanti-p** [comment]
This feature exists, but you won't know that unless you go code diving like I had to.

It's `d:` prefix.

UI really should provide some hint for that.

**Comment by Kaylakaze** [comment]
Thank you!!!
