### ISSUE TITLE
ASan/UBsan matrix builds getting killed (OoM?)

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#693]
After merging #667, which shouldn't affect non-CMake builds in any way, ASan and UBsan general matrix test runs have started dying with exit code `137`, which means they were killed, most likely as a result of Out of Memory.

First example:
https://github.com/cataclysmbnteam/Cataclysm-BN/actions/runs/1048215592
This is not a timeout, as the build above took only 6 minutes to die.
I couldn't reproduce the OoM locally. I limited memory for the build+test process tree to 6gb (Github Actions page says Linux VMs get 7gb) and it stayed within bounds.

**Comment by nanohard** [comment]
Could we set debug log to `true` to try to get more info?

![image](https://user-images.githubusercontent.com/10169206/126593164-145d3216-714e-4f68-90ea-d9c2e36ea4f3.png)

**Comment by Coolthulhu** [comment]
Looks like it only adds info about steps taken by the github action, not more console output from the processes inside.

**Comment by nanohard** [comment]
Hmm... it looks like after the JSON lint error was fixed with `terrain_windows.json` it started happening, so I believe it may be either my PR #671 for windows where I added `PERMEABLE` everywhere, or #672. Can we revert #671 first to check?

**Comment by anothersimulacrum** [comment]
FYI: https://github.com/CleverRaven/Cataclysm-DDA/pull/50140

**Comment by Coolthulhu** [comment]
Fix attempt #701, port of the DDA fix above, didn't do the job.
Does anyone know how to analyze peak memory usage with clang? I'll try googling, but my first search had only memory leak related results.

**Comment by anothersimulacrum** [comment]
https://github.com/KDE/heaptrack looks like it would work, e.g.
![image](https://user-images.githubusercontent.com/42699974/126797893-1ea2e5df-168a-45b6-b129-04e0c9c882d1.png)

**Comment by Coolthulhu** [comment]
So far I tried valgrind because it's easy to install, but valgrind+ASan don't work together.

**Comment by nanohard** [comment]
I couldn't get heaptrack to work on `cata_test-tiles`, got an error about DWARF version.

**Comment by Coolthulhu** [comment]
I tried valgrind without ASan. The results should probably be correlated with what would ASan get.
From what I can tell, over half of the memory is used by maps. Maybe clearing the mapbuffer between test cases could help here.

**Comment by Coolthulhu** [comment]
The primary difference in memory usage (from DDA) seems to be the electric grids.
Clearing the map buffer between tests doesn't seem feasible due to architecture of the `Catch.hpp`.
I tried clearing the buffer on `clear_map()`, but my naive implementation was prohibitively expensive, doubling the total test time (even though most tests don't clear map).

**Comment by anothersimulacrum** [comment]
New character test looks suspect https://github.com/anothersimulacrum/Cataclysm-DDA/pull/31/checks?check_run_id=3152950281

**Comment by Coolthulhu** [comment]
In BN, it fails at `effective_dps_test.cpp:weapon_dps_trials`.
The function resets a single character a lot, doesn't clear monster's stats except hp, performs a single melee hit and repeats.

My suspicions:
* Some `avatar` or `monster` container isn't cleared and keeps being inserted into. I thought about `consumption_history`, which is never reset and only clears entries that are 2+ days old, but it wasn't enough. See #710
* Every hit or miss, a sound is enqueued in `sounds::recent_sounds`
* Every hit or miss, a SDL sound thread is generated
* Scrolling combat text is only cleared when the target dies or the text gets to scroll away. While new hit text "pushes" old text further out, clearing of the text only happens on timed intervals, in `handle_action`.

**Comment by Coolthulhu** [comment]
Seems to be fixed now!
