### ISSUE TITLE
[Request (ambitious)] Divide cooking/crafting times into focused/preparing and background

### ISSUE THREAD

**Issue by Kaylakaze** [cataclysmbnteam/Cataclysm-BN#694]
# Is your feature request related to a problem? Please describe.
When cooking in real life, you don't spend the ENTIRE time focused on the task. You may spend 5 minutes preparing something and then have it baking for 40 minutes. Cataclysm has many recipes that have real-life cooking times, but they require your character to dedicate their full focus to the task for the entire time. In RL right now, I'm cooking my lunch while also typing this, so staying focused on cooking the whole time doesn't feel realistic.

# Describe the solution you'd like
Divide cooking (or more likely crafting in general) times into two times: preparation or focus (the time you need to be dedicated to the task) and background (the time that the process continues in the background, similar to how washing machines and dishwashers work). Have a timer that goes off to notify the character that the process is done that will wake them up or interrupt reading or other activities if they're not deaf. The item in use would be unable to be used for other things while the background process is going on (for example, if you have your chemistry station cooking some spaghetti, you can't also be preparing biodiesel on it at the same time.) Handheld processing tools (hotplates, mess kits, food processors, etc) would need to be "set up" before they could be used for recipes with background times and would ruin the recipe if picked up while processing. When checking for tools to use for a recipe, if the tool is in range, but not set up, it could be displayed in yellow. Recipe structure could stay the way they currently are, using the current times as the "focused time". A new parameter for the background time would be added to recipes so that only those recipes that are specifically changed would use the new system.

I think such a solution would be beneficial to the overall gameplay, encouraging players to actually cook meals, set up full kitchens (which would be fantastic with the power grids), have both a kitchen kit and chemistry set on their vehicle, and make some of the longer-to-create items more reasonable.

**Comment by Coolthulhu** [comment]
I'd rather cut down craft time just to that "focused time".
It would be a much faster fix.

Later, if someone commits to it, we can have that division.

**Comment by Coolthulhu** [comment]
Closing as stale.
