### ISSUE TITLE
[Request] DVD players and DVDs

### ISSUE THREAD

**Issue by Kaylakaze** [cataclysmbnteam/Cataclysm-BN#695]
# Describe the solution you'd like
I think it'd be cool to be able to add a TV/DVD player to your home or vehicle and collect DVDs in the world. Some DVDs could train skills, like books while most would be for enjoyment. Perhaps new character traits can add extra enjoyment to certain genres of movie and subtract enjoyment from others.

A similar system could also be put in place for video games.

It'd be fun trying to build a complete DVD or video game collection.

**Comment by Coolthulhu** [comment]
Very unlikely to happen as DVDs are mostly outdated even now, but having named movies/video games/tracks that increase effectiveness of morale devices could be a thing.

**Comment by Coolthulhu** [comment]
Closing as stale
