### ISSUE TITLE
Increase overdrinking limit

### ISSUE THREAD

**Issue by Soadreqm** [cataclysmbnteam/Cataclysm-BN#70]
# Is your feature request related to a problem? Please describe.
Currently, it's fairly common to be "Thirsty", but still get a "You're full already and the excess food will be wasted" warning when attempting to drink water. This makes the "Thirsty" status useless, since it doesn't actually tell when you're thirsty enough to drink something.

# Describe the solution you'd like
Increase how much water the player can store in their body so that the difference between completely full and "Thirsty" is at least 60 quench points, or one cup of sports drink.

# Describe alternatives you've considered
Could also make the "Thirsty" status appear later.

**Comment by Coolthulhu** [comment]
Currently it's 40.
60 would be fine.
Could also push very thirsty to 120, so that the penalties don't start so soon.

**Comment by Firestorm01X2** [comment]
@Soadreqm Issue was resolved by 
>Could also make the "Thirsty" status appear later.

But
>Increase how much water the player can store i
how much water the player can store does not changed. Still
> difference between completely full and "Thirsty" is at least 60 quench points, or one cup of sports drink.

is true. 

If issue was not resolved for you - please write something. It could be investigated more.
