### ISSUE TITLE
Radiogenic mutation needs to be reworked

### ISSUE THREAD

**Issue by cheekygoblin** [cataclysmbnteam/Cataclysm-BN#718]
At high radiation levels, the damage from being irradiated overtakes the healing from the radiogenic mutation entirely.

# Steps To Reproduce
Spawn a radiogenic mutant and irradiate yourself at radiation (30).

# Expected behavior
Either damage should be nullified at the high end or slight healing should still happen.

# Additional context
This issue was raised and rejected by the DDA team under issue https://github.com/CleverRaven/Cataclysm-DDA/issues/36115
It came to my attention from [this reddit post](https://old.reddit.com/r/cataclysmdda/comments/orjdea/radiation_and_rad_healing_mutations/), and I agree that the current implementation is not only not intuitive but not... fun, really, either. 

It seems like the right target for this branch but I wanted to raise the issue to verify/discuss.

**Current implementation, as taken from Kevin's comment in the other issue:**

- At 200 radiation, radiogenic heals one point of damage every 30 minutes.
- At 201 radiation, you take one point of damage from radiation sickness on average every 50 minutes.
- At 333 radiation, you take one point of damage every 30 minutes, healing and damage are balanced out.
- At 500 radiation, you take one point of damage every 20 minutes, i.e. for every two points of healing you take 3 points of damage.
- At 666 radiation, you take damage twice as fast as you heal it, i.e. one point of damage every 30 minutes.
- At 1000 radiation, you take damage once every 10 minutes, so you take two points of damage every 30 minutes after the radiogenic healing..

**Comment by Coolthulhu** [comment]
The question of how exactly should radiogenic work doesn't have an obvious answer. It should probably be redesigned.
Here are some potential roles:

1. Trade healing for long term debuffs of radiation. Possibly with mutagenic toxin generation and mutations. Needs comparison with nanobots and standard medicine. In this case, radiogenic would outheal radiation at high radiation, but only provide healing proportional to stat loss.
2. Heal during radiation gain, then only protect from radiation damage. Radiogenic+rad scrubber combo would have to be compared against nanobots.
3. Be more of a radiation resistance/removal trait than radiation benefit one. This doesn't sound too useful, there aren't many hard to avoid sources of radiation around.
4. Invert it: have it cause fast healing and radiation up to some level, but protect from radiation damage up to that level.

One thing I don't want: treating radiation as a valuable resource that is consumed. Radiogenic shouldn't be just a part of "radioactive+radiogenic" combo (unless radioactive becomes a prerequisite), nor should it provide a "power spike" when you find an atomic nightlight and bash it against the wall until it turns into atomic heal wand.

I think combination of options 2 and 4 is the most manageable.
When disabled, radiogenic would only provide healing when an outside source of radiation triggers it.
When enabled, it would generate its own radioactivity to trigger itself, providing healing at a steady rate, but contaminating the player.
It would allow adding "healing potions" that instantly or just quickly irradiate you to trigger this new radiogenic.

At the moment, prussian blue heals (on average) 1 rad per 10 minutes. Passive radiation healing is (on average) 1 per 250 minutes. Those are a bit too far from each other.
Radiation scrubber bionic heals 5 rad per 4.5kJ spent, instantly. Should probably be turned more passive, over time.

Option 1 sounds like it could be useful at first, but would result in get irradiated->heal->heal rads routine, which doesn't sound fun.
It would also be dependent on finding an atomic healing wand first.

**Comment by cheekygoblin** [comment]
> 
> 
> Regardless of the current implementation being ... wonky, I think radiogenic should be outpaced by radiation damage indeed.

What specifically is your rationale for this? 

I agree with @Coolthulhu points in that it absolutely could use a rework with a closer look at how it functions and is balanced. Obviously it's more complex than just not taking damage, but I also don't feel like a radiogenic mutant should directly suffer from external radioactivity.

**Comment by Zireael07** [comment]
I think radioactivity being dangerous even to radiogenic mutant is a) realistic and b) good for gameplay (it's one of the few things an end-game character will still fear). If radiogenic is an insta-win button "yay radiation isn't a problem", this is kinda bad since you're effectively nullifying what should be one of the most dangerous things in Cata (next to fungi/triffids).

That does not mean @Coolthulhu's ideas are bad, they're more than good, but radioactivity should still deal pain and damage, especially pain as that one is still dangerous no matter how endgame you are.

**Comment by cheekygoblin** [comment]
I'm not sure how realism is a factor for a *radiogenic mutant* , an entirely fabricated condition with no bearing whatsoever on the real world. I do feel that it fits into the realism of the setting, such as it is, and certainly into the 'realism' intended in this branch where fun sci fi mutants and the rule of cool should have *some* bearing within justification.

As I said before, it is clearly more complex than merely nullifying all radiation effects. I am not proposing an "I win cuz radiation!" button. Properly balanced against other methods of removal, healing, etc I fail to see how it would be bad for gameplay. Of course this balancing would be a natural part of revamping the mutation. I could see a case for pain, but in my opinion not for damage.

I'll wait for feedback from BN contributors before doing any PRs, but I think I'll definitely start thinking about the suggested 2/4 combo and see what I can do with it.

**Comment by Coolthulhu** [comment]
> If radiogenic is an insta-win button "yay radiation isn't a problem", this is kinda bad since you're effectively nullifying what should be one of the most dangerous things in Cata (next to fungi/triffids).

Isn't that just in PK mod? In core, fungals are only dangerous until you get fungicide and triffids mostly just destroy environment.

Radiation can be stopped by wearing a hazmat. Hazmat has terrible stats, but I don't think there is a single location in the game that combines high radiation with strong monsters.

> radioactivity should still deal pain and damage

Or radiogenic could require gaining so much radiation that the stat penalties make it hard to fight. And that there's a high risk of mutating.

**Comment by chaosvolt** [comment]
The risk of mutation seems like a good angle to focus on, it'd tie in well with the general mutation overhaul project. Making it so that you have to risk basically becoming a chaos spawn in exchange for high-level regeneration would make for an interesting playstyle (though my bias here may be affected by how one of my most fun playthroughs was as a mutant that ended up constantly mutating yet also exceedingly hard to kill).

Alternatively or in addition, some degree of diminishing returns could be implemented. Such that the degree of regen outpaces radiation damage fairly consistently up to a point, beyond which the effective regen diminishes. I'm not sure what the ideal balance point would be, but it would encourage players to manage their radiation level more like a resource of sorts, maintaining enough radiation to get higher-level regen without overloading on it and suffering degeneration instead.

**Comment by Zireael07** [comment]
> Or radiogenic could require gaining so much radiation that the stat penalties make it hard to fight. And that there's a high risk of mutating.

This is a good idea <3 same goes (even more so) for the idea of diminishing returns. Having to manage radiation level would definitely make gameplay more interesting <3 <3
