### ISSUE TITLE
Cataclysm-BN repository missing topics

### ISSUE THREAD

**Issue by Firestorm01X2** [cataclysmbnteam/Cataclysm-BN#73]
# Cataclysm-BN repository missing topics
Github has repsitory topics feature:
https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics

CDDA repostitoy has them, but BN don't. Adding them should help to attract new contributors.
CCDA has:

- game
- c-plus-plus
- zombies
- cataclysm 

BN probably could use:

- game
- c-plus-plus
- zombies
- cataclysm 
- roguelike
- sci-fi

**Comment by Coolthulhu** [comment]
Done
