### ISSUE TITLE
Less messy way to make releases?

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#737]
I usually mergetest a lot of PRs at once, then merge them one by one as I test them.
In current system, this results in a whole lot of tiny, empty releases. This is obviously not good.

I could try discipline and not merge until I test a whole batch, but that sounds tedious and prone to mistakes.
I could also try merging my mergetesting branch onto main and pushing that, but it only works if all of the tested PRs are ready.

Ideally, there would be a way to:
* Delay releases to something like 1 per day, if something was merged this day
* Automatically delete empty releases and append their changelog to the first complete release
* Detect partly-cancelled releases (cancelled when only some of the builds completed) and treat them like empty ones

**Comment by Firestorm01X2** [comment]
I never seen before anyone complaned. Probably people get used using unstable releases for Cataclysm.
Obvsily it is somewhat messy, but it is not "true" releases - it is experimental releases after all.
Having release strategy will solve that. I mean normal release strategy with master, dev and version tags.
nanohard actually pointed to that: https://github.com/cataclysmbnteam/Cataclysm-BN/issues/673

**Comment by scarf005** [comment]
implemented in #3595.
