### ISSUE TITLE
It's possible to switch to empty gun mode mid-aiming; trying to fire it gives debugmsg

### ISSUE THREAD

**Issue by olanti-p** [cataclysmbnteam/Cataclysm-BN#744]
# Describe the bug
It's possible to switch to empty gun mode mid-aiming; trying to fire it gives debugmsg

# Steps To Reproduce
1. Obtain a loaded gun with an empty rail-mounted crossbow attached
2. Switch mode to regular using `F`, press `f` to start aiming
3. While aiming, press `s` to switch to empty rail-mounted crossbow
4. Attempt to fire. The game will give `Attempted to fire zero or negative shots using rail-mounted crossbow` debugmsg.

The bug works similarly for empty gun with a loaded gunmod.

# Expected behavior
UI should prevent firing if gun cannot fire in selected mode.

# Versions and configuration
Version a62a8995d3ac5ad3b62d1f991fc56f244a06370a

Also, may or may not be related to #743

**Comment by Coolthulhu** [comment]
A simple fix would be to do one of:
* Skipping the empty mode (silently or with msg?)
* Displaying the empty mode, but not allowing shot to be confirmed

This however doesn't fix an underlying problem with range limitation, which doesn't seem to change when the mode is changed.

**Comment by olanti-p** [comment]
Fixed in #804 along with range update issue.
