### ISSUE TITLE
Mess kit cannot be used for boiling when loaded with batteries

### ISSUE THREAD

**Issue by Soadreqm** [cataclysmbnteam/Cataclysm-BN#75]
# Describe the bug

Despite having the Boiling 2 tool quality, a mess kit can't be used for recipes that require boiling if it's loaded with batteries. It only works when unloaded, using some other heat source.

# Steps To Reproduce

1. Obtain mess kit and battery, load mess kit.
2. Make sure there are no other boiling tools nearby.
3. Open crafting menu, examine a recipe that requires boiling (e.g. clean water). Note that a boiling tool is not available.
4. Unload mess kit.
5. Look at crafting menu again. Note that a boiling tool _is_ available.

# Expected behavior

The mess kit should work for boiling whether or not it has a battery inside it. Unless the battery compartment is being used for boiling. That would be weird.

# Versions and configuration

- OS: Windows 10 Pro N 2004
- Game Version: 71e8b1e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    No Rail Stations [No_Rail_Stations]
]

**Comment by Coolthulhu** [comment]
It's supposed to be special-cased for tools containing only their "fuel", magazine containing it, or a toolmod, but for some reason that special case isn't working.

**Comment by Firestorm01X2** [comment]
Reference from dda: https://github.com/CleverRaven/Cataclysm-DDA/issues/30069
