### ISSUE TITLE
Basecamp farm doesn't consume seeds in storage

### ISSUE THREAD

**Issue by Secret-Cisco** [cataclysmbnteam/Cataclysm-BN#758]
# Describe the bug

When NPCs are ordered to plant in the basecamp expansion farm though the bulletin board they won't consume seeds from the camp storage zone. However, they will consume seeds of the same kind and amount that are in your inventory if you have them, but can only be ordered to plant as many as are in camp storage.

# Steps To Reproduce

1. Construct Basecamp farm
2. Order an NPC to plant seeds in field
3. NPC finishes and comes back
4. There are still seeds, no change

# Expected behavior

Seeds should be consumed from storage

# Screenshots

# Versions and configuration

 - OS: Windows 10
 - Game Version: 28c060b
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: the defaults & magiclysm
 

# Additional context

This is also a still existing problem in DDA https://github.com/CleverRaven/Cataclysm-DDA/issues/47672

**Comment by Secret-Cisco** [comment]
DDA fixed this https://github.com/CleverRaven/Cataclysm-DDA/pull/56283

I don't know nearly enough to try to implement that over here myself though.

**Comment by scarf005** [comment]
sorry to say this, but we'll have to close this issue as not planned because we removed basecamp feature due to dev bankruptcy: https://github.com/cataclysmbnteam/Cataclysm-BN/discussions/3866
