### ISSUE TITLE
Auto pickup does not work

### ISSUE THREAD

**Issue by lalavei** [cataclysmbnteam/Cataclysm-BN#761]
# Describe the bug

Item auto pickup doesn't work.

# Steps To Reproduce

1. Add an item to autopickup manager.
2. Enable auto pickup.
3. Walk onto the tile where the added item located.

# Expected behavior

The item should be picked up.

# Screenshots

![1](https://user-images.githubusercontent.com/36934501/128744647-1fc9fda0-d9e9-403c-8d57-cfbacc516f8e.png)
![2](https://user-images.githubusercontent.com/36934501/128744659-b920369f-95e2-4407-98e2-114d2b463f68.png)
![3](https://user-images.githubusercontent.com/36934501/128744675-8412116b-7c63-4dc6-adc9-4901a98f5c51.png)
![4](https://user-images.githubusercontent.com/36934501/128744689-32681ca2-1e15-4687-b11e-cc51e78aba98.png)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 79dadce
 - Graphics version: Tiles
 - Ingame language: English or Russian
 - Mods loaded: default or aftershock, bionic slots

# Additional context

**Comment by Secret-Cisco** [comment]
I just tested this in the same version of the game and can confirm auto pickup didn't work for me either. HOWEVER, it did work in a slightly older version I downloaded the other day 28e060b

![image](https://user-images.githubusercontent.com/77130566/128806783-df39fe75-cda3-4edc-abfd-ec1d42c74232.png)

**Comment by Secret-Cisco** [comment]
It seems NPC companions also don't auto pickup in the latest version (79dadce) either, but I know they did in 28e060b

![image](https://user-images.githubusercontent.com/77130566/128809216-1779d37a-caf3-4ace-a97a-5ee6bc63341e.png)
![image](https://user-images.githubusercontent.com/77130566/128809284-70563b35-d64a-4b16-9509-30c5afc2dae6.png)
