### ISSUE TITLE
Lockpicking skill still shows up in character screen

### ISSUE THREAD

**Issue by Wreckstation** [cataclysmbnteam/Cataclysm-BN#78]
# Describe the bug
Latest release says that lock picking doesn't use the lock picking skill, but it still exists and still can be increased on character creation.

# Steps To Reproduce

- Create a custom character and tab all the way to the skills section. Lock picking exists still.
- OR: press play now (either one) and press @ and see that Lock picking shows up in the list of skills.

# Expected behavior

It should not be there.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: c8f463e [32-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

**Comment by Firestorm01X2** [comment]
Reference on skill removal:
https://github.com/cataclysmbnteam/Cataclysm-BN/pulls?q=is%3Apr+is%3Aclosed
