### ISSUE TITLE
PET_WONT_FOLLOW flag doesn't work

### ISSUE THREAD

**Issue by Andrew-Fall** [cataclysmbnteam/Cataclysm-BN#781]
# Describe the bug
Pets with "PET_WONT_FOLLOW" still attempt to follow the player

# Steps To Reproduce
Tame a horse or chicken, watch as the creature tries to follow you despite having the PET_WONT_FOLLOW flag

# Expected behavior
Creatures with PET_WONT_FOLLOW shouldn't follow

# Screenshots
Chickens and horses are attempting to follow
![image](https://user-images.githubusercontent.com/12163281/129492566-8632f154-451a-4f4c-839a-1fb075f38edd.png)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 79dadce [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Manual Bionic Installation [manualbionicinstall]
]

# Additional context

**Comment by olanti-p** [comment]
DDA issue for reference https://github.com/CleverRaven/Cataclysm-DDA/issues/50532
