### ISSUE TITLE
"Birdsplosions" happen

### ISSUE THREAD

**Issue by Coolthulhu** [cataclysmbnteam/Cataclysm-BN#782]
It goes like this:
* Bird lays eggs
* Eggs are retroactively processed and turn into chicks
* Later, chicks are retroactively processed into adult birds
* Adult birds lay eggs
* Repeat

Reducing egg laying/hatching rate won't help much.
My ideas:
* Arbitrarily prevent reproduction if there are too many critters within a submap - eggs will just rot in this case
* Remove reproduction, make birds like cows which provide milk forever but never breed
* Load nearby submaps just to calculate if the walkable area by the birds provides enough "food" for them all, produce only as many eggs and chicks as the area can support, spread the birds around so that they don't spawn in a clump

**Comment by Secret-Cisco** [comment]
Somewhat related: I've noticed that cities/any place with a kitchen gets a huge explosion of baby birds from eggs left in the fridge by the end of the first year. By fall there's swarms of chicks impeding access inside buildings and blocking the streets.

**Comment by olanti-p** [comment]
>huge explosion of baby birds from eggs left in the fridge by the end of the first year

https://github.com/CleverRaven/Cataclysm-DDA/pull/40896 was ported in #726, this shouldn't happen in new worlds anymore.

**Comment by Secret-Cisco** [comment]
> [CleverRaven/Cataclysm-DDA#40896](https://github.com/CleverRaven/Cataclysm-DDA/pull/40896) was ported in #726, this shouldn't happen in new worlds anymore.

Ah, nvm then! Sorry, my currently used version is from like two days earlier than that and I usually, but failed to do so here, try to check the latest version before complaining about a bug/issue!

**Comment by scarf005** [comment]
closing as it's resolved in #726.
