### ISSUE TITLE
Acid ants kill normal ants

### ISSUE THREAD

**Issue by Spagettore** [cataclysmbnteam/Cataclysm-BN#786]
# Describe the bug

Giant acidic ants kill ant larvas and queen ants in sulfurous anthill

# Steps To Reproduce

1. Create new world
2. Find sulfurous anthill
3. Watch ants war crimes

# Expected behavior

1. Acid ants must be friendly with normal ants.
2. Ant queens and normal ant larvas must be changed to their acid variation in Sulfurous anthill

# Screenshots

Giant acidic ants kill their queens
![image](https://user-images.githubusercontent.com/71641620/130135717-d7b23690-f148-4f9c-9112-54b5383bb4c1.png)

and kill normal larvas
![image](https://user-images.githubusercontent.com/71641620/130135887-f809177c-d64a-41a3-8835-21f017997a6d.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 6cb1224 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en_US]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Hope [no_hope],
    SpeedyDex [speedydex]
]

**Comment by Proxiehunter** [comment]
I agree that queens and larva in a sulpherous anthill should be the acid variants. There is however no reason that acid ants and regular ants would be friendly with each other. [Ant colonies will fight each other over limited resources (like survivors to snack on)](https://ants.com/why-do-ants-fight/).

**Comment by Night-Pryanik** [comment]
https://github.com/CleverRaven/Cataclysm-DDA/pull/48348
