### ISSUE TITLE
Gourmand works only partially

### ISSUE THREAD

**Issue by olanti-p** [cataclysmbnteam/Cataclysm-BN#790]
Trait description:
`You eat faster, and can eat and drink more, than anyone else!  You also enjoy food more; delicious food is better for your morale, and you don't mind unsavory meals as much.  Activate to skip prompt for overeating.`

But in the code, it only affects consumption time and morale:
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/99ce588f21dc6d60cd3f7835e1f0d9eb0a0c6e7f/src/consumption.cpp#L909-L912
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/99ce588f21dc6d60cd3f7835e1f0d9eb0a0c6e7f/src/consumption.cpp#L507-L515

Game version: 99ce588f21dc6d60cd3f7835e1f0d9eb0a0c6e7f

**Comment by Coolthulhu** [comment]
I think I'll want to remove the bloated effect.
Morale stacking is no big deal and health stacking doesn't really work.
I'd like to have proper "ignore this warning for now" setting for this, but having the warning happen every time might be good enough.

In this case, gourmand could simply expand max stored calories.
