### ISSUE TITLE
Grenade launcher rounds don't explode (thanks to TWO bugs at once)

### ISSUE THREAD

**Issue by Cactoideae** [cataclysmbnteam/Cataclysm-BN#82]
# Describe the bug

Grenade launcher ammo (40x46, 40x53) that should explode, doesn't.

# Steps To Reproduce

1. Fire a Milkor MGL / Mark 19 into a crowd. Only the direct hit does damage. Adjacent zombies are unaffected.

# Expected behavior

Grenades explode.

# Versions and configuration

 - OS: win10
 - Game Version: 550
 - Graphics version: tiles

# Additional context

There are 2 reasons these don't work:

1) Ammo references deprecated DDA ammo effects instead of BN-exclusive FRAG_BIG and FRAG. Easy to fix.

2) Extends json method doesn't actually work for ammo effects for whatever reason. This is potentially a very serious issue that affects a lot more than grenade launchers.

The bug can be fixed by changing the ammo effects to proper ones AND redefining relevant ammo types without using json inheritance. This is easy and I can make a PR. This, however, doesn't fix all other potential cases of inheritance not working.

**Comment by Coolthulhu** [comment]
I must have missed some of them. It's also a problem for mods that reuse those effects.
Ammo effect implementation is a big hack that combines actual ids (good) with hardcoded effects (bad) in one vector, but ids+regular flags (terrible) in other vector that has to be checked the same way.

I guess for now it's per-case basis fix.
Except for the whole
> Extends json method doesn't actually work for ammo effects for whatever reason. This is potentially a very serious issue that affects a lot more than grenade launchers.

This one sounds serious.

**Comment by Firestorm01X2** [comment]
Reference from DDA:
https://github.com/CleverRaven/Cataclysm-DDA/issues/42795

Looks like they have it also.

**Comment by Firestorm01X2** [comment]
@Cactoideae 
If you know how to fix that quickly - then go for PR. We will be very thankful! It would be great!

**Comment by Cactoideae** [comment]
I know how to band-aid the grenade launcher issue. I can't possibly fix the underlying issue with json inheritance. It would be much better if someone competent fixed it properly. As mentioned, it affects a lot more than grenades.

I've checked, and incendiary shotgun rounds don't work either. SHOT and NEVER_MISFIRES properties probably don't work either, but they are non-trivial to test.

Rewriting all ammo without using inheritance isn't a real solution, it's a step backwards to avoid fixing the issue.

**Comment by Firestorm01X2** [comment]
So it is really serious thing then.
