### ISSUE TITLE
Several recipe books never spawn, making recipes impossible to perform.

### ISSUE THREAD

**Issue by Secret-Cisco** [cataclysmbnteam/Cataclysm-BN#850]
# Is your feature request related to a problem? Please describe.
 There are several recipes can only be learned from books that can never actually spawn in game.

# Describe the solution you'd like
The books should spawn, added to the relevant item group.

# Describe alternatives you've considered
The books could be removed/obsoleted and the recipes made learnable by other means.

# Additional context
Adding the recipe books to the relevant itemgroups seems quick and easy and I'll probably just do it myself and put in a PR tomorrow.

**Comment by Secret-Cisco** [comment]
Seems BN got the new books but not the later PR that actually added them in: https://github.com/CleverRaven/Cataclysm-DDA/pull/41205

I'll double check to make sure everything is good and then make a PR to get this in here soon.

**Comment by Coolthulhu** [comment]
I'll think about writing a test to find cases like this. There may be more and it would be nice to have it impossible to add/leave "orphaned" recipes like this.
