### ISSUE TITLE
Ideas for improving the clothing warmth system

### ISSUE THREAD

**Issue by SageB** [cataclysmbnteam/Cataclysm-BN#858]
# Is your feature request related to a problem? Please describe.
Currently, the way clothing warmth works is wonky and unintuitive. Clothing only increases warmth, and never decreases it; during hot weather, even clothing that is meant to be worn in hot climates will result in the player being less comfortable than they would if they were naked.

# Describe the solution you'd like
I'd like to ~~rip off~~ take inspiration from Rimworld's clothing insulation system. In this system, there is a comfortable temperature range, and clothing can modify that range by expanding, shrinking, or shifting it. For example, a heavy fur coat would probably lower both the lower and upper bounds of your comfortable temperature range, making it good for cold weather but bad for hot weather. On the other hand, clothing like dusters or keffiyehs would probably raise the upper bound of the range, while not doing much to the lower bound.

# Describe alternatives you've considered
Another alternative would be to add a "cooling" stat to clothing. When you're too cold, the warmth stat applies, when you're too hot, the cooling stat applies. This would probably require less modification of code to make work, but I don't know for sure, because I couldn't find the part of the code that handles warmth.

# Additional context
https://rimworldwiki.com/wiki/Apparel#Insulation

**Comment by Coolthulhu** [comment]
Possibly good idea.
Still, it's an old feature request that no one worked on.

Closing as stale.
