### ISSUE TITLE
Multidrop UI page doesn't accept numpad keys

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#905]
# Describe the bug

Set numpad keys 2 and 8 to next and previous item and the game won't accept them after saving although there's no reason why it shouldn't work. This UI doesn't accept numpad keys at all.

# Steps To Reproduce

1. Drop some item by pressing 'd' (drop item) to acces multidrop UI 
2. press ? to change keybinding
3. set '2' as next item and '8' as previous item
4. exit and save
5. try moving up and down the multidrop UI using numpad 2 and 8

# Expected behavior

After setting 2 and 8 as previous and next item in multidrop UI, i'd expect to be able to move around and perform actions with numpad, as if i was using arrow keys instead.

# Screenshots

![image](https://user-images.githubusercontent.com/72284934/133870556-03441703-534a-49b6-9d39-0a5724cd1f1b.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 44a354b [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins],
    Arcana and Magic Items [Arcana],
    Cataclysm++ [Cata++],
    Hauling Space [hauling_space]

# Additional context

**Comment by Coolthulhu** [comment]
Turns out it's because the game hardcodes number keys in multidrop to mean quantity for partial drops.
So this is `wontfix`, but there's still a bug where it allows rebinding the keys despite not respecting those new binds.
