### ISSUE TITLE
Unable to fire laser weapons from the same tile where turret mount is placed in a vehicle

### ISSUE THREAD

**Issue by Krwak** [cataclysmbnteam/Cataclysm-BN#931]
# Describe the bug

Placed turret mount on the same tile as are vehicle controls and seat, with laser rifle but unable to shoot it by pressing 'f'(fire wielded item).
It works when going through the menu though but this is very tedious.
Error message appears, which is below.
When changing setting 'circular distance' in options then the error disappears but still unable to move reticle from the position.
When using regular weapons it is possible to shoot with 'f' from the same spot as turret mount is, whether vehicle controls are present or not.

# Steps To Reproduce

1. New, world with new vehicle a laser A7 rifle and turret mount
2. Place turret mount somewhere in the vehicle and mount A7 laser rifle
3. Stand on the same spot as the turret mount is and press 'f' while hands of the character are empty.

# Expected behavior

I expect laser weapons to behave the same as non laser weapons - that is i can place turret mount above the driver's seat in a vehicle and be able to shoot from that position by pressing 'f' (fire wielded item).
I expect being able to use turret mount that is not placed in the same spot as vehicle controls using the same method - just like it works with non-laser weapons.

# Screenshots

![image](https://user-images.githubusercontent.com/72284934/134788214-9558ef1a-df1e-4d69-9555-3bbf8790575b.png)
![image](https://user-images.githubusercontent.com/72284934/134788251-aa9d415e-91bb-42a9-9e12-524256d6f380.png)
![image](https://user-images.githubusercontent.com/72284934/134788545-71cc6db2-ceab-4631-bda1-ca2115360e4d.png)
![image](https://user-images.githubusercontent.com/72284934/134788559-b80323cc-e81b-4c39-a750-e084d90b43ab.png)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 31c2adc [64-bit]
- Graphics Version: Tiles
- Game Language:  []
- Mods loaded: [
    Bright Nights [dda]
]

# Additional context

[Lake Success.zip](https://github.com/cataclysmbnteam/Cataclysm-BN/files/7230486/Lake.Success.zip)

**Comment by OrenAudeles** [comment]
Range being set to zero appears to happen here
https://github.com/cataclysmbnteam/Cataclysm-BN/blob/6f2c6c49efb893f8c5af257e32e1d53cc42d8d2f/src/ranged.cpp#L2865-L2880
The value for the A7 laser rifle: `turret->ammo_current()` is `"null"` which trips the error test and sets the range to 0
