### ISSUE TITLE
switchable grid consumers

### ISSUE THREAD

**Issue by Lamandus** [cataclysmbnteam/Cataclysm-BN#955]
# Is your feature request related to a problem? Please describe.
Right now there is no possiblity to make grid users switched on or off. So things like lamps or fridges in grid systems aren't possible.

# Describe the solution you'd like
I would like to either have a action menu (like dashboard) at the item, or at a main hub.

# Describe alternatives you've considered
Let the item switch off automatically when there is no energy left, and let them switch on again, when there is energy to use.

**Comment by Coolthulhu** [comment]
Implemented
