### ISSUE TITLE
New Sewers

### ISSUE THREAD

**Issue by Harrow9** [cataclysmbnteam/Cataclysm-BN#98]
Hello, you can add the new sewers of the mainline version ?

[https://github.com/CleverRaven/Cataclysm-DDA/pull/43326](url)

**Comment by Firestorm01X2** [comment]
By the way. There is something with the link url. It point somewhere else.
Just for convinience I am copying it:
https://github.com/CleverRaven/Cataclysm-DDA/pull/43326

**Comment by olanti-p** [comment]
Implemented in #626
